RbA Build/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Store_Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The store location that this dwelling is related</description>
        <inlineHelpText>The store location that this dwelling is related</inlineHelpText>
        <label>Store Location</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>The account must be of type &quot;Store&quot;</errorMessage>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Store</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Dwellings</relationshipLabel>
        <relationshipName>StoreLocation</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Dwelling</fullName>
        <active>true</active>
        <description>Used to support Dwelling</description>
        <label>Dwelling</label>
    </recordTypes>
    <recordTypes>
        <fullName>Store</fullName>
        <active>true</active>
        <description>Used to track and store data releated to Retail Locations both CORO and ARO</description>
        <label>Store</label>
    </recordTypes>
    <recordTypes>
        <fullName>Vendor</fullName>
        <active>true</active>
        <description>Used to track Vendors</description>
        <label>Vendor</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

RbA Build/src/objects/Contact.object
<CustomObject>
    <recordTypes>
        <fullName>Customer_Contacts</fullName>
        <active>true</active>
        <description>Used to track Customer associated to Accounts</description>
        <label>Customer Contacts</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

RbA Build/src/objects/Contact_History__c.object
<CustomObject>
    <description>Junction object between Account and Contacts.</description>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Associated_Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Dwelling__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>What Dwelling is this Contact associated with?</inlineHelpText>
        <label>Dwelling</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Associated_Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>Tracks the type of association the contact has with the account/dwelling</description>
        <inlineHelpText>Tracks the type of association the contact has with the account/dwelling</inlineHelpText>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Current Resident</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Past Resident</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Current Renter</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Past Renter</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Owner</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Contact History</label>
    <nameField>
        <displayFormat>CH-{00}</displayFormat>
        <label>CH#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Histories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

RbA Build/src/objects/RMS_Settings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>A name value list of RMS settings</description>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>RMS Settings</label>
</CustomObject>

RbA Build/src/classes/RMS_createContactHistoryManagerTests.cls
@isTest
private class RMS_createContactHistoryManagerTests {
	
	static Id customerContactRecordType = UtilityMethods.retrieveRecordTypeId('Customer_Contacts', 'Contact');
	@testSetup static void setupData() {
		TestUtilityMethods utility = new TestUtilityMethods();
		
		utility.setUpConfigs();
		
		Account account1 = utility.createVendorAccount('Vendor Account 1 ');
		insert account1;

		Account account2 = new Account(	Name = 'RbA',
										AccountNumber = '1234567890',
										Phone = '(763) 555-2000'
									);
		insert account2;

		Account dwelling = utility.createDwellingAccount('Dwelling Account');

		Account store = [SELECT Id from Account Where Name = '77 - Twin Cities, MN'];
		dwelling.Store_Location__c = store.Id;
		insert dwelling;		
	}

	@isTest
	static void testcreateContactHistoryonInsert(){
		Account dwelling = [Select Id from Account Where Name = 'Dwelling Account'];

		//Insert first contact
		Contact con = new Contact(AccountId = dwelling.Id, recordTypeId = customerContactRecordType, LastName = 'TestCon1');
		insert con;
		List<Contact_History__c> conHist = [Select Id, Contact__c, Type__c from Contact_History__c where Contact__c =: con.Id AND Dwelling__c =: dwelling.Id];
		System.AssertEquals(conHist.size(),1);
		System.assertEquals(conHist[0].Type__c, 'Current Resident');

		//Update Contact History to another type, then insert a second contact that has the first contact as a spouse. Verify the history is updated to 'Current Resideent'
		conHist[0].Type__c = 'Past Resident';
		update conHist;
		Contact con2 = new Contact(AccountId = dwelling.Id, recordTypeId = customerContactRecordType, LastName = 'TestCon2', Spouse__c = con.Id);
		insert con2;
		conHist = [Select Id, Contact__c, Type__c from Contact_History__c where Dwelling__c =: dwelling.Id];
		System.AssertEquals(conHist.size(),2);
		for(Contact_History__c contactHistory: conHist){
			System.assertEquals(contactHistory.Type__c, 'Current Resident');
		}


	}

	@isTest
	static void testcreateContactHistoryonUpdate(){
		TestUtilityMethods utility = new TestUtilityMethods();
		Account dwelling = [Select Id from Account Where Name = 'Dwelling Account'];

		//Insert first contact
		Contact con = new Contact(AccountId = dwelling.Id, recordTypeId = customerContactRecordType, LastName = 'TestCon1');
		insert con;

		//insert 3 contacts on second account. One will be set as a spouse to the first contact
		Account dwelling2 = utility.createDwellingAccount('Dwelling Account 2');
		insert dwelling2;
		Account dwelling3 = utility.createDwellingAccount('Dwelling Account 3');
		insert dwelling3;
		Contact con2 = new Contact(AccountId = dwelling2.Id, recordTypeId = customerContactRecordType, LastName = 'TestCon2');
		insert con2;
		Contact con3 = new Contact(AccountId = dwelling2.Id, recordTypeId = customerContactRecordType, LastName = 'TestCon3');
		insert con3;
		Contact con1Spouse = new Contact(AccountId = dwelling2.Id, recordTypeId = customerContactRecordType, LastName = 'TestCon1Spouse');
		insert con1Spouse;

		insert new Contact_History__c(Dwelling__c = dwelling3.Id, Contact__c = con3.Id, Type__c = 'Current Resident' );

		con.Spouse__c = con1Spouse.Id;
		con.AccountId = dwelling2.Id;
		update con;

		//Verify the Spouse and the updated contact are Current Resident on the second account, and the other contact gets updated to 'Past Resident'
		List<Contact_History__c> conHist = [Select Id, Contact__c, Type__c from Contact_History__c where Dwelling__c =: dwelling2.Id];
		System.assertEquals(conHist.size(),4);
		for(Contact_History__c ch : conHist){
			if(ch.Contact__c == con.Id || ch.Contact__c == con1Spouse.Id){
				System.assertEquals(ch.Type__c, 'Current Resident');
			}else{
				System.assertEquals(ch.Type__c, 'Past Resident');
			}
		}

		//Verify the 2nd Contact is reparented to the Unassigned Account
		map<String, RMS_Settings__c> RMS_Settings_map = RMS_Settings__c.getAll(); 
    	Id masterAccountId = RMS_Settings_map.get('Unassigned Account Id').Value__c;
		con2 = [Select AccountId from Contact where Id =: con2.Id];
		System.assertEquals(con2.AccountId,masterAccountId);

		//Verify the 3rd Contact is reparented to the Dwelling where a Contact History with Current Resident type exists for it
		con3 = [Select AccountId from Contact where Id =: con3.Id];
		System.assertEquals(con3.AccountId,dwelling3.Id);


	}
}