RbA Build/src/objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Dwelling</fullName>
        <active>true</active>
        <description>Used to support Dwelling</description>
        <label>Dwelling</label>
    </recordTypes>
    <recordTypes>
        <fullName>Store</fullName>
        <active>true</active>
        <description>Used to track and store data releated to Retail Locations both CORO and ARO</description>
        <label>Store</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

RbA Build/src/objects/Municipality__c.object
<CustomObject>
    <description>Holds Municipality information that will help with HOA, Historical and Permitting details.</description>
    <fields>
        <fullName>City_Township__c</fullName>
        <label>City/Township</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>County__c</fullName>
        <label>County</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>For_Retail_Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>What Retail Location is this for?</inlineHelpText>
        <label>For Retail Location</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Store</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Municipalities</relationshipLabel>
        <relationshipName>Municipalities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <inlineHelpText>Sched Department Phone or Main Line</inlineHelpText>
        <label>Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zip_Code__c</fullName>
        <label>Zip Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Municipality</label>
    <nameField>
        <label>Agency Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Municipalities</pluralLabel>
    <recordTypes>
        <fullName>Permit</fullName>
        <active>true</active>
        <description>Hold information for Building Permits (not Building)</description>
        <label>Permit</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

RbA Build/src/objects/RMS_Settings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>A name value list of RMS settings</description>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>RMS Settings</label>
</CustomObject>

RbA Build/src/classes/testRMS_MunicipalityManager.cls
@isTest
public with sharing class testRMS_MunicipalityManager {
    static testmethod void createTestRecords() {    
        RMS_Settings__c turnOffFinancialTrigger = new RMS_Settings__c(Name = 'Turn Financial Transactions Off', Value__c = 'Yes');
        insert turnOffFinancialTrigger;
        
        TestUtilityMethods utility = new TestUtilityMethods();
        utility.setUpConfigs();
        
        id dwellingRT = UtilityMethods.retrieveRecordTypeId('Dwelling', 'Account');
        id muniPermitRT = UtilityMethods.retrieveRecordTypeId('Permit', 'Municipality__c');
        
        Account store = [SELECT id FROM Account WHERE Name ='77 - Twin Cities, MN'];
        
        List<Municipality__c> muniList = new List<Municipality__c>();
        Municipality__c muni1 = new Municipality__c( name = 'Muni 1', recordTypeId=muniPermitRT, City_Township__c = 'Chicago', State__c = 'IL', Zip_Code__c = '60618', County__c = 'Cook', Phone__c = '555-555-5555', For_Retail_Location__c = store.Id);
        muniList.add(muni1);
        Municipality__c muni2 = new Municipality__c( name = 'Muni 1', recordTypeId=muniPermitRT, City_Township__c = 'Chicago', State__c = 'IL', Zip_Code__c = '60618', County__c = 'Cook', Phone__c = '555-555-5555', For_Retail_Location__c = store.Id);
        muniList.add(muni2);
        insert muniList;
        
        System.assertEquals(muniList.size(), 2);
        
        
    }
}