RbA Build/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Primary_Contact__c</fullName>
        <description>The primary contact on a dwelling. Updated with a declarative rollup.</description>
        <inlineHelpText>The primary contact on a dwelling</inlineHelpText>
        <label>Primary Contact</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sales_Tax__c</fullName>
        <description>Pulled from Active Store Configuration</description>
        <formula>Active_Store_Configuration__r.Sales_Tax__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Pulled from Active Store Configuration</inlineHelpText>
        <label>Sales Tax</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Store_Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The store location that this dwelling is related</description>
        <inlineHelpText>The store location that this dwelling is related</inlineHelpText>
        <label>Store Location</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>The account must be of type &quot;Store&quot;</errorMessage>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Store</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Dwellings</relationshipLabel>
        <relationshipName>StoreLocation</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Dwelling</fullName>
        <active>true</active>
        <description>Used to support Dwelling</description>
        <label>Dwelling</label>
    </recordTypes>
    <recordTypes>
        <fullName>Vendor</fullName>
        <active>true</active>
        <description>Used to track Vendors</description>
        <label>Vendor</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

RbA Build/src/objects/Asset.object
<CustomObject>
    <fields>
        <fullName>Sold_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Related Sold Order</inlineHelpText>
        <label>Sold Order</label>
        <referenceTo>Order</referenceTo>
        <relationshipLabel>Assets</relationshipLabel>
        <relationshipName>Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Store_Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Store Location</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Assets</relationshipLabel>
        <relationshipName>Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Unit_Wholesale_Cost__c</fullName>
        <label>Unit Wholesale Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Variant_Number__c</fullName>
        <description>The variant number for this asset.</description>
        <inlineHelpText>The variant number for this asset.</inlineHelpText>
        <label>Variant Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

RbA Build/src/objects/Financial_Account_Number__c.object
<CustomObject>
    <description>Stores financial account numbers used in the journal entries and Baan ERP integration</description>
    <fields>
        <fullName>Store_Configuration__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Select which store configuration to relate this account number.</description>
        <inlineHelpText>Select which store configuration to relate this account number.</inlineHelpText>
        <label>Store Configuration</label>
        <referenceTo>Store_Configuration__c</referenceTo>
        <relationshipLabel>Financial Account Numbers</relationshipLabel>
        <relationshipName>Financial_Account_Numbers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Financial Account Number</label>
    <nameField>
        <label>Financial Account Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Account Numbers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

RbA Build/src/objects/Financial_Transaction__c.object
<CustomObject>
    <description>Object to store financial transaction records</description>
    <fields>
        <fullName>Credit_Account_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Select the account number to credit in this financial transaction</description>
        <inlineHelpText>Select the account number to credit in this financial transaction</inlineHelpText>
        <label>Credit Account Number</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Only account numbers related to this financial transaction&apos;s store location can be selected.</errorMessage>
            <filterItems>
                <field>Financial_Account_Number__c.Store_Configuration__c</field>
                <operation>equals</operation>
                <valueField>$Source.Store_Configuration__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Financial_Account_Number__c</referenceTo>
        <relationshipLabel>Financial Transactions Credit</relationshipLabel>
        <relationshipName>Financial_Transactions_Credit</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Debit_Account_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Select the account number to debit in this financial transaction</description>
        <inlineHelpText>Select the account number to debit in this financial transaction</inlineHelpText>
        <label>Debit Account Number</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Only account numbers related to this financial transaction&apos;s store location can be selected.</errorMessage>
            <filterItems>
                <field>Financial_Account_Number__c.Store_Configuration__c</field>
                <operation>equals</operation>
                <valueField>$Source.Store_Configuration__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Financial_Account_Number__c</referenceTo>
        <relationshipLabel>Financial Transactions Debit</relationshipLabel>
        <relationshipName>Financial_Transactions_Debit</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Store_Configuration__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>The store configuration this transaction is related to</description>
        <inlineHelpText>The store configuration this transaction is related to</inlineHelpText>
        <label>Store Configuration</label>
        <referenceTo>Store_Configuration__c</referenceTo>
        <relationshipLabel>Financial Transactions</relationshipLabel>
        <relationshipName>Financial_Transactions</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Transaction_Type__c</fullName>
        <description>Select the transaction type for this record. This will determine when these accounts will be debited/credited.</description>
        <inlineHelpText>Select the transaction type for this record. This will determine when these accounts will be debited/credited.</inlineHelpText>
        <label>Transaction Type</label>
        <picklist>
            <picklistValues>
                <fullName>Deposit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Final Payment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inventory Received</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inventory Installed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Misc Sub-Payment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>External Labor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Internal Labor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Misc Cash Receipt</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Misc Reimbursement</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Financial Transaction</label>
    <nameField>
        <displayFormat>FT-{00000}</displayFormat>
        <label>Financial Transaction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Financial Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

RbA Build/src/objects/Order.object
<CustomObject>
    <fields>
        <fullName>Customer_Pickup_All__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Sets Customer Pickup to &quot;Yes&quot; when checked for all Order Items, which impacts Billing amounts</description>
        <inlineHelpText>Sets Customer Pickup to &quot;Yes&quot; when checked for all Order Items, which impacts Billing amounts</inlineHelpText>
        <label>Customer Pickup - All</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Installation_Date__c</fullName>
        <description>Updated via Declarative Lookups</description>
        <inlineHelpText>Installation Date Time pulled from Scheduled Appt Date/Time: Install from Installation Work Order</inlineHelpText>
        <label>Installation Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Sales_Tax__c</fullName>
        <description>Multiplies the Billable Tax Amount (the billable amount on all child OrderItems where Customer Pickup = Yes) by the Sales Tax Percent (set by Store Configuration)</description>
        <formula>Billable_Tax_Amount__c *  Sales_Tax_Percent__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Multiplies the Billable Tax Amount (the billable amount on all child OrderItems where Customer Pickup = Yes) by the Sales Tax Percent (set by Store Configuration)</inlineHelpText>
        <label>Sales Tax</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Sold_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>When the Sold Order is Job In Progress, the Service Order must be related to the Sold Order.</inlineHelpText>
        <label>Sold Order</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>$Source.AccountId</field>
                <operation>equals</operation>
                <valueField>Order.AccountId</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Order</referenceTo>
        <relationshipLabel>Service Orders</relationshipLabel>
        <relationshipName>Sold_Order</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Store_Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This order is related to this store location.</description>
        <inlineHelpText>This order is related to this store location.</inlineHelpText>
        <label>Store Location</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Orders (Store Location)</relationshipLabel>
        <relationshipName>Orders1</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

RbA Build/src/objects/OrderItem.object
<CustomObject>
    <fields>
        <fullName>Unit_Wholesale_Cost__c</fullName>
        <description>The wholesale cost of the product</description>
        <inlineHelpText>The wholesale cost of the product</inlineHelpText>
        <label>Wholesale Cost</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Variant_Number__c</fullName>
        <description>The variant number received for the product from manufacturing</description>
        <inlineHelpText>The variant number received for the product from manufacturing</inlineHelpText>
        <label>Variant Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

RbA Build/src/objects/Pricebook2.object
<CustomObject>
    <fields>
        <fullName>Store_Configuration__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Links price books to store configuration.  All configuration that are store based are tied to the store configuration for that store.</description>
        <inlineHelpText>Link this to the store configuration for the store this Price Book is being created for.</inlineHelpText>
        <label>Store Configuration</label>
        <referenceTo>Store_Configuration__c</referenceTo>
        <relationshipLabel>Price Books</relationshipLabel>
        <relationshipName>Price_Books</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadSelect</sharingModel>
</CustomObject>

RbA Build/src/objects/Product2.object
<CustomObject>
    <recordTypes>
        <fullName>Master_Product</fullName>
        <active>true</active>
        <label>Master Product</label>
    </recordTypes>
</CustomObject>

RbA Build/src/objects/RMS_Settings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>A name value list of RMS settings</description>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>RMS Settings</label>
</CustomObject>

RbA Build/src/objects/Store_Configuration__c.object
<CustomObject>
    <description>Holds Store Settings &amp; Configurations</description>
    <fields>
        <fullName>Sales_Tax__c</fullName>
        <inlineHelpText>Add default sales tax amount for this store</inlineHelpText>
        <label>Sales Tax</label>
        <precision>7</precision>
        <scale>3</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Store__c</fullName>
        <label>Store</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Store Configurations</relationshipLabel>
        <relationshipName>Store_Configurations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Store Configuration</label>
    <nameField>
        <displayFormat>SS-{00}</displayFormat>
        <label>Store Setting Record #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Store Configurations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

RbA Build/src/classes/testRMS_createServiceRequestAssetManager.cls
@isTest 
public with sharing class testRMS_createServiceRequestAssetManager {
    
    static testmethod void createTestRecords() {      
        RMS_Settings__c turnOffFinancialTrigger = new RMS_Settings__c(Name = 'Turn Financial Transactions Off', Value__c = 'Yes');
        insert turnOffFinancialTrigger;
        
        TestUtilityMethods utility = new TestUtilityMethods();
        utility.setUpConfigs();
        
        List<Account> dwellingsToInsert = new List<Account>();               
        Account dwelling1 = utility.createDwellingAccount('Dwelling Account');
        Account dwelling2 = utility.createDwellingAccount('Dwelling Account 2');        
        Account store1 = [SELECT Id from Account Where Name = '77 - Twin Cities, MN'];        
        Store_Configuration__c storeConfig1 = [SELECT id FROM Store_Configuration__c WHERE Store__c = :store1.id ];
        storeConfig1.Sales_Tax__c = 5;
        update storeConfig1;
        dwelling1.Store_Location__c = store1.Id;
        dwelling2.Store_Location__c = store1.Id;        
        dwellingsToInsert.add(dwelling1);
        dwellingsToInsert.add(dwelling2);      
        insert dwellingsToInsert;        
        
        List<Contact> contactsToInsert = new List<Contact>();       
        Contact contact1 = new contact ( FirstName='Contact',LastName='1',AccountId=dwelling1.id, Primary_Contact__c =true);
        contactsToInsert.add(contact1);
        Contact contact2 = new contact ( FirstName='Contact',LastName='2',AccountId=dwelling2.id, Primary_Contact__c =true);
        contactsToInsert.add(contact2);
        insert contactsToInsert;
        
        Financial_Account_Number__c finacialAccountNumber1 = new Financial_Account_Number__c (  Store_Configuration__c = storeConfig1.id, Name = '1');
        insert finacialAccountNumber1;
        Financial_Account_Number__c finacialAccountNumber2 = new Financial_Account_Number__c (  Store_Configuration__c = storeConfig1.id, Name = '2');
        insert finacialAccountNumber2;
        
        Financial_Transaction__c finacialTransaction1 = new Financial_Transaction__c(  Store_Configuration__c = storeConfig1.id,
                                                                                     Transaction_Type__c = 'Inventory Received - External Vendor',
                                                                                     Debit_Account_Number__c = finacialAccountNumber1.id,
                                                                                     Credit_Account_Number__c = finacialAccountNumber2.id);
        insert finacialTransaction1;
        
        Product2 masterProduct = new Product2( name = 'master',IsActive = true, recordTypeId=UtilityMethods.GetRecordTypeIdsMapForSObject(Product2.sObjectType).get('Master_Product'));        
        
        Id pricebookId = Test.getStandardPricebookId();
        system.debug(pricebookId);
        
        Pricebook2 pricebook1 =  utility.createPricebook2Name('Standard Price Book');
        insert pricebook1;
        
        List<Product2> products = new List<Product2>{masterProduct};
            insert products;
        
        PricebookEntry pricebookEntryMaster= utility.createPricebookEntry(pricebookId, masterProduct.id);             
        
        List<PriceBookEntry> pbEntries = new List<PricebookEntry>{pricebookEntryMaster};
            insert pbEntries;
        
        
        List<Order> ordersToInsert = new List<Order>();
        
        Order order =  new Order(   Name='Sold Order 1', 
                                 AccountId = dwelling1.id, 
                                 BilltoContactId = contact1.id,
                                 EffectiveDate= Date.Today(), 
                                 Store_Location__c = store1.Id,                           
                                 Status ='Install Complete', 
                                 Pricebook2Id = Test.getStandardPricebookId(),
                                 Customer_Pickup_All__c = FALSE,
                                 Installation_Date__c = system.today()-1 
                                );
        ordersToInsert.add(order);
        
        
        insert ordersToInsert;
        
        System.assertEquals(ordersToInsert.size() , 1); 
        
        
        OrderItem orderItemMaster = new OrderItem(OrderId = Order.id, PricebookentryId = pricebookEntryMaster.Id, Quantity = 2, UnitPrice = 100,Quote_Accepted__c = FALSE );
        insert orderItemMaster;
        
        
        List<Asset> assetsToInsert = new List<Asset>();
        Asset asset = new Asset (     Name='Asset1',
                                 Original_Order_Product__c = orderItemMaster.Id,
                                 Product2Id= masterProduct.Id,
                                 AccountId = dwelling1.id,
                                 ContactId = contact1.id,
                                 Variant_Number__c = '1234ABC',
                                 Unit_Wholesale_Cost__c = 200,
                                 Store_Location__c = store1.id,
                                 Quantity = 1,
                                 Price = 100,
                                 Status = 'Installed',
                                 Sold_Order__c = order.Id,
                                 PurchaseDate = Date.Today()
                                );
        
        assetsToInsert.add(asset);         
        
        
        insert assetsToInsert;  
        System.assertEquals(assetsToInsert.size() , 1);                                 
        
    }
    
    //createServiceRequestRedirectMethods
    
    
    static testmethod void saveAsset(){
        createTestRecords();
        
        Account aid = [Select Id FROM Account WHERE Name = '11111, Dwelling Account'];
        Account slid = [Select Id FROM Account WHERE Name = '77 - Twin Cities, MN'];
        
        Test.startTest();
        
        Order order = new Order(AccountId = aid.Id, Store_Location__c = slid.Id, EffectiveDate= Date.Today(), Status ='Install Complete', Pricebook2Id = Test.getStandardPricebookId());
        insert order;
        
        Test.setCurrentPage(Page.RMS_createServiceRequestRedirect);
        ApexPages.currentPage().getParameters().put('aid',aid.id);
        ApexPages.currentPage().getParameters().put('slid',slid.id);
        ApexPages.StandardController sc = new ApexPages.StandardController(order);
        RMS_ServiceOrderExtensionMgr TE = new RMS_ServiceOrderExtensionMgr(sc);
        Integer num_orders = TE.getnumorders();
        Integer num_assets = TE.getnumassets();
        String propPickValSelected = TE.getpropPickValSelected();        
        
        Pagereference pr = TE.saveOrder();        
        Order ord = [select AccountId from Order where id =: order.id];
        
        System.Assertequals(ord.AccountId, aid.Id);
        System.assertEquals(2, num_orders);
        System.assertEquals(1, num_assets);  
        
        Test.stopTest();       
    }
    
    
    static testmethod void saveAssetTest2(){
        createTestRecords();
        
        Account acct = [Select Id FROM Account WHERE Name = '11111, Dwelling Account 2'];
        Contact cont = [Select Id FROM Contact Where LastName = '2'];
        Account store1 = [Select Id FROM Account WHERE Name = '77 - Twin Cities, MN'];
        
        Test.startTest();
        
        Test.setCurrentPage(Page.RMS_createAssetRedirect);
        ApexPages.currentPage().getParameters().put('aid',acct.id);
        ApexPages.currentPage().getParameters().put('slid',store1.id);
        
        Asset asset2 = new Asset (     Name='Asset2',                             
                                  AccountId = acct.id,
                                  ContactId = cont.id,                                  
                                  Store_Location__c = store1.id,                                  
                                  Status = 'Installed',                                 
                                  PurchaseDate = Date.Today()
                                 );
        
        
        insert asset2;
        
        ApexPages.StandardController sc2 = new ApexPages.StandardController(asset2);
        RMS_createServiceRequestAssetManager TE2 = new RMS_createServiceRequestAssetManager(sc2);
        Pagereference pr2 = TE2.saveAsset();        
        
        Test.stopTest();
    }
    
    static testmethod void saveContinuetest(){
        createTestRecords();
        
        Test.startTest();        
        Account aid = [Select Id,Name FROM Account WHERE Name = '11111, Dwelling Account'];
        Account slid = [Select Id, Name FROM Account WHERE Name = '77 - Twin Cities, MN'];
        Asset asset = [Select Id, AccountId FROM Asset WHERE AccountId =:aid.id];        
        
        Test.setCurrentPage(Page.RMS_createServiceRequestAsset);
        ApexPages.StandardController sc = new ApexPages.StandardController(asset);
        RMS_createServiceRequestAssetManager TE = new RMS_createServiceRequestAssetManager(sc); 
        
        asset.AccountId = aid.Id;
        Pagereference pr = TE.saveContinueAsset();        
        
        
        Test.stopTest();        
    }
    
    static testmethod void saveContinuetestFail(){
        createTestRecords();
        
        Test.startTest();        
        Account aid = [Select Id,Name FROM Account WHERE Name = '11111, Dwelling Account'];
        Account slid = [Select Id, Name FROM Account WHERE Name = '77 - Twin Cities, MN'];
        Asset asset = [Select Id, AccountId FROM Asset WHERE AccountId =:aid.id];        
        
        Test.setCurrentPage(Page.RMS_createServiceRequestAsset);
        ApexPages.StandardController sc = new ApexPages.StandardController(asset);
        RMS_createServiceRequestAssetManager TE = new RMS_createServiceRequestAssetManager(sc); 
        
        asset.AccountId = null;
        Pagereference pr = TE.saveContinueAsset();        
        
        
        Test.stopTest();        
    }
    
    static testmethod void customDeleteTest(){
        
        createTestRecords();
        Test.startTest();
        Asset asset = [SELECT Id,AccountId FROM Asset WHERE Name = 'Asset1'];        
        
        Test.setCurrentPage(Page.RMS_createServiceRequestAsset);
        ApexPages.StandardController sc = new ApexPages.StandardController(asset);
        RMS_createServiceRequestAssetManager TE = new RMS_createServiceRequestAssetManager(sc);
        Pagereference pr = TE.customDelete();                    
        Asset delAsst = [select id,isdeleted from Asset where id =: asset.id All rows];
        System.Assertequals(delAsst.isdeleted, true);
        
        Test.stopTest();         
        
    }
    
}