RbA Build/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Store_Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The store location that this dwelling is related</description>
        <inlineHelpText>The store location that this dwelling is related</inlineHelpText>
        <label>Store Location</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>The account must be of type &quot;Store&quot;</errorMessage>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Store</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Dwellings</relationshipLabel>
        <relationshipName>StoreLocation</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Dwelling</fullName>
        <active>true</active>
        <description>Used to support Dwelling</description>
        <label>Dwelling</label>
    </recordTypes>
    <recordTypes>
        <fullName>Store</fullName>
        <active>true</active>
        <description>Used to track and store data releated to Retail Locations both CORO and ARO</description>
        <label>Store</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

RbA Build/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Store_Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Store Location</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>The account must be of type &quot;Store&quot;.</errorMessage>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Store</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Store Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

RbA Build/src/objects/Order.object
<CustomObject>
    <fields>
        <fullName>Store_Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This order is related to this store location.</description>
        <inlineHelpText>This order is related to this store location.</inlineHelpText>
        <label>Store Location</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Orders (Store Location)</relationshipLabel>
        <relationshipName>Orders1</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

RbA Build/src/objects/RbA_Work_Order__c.object
<CustomObject>
    <description>Custom Object used to track Work Orders related to Orders.</description>
    <label>RbA Work Order</label>
    <nameField>
        <displayFormat>WO-{00000000}</displayFormat>
        <label>Work Order #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RbA Work Orders</pluralLabel>
    <recordTypes>
        <fullName>Actions</fullName>
        <active>true</active>
        <description>Holds HOA and Historical Details</description>
        <label>Actions</label>
    </recordTypes>
    <recordTypes>
        <fullName>LSWP</fullName>
        <active>true</active>
        <description>Holds LSWP Details</description>
        <label>LSWP</label>
    </recordTypes>
    <recordTypes>
        <fullName>Permit</fullName>
        <active>true</active>
        <description>Holds Building Permit Details</description>
        <label>Permit</label>
    </recordTypes>
    <recordTypes>
        <fullName>Visit</fullName>
        <active>true</active>
        <description>Hold Work Order details that can be have a scheduled visit to the home</description>
        <label>Visit</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

RbA Build/src/classes/RMS_createWorkOrderControllerTest.cls
@isTest
public with sharing class RMS_createWorkOrderControllerTest {


	static testMethod void testingConstructor(){
		
		TestUtilityMethods utility = new TestUtilityMethods();
		utility.setUpConfigs();
		
		id dwellingRT = UtilityMethods.retrieveRecordTypeId('Dwelling', 'Account');
		Account store = [SELECT id FROM Account WHERE Name ='77 - Twin Cities, MN'];
		Account newDwelling = new Account(Name='test1', Store_Location__c = store.id, RecordTypeId = dwellingRT, BillingPostalCode = '55429' , BillingCity = 'Blaine' );
		insert newDwelling;
		
		//CREATE AN ORDER RELATED TO OPPORTUNITY
		Order ord1 = new Order( AccountId = newDwelling.id ,
								Status = 'Draft', 
								EffectiveDate = Date.Today(),
								Pricebook2Id = Test.getStandardPricebookId()
								);
		insert ord1;
		
		//CREATE OPPORTUNITY
		Opportunity opp1 = new Opportunity(Name='Opp1', AccountId=newDwelling.id, StageName = 'New', CloseDate = Date.today().addYears(1) );
		insert opp1;
		
		Id serviceOrderVisitRecordTypeId = UtilityMethods.retrieveRecordTypeId('Visit', 'RbA_Work_Order__c');
		RbA_Work_Order__c workOrder = new RbA_Work_Order__c(  	RecordTypeId = serviceOrderVisitRecordTypeId  
															                    );
		
		String actionUrl = '/apex/RMS_createActionsWorkOrder?'+
		'type=actions'+
		'&orderId='+ord1.id+
		'&accountId='+newDwelling.id+
		'&billingStreet=300 Stanley Ave'+
		'&billingCity=Long Beach'+
		'&billingPostalCode=California'+
		'&billingCountry=United States'+
		'&relatedOpp='+opp1.id+
		'&permit='+
		'&hoa='+
		'&historical=';
		
		PageReference pageRef = new PageReference(actionUrl); 
		Test.setCurrentPage(pageRef);
			
		ApexPages.StandardController stdController = new ApexPages.StandardController(workOrder);
		RMS_createWorkOrderController customController  = new RMS_createWorkOrderController(stdController);
		

		
		String visitUrl = '/apex/RMS_createActionsWorkOrder?'+
		'type=visit'+
		'&orderId='+ord1.id+
		'&accountId='+newDwelling.id+
		'&billingStreet=300 Stanley Ave'+
		'&billingCity=Long Beach'+
		'&billingPostalCode=California'+
		'&billingCountry=United States'+
		'&relatedOpp='+opp1.id+
		'&permit='+
		'&hoa='+
		'&historical=';
		PageReference pageRefVisit = new PageReference(visitUrl); 
		Test.setCurrentPage(pageRefVisit);
			
		ApexPages.StandardController stdControllerVisit = new ApexPages.StandardController(workOrder);
		RMS_createWorkOrderController customControllerVisit  = new RMS_createWorkOrderController(stdControllerVisit);
		
		
		
		String lswpUrl = '/apex/RMS_createActionsWorkOrder?'+
		'type=lswp'+
		'&orderId='+ord1.id+
		'&accountId='+newDwelling.id+
		'&billingStreet=300 Stanley Ave'+
		'&billingCity=Long Beach'+
		'&billingPostalCode=California'+
		'&billingCountry=United States'+
		'&relatedOpp='+opp1.id+
		'&permit='+
		'&hoa='+
		'&historical=';
		PageReference pageReflswp = new PageReference(lswpUrl); 
		Test.setCurrentPage(pageReflswp);
			
		ApexPages.StandardController stdControllerlswp = new ApexPages.StandardController(workOrder);
		RMS_createWorkOrderController customControllerlswp = new RMS_createWorkOrderController(stdControllerlswp);
		
		
		
		String paintStainUrl = '/apex/RMS_createActionsWorkOrder?'+
		'type=paintStain'+
		'&orderId='+ord1.id+
		'&accountId='+newDwelling.id+
		'&billingStreet=300 Stanley Ave'+
		'&billingCity=Long Beach'+
		'&billingPostalCode=California'+
		'&billingCountry=United States'+
		'&relatedOpp='+opp1.id+
		'&permit='+
		'&hoa='+
		'&historical=';
		PageReference pageRefpaintStain = new PageReference(paintStainUrl); 
		Test.setCurrentPage(pageRefpaintStain);
			
		ApexPages.StandardController stdControllerpaintStain = new ApexPages.StandardController(workOrder);
		RMS_createWorkOrderController customControllerpaintStain  = new RMS_createWorkOrderController(stdControllerpaintStain);
		
		
		String permitUrl = '/apex/RMS_createActionsWorkOrder?'+
		'type=permit'+
		'&orderId='+ord1.id+
		'&accountId='+newDwelling.id+
		'&billingStreet=300 Stanley Ave'+
		'&billingCity=Long Beach'+
		'&billingPostalCode=California'+
		'&billingCountry=United States'+
		'&relatedOpp='+opp1.id+
		'&permit='+
		'&hoa='+
		'&historical=';
		PageReference pageRefpermit = new PageReference(permitUrl); 
		Test.setCurrentPage(pageRefpermit);
			
		ApexPages.StandardController stdControllerpermit = new ApexPages.StandardController(workOrder);
		RMS_createWorkOrderController customControllerpermit  = new RMS_createWorkOrderController(stdControllerpermit);
		
		customControllerpermit.save();
	
	}

}