RbA Build/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Primary_Contact__c</fullName>
        <description>The primary contact on a dwelling. Updated with a declarative rollup.</description>
        <inlineHelpText>The primary contact on a dwelling</inlineHelpText>
        <label>Primary Contact</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Store_Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The store location that this dwelling is related</description>
        <inlineHelpText>The store location that this dwelling is related</inlineHelpText>
        <label>Store Location</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>The account must be of type &quot;Store&quot;</errorMessage>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Store</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Dwellings</relationshipLabel>
        <relationshipName>StoreLocation</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Store</fullName>
        <active>true</active>
        <description>Used to track and store data releated to Retail Locations both CORO and ARO</description>
        <label>Store</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

RbA Build/src/objects/Asset.object
<CustomObject>
    <fields>
        <fullName>Store_Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Store Location</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Assets</relationshipLabel>
        <relationshipName>Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Installed_Products</fullName>
        <active>true</active>
        <description>Windows and Doors installed by RbA</description>
        <label>Installed Products</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

RbA Build/src/objects/Contact_History__c.object
<CustomObject>
    <description>Junction object between Account and Contacts.</description>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Associated_Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Dwelling__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>What Dwelling is this Contact associated with?</inlineHelpText>
        <label>Dwelling</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Associated_Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Contact History</label>
    <nameField>
        <displayFormat>CH-{00}</displayFormat>
        <label>CH#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Histories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

RbA Build/src/classes/RMS_createServiceRequestAssetManager.cls
public with sharing class RMS_createServiceRequestAssetManager  {
    
    public final Asset o;
    
    public RMS_createServiceRequestAssetManager(ApexPages.StandardController stdController) {
        this.o = (Asset)stdController.getRecord();
    }
    
    public String aid { get; set; }{
        aid = apexpages.currentpage().getparameters().get('aid');
        if ( aid == null ) aid = '';
    }
    
    public String slid { get; set; }{
        slid = apexpages.currentpage().getparameters().get('slid');
        if ( slid == null ) slid = '';
    }
    
    public String name { get; set; }{
        name = apexpages.currentpage().getparameters().get('name');
        if ( name == null ) name = 'New Asset';
    }
    
    public PageReference saveAsset(){
        
        try{
            
            
            o.Name='New Asset';
            o.AccountId = aid;                                                    
            o.RecordTypeId = UtilityMethods.retrieveRecordTypeId('Installed_Products', 'Asset');
            o.Status = 'Installed'; 
            o.Quantity = 1;
            upsert o;            
            
            List<Account> store = [SELECT Store_Location__c FROM Account WHERE Id =: o.AccountId];
            
            If(store.size()>0){
                o.Store_Location__c = store[0].Store_Location__c;
                upsert o;
            }
            
            
            list<Contact_History__c> ch = [Select Contact__c, Dwelling__c, Primary_Contact__c, Id 
                                           FROM Contact_History__c 
                                           WHERE Dwelling__c =: o.AccountId 
                                           AND Primary_Contact__c = true];
            if (ch.size()>0){
                o.ContactId = ch[0].Contact__c;
                upsert o;
            }
            
            PageReference newPage;
            
            
            
            newPage = new PageReference('/apex/RMS_createServiceRequestAsset?id='+ o.Id + '&retUrl=' + o.Id);
            
            
            newPage.setRedirect(true);
            return newPage;
        }catch(DMLException saveEx){
            ApexPages.addMessages(saveEx);
            PageReference newPage = new PageReference('/apex/RMS_createServiceRequestAsset?id='+ o.Id + '&retUrl=' + o.Id);
            newPage.setRedirect(false);
            return newPage;
        }
        
    }
    
    public PageReference saveContinueAsset(){
        
        PageReference newPage;
        try{    
            
            upsert o;
            newPage = new PageReference('/apex/RMS_createServiceRequestRedirect?aid='+o.AccountId+'&slid='+o.Store_Location__c);
        }
        catch(DMLException ex){
            ApexPages.addMessages(ex);
        }
        
        return newPage;
    } 
    
    public PageReference customDelete(){       
        
        PageReference deletePage = new PageReference('/'+ o.AccountId);
        deletePage.setRedirect(true);
        delete o;
        return deletePage;
        
    }
}