RbA Build/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Active_Store_Configuration__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>currently active store configuration</description>
        <label>Active Store Configuration</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Store_Configuration__c.Store__c</field>
                <operation>equals</operation>
                <valueField>$Source.Id</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Store_Configuration__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Check if this account is active</description>
        <inlineHelpText>Check if this account is active</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Dwelling_Style__c</fullName>
        <label>Dwelling Style</label>
        <picklist>
            <picklistValues>
                <fullName>House</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Condo</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>???</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Store_Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The store location that this dwelling is related</description>
        <inlineHelpText>The store location that this dwelling is related</inlineHelpText>
        <label>Store Location</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>The account must be of type &quot;Store&quot;</errorMessage>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Store</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Dwellings</relationshipLabel>
        <relationshipName>StoreLocation</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Dwelling</fullName>
        <active>true</active>
        <description>Used to support Dwelling</description>
        <label>Dwelling</label>
    </recordTypes>
    <recordTypes>
        <fullName>Store</fullName>
        <active>true</active>
        <description>Used to track and store data releated to Retail Locations both CORO and ARO</description>
        <label>Store</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

RbA Build/src/objects/Assigned_Resources__c.object
<CustomObject>
    <description>Resources Assigned to RbA Work Orders</description>
    <fields>
        <fullName>Work_Order_Type__c</fullName>
        <formula>TEXT(Work_Order__r.Work_Order_Type__c)</formula>
        <label>Work Order Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Work_Order__c</fullName>
        <inlineHelpText>Assigned Work Order</inlineHelpText>
        <label>Work Order</label>
        <referenceTo>RbA_Work_Order__c</referenceTo>
        <relationshipLabel>Assigned Resources</relationshipLabel>
        <relationshipName>Assigned_Resources</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Assigned Resource</label>
    <nameField>
        <displayFormat>AR#-{00}</displayFormat>
        <label>Assigned Resources #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assigned Resources</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

RbA Build/src/objects/MA_Scheduler_Event__c.object
<CustomObject>
    <fields>
        <fullName>RbA_Work_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>RbA Work Order</label>
        <referenceTo>RbA_Work_Order__c</referenceTo>
        <relationshipLabel>MA Scheduler Events</relationshipLabel>
        <relationshipName>MA_Scheduler_Events</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Resource__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Resource</label>
        <referenceTo>Resource__c</referenceTo>
        <relationshipLabel>MA Scheduler Events</relationshipLabel>
        <relationshipName>MA_Scheduler_Events</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Work_Order_Type__c</fullName>
        <formula>TEXT(RbA_Work_Order__r.Work_Order_Type__c)</formula>
        <label>Work Order Type</label>
        <type>Text</type>
    </fields>
    <label>MA Scheduler Event</label>
    <nameField>
        <label>MA Scheduler Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MA Scheduler Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

RbA Build/src/objects/MA_Scheduler_Settings__c.object
<CustomObject>
    <fields>
        <fullName>Resource_Id__c</fullName>
        <label>Resource Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Settings__c</fullName>
        <label>Settings</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Store_Id__c</fullName>
        <label>Store Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>MA Scheduler Settings</label>
    <nameField>
        <displayFormat>MASS - {000000}</displayFormat>
        <label>MA Scheduler Settings Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MA Scheduler Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

RbA Build/src/objects/RbA_Work_Order__c.object
<CustomObject>
    <description>Custom Object used to track Work Orders related to Orders.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Dwelling association to the Work Order.</inlineHelpText>
        <label>Account</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Dwelling</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>RbA Work Orders (Account)</relationshipLabel>
        <relationshipName>RbA_Work_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Name of the contact person from the customer account for this service order. Is a lookup to an existing salesforce contact record</description>
        <inlineHelpText>Name of the contact person from the customer account for this service order. Is a lookup to an existing salesforce contact record</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Service_Order</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>RbA Work Order</label>
    <nameField>
        <displayFormat>WO-{00000000}</displayFormat>
        <label>Work Order #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RbA Work Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

RbA Build/src/objects/Resource__c.object
<CustomObject>
    <description>Used to hold details about the recourse for scheduling</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>By default when a Resource is created they will be Active. Will be marked as inactive when any one of the liability insurance expires.</description>
        <inlineHelpText>Is this resource active?</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Crew_Size__c</fullName>
        <label>Crew Size</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RbA_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Enter individual for Tech Measure. Enter Crew name for Installer</inlineHelpText>
        <label>RbA User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Resources</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Resource_Type__c</fullName>
        <label>Primary Resource Type</label>
        <picklist>
            <picklistValues>
                <fullName>Tech Measure</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Install Crew</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Field Service</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Scheduler</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Retail_Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Store Configuration</label>
        <referenceTo>Store_Configuration__c</referenceTo>
        <relationshipLabel>Resources</relationshipLabel>
        <relationshipName>Resources</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Resource</label>
    <nameField>
        <label>Resource Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Resources</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

RbA Build/src/objects/Resource_Skill__c.object
<CustomObject>
    <description>Skills assigned to Resources</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>This checkbox determines if the resource skill is active or not</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Resource__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Resource</label>
        <referenceTo>Resource__c</referenceTo>
        <relationshipLabel>Resource Skills</relationshipLabel>
        <relationshipName>Resource_Skills</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <inlineHelpText>Select if this is a Primary or Secondary skills for the Resource.</inlineHelpText>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Primary</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Secondary</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Resource Skill</label>
    <nameField>
        <displayFormat>Resource Skill #-{00}</displayFormat>
        <label>Resource Skill #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Resource Skills</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

RbA Build/src/objects/RMS_Settings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>A name value list of RMS settings</description>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>RMS Settings</label>
</CustomObject>

RbA Build/src/objects/Store_Configuration__c.object
<CustomObject>
    <description>Holds Store Settings &amp; Configurations</description>
    <fields>
        <fullName>Order_Number__c</fullName>
        <label>Order Number</label>
        <precision>7</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Store__c</fullName>
        <label>Store</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Store Configurations</relationshipLabel>
        <relationshipName>Store_Configurations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Store Configuration</label>
    <nameField>
        <displayFormat>SS-{00}</displayFormat>
        <label>Store Setting Record #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Store Configurations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

RbA Build/src/objects/Work_Order_Required_Skill__c.object
<CustomObject>
    <description>Required Skills on the Work Order</description>
    <fields>
        <fullName>RbA_Work_Order__c</fullName>
        <label>RbA Work Order</label>
        <referenceTo>RbA_Work_Order__c</referenceTo>
        <relationshipLabel>Work Order Required Skills</relationshipLabel>
        <relationshipName>Work_Order_Required_Skills</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Work Order Required Skill</label>
    <nameField>
        <displayFormat>WO ReqSkill - {00}</displayFormat>
        <label>WO Required Skill #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work Order Required Skills</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

RbA Build/src/classes/MA_SchedulerFakeDataGenerator.cls
/************************************************************************************/
/*                                                                                  */
/*      This class is used to create fake data for the test classes 				*/
/*                                                                                  */
/*      @author     Daniel Taylor   (MapAnything)                                   */
/*                  Ethan Rush      (MapAnything)                                   */
/*                                                                                  */
/*      @version    6/29/2016   MapAnything                                         */
/*      Created                                                                     */
/*                                                                                  */
/*      @copyright (c)2016 MapAnything. All Rights Reserved.                        */
/*      Unauthorized use is prohibited                                              */
/*                                                                                  */
/************************************************************************************/

public class MA_SchedulerFakeDataGenerator {
	
	public static Map<String, Object> deserializeResponse(String responseString) {
		return (Map<String, Object>)JSON.deserializeUntyped(responseString);
	}

	public static Store_Configuration__c createFakeStoreConfig(Boolean insertNeeded, Id storeId) {
		Store_Configuration__c storeConfig = new Store_Configuration__c(
			Store__c = storeId,
			Order_Number__c = 1
		);

		if (insertNeeded) {
			insert storeConfig;

			Account store = [SELECT Id FROM Account WHERE Id = :storeId];
			store.Active_Store_Configuration__c = storeConfig.Id;
			update store;
		}

		return storeConfig;
	}

	public static Account createFakeStore(Boolean insertNeeded) {
		Id storeRecordTypeId = [SELECT Id FROM RecordType WHERE SObjectType = 'Account' AND DeveloperName = 'Store'].Id;

		if (RMS_Settings__c.getInstance('Data Loading Profile ID') == null || String.isBlank(RMS_Settings__c.getValues('Data Loading Profile ID').value__c)) {
			insert new RMS_Settings__c(
				Name = 'Data Loading Profile ID',
				Value__c = '2'
			);
		}

		Account store = new Account(
			Type = 'South',
			Name = 'Atlanta Office',
			ShippingCity = 'Atlanta',
			ShippingState = 'Georgia',
			ShippingPostalCode = '30328',
			RecordTypeId = storeRecordTypeId,
			ShippingStreet = '10 Glenlake Pkwy',
			ShippingLongitude = -84.361648, 
			ShippingLatitude = 33.936008
		);

		if (insertNeeded) {
			insert store;
		}

		return store;
	}

	public static Resource__c createFakeResource(Boolean insertNeeded, String resType, Id storeConfigId) {
		Resource__c res = new Resource__c(
			Active__c = true,
			Crew_Size__c = 5,
			Resource_Type__c = resType,
			Retail_Location__c = storeConfigId,
			RbA_User__c = UserInfo.getUserId()
		);

		if (insertNeeded) {
			insert res;
		}

		return res;
	}

	public static MA_Scheduler_Settings__c createFakeSetting(Boolean insertNeeded, Id storeConfigId, Id resId, Boolean isError) {
		String resourceSetting = '{"resourceHours":{"Monday":[{"start":"07:00","end":"20:00"}],"Tuesday":[{"start":"07:00","end":"20:00"}],"Wednesday":[{"start":"07:00","end":"20:00"}],"Thursday":[{"start":"07:00","end":"20:00"}],"Friday":[{"start":"07:00","end":"20:00"}],"Saturday":[{"start":"07:00","end":"20:00"}],"Sunday":[{"start":"07:00","end":"20:00"}]}}';
		String storeSetting = '{"timezone":"America/Chicago",';
		if (!isError) {
		      storeSetting += '"esriClientId":"1J1NXVUC9GGzfaqN","esriClientSecret":"de5b27126b874e34abda94f8a66de056","esriClientSecretVerified":true,';
		}
		storeSetting += '"storeHours":{"Monday":[{"start":"10:00","end":"16:00"}],"Tuesday":[{"start":"10:00","end":"16:00"}],"Wednesday":[{"start":"10:00","end":"16:00"}],"Thursday":[{"start":"10:00","end":"18:00"}],"Friday":[{"start":"06:00","end":"20:00"}],"Saturday":[{"start":"06:00","end":"20:00"}]},'
						+ '"Tech Measure":{"bookingWindows":{"Monday":[{"start":"10:00","end":"12:00"},{"start":"14:00","end":"16:00"}],"Tuesday":[{"start":"10:00","end":"12:00"},{"start":"14:00","end":"16:00"}],"Wednesday":[{"start":"10:00","end":"12:00"},{"start":"14:00","end":"16:00"}],"Thursday":[{"start":"10:00","end":"12:00"},{"start":"14:00","end":"16:00"},{"start":"16:00","end":"18:00"}],"Friday":[{"start":"08:00","end":"10:00"},{"start":"10:00","end":"12:00"},{"start":"14:00","end":"16:00"},{"start":"16:00","end":"18:00"}],"Saturday":[{"start":"08:00","end":"10:00"},{"start":"10:00","end":"12:00"},{"start":"14:00","end":"16:00"},{"start":"16:00","end":"18:00"}],"Sunday":[{"start":"08:00","end":"10:00"},{"start":"10:00","end":"12:00"},{"start":"14:00","end":"16:00"},{"start":"16:00","end":"18:00"}]}},'
						+ '"Install":{"bookingWindows":{"Monday":[{"start":"10:00","end":"16:00"}],"Tuesday":[{"start":"10:00","end":"16:00"}],"Wednesday":[{"start":"10:00","end":"16:00"}],"Thursday":[{"start":"10:00","end":"14:00"},{"start":"14:00","end":"18:00"}],"Friday":[{"start":"06:00","end":"10:00"},{"start":"10:00","end":"14:00"},{"start":"14:00","end":"20:00"}],"Saturday":[{"start":"06:00","end":"10:00"},{"start":"10:00","end":"14:00"},{"start":"14:00","end":"20:00"}]}},'
						+ '"storeHolidays":[{"date":"01/01/2016","reason":"New Year\'s","dayOfWeek":"Friday"},{"date":"05/10/2016","reason":"Memorial Day","dayOfWeek":"Tuesday"},{"date":"11/24/2016","reason":"Thanksgiving","dayOfWeek":"Thursday"},{"date":"11/25/2016","reason":"Black Friday","dayOfWeek":"Friday"},{"date":"12/23/2016","reason":"Christmas Eve","dayOfWeek":"Friday"},{"date":"12/26/2016","reason":"Christmas Day","dayOfWeek":"Monday"},{"date":"01/02/2017","reason":"","dayOfWeek":"Monday"}]}';
		
		MA_Scheduler_Settings__c setting = new MA_Scheduler_Settings__c(
			Resource_Id__c = resId,
			Store_Id__c = storeConfigId,
			Settings__c = resId == null ? storeSetting : resourceSetting
		);

		if (insertNeeded) {
			insert setting;
		}

		return setting;
	}

	public static Account createFakeDwelling(Boolean insertNeeded, Id storeId) {
		Id dwellingRecordTypeId = [SELECT Id FROM RecordType WHERE SObjectType = 'Account' AND DeveloperName = 'Dwelling'].Id;

		Account dwelling = new Account(
			Type = 'South',
			Name = 'House',
			ShippingState = 'Georgia',
			Dwelling_Style__c = 'House',
			Store_Location__c = storeId,
			ShippingPostalCode = '30043',
			ShippingCity = 'Lawrenceville',
			RecordTypeId = dwellingRecordTypeId,
			ShippingStreet = '2820 Springtime Ct', 
			ShippingLongitude = 34.044074,
			ShippingLatitude = -84.007345
		);

		if (insertNeeded) {
			insert dwelling;
		}

		return dwelling;
	}

	public static Contact createFakeContact(Boolean insertNeeded, Id storeId) {
		Contact homeOwner = new Contact(
			LastName = 'Taylor',
			AccountId = storeId,
			FirstName = 'Daniel'
		);

		if (insertNeeded) {
			insert homeOwner;
		}

		return homeOwner;
	}

	public static RbA_Work_Order__c createFakeWorkOrder(Boolean insertNeeded, Id dwellingId, Id homeOwnerId, String workOrderType) {
		RbA_Work_Order__c wo = new RbA_Work_Order__c(
			Account__c = dwellingId,
			Contact__c = homeOwnerId,
			Work_Order_Type__c = workOrderType
		);

		if (insertNeeded) {
			insert wo;
		}

		return wo;
	}

	public static RbA_Work_Order__c createFakeBookedWorkOrder(Boolean insertNeeded, Id dwellingId, Id homeOwnerId, String workOrderType, Boolean isMultiDay) {
		RbA_Work_Order__c wo = new RbA_Work_Order__c(
			Account__c = dwellingId,
			Contact__c = homeOwnerId,
			Work_Order_Type__c = workOrderType,
			Appointment_End_Time__c = '12:00 PM',
			Appointment_Start_Time__c = '10:00 AM',
			Appointment_Duration__c = isMultiDay ? 20 : 2,
			Appointment_Date__c = Date.parse('01/10/1987')
		);

		if (insertNeeded) {
			insert wo;
		}

		return wo;
	}

	public static MA_Scheduler_Event__c createFakeMaEvent(Boolean insertNeeded, Id woId, Id resourceId) {
		Date startDate = Date.parse('01/10/1987');
		Time startTime = Time.newInstance(12, 0, 0, 0);
		DateTime startDateTime = DateTime.newInstance(startDate, startTime);
		DateTime endDateTime = startDateTime.addHours(2);

		MA_Scheduler_Event__c maEvent = new MA_Scheduler_Event__c(
			Date__c = startDate,
			Resource__c = resourceId,
			RbA_Work_Order__c = woId,
			EndDateTime__c = endDateTime,
			StartDateTime__c = startDateTime,
			Estimated_End_Date_Time__c = endDateTime,
			Estimated_Start_Date_Time__c = startDateTime
		);

		if (insertNeeded) {
			insert maEvent;
		}

		return maEvent;
	}

	public static Event createFakeSfEvent(Boolean insertNeeded, Id maEventId) {
		Date startDate = Date.parse('01/10/1987');
		Time startTime = Time.newInstance(12, 0, 0, 0);
		DateTime startDateTime = DateTime.newInstance(startDate, startTime);

		Event sfEvent = new Event(
			StartDateTime = startDateTime,
			OwnerId = UserInfo.getUserId(),
			MA_Scheduler_Event__c = maEventId,
			EndDateTime = startDateTime.addHours(2)
		);

		if (insertNeeded) {
			try {
				insert sfEvent;
			}
			catch(Exception ex) {}
		}

		return sfEvent;
	}

	public static RbA_Skills__c createFakeSkill(Boolean insertNeeded, String skillName) {
		RbA_Skills__c skill = new RbA_Skills__c(
			Name = skillName
		);

		if (insertNeeded) {
			insert skill;
		}

		return skill;
	}

	public static Resource_Skill__c createFakeResourceSkill(Boolean insertNeeded, Id skillId, Id resourceId) {
		Resource_Skill__c skill = new Resource_Skill__c(
			Type__c = 'Primary',
			RbA_Skill__c = skillId,
			Resource__c = resourceId
		);

		if (insertNeeded) {
			insert skill;
		}

		return skill;
	}

	public static Work_Order_Required_Skill__c createFakeWorkOrderSkill(Boolean insertNeeded, Id skillId, Id woId) {
		Work_Order_Required_Skill__c skill = new Work_Order_Required_Skill__c(
			RbA_Skill__c = skillId,
			RbA_Work_Order__c = woId
		);

		if (insertNeeded) {
			insert skill;
		}

		return skill;
	}

	public static Assigned_Resources__c createFakeAssignedResource(Boolean insertNeeded, Id woId, Id resourceId, Boolean isPrimary) {
		Assigned_Resources__c assignedResource = new Assigned_Resources__c(
			Work_Order__c = woId,
			IsPrimary__c = isPrimary,
			Scheduled_Resource__c = resourceId
		);

		if (insertNeeded) {
			insert assignedResource;
		}

		return assignedResource;
	}
	
}