RbA Build/src/objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Dwelling</fullName>
        <active>true</active>
        <description>Used to support Dwelling</description>
        <label>Dwelling</label>
    </recordTypes>
    <recordTypes>
        <fullName>Store</fullName>
        <active>true</active>
        <description>Used to track and store data releated to Retail Locations both CORO and ARO</description>
        <label>Store</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

RbA Build/src/objects/Municipality__c.object
<CustomObject>
    <description>Holds Municipality information that will help with HOA, Historical and Permitting details.</description>
    <fields>
        <fullName>Application_Notes__c</fullName>
        <inlineHelpText>Notes about the Application process</inlineHelpText>
        <label>Application Notes</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>City_Township__c</fullName>
        <label>City/Township</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>County__c</fullName>
        <label>County</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>For_Retail_Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>What Retail Location is this for?</inlineHelpText>
        <label>For Retail Location</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Store</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Municipalities</relationshipLabel>
        <relationshipName>Municipalities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <inlineHelpText>Sched Department Phone or Main Line</inlineHelpText>
        <label>Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zip_Code__c</fullName>
        <label>Zip Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Municipality</label>
    <nameField>
        <label>Agency Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Municipalities</pluralLabel>
    <recordTypes>
        <fullName>HOA</fullName>
        <active>true</active>
        <description>Homeowner Association Details</description>
        <label>HOA</label>
    </recordTypes>
    <recordTypes>
        <fullName>Historical</fullName>
        <active>true</active>
        <description>Holds information on Historial requirements</description>
        <label>Historical</label>
    </recordTypes>
    <recordTypes>
        <fullName>Permit</fullName>
        <active>true</active>
        <description>Hold information for Building Permits (not Building)</description>
        <label>Permit</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

RbA Build/src/objects/RbA_Work_Order__c.object
<CustomObject>
    <description>Custom Object used to track Work Orders related to Orders.</description>
    <fields>
        <fullName>Application_Notes__c</fullName>
        <inlineHelpText>Pulled from Municipality record</inlineHelpText>
        <label>Application Notes</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Municipality__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>What Municipality does this Dwelling fall into?</inlineHelpText>
        <label>Municipality</label>
        <referenceTo>Municipality__c</referenceTo>
        <relationshipLabel>Permit Work Orders</relationshipLabel>
        <relationshipName>Work_Orders_Permits1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <description>“State” part of the work order location</description>
        <inlineHelpText>“State” part of the work order location</inlineHelpText>
        <label>State</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Work_Order_Type__c</fullName>
        <description>Type of work order: HOA, Historical, LSWP, Building, Tech Measure, Install, Service. etc.</description>
        <inlineHelpText>Type of work order: HOA, Historical, LSWP, Building, Tech Measure, Install, Service. etc.</inlineHelpText>
        <label>Work Order Type</label>
        <picklist>
            <picklistValues>
                <fullName>Tech Measure</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Install</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Service</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HOA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Historical</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Building Permit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Paint/Stain</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LSWP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Collections</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>RbA Work Order</label>
    <nameField>
        <displayFormat>WO-{00000000}</displayFormat>
        <label>Work Order #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RbA Work Orders</pluralLabel>
    <recordTypes>
        <fullName>Actions</fullName>
        <active>true</active>
        <description>Holds HOA and Historical Details</description>
        <label>Actions</label>
    </recordTypes>
    <recordTypes>
        <fullName>Permit</fullName>
        <active>true</active>
        <description>Holds Building Permit Details</description>
        <label>Permit</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

RbA Build/src/classes/testRMS_addApplicationNotes.cls
@isTest
public with sharing class testRMS_addApplicationNotes {
    
    static testMethod void createRecords(){
        TestUtilityMethods utility = new TestUtilityMethods();
        utility.setUpConfigs();
        
        id dwellingRT = UtilityMethods.retrieveRecordTypeId('Dwelling', 'Account');
        id muniPermitRT = UtilityMethods.retrieveRecordTypeId('Permit', 'Municipality__c');
        
        Account store = [SELECT id FROM Account WHERE Name ='77 - Twin Cities, MN'];
        
        List<Municipality__c> muniList = new List<Municipality__c>();
        Municipality__c muni1 = new Municipality__c( name = 'Muni 1', recordTypeId=muniPermitRT, Application_Notes__c = 'Testing Notes', City_Township__c = 'Chicago', State__c = 'IL', Zip_Code__c = '60618', County__c = 'Cook', Phone__c = '555-555-5555', For_Retail_Location__c = store.Id);
        muniList.add(muni1);
        Municipality__c muni2 = new Municipality__c( name = 'Muni 1', recordTypeId=muniPermitRT, Application_Notes__c = 'Testing Notes', City_Township__c = 'Chicago', State__c = 'IL', Zip_Code__c = '60618', County__c = 'Cook', Phone__c = '555-555-5555', For_Retail_Location__c = store.Id);
        muniList.add(muni2);
        insert muniList;
        
        System.assertEquals(muniList.size(), 2);
        
        
        Id actionWORecordTypeId = UtilityMethods.retrieveRecordTypeId('Actions', 'RbA_Work_Order__c');
        Id permitWORecordTypeId = UtilityMethods.retrieveRecordTypeId('Permit', 'RbA_Work_Order__c');
        
        List<RbA_Work_Order__c> woList = new List<RbA_Work_Order__c>();
        RbA_Work_Order__c wo1 = new RbA_Work_Order__c(  RecordTypeId = actionWORecordTypeId,  
                                                      Work_Order_Type__c = 'HOA',
                                                      Municipality__c = muni1.id
                                                     );
        woList.add(wo1);
        RbA_Work_Order__c wo2 = new RbA_Work_Order__c(  RecordTypeId = actionWORecordTypeId,  
                                                      Work_Order_Type__c = 'Historical',
                                                      Municipality__c = muni1.id
                                                     );
        woList.add(wo2);
        RbA_Work_Order__c wo3 = new RbA_Work_Order__c(  RecordTypeId = permitWORecordTypeId,  
                                                      Work_Order_Type__c = 'Building Permit',
                                                      Municipality__c = muni1.id
                                                     );
        woList.add(wo3);
        insert woList;
        
        System.assertEquals(woList.size(),3);
        
        
    }
    
    static testMethod void updateRecords(){
        TestUtilityMethods utility = new TestUtilityMethods();
        utility.setUpConfigs();
        
        id dwellingRT = UtilityMethods.retrieveRecordTypeId('Dwelling', 'Account');
        id muniPermitRT = UtilityMethods.retrieveRecordTypeId('Permit', 'Municipality__c');
        
        Account store = [SELECT id FROM Account WHERE Name ='77 - Twin Cities, MN'];
        
        List<Municipality__c> muniList = new List<Municipality__c>();
        Municipality__c muni1 = new Municipality__c( name = 'Muni 1', recordTypeId=muniPermitRT, Application_Notes__c = 'Testing Notes', City_Township__c = 'Chicago', State__c = 'IL', Zip_Code__c = '60618', County__c = 'Cook', Phone__c = '555-555-5555', For_Retail_Location__c = store.Id);
        muniList.add(muni1);
        Municipality__c muni2 = new Municipality__c( name = 'Muni 1', recordTypeId=muniPermitRT, Application_Notes__c = 'Testing Notes', City_Township__c = 'Chicago', State__c = 'IL', Zip_Code__c = '60618', County__c = 'Cook', Phone__c = '555-555-5555', For_Retail_Location__c = store.Id);
        muniList.add(muni2);
        insert muniList;
        
        System.assertEquals(muniList.size(), 2);
        
        
        Id actionWORecordTypeId = UtilityMethods.retrieveRecordTypeId('Actions', 'RbA_Work_Order__c');
        Id permitWORecordTypeId = UtilityMethods.retrieveRecordTypeId('Permit', 'RbA_Work_Order__c');
        
        List<RbA_Work_Order__c> woList = new List<RbA_Work_Order__c>();
        RbA_Work_Order__c wo1 = new RbA_Work_Order__c(  RecordTypeId = actionWORecordTypeId,  
                                                      Work_Order_Type__c = 'HOA'                                        
                                                     );
        woList.add(wo1);
        RbA_Work_Order__c wo2 = new RbA_Work_Order__c(  RecordTypeId = actionWORecordTypeId,  
                                                      Work_Order_Type__c = 'Historical'
                                                     );
        woList.add(wo2);
        RbA_Work_Order__c wo3 = new RbA_Work_Order__c(  RecordTypeId = permitWORecordTypeId,  
                                                      Work_Order_Type__c = 'Building Permit'
                                                     );
        woList.add(wo3);
        insert woList;
        
        System.assertEquals(woList.size(),3);
        
        wo1.Municipality__c = muni1.Id;
        update wo1;
        wo2.Municipality__c = muni1.Id;
        update wo2;
        wo3.Municipality__c = muni1.Id;
        update wo3;
        
        
    }
    
    
}