RbA Build/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Building_Permit__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The Building Permit is populated in Code
Matching in the Municipalities table.
Matching criteria Address City and Zip code, match is found in the Municipality Match object</inlineHelpText>
        <label>Building Permit</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>You must select a Building record. If the record for you are for isn&apos;t in the system, please contact your manager to have it created.</errorMessage>
            <filterItems>
                <field>Municipality__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Permit</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Municipality__c</referenceTo>
        <relationshipLabel>Building Permit Dwellings</relationshipLabel>
        <relationshipName>Accounts2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Store_Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The store location that this dwelling is related</description>
        <inlineHelpText>The store location that this dwelling is related</inlineHelpText>
        <label>Store Location</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>The account must be of type &quot;Store&quot;</errorMessage>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Store</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Dwellings</relationshipLabel>
        <relationshipName>StoreLocation</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Dwelling</fullName>
        <active>true</active>
        <description>Used to support Dwelling</description>
        <label>Dwelling</label>
    </recordTypes>
    <recordTypes>
        <fullName>Store</fullName>
        <active>true</active>
        <description>Used to track and store data releated to Retail Locations both CORO and ARO</description>
        <label>Store</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

RbA Build/src/objects/Municipality__c.object
<CustomObject>
    <description>Holds Municipality information that will help with HOA, Historical and Permitting details.</description>
    <fields>
        <fullName>City_Township__c</fullName>
        <label>City/Township</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>For_Retail_Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>What Retail Location is this for?</inlineHelpText>
        <label>For Retail Location</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Store</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Municipalities</relationshipLabel>
        <relationshipName>Municipalities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Zip_Code__c</fullName>
        <label>Zip Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Municipality</label>
    <nameField>
        <label>Agency Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Municipalities</pluralLabel>
    <recordTypes>
        <fullName>Permit</fullName>
        <active>true</active>
        <description>Hold information for Building Permits (not Building)</description>
        <label>Permit</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

RbA Build/src/objects/Municipality_Match__c.object
<CustomObject>
    <fields>
        <fullName>Agency_Name__c</fullName>
        <label>Agency Name</label>
        <referenceTo>Municipality__c</referenceTo>
        <relationshipLabel>Municipalities Match</relationshipLabel>
        <relationshipName>Municipalities_Match</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>City_Township__c</fullName>
        <label>City/Township</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zip_Code__c</fullName>
        <label>Zip Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Municipality Match</label>
    <nameField>
        <displayFormat>MM-{00}</displayFormat>
        <label>Municipality Match Record Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Municipalities Match</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

RbA Build/src/classes/RMS_MunicipalityMatchManager.cls
/*******************************************************//**

@class	RMS_MunicipalityMatchManager

@brief	Controller to hold logic about matching Municipalities to Dwellings(Accounts).

@author  Anthony Strafaccia (Slalom.ADS)

@version	2015-10/27  Slalom.ADS
	Created.

@see		RMS_MunicipalityMatchManagerTest

@copyright  (c)2015 Slalom.  All Rights Reserved.
			Unauthorized use is prohibited.

***********************************************************/

public with sharing class RMS_MunicipalityMatchManager {

    public void matchBuildingPermitMunicipality(List<Account> listNew){ 
        system.debug('******INSIDE RMS_MunicipalityMatchManager/matchBuildingPermitMunicipality'); 
		
		//CREATE LIST TO ALLOW EDITING
 		list<Account> dwellingList = new list<Account>();
 		
        //SETTING UP RECORD TYPES VAR 
        Id dwellingAccountRecordType = UtilityMethods.retrieveRecordTypeId(Constants.DWELLING_ACCOUNT_RECORD_TYPE_NAME , 'Account');
        Id buildingPermitMunicipalitiesRecordType = UtilityMethods.retrieveRecordTypeId(Constants.PERMIT_MUNICIPALITY_RECORD_TYPE_NAME , 'Municipality__c');
        
        //BUILDING LIST OF STORE LOCATION IDs TO BE USED LATER
        list<id> storeLocationIds = new list<id>();
        
        //FOR LOOP TO REMOVE NON-DWELLING RECORD TYPE AND NULL ZIP CODE OR CITY BY ADDING TO NEW LIST
        for(Account acct : listNew){
        	if(acct.RecordTypeId == dwellingAccountRecordType && acct.BillingPostalCode != null && acct.BillingCity != null){
        		storeLocationIds.add(acct.Store_Location__c);
        		dwellingList.add(acct);
        	}
        }
	
		//GETTING ALL BUILDING PERMIT RECORD TYPE MUNICIPALITYS RELATED TO STORES
        list<Municipality__c> permitMunicipalities = [SELECT Id  FROM Municipality__c WHERE For_Retail_Location__c IN :storeLocationIds AND RecordTypeId = :buildingPermitMunicipalitiesRecordType];
        list<id> permitMunicipalityIds = new list<id>();
        
        //IF NO MUNICIPALITIES THEN SKIP REST OF LOGIC
        if(permitMunicipalities.size() > 0){
        	
        	//CREATING LIST OF MUNICIPALITY IDs TO BE USED LATER
	        for(Municipality__c muni : permitMunicipalities){
	        	permitMunicipalityIds.add(muni.Id);
	        }
        
	        list<Municipality_Match__c> permitMunicipalityMatchs = [SELECT 	id, 
	        																Agency_Name__c, 
	        																Zip_Code__c, 
	        																City_Township__c, 
	        																Agency_Name__r.For_Retail_Location__c 
    																FROM Municipality_Match__c 
    																WHERE Agency_Name__c IN :permitMunicipalityIds];
			
			//IF NO MUNICIPALITY MATCHES THEN SKIP REST OF LOGIC
			if(permitMunicipalityMatchs.size() > 0){
		        
		        //CREATE MAP OF STORE ID TO LIST OF MUNICIPALITY MATCHES
		        map<id, list<Municipality_Match__c>> storeIDtoListOfMatchMap = new  map<id, list<Municipality_Match__c>>();
				for(Municipality_Match__c muniMatch : permitMunicipalityMatchs){
					if(storeIDtoListOfMatchMap.containsKey(muniMatch.Agency_Name__r.For_Retail_Location__c)){
						storeIDtoListOfMatchMap.get(muniMatch.Agency_Name__r.For_Retail_Location__c).add(muniMatch);
					}else{
						storeIDtoListOfMatchMap.put(muniMatch.Agency_Name__r.For_Retail_Location__c, new list<Municipality_Match__c>{muniMatch});
					}	
				}   
		
		        //LOOP THROUGH DWELLINGS TO PREFORM LOGIC OF ASSINGING MUNICIPALITY
		        for(Account dwelling : dwellingList){
		        	
		        	//GET LIST OF MUNICIPALITY MATCHES AND LOOP THROUGH THEM TO CHECK FOR A ZIP&CITY MATCH
	        		list<Municipality_Match__c> relatedMatches = storeIDtoListOfMatchMap.get(dwelling.Store_Location__c);
	        		
	        		for(Municipality_Match__c mm : relatedMatches){
	        			if(	mm.Zip_Code__c == dwelling.BillingPostalCode && mm.City_Township__c.toUpperCase() == dwelling.BillingCity.toUpperCase()){
	        				
	        				//IF MATCHED ZIP&CITY THEN ASSIGN BUILDING PERMIT MUNICIPALITY TO DWELLING AND BREAK LOOP
	        				dwelling.Building_Permit__c = mm.Agency_Name__c;
	        				break;
	    				}
	        		}
		        }
	        
			} // END OF IF permitMunicipalityMatchs.size() > 0
       
        } // END OF IF permitMunicipalities.size() > 0
   
    } // END OF matchBuildingPermitMunicipality
    
    
    
} // EOF