RbA Build/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Store_Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The store location that this dwelling is related</description>
        <inlineHelpText>The store location that this dwelling is related</inlineHelpText>
        <label>Store Location</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>The account must be of type &quot;Store&quot;</errorMessage>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Store</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Dwellings</relationshipLabel>
        <relationshipName>StoreLocation</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

RbA Build/src/objects/Discount__c.object
<CustomObject>
    <description>Discounts &amp; promotions for customers</description>
    <fields>
        <fullName>Store_Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The store or group of stores this discount is used by</description>
        <inlineHelpText>The store or group of stores this discount is used by</inlineHelpText>
        <label>Store Location</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>The selected account must be a store.</errorMessage>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Store</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Discounts</relationshipLabel>
        <relationshipName>Discounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Discount</label>
    <nameField>
        <label>Discount Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Discounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

RbA Build/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Discount_Amount__c</fullName>
        <description>The rollup of discounts applied to the opportunity</description>
        <inlineHelpText>The rollup of discounts applied to the opportunity</inlineHelpText>
        <label>Discount Amount</label>
        <summarizedField>Opportunity_Discount__c.Discount_Amount__c</summarizedField>
        <summaryFilterItems>
            <field>Opportunity_Discount__c.Status__c</field>
            <operation>notEqual</operation>
            <value>Cancelled</value>
        </summaryFilterItems>
        <summaryForeignKey>Opportunity_Discount__c.Opportunity__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Discount__c</fullName>
        <description>The discount percent applied to the whole opportunity amount.</description>
        <inlineHelpText>The discount percent applied to the whole opportunity amount.</inlineHelpText>
        <label>Discount</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Store_Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Store Location</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>The account must be of type &quot;Store&quot;.</errorMessage>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Store</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Store Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

RbA Build/src/objects/Opportunity_Discount__c.object
<CustomObject>
    <description>Junction from the discount to the opportunity</description>
    <fields>
        <fullName>Discount_Amount__c</fullName>
        <defaultValue>0</defaultValue>
        <description>The amount in dollars discounted from the opportunity.</description>
        <inlineHelpText>The amount in dollars discounted from the opportunity.</inlineHelpText>
        <label>Discount Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Discount__c</fullName>
        <description>The discount linked to this discount applied junction.</description>
        <inlineHelpText>The discount linked to this discount applied junction.</inlineHelpText>
        <label>Discount</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Discount__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Discount__c</referenceTo>
        <relationshipLabel>Opportunity Discounts</relationshipLabel>
        <relationshipName>Opportunity_Discount_Applied</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <description>The discount is applied to this opportunity</description>
        <inlineHelpText>The discount is applied to this opportunity</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Discount_Applied</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>The status of the opportunity discount.</description>
        <inlineHelpText>The status of the opportunity discount.</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Applied</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Store_Location__c</fullName>
        <description>The discount&apos;s store location</description>
        <formula>Discount__r.Store_Location__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>The discount&apos;s store location</inlineHelpText>
        <label>Store Location</label>
        <type>Text</type>
    </fields>
    <label>Opportunity Discount</label>
    <nameField>
        <displayFormat>OD-{00000000}</displayFormat>
        <label>Opportunity Discount Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Discounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

RbA Build/src/objects/Order.object
<CustomObject>
    <fields>
        <fullName>Discount_Amount__c</fullName>
        <description>A roll-up sum of all discounts applied to this order (see the order discount related list).</description>
        <inlineHelpText>A roll-up sum of all discounts applied to this order (see the order discount related list).</inlineHelpText>
        <label>Discount Amount</label>
        <summarizedField>Order_Discount__c.Discount_Amount__c</summarizedField>
        <summaryFilterItems>
            <field>Order_Discount__c.Status__c</field>
            <operation>equals</operation>
            <value>Applied</value>
        </summaryFilterItems>
        <summaryForeignKey>Order_Discount__c.Order__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Discount__c</fullName>
        <formula>Discount_Amount__c/Retail_Total__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Discount %</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Store_Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This order is related to this store location.</description>
        <inlineHelpText>This order is related to this store location.</inlineHelpText>
        <label>Store Location</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Orders (Store Location)</relationshipLabel>
        <relationshipName>Orders1</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

RbA Build/src/objects/Order_Discount__c.object
<CustomObject>
    <description>Junction from the discount to the order</description>
    <fields>
        <fullName>Discount_Amount__c</fullName>
        <defaultValue>0</defaultValue>
        <description>The amount in dollars discounted from the order.</description>
        <inlineHelpText>The amount in dollars discounted from the order.</inlineHelpText>
        <label>Discount Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <description>The discount is applied to this order</description>
        <inlineHelpText>The discount is applied to this order</inlineHelpText>
        <label>Order</label>
        <referenceTo>Order</referenceTo>
        <relationshipName>Discount_Applied</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>The status of the order discount.</description>
        <inlineHelpText>The status of the order discount.</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Applied</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Store_Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The store location that is creating this discount.</description>
        <inlineHelpText>The store location that is creating this discount.</inlineHelpText>
        <label>Store Location</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Store</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Order Discounts</relationshipLabel>
        <relationshipName>Order_Discounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Order Discount</label>
    <nameField>
        <displayFormat>OD-{00000000}</displayFormat>
        <label>Order Discount Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Discounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

RbA Build/src/objects/OrderItem.object
<CustomObject>
    <fields>
        <fullName>Discount_Amount__c</fullName>
        <description>The discount (in currency) applied to the purchase order (used for AROs)</description>
        <inlineHelpText>The discount (in currency) applied to the purchase order (used for AROs).</inlineHelpText>
        <label>Discount Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>The status of the order line item.</description>
        <inlineHelpText>The status of the order line item.</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Configured</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Verified</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Partially Received</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Received</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

RbA Build/src/objects/Quote.object
<CustomObject>
    <fields>
        <fullName>Discount_Amount__c</fullName>
        <description>The rollup of discounts applied to the quote</description>
        <inlineHelpText>The rollup of discounts applied to the quote</inlineHelpText>
        <label>Discount Amount</label>
        <summarizedField>Quote_Discount__c.Discount_Amount__c</summarizedField>
        <summaryFilterItems>
            <field>Quote_Discount__c.Status__c</field>
            <operation>notEqual</operation>
            <value>Cancelled</value>
        </summaryFilterItems>
        <summaryForeignKey>Quote_Discount__c.Quote__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Discount__c</fullName>
        <description>Discount applied to the entire quote.</description>
        <inlineHelpText>Discount applied to the entire quote.</inlineHelpText>
        <label>Discount</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

RbA Build/src/classes/RMS_salesOrderManager.cls
public with sharing class RMS_salesOrderManager {

	 public void createSalesOrderOnOpportunityClosedWon(List<Opportunity> listOld, List<Opportunity> listNew, Map<Id, Opportunity> mapOld, Map<Id, Opportunity> mapNew){
	 	system.debug('****** Inside RMS_salesOrderManager/createSalesOrderOnOpportunityClosedWon');
	 	
	 	
	 	//CREATE AND POPULATE LIST OF ONLY OPPORTUNITIES THAT HAVE BEEN CLOSED/WON AND HAVE A SYNCED QUOTE TO PREFORM LOGIC ON
	 	list<Opportunity> closedWonOpportunities = new list<Opportunity>();
	 	list<Id> closedWonOpportunitiesIds = new list<Id>();

	 	
	 	for(Opportunity opp : listNew){
	 		if(	opp.IsWon == true  &&  mapOld.get(opp.id).IsWon != true  &&  opp.SyncedQuoteId != null ){
		 		closedWonOpportunitiesIds.add(opp.id);
	 		}
	 	}
		//QUERY FOR ADDITIONAL FIELDS NOT PASSED BY TRIGGER
		closedWonOpportunities = [SELECT 	id,
											AccountId,
											Store_Location__r.id,
											OwnerId,
											Description,
											SyncedQuoteId,
											Pricebook2Id,
											Account.BillingStreet,
											Account.BillingCity,
											Account.BillingStateCode,
											Account.BillingPostalCode, 
											Account.BillingCountryCode,
											CloseDate
											
								FROM Opportunity WHERE Id IN :closedWonOpportunitiesIds];	
		
		//CREATE MAP OF OPPORTUNITYID TO OPPORTUNITYCONTACTROLE LIST TO BE USED TO ASSIGN ORDER BILL TO CONTACT
		list<OpportunityContactRole> relatedOpportunityContactRole = [SELECT Id, IsPrimary, OpportunityId, ContactId, Contact.LastName FROM OpportunityContactRole WHERE OpportunityId IN :closedWonOpportunitiesIds];
		map<id, list<OpportunityContactRole>> oppIdToListofOpportunityContactRoleMap = new map<id, list<OpportunityContactRole>>();
		for(OpportunityContactRole ocr : relatedOpportunityContactRole){
	 		if(oppIdToListofOpportunityContactRoleMap.containsKey(ocr.OpportunityId)){
				oppIdToListofOpportunityContactRoleMap.get(ocr.OpportunityId).add(ocr);
			}else{
				oppIdToListofOpportunityContactRoleMap.put(ocr.OpportunityId, new list<OpportunityContactRole>{ocr});
			}	
	 	}
	 	
	 	//CREATE MAP OF OPPORTUNITYID TO Opportunity_Discount__c LIST TO BE USED TO BUILD OrderDiscountS
		list<Opportunity_Discount__c > relatedOpportunityDiscount = [SELECT Status__c, Discount__c, Discount_Amount__c, Opportunity__c  FROM Opportunity_Discount__c WHERE Opportunity__c IN :closedWonOpportunitiesIds];
		map<id, list<Opportunity_Discount__c>> oppIdToListofOpportunityDiscountMap = new map<id, list<Opportunity_Discount__c>>();
		
		for(Opportunity_Discount__c oppD : relatedOpportunityDiscount){
	 		if(oppIdToListofOpportunityDiscountMap.containsKey(oppD.Opportunity__c)){
				oppIdToListofOpportunityDiscountMap.get(oppD.Opportunity__c).add(oppD);
			}else{
				oppIdToListofOpportunityDiscountMap.put(oppD.Opportunity__c, new list<Opportunity_Discount__c>{oppD});
			}	
	 	}
		 
		
	 	system.debug('****** closedWonOpportunities.size(): '+closedWonOpportunities.size());
	 	if(closedWonOpportunities.size() > 0){
		 	//DYNAMICLY QUERY FOR ALL OPPORTUNITYLINEITEM FIELDS
	    	SObjectType OLIx = Schema.getGlobalDescribe().get('OpportunityLineItem');
			map<String,Schema.SObjectField> OLIFieldsMap = OLIx.getDescribe().fields.getMap();
		    
		    String oliQuery = 'SELECT ';
		    
			for(String oliField : OLIFieldsMap.KeySet()){
				oliQuery = oliQuery + oliField + ', ';
		    }
		     
		    oliQuery = oliQuery.substring(0,oliQuery.length()-2);
		    oliQuery = oliQuery + ' FROM OpportunityLineItem WHERE OpportunityId IN :closedWonOpportunities';
		 	list<OpportunityLineItem> relatedOLI= Database.query(oliQuery);
		 	
		 	
		 	//CREATE A MAP OF OPPORTUNITY ID TO LIST OF OPPORTUNITYLINEITEMS
		 	map<Id, list<OpportunityLineItem>> opportunityIdToOLIListMap = new map<Id, list<OpportunityLineItem>>();
		 	for(OpportunityLineItem oli : relatedOLI){
		 		if(opportunityIdToOLIListMap.containsKey(oli.OpportunityId)){
					opportunityIdToOLIListMap.get(oli.OpportunityId).add(oli);
				}else{
					opportunityIdToOLIListMap.put(oli.OpportunityId, new list<OpportunityLineItem>{oli});
				}	
		 		
		 	}
		 	
		 	//CREATE A MAP OF ORDER ITEM FIELD NAMES
		 	SObjectType OrderItemx = Schema.getGlobalDescribe().get('OrderItem');
			map<String,Schema.SObjectField> OrderItemFieldsMapReadOnly = OrderItemx.getDescribe().fields.getMap();
			map<String,Schema.SObjectField> OrderItemFieldsMap = OrderItemFieldsMapReadOnly.Clone();
			
		 	//LOOP THROUGH ALL ORDERITEM FIELDS AND CHECK IF THERE IS A FIELD WITH SAME NAME
		 	for(String OrderItemField : OrderItemFieldsMap.KeySet()){
		 		Boolean matchMade = false;
		 		for(String oliField : OLIFieldsMap.KeySet()){
		 			//IF FIELD MATCHES IN NAME THEN SET MATCH MADE TO TRUE AND BREAK
		 			if(oliField == OrderItemField){
		 				matchMade = true;
		 				break;
		 			}
		 		}
		 		//AFTER LOOP IF NO MATCHES FOUND THEN REMOVE ORDERITEMFIELD
		 		if(matchMade == false){
		 			OrderItemFieldsMap.remove(OrderItemField);
		 		}
		 		
		 			OrderItemFieldsMap.remove('isdeleted');
		 			OrderItemFieldsMap.remove('listprice');
		 			OrderItemFieldsMap.remove('id');
		 			OrderItemFieldsMap.remove('createdate');
		 	}
		 	
		 	
		 	
		 	
		 	list<Order> ordersToAdd = new list<Order>();
			list<sObject> orderItemsToAdd = new list<sObject>();
		 	list<Order_Discount__c> orderDiscountsToAdd = new list<Order_Discount__c>();
		 	
		 	map<id, Order> opportunityIdToOrderMap = new map<id, Order>();
		 	
		 	for(Opportunity opp : closedWonOpportunities){
				
				//DECIDE WHO IS PRIMARY CONTACT
				OpportunityContactRole primaryContactRole;
				Boolean foundPrimary = false;
				if(oppIdToListofOpportunityContactRoleMap.get(opp.id) != null){
					for(OpportunityContactRole contactRole : oppIdToListofOpportunityContactRoleMap.get(opp.id)){
						if(contactRole.IsPrimary == true){
							primaryContactRole = contactRole;
							foundPrimary = true;
							break;
						}
					}
					if(foundPrimary == false){
						primaryContactRole = oppIdToListofOpportunityContactRoleMap.get(opp.id)[0];
					}
				}
				
				
				Id primaryContactId;
				String orderName;
				if(primaryContactRole != null){
					primaryContactId = primaryContactRole.ContactId;
					orderName = primaryContactRole.Contact.LastName + ' - ';
				}
				orderName = orderName + opp.Account.BillingStreet + ' - ' + opp.CloseDate;
				
				
				//CREATE ORDER
				Order ord = new Order(	
										Name = orderName,
										OpportunityId = opp.id, 
										AccountId = opp.AccountId, 
										Store_Location2__c = opp.Store_Location__r.id,
										OwnerId = opp.OwnerId,
										Description = opp.Description,
										QuoteId = opp.SyncedQuoteId,
										Pricebook2Id = opp.Pricebook2Id,
										BillingStreet = opp.Account.BillingStreet,
										BillingCity = opp.Account.BillingCity,
										BillingStateCode = opp.Account.BillingStateCode,
										BillingPostalCode = opp.Account.BillingPostalCode, 
										BillingCountryCode = opp.Account.BillingCountryCode,
										Status = 'Draft',
										EffectiveDate = opp.CloseDate,
										BillToContactId = primaryContactId
										);
				ordersToAdd.add(ord);
				opportunityIdToOrderMap.put(opp.id, ord);
		 	}
		 	
		 	insert ordersToAdd;
		
			
		 	for(Opportunity opp : closedWonOpportunities){
				//FOR EACH OPPORTUNITYLINEITEM CREATE A ORDERLINE ITEM
				for(OpportunityLineItem oli : opportunityIdToOLIListMap.get(opp.id)){
					
					//CREATE NEW SOBJECT ORDER
					sObject orderItem = Schema.getGlobalDescribe().get('OrderItem').newSObject();
					
					orderItem.put('OrderId', opportunityIdToOrderMap.get(opp.id).id );
					orderItem.put('PricebookEntryId', oli.get('PricebookEntryId') );
					
					for(String orderItemField : OrderItemFieldsMap.keySet()){
						if(OrderItemFieldsMap.get(orderItemField).getDescribe().isUpdateable()){
							orderItem.put(orderItemField , oli.get(orderItemField) );
						}
					}
					
					orderItemsToAdd.add(orderItem);
				}
				
				//FOR EACH OPPORTUNITY DISCOUNT CREATE AN ORDER DISCOUNT
				if(oppIdToListofOpportunityDiscountMap.get(opp.id) != null){
			 		for(Opportunity_Discount__c oppDiscount : oppIdToListofOpportunityDiscountMap.get(opp.id)){
			 			Order_Discount__c orderDiscount = new Order_Discount__c(
	 																			Discount__c = oppDiscount.Discount__c,
	 																			Discount_Amount__c = oppDiscount.Discount_Amount__c,
	 																			Status__c = oppDiscount.Status__c,
	 																			Order__c = opportunityIdToOrderMap.get(opp.id).id
	 																			);
	 					orderDiscountsToAdd.add(orderDiscount);													
			 		}
				}
		 	}//END OF closedWonOpportunities LOOP
			
			//CAST SOBJECT LIST TO ORDERITEM LIST FOR INSERT
			list<OrderItem> orderItemsToAdd2 = orderItemsToAdd;
			insert orderItemsToAdd2;
			insert orderDiscountsToAdd;
			
			
	 	}//END OF closedWonOpportunities.size() > 0 IF
	 }// END OF createSalesOrderOnOpportunityClosedWon METHOD
	  
	 
}//EOF