RbA Build/src/objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Dwelling</fullName>
        <active>true</active>
        <description>Used to support Dwelling</description>
        <label>Dwelling</label>
    </recordTypes>
    <recordTypes>
        <fullName>Store</fullName>
        <active>true</active>
        <description>Used to track and store data releated to Retail Locations both CORO and ARO</description>
        <label>Store</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

RbA Build/src/objects/Assigned_Resources__c.object
<CustomObject>
    <description>Resources Assigned to RbA Work Orders</description>
    <fields>
        <fullName>Scheduled_Resource__c</fullName>
        <inlineHelpText>Resource Scheduled on the Work Order</inlineHelpText>
        <label>Scheduled Resource</label>
        <referenceTo>Resource__c</referenceTo>
        <relationshipLabel>Scheduled Resources</relationshipLabel>
        <relationshipName>Scheduled_Resources</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Work_Order__c</fullName>
        <inlineHelpText>Assigned Work Order</inlineHelpText>
        <label>Work Order</label>
        <referenceTo>RbA_Work_Order__c</referenceTo>
        <relationshipLabel>Assigned Resources</relationshipLabel>
        <relationshipName>Assigned_Resources</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>isPrimary__c</fullName>
        <defaultValue>false</defaultValue>
        <label>isPrimary</label>
        <type>Checkbox</type>
    </fields>
    <label>Assigned Resource</label>
    <nameField>
        <displayFormat>AR#-{00}</displayFormat>
        <label>Assigned Resources #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assigned Resources</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

RbA Build/src/objects/MA_Scheduler_Event__c.object
<CustomObject>
    <fields>
        <fullName>RbA_Work_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>RbA Work Order</label>
        <referenceTo>RbA_Work_Order__c</referenceTo>
        <relationshipLabel>MA Scheduler Events</relationshipLabel>
        <relationshipName>MA_Scheduler_Events</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Resource__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Resource</label>
        <referenceTo>Resource__c</referenceTo>
        <relationshipLabel>MA Scheduler Events</relationshipLabel>
        <relationshipName>MA_Scheduler_Events</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>MA Scheduler Event</label>
    <nameField>
        <label>MA Scheduler Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MA Scheduler Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

RbA Build/src/objects/MA_Scheduler_Settings__c.object
<CustomObject>
    <label>MA Scheduler Settings</label>
    <nameField>
        <displayFormat>MASS - {000000}</displayFormat>
        <label>MA Scheduler Settings Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MA Scheduler Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

RbA Build/src/objects/RbA_Skills__c.object
<CustomObject>
    <description>Used for Scheduling.  Skills are assiged to Resources and RbA Work Orders.</description>
    <label>RbA Skill</label>
    <nameField>
        <label>RbA Skill Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RbA Skills</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

RbA Build/src/objects/RbA_Work_Order__c.object
<CustomObject>
    <description>Custom Object used to track Work Orders related to Orders.</description>
    <fields>
        <fullName>Assigned_Resources__c</fullName>
        <label># Assigned Resources</label>
        <summaryForeignKey>Assigned_Resources__c.Work_Order__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>RbA Work Order</label>
    <nameField>
        <displayFormat>WO-{00000000}</displayFormat>
        <label>Work Order #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RbA Work Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

RbA Build/src/objects/Resource__c.object
<CustomObject>
    <description>Used to hold details about the recourse for scheduling</description>
    <label>Resource</label>
    <nameField>
        <label>Resource Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Resources</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

RbA Build/src/objects/Resource_Skill__c.object
<CustomObject>
    <description>Skills assigned to Resources</description>
    <fields>
        <fullName>Resource__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Resource</label>
        <referenceTo>Resource__c</referenceTo>
        <relationshipLabel>Resource Skills</relationshipLabel>
        <relationshipName>Resource_Skills</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Resource Skill</label>
    <nameField>
        <displayFormat>Resource Skill #-{00}</displayFormat>
        <label>Resource Skill #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Resource Skills</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

RbA Build/src/objects/Store_Configuration__c.object
<CustomObject>
    <description>Holds Store Settings &amp; Configurations</description>
    <label>Store Configuration</label>
    <nameField>
        <displayFormat>SS-{00}</displayFormat>
        <label>Store Setting Record #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Store Configurations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

RbA Build/src/classes/MA_SchedulerRouteTESTS.cls
/************************************************************************************/
/*                                                                                  */
/*      This class is used to test MA_SchedulerRoutingController 	 				*/
/*                                                                                  */
/*      @author     Daniel Taylor   (MapAnything)                                   */
/*                                                                                  */
/*      @version    6/29/2016   MapAnything                                         */
/*      Created                                                                     */
/*                                                                                  */
/*      @copyright (c)2016 MapAnything. All Rights Reserved.                        */
/*      Unauthorized use is prohibited                                              */
/*                                                                                  */
/************************************************************************************/

@isTest (SeeAllData = false)
private class MA_SchedulerRouteTESTS {

	@isTest static void testMARoutingSchedulerConstructor() {
		MA_RoutingSchedulerController maRoute = new MA_RoutingSchedulerController();
		System.assertNotEquals(null, maRoute.tempWo);
	}

 	public class MockHttpResponseGeneratorESRIToken implements HttpCalloutMock{
   		public HTTPResponse respond(HTTPRequest req) {
	       HttpResponse res2 = new HttpResponse();
	       res2.setHeader('Content-Type', 'application/json');
	       res2.setBody('{"access_token":"rbgBLBZiCr1vywSE2Ks3iZbwzqJyWiSc8BSA7rtaU06_GERZeVCMpEPDj3Vv2MoIvQ0hKDAfPW0ti72RV0TL7n4J08xx4_R57ofYMuJXpX35RUcRWyHqd46CcLIDcdntPC2pj6MMf28__GjZ_ilJOQ..","expires_in":480000}');
	       res2.setStatusCode(200);
	       return res2;
		}
	}

	@isTest static void testMARoutingSchedulerGETESRIToken() {
		Account store = MA_SchedulerFakeDataGenerator.createFakeStore(true);
		Store_Configuration__c storeConfig = MA_SchedulerFakeDataGenerator.createFakeStoreConfig(true, store.Id);
		MA_Scheduler_Settings__c storeSetting = MA_SchedulerFakeDataGenerator.createFakeSetting(false, storeConfig.Id, null, false);
		insert new List<MA_Scheduler_Settings__c> { storeSetting };

		Test.startTest();
 		Test.setMock(HttpCalloutMock.class, new MockHttpResponseGeneratorESRIToken());
		String responseString = MA_RoutingSchedulerController.getESRIToken(storeConfig.Id, false, null, null);
		Map<String, Object> responseObj = MA_SchedulerFakeDataGenerator.deserializeResponse(responseString);
		Object accessToken = (Object)responseObj.get('access_token');
		System.assertNotEquals(null, accessToken);

 		responseString = MA_RoutingSchedulerController.getESRIToken(storeConfig.Id, true, null, null);
		responseObj = MA_SchedulerFakeDataGenerator.deserializeResponse(responseString);
		Object error = (Object)responseObj.get('error');
		System.assertNotEquals(null, error);
		Test.stopTest();
	}
	
	@isTest static void testMARoutingSchedulerGetRecords() {
		Account store = MA_SchedulerFakeDataGenerator.createFakeStore(true);
		Account dwelling = MA_SchedulerFakeDataGenerator.createFakeDwelling(true, store.Id);
		Contact homeOwner = MA_SchedulerFakeDataGenerator.createFakeContact(true, store.Id);
		Store_Configuration__c storeConfig = MA_SchedulerFakeDataGenerator.createFakeStoreConfig(true, store.Id);
		RbA_Work_Order__c wo = MA_SchedulerFakeDataGenerator.createFakeBookedWorkOrder(true, dwelling.Id, homeOwner.Id, 'Tech Measure', false);
		RbA_Work_Order__c wo2 = MA_SchedulerFakeDataGenerator.createFakeBookedWorkOrder(true, dwelling.Id, homeOwner.Id, 'Tech Measure', false);
		RbA_Work_Order__c wo3 = MA_SchedulerFakeDataGenerator.createFakeBookedWorkOrder(true, dwelling.Id, homeOwner.Id, 'Tech Measure', false );
		RbA_Work_Order__c wo4 = MA_SchedulerFakeDataGenerator.createFakeBookedWorkOrder(true, dwelling.Id, homeOwner.Id, 'Tech Measure', false );

		Resource__c res1 = MA_SchedulerFakeDataGenerator.createFakeResource(false, 'Tech Measure', storeConfig.Id);
		Resource__c res2 = MA_SchedulerFakeDataGenerator.createFakeResource(false, 'Tech Measure', storeConfig.Id);
		Resource__c res3 = MA_SchedulerFakeDataGenerator.createFakeResource(false, 'Tech Measure', storeConfig.Id);
		Resource__c res4 = MA_SchedulerFakeDataGenerator.createFakeResource(false, 'Tech Measure', storeConfig.Id);
		insert new List<Resource__c> { res1, res2, res3, res4 };

		MA_SchedulerFakeDataGenerator.createFakeSfEvent(true, wo4.Id);
		MA_SchedulerFakeDataGenerator.createFakeSfEvent(true, null);
		MA_Scheduler_Event__c maEvent1 = MA_SchedulerFakeDataGenerator.createFakeMaEvent(false, wo.Id, null);
		MA_Scheduler_Event__c maEvent2 = MA_SchedulerFakeDataGenerator.createFakeMaEvent(false, wo2.Id, null);
		MA_Scheduler_Event__c maEvent3 = MA_SchedulerFakeDataGenerator.createFakeMaEvent(false, wo3.Id, null);
		MA_Scheduler_Event__c maEvent4 = MA_SchedulerFakeDataGenerator.createFakeMaEvent(false, wo4.Id, res2.Id);
		MA_Scheduler_Event__c maEvent5 = MA_SchedulerFakeDataGenerator.createFakeMaEvent(false, null, res3.Id);
		MA_Scheduler_Event__c maEvent6 = MA_SchedulerFakeDataGenerator.createFakeMaEvent(false, null, res4.Id);
		insert new List<MA_Scheduler_Event__c> { maEvent1, maEvent2, maEvent3, maEvent4, maEvent5, maEvent6 };

		MA_Scheduler_Settings__c resourceSetting1 = MA_SchedulerFakeDataGenerator.createFakeSetting(false, storeConfig.Id, res1.Id, false);
		MA_Scheduler_Settings__c resourceSetting2 = MA_SchedulerFakeDataGenerator.createFakeSetting(false, storeConfig.Id, res2.Id, false);
		MA_Scheduler_Settings__c resourceSetting3 = MA_SchedulerFakeDataGenerator.createFakeSetting(false, storeConfig.Id, res3.Id, false);
		MA_Scheduler_Settings__c storeSetting = MA_SchedulerFakeDataGenerator.createFakeSetting(false, storeConfig.Id, null, false);
		insert new List<MA_Scheduler_Settings__c> { resourceSetting1, resourceSetting2, resourceSetting3, storeSetting };

		RbA_Skills__c skill = MA_SchedulerFakeDataGenerator.createFakeSkill(true, 'skill1');
		MA_SchedulerFakeDataGenerator.createFakeWorkOrderSkill(true, skill.Id, wo.Id);
		MA_SchedulerFakeDataGenerator.createFakeWorkOrderSkill(true, skill.Id, wo2.Id);
		MA_SchedulerFakeDataGenerator.createFakeWorkOrderSkill(true, skill.Id, wo3.Id);
		MA_SchedulerFakeDataGenerator.createFakeWorkOrderSkill(true, skill.Id, wo4.Id);
		MA_SchedulerFakeDataGenerator.createFakeAssignedResource(true, wo4.Id, res2.Id, true);

		Resource_Skill__c resSkill1 = MA_SchedulerFakeDataGenerator.createFakeResourceSkill(false, skill.Id, res1.Id);
		Resource_Skill__c resSkill2 = MA_SchedulerFakeDataGenerator.createFakeResourceSkill(false, skill.Id, res2.Id);
		Resource_Skill__c resSkill3 = MA_SchedulerFakeDataGenerator.createFakeResourceSkill(false, skill.Id, res3.Id);
		Resource_Skill__c resSkill4 = MA_SchedulerFakeDataGenerator.createFakeResourceSkill(false, skill.Id, res4.Id);
		insert new List<Resource_Skill__c> { resSkill1, resSkill2, resSkill3, resSkill4 };

		Test.startTest();
		String responseString = MA_RoutingSchedulerController.getRecords('1987-01-10', String.valueOf(storeConfig.Id), 'Tech Measure', '0');
		Map<String, Object> responseObj = MA_SchedulerFakeDataGenerator.deserializeResponse(responseString);
		System.debug(responseObj);
		System.assertEquals(true, (Object)responseObj.get('success'));
		Test.stopTest();
	}

	@isTest static void testMARoutingSchedulerProcessConfirmBatch() {
		Account store = MA_SchedulerFakeDataGenerator.createFakeStore(true);
		Account dwelling = MA_SchedulerFakeDataGenerator.createFakeDwelling(true, store.Id);
		Contact homeOwner = MA_SchedulerFakeDataGenerator.createFakeContact(true, store.Id);
		Store_Configuration__c storeConfig = MA_SchedulerFakeDataGenerator.createFakeStoreConfig(true, store.Id);
		RbA_Work_Order__c wo = MA_SchedulerFakeDataGenerator.createFakeBookedWorkOrder(true, dwelling.Id, homeOwner.Id, 'Tech Measure', false);
		RbA_Work_Order__c wo2 = MA_SchedulerFakeDataGenerator.createFakeBookedWorkOrder(true, dwelling.Id, homeOwner.Id, 'Tech Measure', false);

		Resource__c res1 = MA_SchedulerFakeDataGenerator.createFakeResource(false, 'Tech Measure', storeConfig.Id);
		Resource__c res2 = MA_SchedulerFakeDataGenerator.createFakeResource(false, 'Tech Measure', storeConfig.Id);
		insert new List<Resource__c> { res1, res2};

		MA_SchedulerFakeDataGenerator.createFakeSfEvent(true, wo.Id);
		MA_SchedulerFakeDataGenerator.createFakeSfEvent(true, wo2.Id);
		MA_Scheduler_Event__c maEvent1 = MA_SchedulerFakeDataGenerator.createFakeMaEvent(false, wo.Id, res1.Id);
		MA_Scheduler_Event__c maEvent2 = MA_SchedulerFakeDataGenerator.createFakeMaEvent(false, wo2.Id, res2.Id);
		insert new List<MA_Scheduler_Event__c> { maEvent1, maEvent2 };

		MA_Scheduler_Settings__c resourceSetting1 = MA_SchedulerFakeDataGenerator.createFakeSetting(false, storeConfig.Id, res1.Id, false);
		MA_Scheduler_Settings__c resourceSetting2 = MA_SchedulerFakeDataGenerator.createFakeSetting(false, storeConfig.Id, res2.Id, false);
		MA_Scheduler_Settings__c storeSetting = MA_SchedulerFakeDataGenerator.createFakeSetting(false, storeConfig.Id, null, false);
		insert new List<MA_Scheduler_Settings__c> { resourceSetting1, resourceSetting2, storeSetting };

		RbA_Skills__c skill = MA_SchedulerFakeDataGenerator.createFakeSkill(true, 'skill1');
		MA_SchedulerFakeDataGenerator.createFakeWorkOrderSkill(true, skill.Id, wo.Id);
		MA_SchedulerFakeDataGenerator.createFakeWorkOrderSkill(true, skill.Id, wo2.Id);
		Assigned_Resources__c assignedRes = MA_SchedulerFakeDataGenerator.createFakeAssignedResource(true, wo2.Id, res1.Id, true);
		Assigned_Resources__c assignedRes2 = MA_SchedulerFakeDataGenerator.createFakeAssignedResource(true, wo2.Id, res2.Id, true);
		
		Resource_Skill__c resSkill1 = MA_SchedulerFakeDataGenerator.createFakeResourceSkill(false, skill.Id, res1.Id);
		Resource_Skill__c resSkill2 = MA_SchedulerFakeDataGenerator.createFakeResourceSkill(false, skill.Id, res2.Id);
		insert new List<Resource_Skill__c> { resSkill1, resSkill2 };

		Map<Id, Set<Id>> woToResIdsMapString = new Map<Id, Set<Id>>();
	  	Map<Id, Id> primaryResourceMap = new Map<Id, Id> ();
		Assigned_Resources__c[] rbaAssignedResources = new Assigned_Resources__c[]{assignedRes, assignedRes2};

		for(Assigned_Resources__c resource : rbaAssignedResources){
			if(woToResIdsMapString.containsKey(resource.Work_Order__c)){
				woToResIdsMapString.get(resource.Work_Order__c).add(resource.Scheduled_Resource__c);
			}
			else{
				woToResIdsMapString.put(resource.Work_Order__c, new Set<Id>{ resource.Scheduled_Resource__c });
			}

			if(resource.isPrimary__c){
				primaryResourceMap.put(resource.Work_Order__c, resource.Scheduled_Resource__c);
			}
		}

		Test.startTest();
		String responseString = MA_RoutingSchedulerController.processConfirmBatch( JSON.serialize(woToResIdsMapString), storeConfig.Id, '1987-01-10', JSON.serialize(primaryResourceMap));
		Map<String, Object> responseObj = MA_SchedulerFakeDataGenerator.deserializeResponse(responseString);
		System.assertEquals(true, (Object)responseObj.get('success'));
		Test.stopTest();
	}

	@isTest static void testMARoutingSchedulerRetrieveResourceRouteRecords() {
		Account store = MA_SchedulerFakeDataGenerator.createFakeStore(true);
		Account dwelling = MA_SchedulerFakeDataGenerator.createFakeDwelling(true, store.Id);
		Contact homeOwner = MA_SchedulerFakeDataGenerator.createFakeContact(true, store.Id);
		Store_Configuration__c storeConfig = MA_SchedulerFakeDataGenerator.createFakeStoreConfig(true, store.Id);
		RbA_Work_Order__c wo = MA_SchedulerFakeDataGenerator.createFakeBookedWorkOrder(true, dwelling.Id, homeOwner.Id, 'Tech Measure', false);

		Resource__c res1 = MA_SchedulerFakeDataGenerator.createFakeResource(false, 'Tech Measure', storeConfig.Id);
		insert new List<Resource__c> { res1 };

		MA_SchedulerFakeDataGenerator.createFakeSfEvent(true, null);
		MA_Scheduler_Event__c maEvent1 = MA_SchedulerFakeDataGenerator.createFakeMaEvent(false, wo.Id, res1.Id);
		insert new List<MA_Scheduler_Event__c> { maEvent1 };

		MA_Scheduler_Settings__c resourceSetting1 = MA_SchedulerFakeDataGenerator.createFakeSetting(false, storeConfig.Id, res1.Id, false);
		MA_Scheduler_Settings__c storeSetting = MA_SchedulerFakeDataGenerator.createFakeSetting(false, storeConfig.Id, null, false);
		insert new List<MA_Scheduler_Settings__c> { resourceSetting1, storeSetting };

		RbA_Skills__c skill = MA_SchedulerFakeDataGenerator.createFakeSkill(true, 'skill1');
		MA_SchedulerFakeDataGenerator.createFakeWorkOrderSkill(true, skill.Id, wo.Id);
		Resource_Skill__c resSkill1 = MA_SchedulerFakeDataGenerator.createFakeResourceSkill(false, skill.Id, res1.Id);
		insert new List<Resource_Skill__c> { resSkill1 };

		Test.startTest();
		String responseString = MA_RoutingSchedulerController.retrieveResourceRouteRecords(res1.Id ,'01/10/1987' , storeConfig.Id, new List<Id>());
		Map<String, Object> responseObj = MA_SchedulerFakeDataGenerator.deserializeResponse(responseString);
		Object retrieveSuccess = (Object)responseObj.get('success');
		System.assertEquals(true, retrieveSuccess);

		responseString = MA_RoutingSchedulerController.retrieveResourceRouteRecords(res1.Id ,'01/10/1987' , storeConfig.Id, new List<Id>{res1.Id});
		responseObj = MA_SchedulerFakeDataGenerator.deserializeResponse(responseString);
		retrieveSuccess = (Object)responseObj.get('success');
		System.assertEquals(true, retrieveSuccess);
		Test.stopTest();
	}

	@isTest static void testMARoutingSchedulerErrorTest() {
		Account store = MA_SchedulerFakeDataGenerator.createFakeStore(true);
		Store_Configuration__c storeConfig = MA_SchedulerFakeDataGenerator.createFakeStoreConfig(true, store.Id);

 		Test.startTest();
 		Test.setMock(HttpCalloutMock.class, new MockHttpResponseGeneratorESRIToken());
		String responseString = MA_RoutingSchedulerController.getESRIToken(storeConfig.Id, false, null, null);
		Map<String, Object> responseObj = MA_SchedulerFakeDataGenerator.deserializeResponse(responseString);
		Object errorAccessToken = (Object)responseObj.get('error');
		System.assertNotEquals(null, errorAccessToken);

		String responseString2 = MA_RoutingSchedulerController.getRecords('', String.valueOf(store.Id), '', '0');
		Map<String, Object> responseObjMaster = MA_SchedulerFakeDataGenerator.deserializeResponse(responseString2);
		Object masterSuccessFalse = (Object)responseObjMaster.get('success');
		System.assertEquals(false, masterSuccessFalse);
	
		String responseString3 = MA_RoutingSchedulerController.retrieveResourceRouteRecords(String.valueOf(store.Id),'01/10/1987', String.valueOf(store.Id), new List<Id>());
		Map<String, Object> responseObjReRouteRec = MA_SchedulerFakeDataGenerator.deserializeResponse(responseString2);
		Object masterRouteRecFalse = (Object)responseObjReRouteRec.get('success');
		System.assertEquals(false, masterRouteRecFalse);
		
		String responseString4 = MA_RoutingSchedulerController.processConfirmBatch('', String.valueOf(store.Id),'1987-01-10', '');
		Map<String, Object> responseObjConfirmBatch = MA_SchedulerFakeDataGenerator.deserializeResponse(responseString4);
		Object masterConfirmBatch = (Object)responseObjConfirmBatch.get('success');
		System.assertEquals(false, masterConfirmBatch);
		Test.stopTest();
	}

}