RbA Build/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Store_Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The store location that this dwelling is related</description>
        <inlineHelpText>The store location that this dwelling is related</inlineHelpText>
        <label>Store Location</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>The account must be of type &quot;Store&quot;</errorMessage>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Store</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Dwellings</relationshipLabel>
        <relationshipName>StoreLocation</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Dwelling</fullName>
        <active>true</active>
        <description>Used to support Dwelling</description>
        <label>Dwelling</label>
    </recordTypes>
    <recordTypes>
        <fullName>Vendor</fullName>
        <active>true</active>
        <description>Used to track Vendors</description>
        <label>Vendor</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

RbA Build/src/objects/Financial_Account_Number__c.object
<CustomObject>
    <description>Stores financial account numbers used in the journal entries and Baan ERP integration</description>
    <fields>
        <fullName>Store_Configuration__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Select which store configuration to relate this account number.</description>
        <inlineHelpText>Select which store configuration to relate this account number.</inlineHelpText>
        <label>Store Configuration</label>
        <referenceTo>Store_Configuration__c</referenceTo>
        <relationshipLabel>Financial Account Numbers</relationshipLabel>
        <relationshipName>Financial_Account_Numbers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Financial Account Number</label>
    <nameField>
        <label>Financial Account Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Account Numbers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

RbA Build/src/objects/Financial_Transaction__c.object
<CustomObject>
    <description>Object to store financial transaction records</description>
    <fields>
        <fullName>Credit_Account_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Select the account number to credit in this financial transaction</description>
        <inlineHelpText>Select the account number to credit in this financial transaction</inlineHelpText>
        <label>Credit Account Number</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Only account numbers related to this financial transaction&apos;s store location can be selected.</errorMessage>
            <filterItems>
                <field>Financial_Account_Number__c.Store_Configuration__c</field>
                <operation>equals</operation>
                <valueField>$Source.Store_Configuration__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Financial_Account_Number__c</referenceTo>
        <relationshipLabel>Financial Transactions Credit</relationshipLabel>
        <relationshipName>Financial_Transactions_Credit</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Debit_Account_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Select the account number to debit in this financial transaction</description>
        <inlineHelpText>Select the account number to debit in this financial transaction</inlineHelpText>
        <label>Debit Account Number</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Only account numbers related to this financial transaction&apos;s store location can be selected.</errorMessage>
            <filterItems>
                <field>Financial_Account_Number__c.Store_Configuration__c</field>
                <operation>equals</operation>
                <valueField>$Source.Store_Configuration__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Financial_Account_Number__c</referenceTo>
        <relationshipLabel>Financial Transactions Debit</relationshipLabel>
        <relationshipName>Financial_Transactions_Debit</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Store_Configuration__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>The store configuration this transaction is related to</description>
        <inlineHelpText>The store configuration this transaction is related to</inlineHelpText>
        <label>Store Configuration</label>
        <referenceTo>Store_Configuration__c</referenceTo>
        <relationshipLabel>Financial Transactions</relationshipLabel>
        <relationshipName>Financial_Transactions</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Transaction_Type__c</fullName>
        <description>Select the transaction type for this record. This will determine when these accounts will be debited/credited.</description>
        <inlineHelpText>Select the transaction type for this record. This will determine when these accounts will be debited/credited.</inlineHelpText>
        <label>Transaction Type</label>
        <picklist>
            <picklistValues>
                <fullName>Deposit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Final Payment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inventory Received</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inventory Installed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Misc Sub-Payment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>External Labor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Internal Labor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Misc Cash Receipt</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Misc Reimbursement</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Financial Transaction</label>
    <nameField>
        <displayFormat>FT-{00000}</displayFormat>
        <label>Financial Transaction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Financial Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

RbA Build/src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Master_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Master Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Sub Products</relationshipLabel>
        <relationshipName>SubProducts</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Master_Product</fullName>
        <active>true</active>
        <label>Master Product</label>
    </recordTypes>
</CustomObject>

RbA Build/src/objects/RMS_Settings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>A name value list of RMS settings</description>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>RMS Settings</label>
</CustomObject>

RbA Build/src/objects/Service_Product__c.object
<CustomObject>
    <description>Junction Object linking Master Products to Service Products</description>
    <fields>
        <fullName>Master_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Master Product</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Product2.Master_Legacy_Product__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Service Products</relationshipLabel>
        <relationshipName>Service_Products1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Service_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service Product</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Product2.RecordTypeId</field>
                <operation>equals</operation>
                <value>Service Product</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Master Products</relationshipLabel>
        <relationshipName>Service_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Service Product</label>
    <nameField>
        <displayFormat>SPA-{000000}</displayFormat>
        <label>Service Product Assignment</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

RbA Build/src/objects/Store_Configuration__c.object
<CustomObject>
    <description>Holds Store Settings &amp; Configurations</description>
    <fields>
        <fullName>Store__c</fullName>
        <label>Store</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Store Configurations</relationshipLabel>
        <relationshipName>Store_Configurations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Store Configuration</label>
    <nameField>
        <displayFormat>SS-{00}</displayFormat>
        <label>Store Setting Record #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Store Configurations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

RbA Build/src/classes/testRMS_serviceWarrantyManager.cls
@isTest 
public with sharing class testRMS_serviceWarrantyManager {
    static testmethod void createTestRecords() {
        RMS_Settings__c turnOffFinancialTrigger = new RMS_Settings__c(Name = 'Turn Financial Transactions Off', Value__c = 'Yes');
        insert turnOffFinancialTrigger;
        
        TestUtilityMethods utility = new TestUtilityMethods();
        utility.setUpConfigs();
        
        
        Account dwelling1 = utility.createDwellingAccount('Dwelling Account');       
        Account store1 = [SELECT Id from Account Where Name = '77 - Twin Cities, MN'];
        Store_Configuration__c storeConfig1 = [SELECT id FROM Store_Configuration__c WHERE Store__c = :store1.id ];
        dwelling1.Store_Location__c = store1.Id;         
        insert dwelling1;       
        
        Contact contact1 = new contact ( FirstName='Contact',LastName='1',AccountId=dwelling1.id);
        insert contact1;
        
        Financial_Account_Number__c finacialAccountNumber1 = new Financial_Account_Number__c (  Store_Configuration__c = storeConfig1.id, Name = '1');
        insert finacialAccountNumber1;
        Financial_Account_Number__c finacialAccountNumber2 = new Financial_Account_Number__c (  Store_Configuration__c = storeConfig1.id, Name = '2');
        insert finacialAccountNumber2;
        
        Financial_Transaction__c finacialTransaction1 = new Financial_Transaction__c(  Store_Configuration__c = storeConfig1.id,
                                                                                     Transaction_Type__c = 'Inventory Received - External Vendor',
                                                                                     Debit_Account_Number__c = finacialAccountNumber1.id,
                                                                                     Credit_Account_Number__c = finacialAccountNumber2.id);
        insert finacialTransaction1;
        
        List<Product2> products = new List<Product2>();
        Product2 masterProduct = new Product2( name = 'master',IsActive = true, recordTypeId=UtilityMethods.GetRecordTypeIdsMapForSObject(Product2.sObjectType).get('Master_Product'));
        products.add(masterProduct);
        Product2 servProduct = new Product2( name = 'service',IsActive = true, recordTypeId=UtilityMethods.GetRecordTypeIdsMapForSObject(Product2.sObjectType).get('Service_Product'));
        products.add(servProduct);
        Product2 servProduct2 = new Product2(name = 'service2',IsActive = true, recordTypeId=UtilityMethods.GetRecordTypeIdsMapForSObject(Product2.sObjectType).get('Service_Product'));
        products.add(servProduct2);
        Id pricebookId = Test.getStandardPricebookId();
        system.debug(pricebookId);
        
        
        insert products;
        
        System.assertEquals(products.size(), 3);
        
        PricebookEntry pricebookEntryMaster= utility.createPricebookEntry(pricebookId, masterProduct.id);     
        PricebookEntry pricebookEntryServ = utility.createPricebookEntry(pricebookId, servProduct.id);    
        PricebookEntry pricebookEntryServ2 = utility.createPricebookEntry(pricebookId, servProduct2.id);      
        List<PriceBookEntry> pbEntries = new List<PricebookEntry>{pricebookEntryMaster,pricebookEntryServ,pricebookEntryServ2};
            insert pbEntries;
        //utility.createOrderTestRecords();
        //
        
        Service_Product__c servProd1 = new Service_Product__c(name = 'service', Service_Product__c = servProduct.Id, Master_Product__c = masterProduct.Id);
        Service_Product__c servProd2 = new Service_Product__c(name = 'service2', Service_Product__c = servProduct2.Id, Master_Product__c = masterProduct.Id);
        List<Service_Product__c> sprods = new List<Service_Product__c>{servProd1,servProd2};
            insert sprods;
        
        List<Service_Field_Ids__c> customSettings = new List<Service_Field_Ids__c>();
        Service_Field_Ids__c spMP = new Service_Field_Ids__c(Name='Service Product - Master Product', Value__c = 'CF0000000000000');
        customSettings.add(spMP);
        Service_Field_Ids__c spSP = new Service_Field_Ids__c(Name='Service Product - Service Product', Value__c = 'CF0000000000000');
        customSettings.add(spSP);
        Service_Field_Ids__c pcSP = new Service_Field_Ids__c(Name='Procedure Code - Service Product', Value__c = 'CF0000000000000');
        customSettings.add(pcSP);
        insert customSettings;
        System.AssertEquals(customSettings.size(),3);
        
        
    }
    
    static testmethod void addServiceProductTest(){
        createTestRecords();
        Test.startTest();
        
        Product2 prod = [SELECT Id, Name FROM Product2 WHERE Name = 'service'];
        
        Test.setCurrentPage(Page.RMS_viewServiceProduct);
        ApexPages.StandardController sc = new ApexPages.StandardController(prod);
        RMS_serviceWarrantyManager TE = new RMS_serviceWarrantyManager(sc);
        Pagereference pr = TE.addServiceProduct();
        
        Test.stopTest();              
    }
    
    static testmethod void addMasterProductTest(){
        createTestRecords();
        Test.startTest();
        
        Product2 prod = [SELECT Id, Name FROM Product2 WHERE Name = 'master'];
        
        Test.setCurrentPage(Page.RMS_viewServiceProduct);
        ApexPages.StandardController sc = new ApexPages.StandardController(prod);
        RMS_serviceWarrantyManager TE = new RMS_serviceWarrantyManager(sc);
        Pagereference pr = TE.addMasterProduct();
        
        Test.stopTest();              
    }
    
    static testmethod void addProcedureCodeTest(){
        createTestRecords();
        Test.startTest();
        
        Product2 prod = [SELECT Id, Name FROM Product2 WHERE Name = 'service'];
        
        Test.setCurrentPage(Page.RMS_viewServiceProduct);
        ApexPages.StandardController sc = new ApexPages.StandardController(prod);
        RMS_serviceWarrantyManager TE = new RMS_serviceWarrantyManager(sc);
        Pagereference pr = TE.addProcedureCode();
        
        Test.stopTest();              
    }        
    
}