RbA Build/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Store_Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The store location that this dwelling is related</description>
        <inlineHelpText>The store location that this dwelling is related</inlineHelpText>
        <label>Store Location</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>The account must be of type &quot;Store&quot;</errorMessage>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Store</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Dwellings</relationshipLabel>
        <relationshipName>StoreLocation</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

RbA Build/src/objects/Order.object
<CustomObject>
    <fields>
        <fullName>Service_Type__c</fullName>
        <inlineHelpText>Job In Progress should be selected if the Installation Date of the original product was in the last 30 days. Select Save if the request is solved during the initial phone call. Field Service is the default and only option for Cottage Grove users.</inlineHelpText>
        <label>Service Type</label>
        <picklist>
            <picklistValues>
                <fullName>Job in Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Field Service</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Service</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Save</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Sold_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>When the Sold Order is Job In Progress, the Service Order must be related to the Sold Order.</inlineHelpText>
        <label>Sold Order</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>$Source.AccountId</field>
                <operation>equals</operation>
                <valueField>Order.AccountId</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Order</referenceTo>
        <relationshipLabel>Service Orders</relationshipLabel>
        <relationshipName>Sold_Order</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Store_Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This order is related to this store location.</description>
        <inlineHelpText>This order is related to this store location.</inlineHelpText>
        <label>Store Location</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Orders (Store Location)</relationshipLabel>
        <relationshipName>Orders1</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>CORO_Record_Type</fullName>
        <active>true</active>
        <description>CORO Orders</description>
        <label>CORO Record Type</label>
    </recordTypes>
    <recordTypes>
        <fullName>CORO_Service</fullName>
        <active>true</active>
        <description>CORO Service Records</description>
        <label>CORO Service</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

RbA Build/src/objects/Purchase_Order__c.object
<CustomObject>
    <description>The purchase order header for ordering RbA and 3rd party products linked to order line items</description>
    <label>Purchase Order</label>
    <nameField>
        <label>Purchase Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Purchase Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

RbA Build/src/classes/RMS_viewOrdersController.cls
/*******************************************************//**

@class  RMS_viewOrdersController

@brief  Controller for RMS_viewCOROOrders and RMS_viewServiceOrders visualforce page

@author  Kai Ruan (Slalom)

@version    2016-3-11  Slalom
Created.

@copyright  (c)2016 Slalom.  All Rights Reserved. 
Unauthorized use is prohibited.

***********************************************************/
public with sharing class RMS_viewOrdersController {
    
    
    public String strurl;
    public String baseUrl{get;set;}
    public String createServiceRequestURL{get;set;}
    
    public Id serviceRecordTypeId{get;set;}
    public Id CORORecordTypeId{get;set;}
    public List<Order> orders{get;set;}
    
    /******* Set up Standard Controller for Purchase_Order__c  *****************/
    private Apexpages.StandardController standardController;
    private final Account acc;
    
    
    //Constructor
    public RMS_viewOrdersController(ApexPages.StandardController stdController) {
        if(!test.isRunningTest()){
            stdController.addFields(new List<String>{'Store_Location__c'});
        }
        this.acc = (Account)stdController.getRecord();
        
        strurl = ApexPages.currentPage().getUrl();
        strurl = strurl.split('apex/')[1];
        baseUrl = URL.getSalesforceBaseUrl().toExternalForm();
        
        
        serviceRecordTypeId = UtilityMethods.retrieveRecordTypeId('CORO_Service', 'Order');
        CORORecordTypeId = UtilityMethods.retrieveRecordTypeId('CORO_Record_Type', 'Order');
        
        Id recordTypeId = null;
        System.debug(strurl);
        System.debug(serviceRecordTypeId);
        if(strurl.Contains('viewService')){
            recordTypeId = serviceRecordTypeId;
        }else {
            recordTypeId = CORORecordTypeId;			
        }
        
        orders = [SELECT 	Name,
                  OrderNumber,
                  Status,
                  EffectiveDate,
                  Contract.Name,
                  ContractId,
                  TotalAmount,
                  RecordType.Name,
                  Sold_Order__c,
                  Description,
                  Service_Type__c,
                  Sold_Order__r.OrderNumber
                  FROM 	Order
                  WHERE 	RecordTypeId =: recordTypeId
                  AND 	AccountId =: acc.Id];	 
        
        system.debug(orders);
        createServiceRequestURL = '/apex/RMS_createServiceRequestRedirect?isdtp=vw&aid='+acc.Id+'&slid='+acc.Store_Location__c; 
        
    }
    
}