RbA Build/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Store_Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The store location that this dwelling is related</description>
        <inlineHelpText>The store location that this dwelling is related</inlineHelpText>
        <label>Store Location</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>The account must be of type &quot;Store&quot;</errorMessage>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Store</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Dwellings</relationshipLabel>
        <relationshipName>StoreLocation</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Dwelling</fullName>
        <active>true</active>
        <description>Used to support Dwelling</description>
        <label>Dwelling</label>
    </recordTypes>
    <recordTypes>
        <fullName>Store</fullName>
        <active>true</active>
        <description>Used to track and store data releated to Retail Locations both CORO and ARO</description>
        <label>Store</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

RbA Build/src/objects/Contact_History__c.object
<CustomObject>
    <description>Junction object between Account and Contacts.</description>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Associated_Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Dwelling__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>What Dwelling is this Contact associated with?</inlineHelpText>
        <label>Dwelling</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Associated_Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>Tracks the type of association the contact has with the account/dwelling</description>
        <inlineHelpText>Tracks the type of association the contact has with the account/dwelling</inlineHelpText>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Current Resident</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Past Resident</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Current Renter</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Past Renter</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Owner</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Contact History</label>
    <nameField>
        <displayFormat>CH-{00}</displayFormat>
        <label>CH#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Histories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

RbA Build/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Store_Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Store Location</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>The account must be of type &quot;Store&quot;.</errorMessage>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Store</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Store Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

RbA Build/src/classes/RMS_mobileAppContactHelperTests.cls
/**
 *@class	RMS_mobileAppContactHelperTests
 *@brief	Test class for RMS_mobileAppContactHelper
 *@author   Kai Ruan
 *@version	2016-3/1 Created
 *@copyright  (c)2016 Slalom.  All Rights Reserved.	Unauthorized use is prohibited.
 */
 @isTest
private class RMS_mobileAppContactHelperTests {
	
	@testSetup static void setupData(){
		TestUtilityMethods utility = new TestUtilityMethods();
		utility.setUpConfigs();
		Account dwelling = utility.createDwellingAccount('Dwelling Account');
		Account store = [SELECT Id from Account Where Name = '77 - Twin Cities, MN'];
		dwelling.Store_Location__c = store.Id;
		insert dwelling;
		Opportunity opp = utility.createOpportunity(dwelling.Id, 'New');
		insert opp;
	}
	
	@isTest
	public static void testSaveNewContact(){
		TestUtilityMethods utility = new TestUtilityMethods();
		Account dwelling = [Select Id from Account where Name = 'Dwelling Account'];
		Opportunity opp = [Select Id from Opportunity where AccountId =: dwelling.Id limit 1];
		Contact c = utility.createContact(dwelling.ID, 'TestName1');
		RMS_mobileAppContactHelper.DTOContact dtoContact = new RMS_mobileAppContactHelper.DTOContact();
		dtoContact.AccountId = dwelling.Id;
		dtoContact.OpportunityId = opp.Id;
		dtoContact.contact = c;
		String jsonResult = RMS_mobileAppContactHelper.saveNewContact(JSON.serialize(dtoContact));
		//Assert Contact is created
		List<Contact> cList = [select Id, AccountId from Contact where AccountId =: dwelling.Id AND FirstName Like '%TestName1%'];
		System.assert(!cList.isEmpty());
		//Assert Contact History is created
		List<Contact_History__c> cHistList = [select Contact__c, Dwelling__c, Type__c from Contact_History__c where Contact__c =: clist[0].Id];
		System.assert(!cHistList.isEmpty());
		System.assertEquals(cHistList[0].Dwelling__c, dwelling.Id);
		System.assertEquals(cHistList[0].Type__c, 'Current Resident');
		//Assert Opportunity Contact Role is created
		List<OpportunityContactRole> cRoleList = [select ContactId, OpportunityId,Role from OpportunityContactRole where ContactId =: clist[0].Id];
		System.assert(!cRoleList.isEmpty());
		System.assertEquals(cRoleList[0].OpportunityId, opp.Id);
		System.assertEquals(cRoleList[0].Role, 'Decision Maker');
		//Assert Json response contains contact Id
		System.assert(jsonResult.contains(clist[0].Id));		
	}

	@isTest
	public static void testSaveNewContactWithoutAccountId(){
		TestUtilityMethods utility = new TestUtilityMethods();
		Account dwelling = [Select Id from Account where Name = 'Dwelling Account'];
		Opportunity opp = [Select Id from Opportunity where AccountId =: dwelling.Id limit 1];
		Contact c = utility.createContact(dwelling.ID, 'TestName1');
		RMS_mobileAppContactHelper.DTOContact dtoContact = new RMS_mobileAppContactHelper.DTOContact();
		dtoContact.AccountId = null;
		dtoContact.OpportunityId = opp.Id;
		dtoContact.contact = c;
		String jsonResult = RMS_mobileAppContactHelper.saveNewContact(JSON.serialize(dtoContact));
		//Assert Contact is created
		List<Contact> cList = [select Id, AccountId from Contact where FirstName Like '%TestName1%'];
		System.assert(!cList.isEmpty());		
		//Assert Contact History is not created
		List<Contact_History__c> cHistList = [select Contact__c, Dwelling__c, Type__c from Contact_History__c where Contact__c =: clist[0].Id];
		System.assert(cHistList.isEmpty());
	}

	@isTest
	public static void testSaveNewContactWithoutOpportunityId(){
		TestUtilityMethods utility = new TestUtilityMethods();
		Account dwelling = [Select Id from Account where Name = 'Dwelling Account'];
		Opportunity opp = [Select Id from Opportunity where AccountId =: dwelling.Id limit 1];
		Contact c = utility.createContact(dwelling.ID, 'TestName1');
		RMS_mobileAppContactHelper.DTOContact dtoContact = new RMS_mobileAppContactHelper.DTOContact();
		dtoContact.AccountId = dwelling.Id;
		dtoContact.OpportunityId = null;
		dtoContact.contact = c;
		String jsonResult = RMS_mobileAppContactHelper.saveNewContact(JSON.serialize(dtoContact));
		//Assert Contact is created
		List<Contact> cList = [select Id, AccountId from Contact where AccountId =: dwelling.Id AND FirstName Like '%TestName1%'];
		System.assert(!cList.isEmpty());
		//Assert Contact History is created
		List<Contact_History__c> cHistList = [select Contact__c, Dwelling__c, Type__c from Contact_History__c where Contact__c =: clist[0].Id];
		System.assert(!cHistList.isEmpty());
		System.assertEquals(cHistList[0].Dwelling__c, dwelling.Id);
		System.assertEquals(cHistList[0].Type__c, 'Current Resident');
		//Assert Opportunity Contact Role is not created
		List<OpportunityContactRole> cRoleList = [select ContactId, OpportunityId,Role from OpportunityContactRole where ContactId =: clist[0].Id];
		System.assert(cRoleList.isEmpty());
		//Assert Json response contains contact Id
		System.assert(jsonResult.contains(clist[0].Id));
	}
}