RbA Build/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Store_Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The store location that this dwelling is related</description>
        <inlineHelpText>The store location that this dwelling is related</inlineHelpText>
        <label>Store Location</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>The account must be of type &quot;Store&quot;</errorMessage>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Store</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Dwellings</relationshipLabel>
        <relationshipName>StoreLocation</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Dwelling</fullName>
        <active>true</active>
        <description>Used to support Dwelling</description>
        <label>Dwelling</label>
    </recordTypes>
    <recordTypes>
        <fullName>Store</fullName>
        <active>true</active>
        <description>Used to track and store data releated to Retail Locations both CORO and ARO</description>
        <label>Store</label>
    </recordTypes>
    <recordTypes>
        <fullName>Vendor</fullName>
        <active>true</active>
        <description>Used to track Vendors</description>
        <label>Vendor</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

RbA Build/src/objects/Financial_Account_Number__c.object
<CustomObject>
    <description>Stores financial account numbers used in the journal entries and Baan ERP integration</description>
    <fields>
        <fullName>Store_Configuration__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Select which store configuration to relate this account number.</description>
        <inlineHelpText>Select which store configuration to relate this account number.</inlineHelpText>
        <label>Store Configuration</label>
        <referenceTo>Store_Configuration__c</referenceTo>
        <relationshipLabel>Financial Account Numbers</relationshipLabel>
        <relationshipName>Financial_Account_Numbers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Financial Account Number</label>
    <nameField>
        <label>Financial Account Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Account Numbers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

RbA Build/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Store_Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Store Location</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>The account must be of type &quot;Store&quot;.</errorMessage>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Store</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Store Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

RbA Build/src/objects/Order.object
<CustomObject>
    <fields>
        <fullName>Install_Order_Status__c</fullName>
        <inlineHelpText>Set by status of related Install Work Order</inlineHelpText>
        <label>Install Order Status</label>
        <picklist>
            <picklistValues>
                <fullName>To be scheduled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Scheduled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>JIP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On Hold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Store_Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This order is related to this store location.</description>
        <inlineHelpText>This order is related to this store location.</inlineHelpText>
        <label>Store Location</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Orders (Store Location)</relationshipLabel>
        <relationshipName>Orders1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Tech_Measure_Status__c</fullName>
        <inlineHelpText>Set by related Tech Measure Work Order</inlineHelpText>
        <label>Tech Measure Status</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

RbA Build/src/objects/OrderItem.object
<CustomObject>
    <fields>
        <fullName>Purchase_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The purchase order that covers this sales order line item</description>
        <inlineHelpText>The purchase order that covers this sales order line item</inlineHelpText>
        <label>Purchase Order</label>
        <referenceTo>Purchase_Order__c</referenceTo>
        <relationshipLabel>Order Products</relationshipLabel>
        <relationshipName>Order_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>The status of the order line item.</description>
        <inlineHelpText>The status of the order line item.</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Configured</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Verified</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Partially Received</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Received</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

RbA Build/src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Vendor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Vendor</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>Products</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

RbA Build/src/objects/Purchase_Order__c.object
<CustomObject>
    <description>The purchase order header for ordering RbA and 3rd party products linked to order line items</description>
    <fields>
        <fullName>Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The parent sales order of this purchase order</description>
        <inlineHelpText>The parent sales order of this purchase order</inlineHelpText>
        <label>Order</label>
        <referenceTo>Order</referenceTo>
        <relationshipLabel>Purchase Orders</relationshipLabel>
        <relationshipName>Purchase_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>The status of the purchase order.</description>
        <inlineHelpText>The status of the purchase order.</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>In Process</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On Hold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Released</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Confirmed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Received</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Vendor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The vendor linked to the PO</description>
        <inlineHelpText>The vendor linked to the PO</inlineHelpText>
        <label>Vendor</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>The account must be of type Vendor.</errorMessage>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Vendor</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Purchase Orders</relationshipLabel>
        <relationshipName>Purchase_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Purchase Order</label>
    <nameField>
        <label>Purchase Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Purchase Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

RbA Build/src/objects/Store_Configuration__c.object
<CustomObject>
    <description>Holds Store Settings &amp; Configurations</description>
    <fields>
        <fullName>Store__c</fullName>
        <label>Store</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Store Configurations</relationshipLabel>
        <relationshipName>Store_Configurations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Store Configuration</label>
    <nameField>
        <displayFormat>SS-{00}</displayFormat>
        <label>Store Setting Record #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Store Configurations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

RbA Build/src/classes/PurchaseOrderTriggerHandlerTests.cls
@isTest
private class PurchaseOrderTriggerHandlerTests {
	
	@testSetup static void setupData() {
		TestUtilityMethods utility = new TestUtilityMethods();
		
		utility.setUpConfigs();
		
		Account account1 = utility.createVendorAccount('Vendor Account 1 ');
		insert account1;

		Account account2 = new Account(	Name = 'RbA',
										AccountNumber = '1234567890',
										Phone = '(763) 555-2000'
									);
		insert account2;

		Account dwelling = utility.createDwellingAccount('Dwelling Account');

		Account store = [SELECT Id from Account Where Name = '77 - Twin Cities, MN'];
		dwelling.Store_Location__c = store.Id;
		insert dwelling;

		
		Opportunity opp1 = utility.createOpportunity(dwelling.id, 'Closed - Won');
		insert opp1;
	
		//Store_Configuration__c stconfig = new Store_Configuration__c(Store__c = store.Id);
		//insert stconfig;
		
		Financial_Account_Number__c fan = new Financial_Account_Number__c(Name ='Finan Acc');
		insert fan;
		Product2 product1 = new Product2(
			Name='Test Product',
			Vendor__c = account1.id,
			Cost_PO__c = true,
			isActive = true,
			Account_Number__c =  fan.Id
		);
		
		insert product1;
		
		PricebookEntry pricebookEntry1 = utility.createPricebookEntry(Test.getStandardPricebookId(), product1.id);
		insert pricebookEntry1;
		
		List<Order> orderList =  new List<Order>{ new Order(	Name='Order1', 
									AccountId = dwelling.id, 
									EffectiveDate= Date.Today(), 
									Store_Location__c = store.Id,
									Opportunity = opp1,									
									Status ='Draft', 
									Tech_Measure_Status__c = 'New',
									Pricebook2Id = Test.getStandardPricebookId()
								),	new Order(	Name='Order2', 
									AccountId = dwelling.id, 
									EffectiveDate= Date.Today(), 
									Store_Location__c = store.Id,
									Opportunity = opp1, 									
									Status ='Draft',
									Tech_Measure_Status__c = 'New', 
									Pricebook2Id = Test.getStandardPricebookId()
								),	new Order(Name='Order3', 
									AccountId = dwelling.id, 
									EffectiveDate= Date.Today(), 
									Store_Location__c = store.Id,
									Opportunity = opp1, 									
									Status ='Draft', 
									Install_Order_Status__c = 'New',
									Pricebook2Id = Test.getStandardPricebookId()
								)};		
		insert orderList;

		List<OrderItem> oiList = new List<OrderItem>{new OrderItem(OrderId = OrderList[0].Id, PricebookentryId = pricebookEntry1.Id, Quantity = 2, UnitPrice = 100 ),
				new OrderItem(OrderId = OrderList[1].Id, PricebookentryId = pricebookEntry1.Id, Quantity = 2, UnitPrice = 100 ),
				new OrderItem(OrderId = OrderList[2].Id, PricebookentryId = pricebookEntry1.Id, Quantity = 2, UnitPrice = 100 )};
		insert oiList;

	}

	@isTest static void testeupdateOrderStatusToOrderReleased() {
		Account dwelling = [Select Id from Account where Name = 'Dwelling Account'];
		List<Order> orderList = [Select Id, Name, Status, Tech_Measure_Status__c,Install_Order_Status__c from Order where accountId =: dwelling.Id];
		for(Order o: orderList){
			o.Status = 'Ready to Order';
		}
		update orderList;
		List<Purchase_Order__c> poList = new List<Purchase_Order__c>();
		//Add two Purchase Orders for each Order in the list. Order1 will have one PO updated to Released, but have a related PO in New Status.
		//Order2 will have a related PO in Cancelled Status, and Order3 will have a related PO in Released status.
		for(Order o: orderList){
			if(o.Name == 'Order1'){
				poList.add(new Purchase_Order__c(Order__c = o.Id, Status__c = 'In Progress'));
				poList.add(new Purchase_Order__c(Order__c = o.Id, Status__c = 'New'));
			}else if(o.Name == 'Order2'){
				poList.add(new Purchase_Order__c(Order__c = o.Id, Status__c = 'In Progress'));
				poList.add(new Purchase_Order__c(Order__c = o.Id, Status__c = 'Cancelled'));
			}else if(o.Name == 'Order3'){
				poList.add(new Purchase_Order__c(Order__c = o.Id, Status__c = 'In Progress'));
				poList.add(new Purchase_Order__c(Order__c = o.Id, Status__c = 'Released'));
			}
		}
		insert poList;

		Map<Id, Purchase_Order__c> oldMap = new Map<Id, Purchase_Order__c>();
		Map<Id, Purchase_Order__c> newMap = new Map<Id, Purchase_Order__c>();
		for(Purchase_Order__c po: poList){
			if(po.Status__c == 'In Progress'){
				oldMap.put(po.Id, po);
				Purchase_Order__c poClone = po.clone(true, true, false, false);
				poClone.Status__c = 'Released';
				newMap.put(poClone.Id, poClone);
			}
		}

		System.assertEquals(newMap.keySet().size(),oldMap.keySet().size());

		PurchaseOrderTriggerHandler handler = new PurchaseOrderTriggerHandler(false,200);
		handler.updateOrderStatusToOrderReleased(oldMap, newMap);
		
		orderList = [Select Id, Name, Status, Tech_Measure_Status__c,Install_Order_Status__c from Order where accountId =: dwelling.Id];
		for(Order o: orderList){
			if(o.Name == 'Order1'){
				System.assertEquals('Ready to Order',o.Status);
			}else if(o.Name == 'Order2'){
				System.assertEquals('Order Released',o.Status);
			}else if(o.Name == 'Order3'){
				System.assertEquals('Order Released',o.Status);
			}
		}
	}

	@isTest static void testeupdateOrderStatusToInstallNeeded() {
		Account dwelling = [Select Id from Account where Name = 'Dwelling Account'];
		List<Order> orderList = [Select Id, Name, Status, Tech_Measure_Status__c,Install_Order_Status__c from Order where accountId =: dwelling.Id];
		for(Order o: orderList){
			o.Status = 'Order Released';
		}
		update orderList;
		List<Purchase_Order__c> poList = new List<Purchase_Order__c>();
		//Add two Purchase Orders for each Order in the list. Order1 will have one PO updated to Confirmed, but have a related PO in New Status.
		//Order2 will have a related PO in Cancelled Status, and Order3 will have a related PO in Confirmed status.
		for(Order o: orderList){
			if(o.Name == 'Order1'){
				poList.add(new Purchase_Order__c(Order__c = o.Id, Status__c = 'In Progress'));
				poList.add(new Purchase_Order__c(Order__c = o.Id, Status__c = 'New'));
			}else if(o.Name == 'Order2'){
				poList.add(new Purchase_Order__c(Order__c = o.Id, Status__c = 'In Progress'));
				poList.add(new Purchase_Order__c(Order__c = o.Id, Status__c = 'Cancelled'));
			}else if(o.Name == 'Order3'){
				poList.add(new Purchase_Order__c(Order__c = o.Id, Status__c = 'In Progress'));
				poList.add(new Purchase_Order__c(Order__c = o.Id, Status__c = 'Confirmed'));
			}
		}
		insert poList;

		Map<Id, Purchase_Order__c> oldMap = new Map<Id, Purchase_Order__c>();
		Map<Id, Purchase_Order__c> newMap = new Map<Id, Purchase_Order__c>();
		for(Purchase_Order__c po: poList){
			if(po.Status__c == 'In Progress'){
				oldMap.put(po.Id, po);
				Purchase_Order__c poClone = po.clone(true, true, false, false);
				poClone.Status__c = 'Confirmed';
				newMap.put(poClone.Id, poClone);
			}
		}

		System.assertEquals(newMap.keySet().size(),oldMap.keySet().size());

		PurchaseOrderTriggerHandler handler = new PurchaseOrderTriggerHandler(false,200);
		handler.updateOrderStatusToInstallNeeded(oldMap, newMap);
		
		orderList = [Select Id, Name, Status, Tech_Measure_Status__c,Install_Order_Status__c from Order where accountId =: dwelling.Id];
		for(Order o: orderList){
			if(o.Name == 'Order1'){
				System.assertEquals('Order Released',o.Status);
			}else if(o.Name == 'Order2'){
				System.assertEquals('Install Needed',o.Status);
			}else if(o.Name == 'Order3'){
				System.assertEquals('Install Needed',o.Status);
			}
		}
	}
	
}