RbA Build/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Building_Permit__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The Building Permit is populated in Code
Matching in the Municipalities table.
Matching criteria Address City and Zip code, match is found in the Municipality Match object</inlineHelpText>
        <label>Building Permit</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>You must select a Building record. If the record for you are for isn&apos;t in the system, please contact your manager to have it created.</errorMessage>
            <filterItems>
                <field>Municipality__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Permit</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Municipality__c</referenceTo>
        <relationshipLabel>Building Permit Dwellings</relationshipLabel>
        <relationshipName>Accounts2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Store_Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The store location that this dwelling is related</description>
        <inlineHelpText>The store location that this dwelling is related</inlineHelpText>
        <label>Store Location</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>The account must be of type &quot;Store&quot;</errorMessage>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Store</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Dwellings</relationshipLabel>
        <relationshipName>StoreLocation</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Dwelling</fullName>
        <active>true</active>
        <description>Used to support Dwelling</description>
        <label>Dwelling</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

RbA Build/src/objects/Municipality__c.object
<CustomObject>
    <description>Holds Municipality information that will help with HOA, Historical and Permitting details.</description>
    <fields>
        <fullName>City_Township__c</fullName>
        <label>City/Township</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>For_Retail_Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>What Retail Location is this for?</inlineHelpText>
        <label>For Retail Location</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Store</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Municipalities</relationshipLabel>
        <relationshipName>Municipalities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Zip_Code__c</fullName>
        <label>Zip Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Municipality</label>
    <nameField>
        <label>Agency Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Municipalities</pluralLabel>
    <recordTypes>
        <fullName>Permit</fullName>
        <active>true</active>
        <description>Hold information for Building Permits (not Building)</description>
        <label>Permit</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

RbA Build/src/objects/Municipality_Match__c.object
<CustomObject>
    <fields>
        <fullName>Agency_Name__c</fullName>
        <label>Agency Name</label>
        <referenceTo>Municipality__c</referenceTo>
        <relationshipLabel>Municipalities Match</relationshipLabel>
        <relationshipName>Municipalities_Match</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>City_Township__c</fullName>
        <label>City/Township</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zip_Code__c</fullName>
        <label>Zip Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Municipality Match</label>
    <nameField>
        <displayFormat>MM-{00}</displayFormat>
        <label>Municipality Match Record Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Municipalities Match</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

RbA Build/src/classes/AccountTriggerHandler.cls
/*******************************************************//**

@class	AccountTriggerHandler

@brief	Controller to hold logic for AccountTrigger trigger

@author  Anthony Strafaccia (Slalom.ADS)

@version	2015-10/15  Slalom.ADS
	Created.

@see		AccountTriggerHandlerTest

@copyright  (c)2015 Slalom.  All Rights Reserved.
			Unauthorized use is prohibited.

***********************************************************/


public without sharing class AccountTriggerHandler{

   
    public void OnBeforeInsert(List<Account> listNew){ 
        system.debug('ads INSIDE BEFORE INSERT');  
        
        Id dwellingAccountRecordType = UtilityMethods.retrieveRecordTypeId('Dwelling', 'Account');
        list<id> storeLocationIds = new list<id>();
        for(Account acct : listNew){
        	storeLocationIds.add(acct.Store_Location__c);
        }
        /*
        list<Account> storeLocations = [SELECT id, Building_Permit__c FROM Account WHERE id IN :storeLocationIds];
        list<id> permitMunicipalityIds = new list<id>();
        for(Account acct : storeLocations){
        	permitMunicipalityIds.add(acct.Building_Permit__c);
        }
        */
        list<Municipality__c> permitMunicipalities = [SELECT Id  FROM Municipality__c WHERE For_Retail_Location__c IN :storeLocationIds];
        list<id> permitMunicipalityIds = new list<id>();
        for(Municipality__c muni : permitMunicipalities){
        	permitMunicipalityIds.add(muni.Id);
        }
        list<Municipality_Match__c> permitMunicipalityMatchs = [SELECT id, Agency_Name__c, Zip_Code__c, City_Township__c, Agency_Name__r.For_Retail_Location__c FROM Municipality_Match__c WHERE Agency_Name__c IN :permitMunicipalityIds];
        map<id, list<Municipality_Match__c>> storeIDtoListOfMatchMap = new  map<id, list<Municipality_Match__c>>();
		
		
		
		//map<id, list<Municipality_Match__c>> storeIDtoListOfMatchMap = new  map<id, list<Municipality_Match__c>>();
		
		for(Municipality_Match__c muniMatch : permitMunicipalityMatchs){
			if(storeIDtoListOfMatchMap.containsKey(muniMatch.Agency_Name__r.For_Retail_Location__c)){
				storeIDtoListOfMatchMap.get(muniMatch.Agency_Name__r.For_Retail_Location__c).add(muniMatch);
			}else{
				storeIDtoListOfMatchMap.put(muniMatch.Agency_Name__r.For_Retail_Location__c, new list<Municipality_Match__c>{muniMatch});
			}	
		}   

        
        for(Account dwelling : listNew){
        	if(dwelling.RecordTypeId == dwellingAccountRecordType && dwelling.BillingPostalCode != null && dwelling.BillingCity != null){
        		system.debug('ads permitMunicipalityMatchs.size(): ' +permitMunicipalityMatchs.size());
        		list<Municipality_Match__c> relatedMatches = storeIDtoListOfMatchMap.get(dwelling.Store_Location__c);
        		
        		for(Municipality_Match__c mm : relatedMatches){
        			system.debug('ads mm.Zip_Code__c = dwelling.BillingPostalCode: '+mm.Zip_Code__c+' = '+dwelling.BillingPostalCode);
        			system.debug('ads mm.City_Township__c.toUpperCase() = dwelling.BillingCity.toUpperCase(): '+mm.City_Township__c.toUpperCase()+' = '+dwelling.BillingCity.toUpperCase());
        			
        			if(	mm.Zip_Code__c == dwelling.BillingPostalCode && mm.City_Township__c.toUpperCase() == dwelling.BillingCity.toUpperCase()){
        				system.debug('ads setting Building_Permit__c: ' +mm.Agency_Name__c);
        				dwelling.Building_Permit__c = mm.Agency_Name__c;
        				break;
    				}
        		}
        		
        		/*
        		Store_Location__c on account 
        		that account has Building_Permit__c a lookup to Municipality__c object with record type Permit 
        		find all the children of that object of type Municipality_Match__c
        		Billing Zip/Postal Code + Billing City = Zip Code + City/Township
        		*/
        	}
        }
    } 
    

    /*
    public void OnBeforeUpdate(List<Account> listOld, List<Account> listNew, Map<Id, Account> mapOld, Map<Id, Account> mapNew){
        system.debug('ads INSIDE BEFORE UPDATE');
    }
    */

    /*
    public void OnBeforeDelete(List<Account> listToDelete, Map<Id, Account> mapToDelete){
        system.debug('ads INSIDE BEFORE DELETE');
    }
    */

    /*
    public void OnAfterInsert(List<Account> listNew, Map<Id, Account> mapNew){
         system.debug('ads INSIDE AFTER INSERT');       
    }
    */

    /*
    public void OnAfterUpdate(List<Account> listOld, List<Account> listNew, Map<Id, Account> mapOld, Map<Id, Account> mapNew){
          system.debug('ads INSIDE AFTER UPDATE');        
    }
    /*

    /*
    public void OnAfterDelete(List<Account> listDeleted, Map<Id, Account> listNew){
         system.debug('ads INSIDE AFTER DELETE'); 
    }
    */
 
    /*
    public void OnUndelete(List<Account> listRestored){
         system.debug('ads INSIDE ON UNDELETE'); 
    }
    */
}