RbA Build/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Active_Store_Configuration__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>currently active store configuration</description>
        <label>Active Store Configuration</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Store_Configuration__c.Store__c</field>
                <operation>equals</operation>
                <valueField>$Source.Id</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Store_Configuration__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Store_Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The store location that this dwelling is related</description>
        <inlineHelpText>The store location that this dwelling is related</inlineHelpText>
        <label>Store Location</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>The account must be of type &quot;Store&quot;</errorMessage>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Store</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Dwellings</relationshipLabel>
        <relationshipName>StoreLocation</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Dwelling</fullName>
        <active>true</active>
        <description>Used to support Dwelling</description>
        <label>Dwelling</label>
    </recordTypes>
    <recordTypes>
        <fullName>Store</fullName>
        <active>true</active>
        <description>Used to track and store data releated to Retail Locations both CORO and ARO</description>
        <label>Store</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

RbA Build/src/objects/Financial_Account_Number__c.object
<CustomObject>
    <description>Stores financial account numbers used in the journal entries and Baan ERP integration</description>
    <fields>
        <fullName>Account_Type__c</fullName>
        <description>Type used to filter which accounts are available for selection.</description>
        <inlineHelpText>Type used to filter which accounts are available for selection.</inlineHelpText>
        <label>Account Type</label>
        <picklist>
            <picklistValues>
                <fullName>Intercompany Accounts Payable</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cost PO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Accts Receivable Acct</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Internal Labor Transfer Acct</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ACH Payment Acct</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inventory Acct</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bond Refund Payment Acct</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>JIP External Labor Acct</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Change Order Adjustment Acct</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>JIP Internal Labor Acct</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Check Acct</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Marketing Discount Acct</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consumer Deposits Acct</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Marketing Display Cost Acct</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Credit Card AmEx Acct</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Materials Acct</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Credit Card Diners Club Acct</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Miscellaneous Receipts Acct</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Credit Card Discover Acct</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Misc Service Revenue Acct</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Credit Card VM Acct</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NSF Check Acct</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Refund CC Acct</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Permit Refunds Acct</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Refund Check Acct</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Product COGS Acct</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Debit on Account Acct</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Remake Expense Acct</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Discount Acct</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Renewal Rewards Acct</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Store_Configuration__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Select which store configuration to relate this account number.</description>
        <inlineHelpText>Select which store configuration to relate this account number.</inlineHelpText>
        <label>Store Configuration</label>
        <referenceTo>Store_Configuration__c</referenceTo>
        <relationshipLabel>Financial Account Numbers</relationshipLabel>
        <relationshipName>Financial_Account_Numbers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Financial Account Number</label>
    <nameField>
        <label>Financial Account Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Account Numbers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

RbA Build/src/objects/Financial_Transaction__c.object
<CustomObject>
    <description>Object to store financial transaction records</description>
    <fields>
        <fullName>Credit_Account_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Select the account number to credit in this financial transaction</description>
        <inlineHelpText>Select the account number to credit in this financial transaction</inlineHelpText>
        <label>Credit Account Number</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Only account numbers related to this financial transaction&apos;s store location can be selected.</errorMessage>
            <filterItems>
                <field>Financial_Account_Number__c.Store_Configuration__c</field>
                <operation>equals</operation>
                <valueField>$Source.Store_Configuration__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Financial_Account_Number__c</referenceTo>
        <relationshipLabel>Financial Transactions Credit</relationshipLabel>
        <relationshipName>Financial_Transactions_Credit</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Debit_Account_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Select the account number to debit in this financial transaction</description>
        <inlineHelpText>Select the account number to debit in this financial transaction</inlineHelpText>
        <label>Debit Account Number</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Only account numbers related to this financial transaction&apos;s store location can be selected.</errorMessage>
            <filterItems>
                <field>Financial_Account_Number__c.Store_Configuration__c</field>
                <operation>equals</operation>
                <valueField>$Source.Store_Configuration__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Financial_Account_Number__c</referenceTo>
        <relationshipLabel>Financial Transactions Debit</relationshipLabel>
        <relationshipName>Financial_Transactions_Debit</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Store_Configuration__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>The store configuration this transaction is related to</description>
        <inlineHelpText>The store configuration this transaction is related to</inlineHelpText>
        <label>Store Configuration</label>
        <referenceTo>Store_Configuration__c</referenceTo>
        <relationshipLabel>Financial Transactions</relationshipLabel>
        <relationshipName>Financial_Transactions</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Transaction_Type__c</fullName>
        <description>Select the transaction type for this record. This will determine when these accounts will be debited/credited.</description>
        <inlineHelpText>Select the transaction type for this record. This will determine when these accounts will be debited/credited.</inlineHelpText>
        <label>Transaction Type</label>
        <picklist>
            <picklistValues>
                <fullName>Deposit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Final Payment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inventory Received</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inventory Installed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Misc Sub-Payment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>External Labor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Internal Labor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Misc Cash Receipt</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Misc Reimbursement</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Financial Transaction</label>
    <nameField>
        <displayFormat>FT-{00000}</displayFormat>
        <label>Financial Transaction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Financial Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

RbA Build/src/objects/Order.object
<CustomObject>
    <fields>
        <fullName>Store_Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This order is related to this store location.</description>
        <inlineHelpText>This order is related to this store location.</inlineHelpText>
        <label>Store Location</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Orders (Store Location)</relationshipLabel>
        <relationshipName>Orders1</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

RbA Build/src/objects/OrderItem.object
<CustomObject>
    <fields>
        <fullName>Unit_Wholesale_Cost__c</fullName>
        <description>The wholesale cost of the product</description>
        <inlineHelpText>The wholesale cost of the product</inlineHelpText>
        <label>Wholesale Cost</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
</CustomObject>

RbA Build/src/objects/Payment__c.object
<CustomObject>
    <description>The object used to store payment records</description>
    <fields>
        <fullName>Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The payment record is related to this order.</description>
        <inlineHelpText>The payment record is related to this order.</inlineHelpText>
        <label>Order</label>
        <referenceTo>Order</referenceTo>
        <relationshipLabel>Payments</relationshipLabel>
        <relationshipName>Payments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Payment_Amount__c</fullName>
        <description>The amount paid.</description>
        <inlineHelpText>The amount paid.</inlineHelpText>
        <label>Payment Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Store_Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The store location where this payment was received.</description>
        <inlineHelpText>The store location where this payment was received.</inlineHelpText>
        <label>Store Location</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Payments</relationshipLabel>
        <relationshipName>Payments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Payment</label>
    <nameField>
        <displayFormat>P-{00000000}</displayFormat>
        <label>Payment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <recordTypes>
        <fullName>Deposit</fullName>
        <active>true</active>
        <description>Deposit record type</description>
        <label>Deposit</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

RbA Build/src/objects/Product2.object
<CustomObject>
    <recordTypes>
        <fullName>Master_Product</fullName>
        <active>true</active>
        <label>Master Product</label>
    </recordTypes>
</CustomObject>

RbA Build/src/objects/Store_Configuration__c.object
<CustomObject>
    <description>Holds Store Settings &amp; Configurations</description>
    <fields>
        <fullName>Store__c</fullName>
        <label>Store</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Store Configurations</relationshipLabel>
        <relationshipName>Store_Configurations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Store Configuration</label>
    <nameField>
        <displayFormat>SS-{00}</displayFormat>
        <label>Store Setting Record #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Store Configurations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

RbA Build/src/objects/SVMXC__Service_Order__c.object
<CustomObject>
    <customHelp>SVMXC__SVMXC_LaunchHelp</customHelp>
    <description>Service Order is used to plan, execute and manage Service events for Field and Depot Service activities. Depending upon the service scenario, the order creation can be triggered by many events: When creating a Support Case, when one or more installed products require periodic service or calibration, when troubleshooting a customer problem on the field, if the field service engineer learns that the product requires specialized conditions of a factory/depot to resolve the problem, or when a new/repair shipment to customer requires specialized installation activity.</description>
    <label>Work Order</label>
    <nameField>
        <displayFormat>WO-{00000000}</displayFormat>
        <label>Work Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

RbA Build/src/classes/UtilityMethodsTest.cls
/*******************************************************//**

@class	UtilityMethodsTest

@brief	Test Class for UtilityMethods

@author  Creston Kuenzi (Slalom.CDK)

@version	2015-2-2  Slalom.CDK
	Created.

@see		UtilityMethods

@copyright  (c)2016 Slalom.  All Rights Reserved. 
			Unauthorized use is prohibited.

***********************************************************/
@isTest
private class UtilityMethodsTest {

	/*******************************************************
					retrieveRecordTypeIdTest
	*******************************************************/
	static testMethod void retrieveRecordTypeIdTest() {

		// Verify the retrieveRecordTypeId retrieves an id for Account->Dwelling
		id dwellingRT = UtilityMethods.retrieveRecordTypeId('Dwelling', 'Account');
		System.Assert(dwellingRT != null);
	}

	/*******************************************************
					RecordTypeForTest
	*******************************************************/
	static testMethod void RecordTypeForTest() {

		// Verify the RecordTypeFor retrieves an id for Account->Dwelling
		id dwellingRT = UtilityMethods.RecordTypeFor('Account', 'Dwelling');
		System.Assert(dwellingRT != null);
	}

	/*******************************************************
	 GetRecordTypeIdsMapForSObjectTest
	*******************************************************/

	 static testMethod void GetRecordTypeIdsMapForSObjectTest(){
	 	id masterProductId =  UtilityMethods.GetRecordTypeIdsMapForSObject(Product2.sObjectType).get('Master_Product');
	 	system.assert(masterProductId != null);
	 }

	/*******************************************************
					buildWorkOrderTest
	*******************************************************/
	static testMethod void buildWorkOrderTest() {
		Account a = new Account();
		Order o = new Order();
		Id rtID = '111000000000000';
		Id ownerId = '111000000000000';
		String ordtype = '111000000000000';
		Id munici = '111000000000000';
		
		// Verify the RecordTypeFor retrieves an id for Account->Dwelling
//		SVMXC__Service_Order__c workOrder = UtilityMethods.BuildWorkOrder(a, o, rtId, ownerId, ordType, munici);
//		System.Assert(workOrder != null);
	}

	/*******************************************************
					mapStoreConfigsTest
	*******************************************************/
	static testMethod void mapStoreConfigsTest() {

		TestUtilityMethods utility = new TestUtilityMethods();
		
		utility.setUpConfigs();
		
		Account myStore = utility.createStoreAccount('mystore');
		insert myStore;
		
		Store_Configuration__c myStoreConfig = new Store_Configuration__c(Store__c = myStore.Id);
		insert myStoreConfig;
		
		List<Id> storeIds = new List<Id>();
		storeIds.add(myStore.Id);
		
		map<Id, Store_Configuration__c> myStoreMap = UtilityMethods.mapStoreConfigs(storeIds);
		
		System.AssertEquals(myStoreConfig, myStoreMap.get(myStore.Id));

	}

	/*******************************************************
					calculateFractionTest
	*******************************************************/
	static testMethod void calculateFractionTest() {

		decimal testFraction = UtilityMethods.calculateFraction('1/2');
		System.AssertEquals(0.5, testFraction);

		testFraction = UtilityMethods.calculateFraction('Even');
		System.AssertEquals(0, testFraction);

		testFraction = UtilityMethods.calculateFraction('7/8');
		System.AssertEquals(0.875, testFraction);

		testFraction = UtilityMethods.calculateFraction('1/16');
		System.AssertEquals(0.062, testFraction);
	}
	
	/*******************************************************
					retrieveAccountNumbersTest
	*******************************************************/
	static testMethod void retrieveAccountNumbersTest() {

		TestUtilityMethods utility = new TestUtilityMethods();
		
		utility.setUpConfigs();
		
		Account myStore = utility.createStoreAccount('mystore');
		insert myStore;
		
		Store_Configuration__c myStoreConfig = new Store_Configuration__c(Store__c = myStore.Id);
		insert myStoreConfig;
		
		Financial_Account_Number__c finNumber = new Financial_Account_Number__c(Name='123', Account_Type__c='myaccounttype', Store_Configuration__c = myStoreConfig.Id);
		insert finNumber;
		
		map<String, String> myStoreMap = UtilityMethods.retrieveAccountNumbers(myStore.Id);
		
		System.AssertEquals('123', myStoreMap.get('myaccounttype'));

	}

	/*******************************************************
					lockRecordsTest
	*******************************************************/
	static testMethod void lockRecordsTest() {

		TestUtilityMethods utility = new TestUtilityMethods();
		
		utility.setUpConfigs();

		List<Account> recordsToLock = new List<Account>();		
		Account Account1 = utility.createAccount('Account1');
		recordsToLock.add(Account1);

		Account Account2 = utility.createAccount('Account2');
		recordsToLock.add(Account2);

		insert recordsToLock;
		
		// Lock the accounts
		String result = UtilityMethods.lockRecords(recordsToLock);
		System.AssertEquals('Records successfully locked', result);
		
	}

	/*******************************************************
					checkLockedTest
	*******************************************************/
	static testMethod void checkLockedTest() {

		TestUtilityMethods utility = new TestUtilityMethods();
		
		utility.createOrderTestRecords();

		Order soldOrder = [SELECT Id FROM Order WHERE Name = 'Sold Order 1'];
		Account store = [SELECT Id, Active_Store_Configuration__c from Account Where Name = '77 - Twin Cities, MN'];

		Test.startTest();
		List<Financial_Account_Number__c> numbersList = new List<Financial_Account_Number__c>();
		Financial_Account_Number__c accountNumber1 = new Financial_Account_Number__c(Name='123', Store_Configuration__c = store.Active_Store_Configuration__c);	
		Financial_Account_Number__c accountNumber2 = new Financial_Account_Number__c(Name='234', Store_Configuration__c = store.Active_Store_Configuration__c);	
		insert numbersList;
		
		Financial_Transaction__c finTransaction = new Financial_Transaction__c(Transaction_Type__c='Deposit', Debit_Account_Number__c = accountNumber1.Id, Credit_Account_Number__c = accountNumber2.Id, Store_Configuration__c = store.Active_Store_Configuration__c);	
		insert finTransaction;

		List<Payment__c> lockedRecords = new List<Payment__c>();		
		List<Payment__c> unlockedRecords = new List<Payment__c>();		
		Payment__c Payment1 = new Payment__c(Order__c = soldOrder.Id, Store_Location__c = store.Id, Payment_Amount__c = 500, Locked__c = false);
		unlockedRecords.add(Payment1);

		Payment__c Payment2 = new Payment__c(Order__c = soldOrder.Id, Store_Location__c = store.Id, Payment_Amount__c = 500, Locked__c = false);
		unlockedRecords.add(Payment2);

		insert unlockedRecords;
//		insert unlockedRecords2;
		
		Payment__c Payment3 = new Payment__c(Order__c = soldOrder.Id, Store_Location__c = store.Id, Payment_Amount__c = 500, Locked__c = true);
		lockedRecords.add(Payment3);

		Payment__c Payment4 = new Payment__c(Order__c = soldOrder.Id, Store_Location__c = store.Id, Payment_Amount__c = 500, Locked__c = true);
		lockedRecords.add(Payment4);

		insert lockedRecords;

		map<id, sObject> unlockedMap = new map<id, Payment__c>();
		map<id, sObject> lockedMap = new map<id, Payment__c>();
		
		unlockedMap.put(Payment1.Id, Payment1);
		unlockedMap.put(Payment2.Id, Payment2);

		lockedMap.put(Payment1.Id, Payment3);
		lockedMap.put(Payment2.Id, Payment4);

		// Just send the unlocked lists/maps so no records will be locked since there is no change
		String result = UtilityMethods.checkLocked(unlockedRecords, unlockedRecords, unlockedMap, unlockedMap, 'Update');		
		System.AssertEquals('No records locked', result);

		// TODO:
		// This should work but throws a null pointer exception in the utility class. I suspect this is a salesforce bug
//		String result = UtilityMethods.checkLocked(lockedRecords, unlockedRecords, lockedMap, unlockedMap, 'Update');		
//		System.AssertEquals('At least one record was locked', result);

		Test.stopTest();
		
	}

	/*******************************************************
					checkLockedOrderTest
	*******************************************************/
	static testMethod void checkLockedOrderTest() {

		TestUtilityMethods utility = new TestUtilityMethods();
		
		utility.createOrderTestRecords();

		Order soldOrder = [SELECT Id, Name, Status FROM Order WHERE Name = 'Sold Order 1'];
		Account store = [SELECT Id, Active_Store_Configuration__c from Account Where Name = '77 - Twin Cities, MN'];

		List<Order> lockedRecords = new List<Order>();		
		List<Order> unlockedRecords = new List<Order>();		
		unlockedRecords.add(soldOrder);

		lockedRecords.add(soldOrder);

		map<id, sObject> unlockedMap = new map<id, Order>();
		map<id, sObject> lockedMap = new map<id, Order>();
		
		unlockedMap.put(soldOrder.Id, soldOrder);

		lockedMap.put(soldOrder.Id, soldOrder);

		// Just send the unlocked lists/maps so no records will be locked since there is no change
		String result = UtilityMethods.checkLockedByStatus(unlockedRecords, unlockedRecords, unlockedMap, unlockedMap, 'Order');		
		System.AssertEquals('No records locked', result);

		// TODO:
		// This should work but throws a null pointer exception in the utility class. I suspect this is a salesforce bug
//		String result = UtilityMethods.checkLocked(lockedRecords, unlockedRecords, lockedMap, unlockedMap, 'Update');		
//		System.AssertEquals('At least one record was locked', result);
		
	}

	/*******************************************************
					calculateTaxesTest
	*******************************************************/
	static testMethod void calculateTaxesTest() {

		OrderItem orderItem1 = new OrderItem();
		OrderItem orderItem2 = new OrderItem(Unit_Wholesale_Cost__c = 100, Quantity = 1);
		OrderItem orderItem3 = new OrderItem(Unit_Wholesale_Cost__c = 100, Quantity = 2);
		OrderItem orderItem4 = new OrderItem(Unit_Wholesale_Cost__c = 100, Quantity = 1);
		List<OrderItem> itemstoSend = new List<OrderItem> { orderItem1, orderItem2, orderItem3, orderItem4 };

		// Calculate taxes for subtotal of 400 and 10 in tax
		List<OrderItem> returnedItems = UtilityMethods.calculateTaxes(itemstoSend, 400, 10);

		System.AssertEquals(null, orderItem1.Tax__c);				
		System.AssertEquals(2.5, orderItem2.Tax__c);				
		System.AssertEquals(5, orderItem3.Tax__c);				
		System.AssertEquals(2.5, orderItem4.Tax__c);				
	}
}