RbA Build/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Store_Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The store location that this dwelling is related</description>
        <inlineHelpText>The store location that this dwelling is related</inlineHelpText>
        <label>Store Location</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>The account must be of type &quot;Store&quot;</errorMessage>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Store</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Dwellings</relationshipLabel>
        <relationshipName>StoreLocation</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Vendor_Account_Type__c</fullName>
        <label>Vendor Account Type</label>
        <picklist>
            <picklistValues>
                <fullName>Intercompany</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Intercompany Consolidation Center</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>External</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>Store</fullName>
        <active>true</active>
        <description>Used to track and store data releated to Retail Locations both CORO and ARO</description>
        <label>Store</label>
    </recordTypes>
    <recordTypes>
        <fullName>Vendor</fullName>
        <active>true</active>
        <description>Used to track Vendors</description>
        <label>Vendor</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

RbA Build/src/objects/Asset.object
<CustomObject>
    <fields>
        <fullName>Sold_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Related Sold Order</inlineHelpText>
        <label>Sold Order</label>
        <referenceTo>Order</referenceTo>
        <relationshipLabel>Assets</relationshipLabel>
        <relationshipName>Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Store_Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Store Location</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Assets</relationshipLabel>
        <relationshipName>Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Unit_Wholesale_Cost__c</fullName>
        <label>Unit Wholesale Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <recordTypes>
        <fullName>Installed_Products</fullName>
        <active>true</active>
        <description>Windows and Doors installed by RbA</description>
        <label>Installed Products</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

RbA Build/src/objects/Financial_Account_Number__c.object
<CustomObject>
    <description>Stores financial account numbers used in the journal entries and Baan ERP integration</description>
    <fields>
        <fullName>Store_Configuration__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Select which store configuration to relate this account number.</description>
        <inlineHelpText>Select which store configuration to relate this account number.</inlineHelpText>
        <label>Store Configuration</label>
        <referenceTo>Store_Configuration__c</referenceTo>
        <relationshipLabel>Financial Account Numbers</relationshipLabel>
        <relationshipName>Financial_Account_Numbers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Financial Account Number</label>
    <nameField>
        <label>Financial Account Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Account Numbers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

RbA Build/src/objects/Journal_Entry__c.object
<CustomObject>
    <description>Holds the Financial Transactions that are sent to an Accounting System.
Baan ERP, etc.</description>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Credit_General_Ledger_Account__c</fullName>
        <label>Credit General Ledger Account</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Debit_General_Ledger_Account__c</fullName>
        <label>Debit General Ledger Account</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order</label>
        <referenceTo>Order</referenceTo>
        <relationshipLabel>Journal Entries</relationshipLabel>
        <relationshipName>Journal_Entries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sent_to_BaanERP__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Sent to BaanERP</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Store_Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Store Location</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Journal Entries</relationshipLabel>
        <relationshipName>Journal_Entries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Deposit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Final Payment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Misc Cash Receipt</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>External Labor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Service External Labor - JIP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Service External Labor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Internal Labor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Post Recognized Service External Labor - JIP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Post Recognized Service External Labor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Post Recognized External Labor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Post Recognized Internal Labor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Misc Reimbursement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rev Recognized - Deposit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rev Recognized - External Labor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rev Recognized - Service External Labor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rev Recognized - Service External Labor - JIP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rev Recognized - Refund Deposit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rev Recognized - COGS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rev Recognized - Discount</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rev Recognized - AR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rev Recognized - Service AR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rev Recognized - Finance Fees</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rev Recognized - Service Tax</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rev Recognized - Install Adjustment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Refund - Deposit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Refund - Final Payment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cost Product Received</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Service Inventory Received - Intercompany Consolidation Center</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Service Inventory Received - External Vendor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Service Inventory Received - Remake External Vendor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inventory Received - Intercompany</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inventory Received - Intercompany Consolidation Center</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inventory Received - External Vendor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inventory Write-Off</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Journal Entry</label>
    <nameField>
        <displayFormat>JEN-{000000}</displayFormat>
        <label>Journal Entry Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Journal Entries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

RbA Build/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Store_Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Store Location</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>The account must be of type &quot;Store&quot;.</errorMessage>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Store</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Store Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

RbA Build/src/objects/Order.object
<CustomObject>
    <fields>
        <fullName>Sold_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>When the Sold Order is Job In Progress, the Service Order must be related to the Sold Order.</inlineHelpText>
        <label>Sold Order</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>$Source.AccountId</field>
                <operation>equals</operation>
                <valueField>Order.AccountId</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Order</referenceTo>
        <relationshipLabel>Service Orders</relationshipLabel>
        <relationshipName>Sold_Order</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Store_Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This order is related to this store location.</description>
        <inlineHelpText>This order is related to this store location.</inlineHelpText>
        <label>Store Location</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Orders (Store Location)</relationshipLabel>
        <relationshipName>Orders1</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

RbA Build/src/objects/OrderItem.object
<CustomObject>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Remake</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Replacement</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Unit_Wholesale_Cost__c</fullName>
        <description>The wholesale cost of the product</description>
        <inlineHelpText>The wholesale cost of the product</inlineHelpText>
        <label>Wholesale Cost</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
</CustomObject>

RbA Build/src/objects/Pricebook2.object
<CustomObject>
    <fields>
        <fullName>Store_Configuration__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Links price books to store configuration.  All configuration that are store based are tied to the store configuration for that store.</description>
        <inlineHelpText>Link this to the store configuration for the store this Price Book is being created for.</inlineHelpText>
        <label>Store Configuration</label>
        <referenceTo>Store_Configuration__c</referenceTo>
        <relationshipLabel>Price Books</relationshipLabel>
        <relationshipName>Price_Books</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadSelect</sharingModel>
</CustomObject>

RbA Build/src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Vendor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Vendor</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>Products</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

RbA Build/src/objects/Store_Configuration__c.object
<CustomObject>
    <description>Holds Store Settings &amp; Configurations</description>
    <fields>
        <fullName>Location_Number__c</fullName>
        <description>Enter the location number for this store.</description>
        <inlineHelpText>Enter the location number for this store.</inlineHelpText>
        <label>Location Number</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Standard_Hourly_Rate__c</fullName>
        <inlineHelpText>Standard Hourly Rate used for Labor</inlineHelpText>
        <label>Standard Hourly Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Store__c</fullName>
        <label>Store</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Store Configurations</relationshipLabel>
        <relationshipName>Store_Configurations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Store Configuration</label>
    <nameField>
        <displayFormat>SS-{00}</displayFormat>
        <label>Store Setting Record #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Store Configurations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

RbA Build/src/classes/RMS_financialTransManInventoryTest.cls
/*******************************************************//**

@class	RMS_financialTransManInventoryTest

@brief	Test Class for RMS_financialTransactionManager

		Separated the original test class into multiple test classes. This one focuses
		on the inventory test classes 

@author  Creston Kuenzi (Slalom.CDK)

@version	2016-10-5  Slalom.CDK
	Created.

@see		RMS_financialTransactionManager

@copyright  (c)2016 Slalom.  All Rights Reserved. 
			Unauthorized use is prohibited.

***********************************************************/
@isTest
private class RMS_financialTransManInventoryTest {

	/*******************************************************
					setupData
	*******************************************************/
	@testSetup static void setupData(){

		TestUtilityMethods testMethods = new TestUtilityMethods();
		testMethods.setUpConfigs();
		
		Account store1 = [SELECT id FROM Account WHERE Name='77 - Twin Cities, MN'];
		Store_Configuration__c storeConfig1 = [SELECT id FROM Store_Configuration__c WHERE Store__c = :store1.id ];
		
		Account dwelling1 = testMethods.createDwellingAccount('dwelling1');
		dwelling1.Store_Location__c = store1.id;
		insert dwelling1;
		
		Contact contact1 = testMethods.createContact(dwelling1.id, 'contact1');
		insert contact1;
		
		Opportunity opp1 = testMethods.createOpportunity(dwelling1.id, 'Draft');
		insert opp1;
		
		Order order1 = new Order(	Name='Sold Order 1', 
									AccountId = dwelling1.id, 
									EffectiveDate= Date.Today(), 
									Store_Location__c = store1.Id,
									Opportunity = opp1, 									
									Status ='Draft',
									BillToContactId = contact1.id, 
									Pricebook2Id = Test.getStandardPricebookId()
								);
		insert order1;

			
		
		Account vend1 = testMethods.createIntercompanyVendorAccount('Intercompany');
		Account vend2 = testMethods.createIntercompanyCCVendorAccount('IntercompanyCC');
		Account vend3 = testMethods.createExternalVendorAccount('External');
		List<Account> vendsToInsert = new List<Account>{vend1,vend2,vend3};
		
		insert vendsToInsert;
		
		Pricebook2 pricebook1 =  testMethods.createPricebook2Name('Standard Price Book');
		insert pricebook1;

		Product2 product1 = new Product2(
			Name='Test Product',
			Vendor__c = vend1.id
		);

		insert product1;
		
		PricebookEntry pricebookEntry1 = testMethods.createPricebookEntry(Test.getStandardPricebookId(), product1.id);
		insert pricebookEntry1;
		
		OrderItem orderItem1 = new OrderItem(OrderId = order1.id, PricebookentryId = pricebookEntry1.Id, Quantity = 2, UnitPrice = 10000 );
		insert orderItem1;	

		testMethods.createAllFinancialRecords(storeConfig1);


	}


	/*******************************************************
					positiveCreateIntercompanyAsset
	*******************************************************/
	static testmethod void positiveCreateIntercompanyAsset(){
		test.starttest();
		Order soldOrder = [SELECT Id, AccountId, BillToContactId FROM Order where Name='Sold Order 1'];		
		Account store = [SELECT id FROM Account WHERE Name='77 - Twin Cities, MN'];		
		Store_Configuration__c storeConfig = [SELECT id FROM Store_Configuration__c WHERE Store__c = :store.id ];
		storeConfig.Standard_Hourly_Rate__c = 100;
		storeConfig.Location_Number__c = '123';
		update storeConfig;
		
		Id assetInstalledProductsRecordTypeId = UtilityMethods.retrieveRecordTypeId('Installed_Products', 'Asset');
		
		Account vendor = [SELECT Id from Account where Vendor_Account_Type__c = 'Intercompany'];

		Financial_Account_Number__c interCompanyDebit = [Select Id, Name From Financial_Account_Number__c Where Name = 'FANInventoryReceivedIntercompanyDebit'];
		Financial_Account_Number__c interCompanyCredit = [Select Id, Name From Financial_Account_Number__c Where Name = 'FANInventoryReceivedIntercompanyCredit'];
	
		Asset asset1 = new Asset(	Unit_Wholesale_Cost__c = 100,
									Quantity = 10,
									Sold_Order__c = soldOrder.id,
									RecordTypeId = assetInstalledProductsRecordTypeId,
									Store_Location__c = store.id,
									Name = 'asset1',
									AccountId = soldOrder.AccountId,
									ContactId = soldOrder.BillToContactId,
									Vendor__c = vendor.id
		);
		

		insert asset1;
		Journal_Entry__c je = [SELECT Id, Amount__c, Type__c, Order__c, Store_Location__c, Date__c, Debit_General_Ledger_Account__c, Credit_General_Ledger_Account__c FROM Journal_Entry__c 
								WHERE Order__c =: soldOrder.Id AND Type__c = 'Inventory Received - Intercompany']; 
		System.AssertEquals(1000, je.Amount__c);
		System.AssertEquals(System.today(), je.Date__c.date());

		// Verify the account numbers 
		System.AssertEquals(interCompanyDebit.Name, je.Debit_General_Ledger_Account__c);
		System.AssertEquals(interCompanyCredit.Name, je.Credit_General_Ledger_Account__c);
		
		
		asset1.Quantity = 2;
		
		update asset1;

		je = [SELECT Id, Amount__c, Type__c, Sent_to_BaanERP__c, Order__c, Store_Location__c, Date__c, Debit_General_Ledger_Account__c, Credit_General_Ledger_Account__c FROM Journal_Entry__c 
								WHERE Order__c =: soldOrder.Id AND Type__c = 'Inventory Received - Intercompany']; 
		System.AssertEquals(200, je.Amount__c);
		System.AssertEquals(System.today(), je.Date__c.date());
		
		// Verify the account numbers 
		System.AssertEquals(interCompanyDebit.Name, je.Debit_General_Ledger_Account__c);
		System.AssertEquals(interCompanyCredit.Name, je.Credit_General_Ledger_Account__c);
		
		je.Sent_to_BaanERP__c = true;
		update je;		
		
		asset1.Quantity = 3;
		update asset1;

		Journal_Entry__c je2 = [SELECT Id, Amount__c, Type__c, Sent_to_BaanERP__c, Order__c, Store_Location__c, Date__c, Debit_General_Ledger_Account__c, Credit_General_Ledger_Account__c FROM Journal_Entry__c 
								WHERE Order__c =: soldOrder.Id AND Type__c = 'Inventory Received - Intercompany' AND Sent_to_BaanERP__c = false]; 

		System.AssertEquals(100, je2.Amount__c);
		System.AssertEquals(System.today(), je2.Date__c.date());
		// Verify the account numbers 
		System.AssertEquals(interCompanyDebit.Name, je2.Debit_General_Ledger_Account__c);
		System.AssertEquals(interCompanyCredit.Name, je2.Credit_General_Ledger_Account__c);
// TODO		
//		asset1.Quantity = 3;
//		update asset1;

/*		je2 = [SELECT Id, Amount__c, Type__c, Sent_to_BaanERP__c, Order__c, Store_Location__c, Date__c, Debit_General_Ledger_Account__c, Credit_General_Ledger_Account__c FROM Journal_Entry__c 
								WHERE Order__c =: soldOrder.Id AND Type__c = 'Inventory Received - Intercompany' AND Sent_to_BaanERP__c = false]; 

		System.AssertEquals(100, je2.Amount__c);
		System.AssertEquals(System.today(), je2.Date__c.date());
		// Verify the account numbers 
		System.AssertEquals(interCompanyDebit.Name, je2.Credit_General_Ledger_Account__c);
		System.AssertEquals(interCompanyCredit.Name, je2.Debit_General_Ledger_Account__c);*/
		
		Test.stopTest();
	}

	/*******************************************************
					positiveCreateIntercompanyCCAsset
	*******************************************************/
	static testmethod void positiveCreateIntercompanyCCAsset(){
		test.starttest();
		Order soldOrder = [SELECT Id, AccountId, BillToContactId FROM Order where Name='Sold Order 1'];		
		Account store = [SELECT id FROM Account WHERE Name='77 - Twin Cities, MN'];		
		Store_Configuration__c storeConfig = [SELECT id FROM Store_Configuration__c WHERE Store__c = :store.id ];
		storeConfig.Standard_Hourly_Rate__c = 100;
		storeConfig.Location_Number__c = '123';
		update storeConfig;
		
		Id assetInstalledProductsRecordTypeId = UtilityMethods.retrieveRecordTypeId('Installed_Products', 'Asset');
		
		Account vendor = [SELECT Id from Account where Vendor_Account_Type__c = 'Intercompany Consolidation Center'];

		Financial_Account_Number__c interCompanyCCDebit = [Select Id, Name From Financial_Account_Number__c Where Name = 'FANInventoryReceivedIntercompanyCCDebit'];
		Financial_Account_Number__c interCompanyCCCredit = [Select Id, Name From Financial_Account_Number__c Where Name = 'FANInventoryReceivedIntercompanyCCCredit'];
	
		Asset asset1 = new Asset(	Unit_Wholesale_Cost__c = 100,
									Quantity = 10,
									Sold_Order__c = soldOrder.id,
									RecordTypeId = assetInstalledProductsRecordTypeId,
									Store_Location__c = store.id,
									Name = 'asset1',
									AccountId = soldOrder.AccountId,
									ContactId = soldOrder.BillToContactId,
									Vendor__c = vendor.id
		);
		

		insert asset1;
		Journal_Entry__c je = [SELECT Id, Amount__c, Type__c, Order__c, Store_Location__c, Date__c, Debit_General_Ledger_Account__c, Credit_General_Ledger_Account__c FROM Journal_Entry__c 
								WHERE Order__c =: soldOrder.Id AND Type__c = 'Inventory Received - Intercompany Consolidation Center']; 
		System.AssertEquals(1000, je.Amount__c);
		System.AssertEquals(System.today(), je.Date__c.date());

		// Verify the account numbers 
		System.AssertEquals(interCompanyCCDebit.Name, je.Debit_General_Ledger_Account__c);
		System.AssertEquals(interCompanyCCCredit.Name, je.Credit_General_Ledger_Account__c);
		
		
		asset1.Quantity = 2;
		
		update asset1;

		je = [SELECT Id, Amount__c, Type__c, Sent_to_BaanERP__c, Order__c, Store_Location__c, Date__c, Debit_General_Ledger_Account__c, Credit_General_Ledger_Account__c FROM Journal_Entry__c 
								WHERE Order__c =: soldOrder.Id AND Type__c = 'Inventory Received - Intercompany Consolidation Center']; 
		System.AssertEquals(200, je.Amount__c);
		System.AssertEquals(System.today(), je.Date__c.date());
		
		// Verify the account numbers 
		System.AssertEquals(interCompanyCCDebit.Name, je.Debit_General_Ledger_Account__c);
		System.AssertEquals(interCompanyCCCredit.Name, je.Credit_General_Ledger_Account__c);
		
		je.Sent_to_BaanERP__c = true;
		update je;		
		
		asset1.Quantity = 3;
		update asset1;

		Journal_Entry__c je2 = [SELECT Id, Amount__c, Type__c, Sent_to_BaanERP__c, Order__c, Store_Location__c, Date__c, Debit_General_Ledger_Account__c, Credit_General_Ledger_Account__c FROM Journal_Entry__c 
								WHERE Order__c =: soldOrder.Id AND Type__c = 'Inventory Received - Intercompany Consolidation Center' AND Sent_to_BaanERP__c = false]; 

		System.AssertEquals(100, je2.Amount__c);
		System.AssertEquals(System.today(), je2.Date__c.date());
		// Verify the account numbers 
		System.AssertEquals(interCompanyCCDebit.Name, je2.Debit_General_Ledger_Account__c);
		System.AssertEquals(interCompanyCCCredit.Name, je2.Credit_General_Ledger_Account__c);
// TODO		
//		asset1.Quantity = 3;
//		update asset1;

/*		je2 = [SELECT Id, Amount__c, Type__c, Sent_to_BaanERP__c, Order__c, Store_Location__c, Date__c, Debit_General_Ledger_Account__c, Credit_General_Ledger_Account__c FROM Journal_Entry__c 
								WHERE Order__c =: soldOrder.Id AND Type__c = 'Inventory Received - Intercompany' AND Sent_to_BaanERP__c = false]; 

		System.AssertEquals(100, je2.Amount__c);
		System.AssertEquals(System.today(), je2.Date__c.date());
		// Verify the account numbers 
		System.AssertEquals(interCompanyDebit.Name, je2.Credit_General_Ledger_Account__c);
		System.AssertEquals(interCompanyCredit.Name, je2.Debit_General_Ledger_Account__c);*/
		
		Test.stopTest();
	}

	/*******************************************************
					positiveCreateExternalVendorAsset
	*******************************************************/
	static testmethod void positiveCreateExternalVendorAsset(){
		test.starttest();
		Order soldOrder = [SELECT Id, AccountId, BillToContactId FROM Order where Name='Sold Order 1'];		
		Account store = [SELECT id FROM Account WHERE Name='77 - Twin Cities, MN'];		
		Store_Configuration__c storeConfig = [SELECT id FROM Store_Configuration__c WHERE Store__c = :store.id ];
		storeConfig.Standard_Hourly_Rate__c = 100;
		storeConfig.Location_Number__c = '123';
		update storeConfig;
		
		Id assetInstalledProductsRecordTypeId = UtilityMethods.retrieveRecordTypeId('Installed_Products', 'Asset');
		
		Account vendor = [SELECT Id from Account where Vendor_Account_Type__c = 'External'];

		Financial_Account_Number__c externalVendorDebit = [Select Id, Name From Financial_Account_Number__c Where Name = 'FANInventoryReceivedExternalDebit'];
		Financial_Account_Number__c externalVendorCredit = [Select Id, Name From Financial_Account_Number__c Where Name = 'FANInventoryReceivedExternalCredit'];
	
		Asset asset1 = new Asset(	Unit_Wholesale_Cost__c = 100,
									Quantity = 10,
									Sold_Order__c = soldOrder.id,
									RecordTypeId = assetInstalledProductsRecordTypeId,
									Store_Location__c = store.id,
									Name = 'asset1',
									AccountId = soldOrder.AccountId,
									ContactId = soldOrder.BillToContactId,
									Vendor__c = vendor.id
		);
		

		insert asset1;
		Journal_Entry__c je = [SELECT Id, Amount__c, Type__c, Order__c, Store_Location__c, Date__c, Debit_General_Ledger_Account__c, Credit_General_Ledger_Account__c FROM Journal_Entry__c 
								WHERE Order__c =: soldOrder.Id AND Type__c = 'Inventory Received - External Vendor']; 
		System.AssertEquals(1000, je.Amount__c);
		System.AssertEquals(System.today(), je.Date__c.date());

		// Verify the account numbers 
		System.AssertEquals(externalVendorDebit.Name, je.Debit_General_Ledger_Account__c);
		System.AssertEquals(externalVendorCredit.Name, je.Credit_General_Ledger_Account__c);
		
		
		asset1.Quantity = 2;
		
		update asset1;

		je = [SELECT Id, Amount__c, Type__c, Sent_to_BaanERP__c, Order__c, Store_Location__c, Date__c, Debit_General_Ledger_Account__c, Credit_General_Ledger_Account__c FROM Journal_Entry__c 
								WHERE Order__c =: soldOrder.Id AND Type__c = 'Inventory Received - External Vendor']; 
		System.AssertEquals(200, je.Amount__c);
		System.AssertEquals(System.today(), je.Date__c.date());
		
		// Verify the account numbers 
		System.AssertEquals(externalVendorDebit.Name, je.Debit_General_Ledger_Account__c);
		System.AssertEquals(externalVendorCredit.Name, je.Credit_General_Ledger_Account__c);
		
		je.Sent_to_BaanERP__c = true;
		update je;		
		
		asset1.Quantity = 3;
		update asset1;

		Journal_Entry__c je2 = [SELECT Id, Amount__c, Type__c, Sent_to_BaanERP__c, Order__c, Store_Location__c, Date__c, Debit_General_Ledger_Account__c, Credit_General_Ledger_Account__c FROM Journal_Entry__c 
								WHERE Order__c =: soldOrder.Id AND Type__c = 'Inventory Received - External Vendor' AND Sent_to_BaanERP__c = false]; 

		System.AssertEquals(100, je2.Amount__c);
		System.AssertEquals(System.today(), je2.Date__c.date());
		// Verify the account numbers 
		System.AssertEquals(externalVendorDebit.Name, je2.Debit_General_Ledger_Account__c);
		System.AssertEquals(externalVendorCredit.Name, je2.Credit_General_Ledger_Account__c);
// TODO		
//		asset1.Quantity = 3;
//		update asset1;

/*		je2 = [SELECT Id, Amount__c, Type__c, Sent_to_BaanERP__c, Order__c, Store_Location__c, Date__c, Debit_General_Ledger_Account__c, Credit_General_Ledger_Account__c FROM Journal_Entry__c 
								WHERE Order__c =: soldOrder.Id AND Type__c = 'Inventory Received - Intercompany' AND Sent_to_BaanERP__c = false]; 

		System.AssertEquals(100, je2.Amount__c);
		System.AssertEquals(System.today(), je2.Date__c.date());
		// Verify the account numbers 
		System.AssertEquals(interCompanyDebit.Name, je2.Credit_General_Ledger_Account__c);
		System.AssertEquals(interCompanyCredit.Name, je2.Debit_General_Ledger_Account__c);*/
		
		Test.stopTest();
	}

	/*******************************************************
					positiveInventoryWriteOffAsset
	*******************************************************/
	static testmethod void positiveInventoryWriteOffAsset(){
		test.starttest();
		Order soldOrder = [SELECT Id, AccountId, BillToContactId FROM Order where Name='Sold Order 1'];		
		Account store = [SELECT id FROM Account WHERE Name='77 - Twin Cities, MN'];		
		Store_Configuration__c storeConfig = [SELECT id FROM Store_Configuration__c WHERE Store__c = :store.id ];
		storeConfig.Standard_Hourly_Rate__c = 100;
		storeConfig.Location_Number__c = '123';
		update storeConfig;
		
		Id assetInstalledProductsRecordTypeId = UtilityMethods.retrieveRecordTypeId('Installed_Products', 'Asset');
		
		Account vendor = [SELECT Id from Account where Vendor_Account_Type__c = 'External'];

		Financial_Account_Number__c invWriteOffDebit = [Select Id, Name From Financial_Account_Number__c Where Name = 'FANInventoryWriteOffDebit'];
		Financial_Account_Number__c invWriteOffCredit = [Select Id, Name From Financial_Account_Number__c Where Name = 'FANInventoryWriteOffCredit'];
	
		Asset asset1 = new Asset(	Unit_Wholesale_Cost__c = 100,
									Quantity = 10,
									Sold_Order__c = soldOrder.id,
									RecordTypeId = assetInstalledProductsRecordTypeId,
									Store_Location__c = store.id,
									Name = 'asset1',
									AccountId = soldOrder.AccountId,
									ContactId = soldOrder.BillToContactId,
									Vendor__c = vendor.id
		);
		

		insert asset1;

		asset1.Quantity_Written_Off__c = 1;
		
		update asset1;

		Journal_Entry__c je = [SELECT Id, Amount__c, Type__c, Sent_to_BaanERP__c, Order__c, Store_Location__c, Date__c, Debit_General_Ledger_Account__c, Credit_General_Ledger_Account__c FROM Journal_Entry__c 
								WHERE Order__c =: soldOrder.Id AND Type__c = 'Inventory Write-Off']; 

		System.AssertEquals(100, je.Amount__c);
		System.AssertEquals(System.today(), je.Date__c.date());

		// Verify the account numbers 
		System.AssertEquals(invWriteOffDebit.Name, je.Debit_General_Ledger_Account__c);
		System.AssertEquals(invWriteOffCredit.Name, je.Credit_General_Ledger_Account__c);
		
		
		asset1.Quantity_Written_Off__c = 2;
		update asset1;

		je = [SELECT Id, Amount__c, Type__c, Sent_to_BaanERP__c, Order__c, Store_Location__c, Date__c, Debit_General_Ledger_Account__c, Credit_General_Ledger_Account__c FROM Journal_Entry__c 
								WHERE Order__c =: soldOrder.Id AND Type__c = 'Inventory Write-Off']; 
		System.AssertEquals(200, je.Amount__c);
		System.AssertEquals(System.today(), je.Date__c.date());
		
		// Verify the account numbers 
		System.AssertEquals(invWriteOffDebit.Name, je.Debit_General_Ledger_Account__c);
		System.AssertEquals(invWriteOffCredit.Name, je.Credit_General_Ledger_Account__c);

		// Delete the Asset and verify the journal entry is deleted
		delete asset1;

		decimal jeCount = 0;
		for (Journal_Entry__c j : [SELECT Id from Journal_Entry__c WHERE Type__c = 'Inventory Write-Off']) {
			jeCount += 1;
		}

		System.AssertEquals(0, jeCount);
		
		
		Test.stopTest();
	}
}