RbA Build/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Active_Store_Configuration__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>currently active store configuration</description>
        <label>Active Store Configuration</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Store_Configuration__c.Store__c</field>
                <operation>equals</operation>
                <valueField>$Source.Id</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Store_Configuration__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Check if this account is active</description>
        <inlineHelpText>Check if this account is active</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

RbA Build/src/objects/Discount__c.object
<CustomObject>
    <description>Discounts &amp; promotions for customers</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Check if this is an active discount or promotion.</description>
        <inlineHelpText>Check if this is an active discount or promotion.</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <label>Discount</label>
    <nameField>
        <label>Discount Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Discounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

RbA Build/src/objects/Order.object
<CustomObject>
    <fields>
        <fullName>Discount_Amount__c</fullName>
        <description>A roll-up sum of all discounts applied to this order (see the order discount related list).</description>
        <inlineHelpText>A roll-up sum of all discounts applied to this order (see the order discount related list).</inlineHelpText>
        <label>Discount Amount</label>
        <summarizedField>Order_Discount__c.Discount_Amount__c</summarizedField>
        <summaryFilterItems>
            <field>Order_Discount__c.Status__c</field>
            <operation>equals</operation>
            <value>Applied</value>
        </summaryFilterItems>
        <summaryForeignKey>Order_Discount__c.Order__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Discount__c</fullName>
        <formula>Discount_Amount__c/Retail_Total__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Discount %</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

RbA Build/src/objects/Order_Discount__c.object
<CustomObject>
    <description>Junction from the discount to the order</description>
    <fields>
        <fullName>Discount_Amount__c</fullName>
        <defaultValue>0</defaultValue>
        <description>The amount in dollars discounted from the order.</description>
        <inlineHelpText>The amount in dollars discounted from the order.</inlineHelpText>
        <label>Discount Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <description>The discount is applied to this order</description>
        <inlineHelpText>The discount is applied to this order</inlineHelpText>
        <label>Order</label>
        <referenceTo>Order</referenceTo>
        <relationshipName>Discount_Applied</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Store_Discount__c</fullName>
        <label>Store Discount</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Store_Discount__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>Store_Discount__c.Store_Configuration__r.Store__c</field>
                <operation>equals</operation>
                <valueField>$Source.Store_Location__c</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Store_Discount__c</referenceTo>
        <relationshipLabel>Order Discounts</relationshipLabel>
        <relationshipName>Order_Discounts</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Order Discount</label>
    <nameField>
        <displayFormat>OD-{00000000}</displayFormat>
        <label>Order Discount Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Discounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

RbA Build/src/objects/Store_Configuration__c.object
<CustomObject>
    <description>Holds Store Settings &amp; Configurations</description>
    <label>Store Configuration</label>
    <nameField>
        <displayFormat>SS-{00}</displayFormat>
        <label>Store Setting Record #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Store Configurations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

RbA Build/src/objects/Store_Discount__c.object
<CustomObject>
    <description>Junctions object to assign discounts to a store through the store configuration</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Discount__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>a discount to link to a store</description>
        <inlineHelpText>a discount to link to a store</inlineHelpText>
        <label>Discount</label>
        <referenceTo>Discount__c</referenceTo>
        <relationshipLabel>Store Discounts</relationshipLabel>
        <relationshipName>Store_Discounts</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Store_Configuration__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>The configuration of a store to that the discount will be enabled for</description>
        <inlineHelpText>The configuration of a store to that the discount will be enabled for</inlineHelpText>
        <label>Store Configuration</label>
        <referenceTo>Store_Configuration__c</referenceTo>
        <relationshipLabel>Store Discounts</relationshipLabel>
        <relationshipName>Store_Discounts</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Store Discount</label>
    <nameField>
        <label>Store Discount Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Store Discounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

RbA Build/src/classes/RMS_OrderDiscountManagerTest.cls
/*******************************************************//**

@class  RMS_OrderDiscountManagerTest

@brief  Test class for the RMS_OrderDiscountManager  

    Test class

@author  Creston Kuenzi (Slalom.CDK)

@version    2015-7-14  Slalom.CDK
    Created. 

@see        RMS_OrderDiscountManager

@copyright  (c)2016 Slalom.  All Rights Reserved.
            Unauthorized use is prohibited.

***********************************************************/
@isTest
private class RMS_OrderDiscountManagerTest {

	// TODO : Write test methods to adequately cover this handler and trigger
    static testMethod void tempTest() {
        TestUtilityMethods utility = new TestUtilityMethods();
        utility.createOrderTestRecords();

        Order soldOrder = [SELECT Id FROM Order WHERE Name = 'Sold Order 1'];

        Discount__c discount1 = new Discount__c(Name = 'my discount');
        insert discount1;

        Account myStore = [select Id, Active_Store_Configuration__c from Account where Name = '77 - Twin Cities, MN' Limit 1];
        Store_Discount__c storeDiscount1 = new Store_Discount__c();
        storeDiscount1.Discount__c = discount1.Id;
        storeDiscount1.Store_Configuration__c = myStore.Active_Store_Configuration__c;
        storeDiscount1.Active__c = true;
        insert storeDiscount1;      

		test.startTest();
        Order_Discount__c orderDiscount1 = new Order_Discount__c(Order__c = soldOrder.id, Store_Discount__c = storeDiscount1.Id, Discount_Amount__c = 50 );
        insert orderDiscount1;    
        orderDiscount1.Discount_Amount__c = 75;
        update orderDiscount1;
        test.stopTest();

    }
}