RbA Build/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Active_Store_Configuration__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>currently active store configuration</description>
        <label>Active Store Configuration</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Store_Configuration__c.Store__c</field>
                <operation>equals</operation>
                <valueField>$Source.Id</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Store_Configuration__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Check if this account is active</description>
        <inlineHelpText>Check if this account is active</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Store_Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The store location that this dwelling is related</description>
        <inlineHelpText>The store location that this dwelling is related</inlineHelpText>
        <label>Store Location</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>The account must be of type &quot;Store&quot;</errorMessage>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Store</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Dwellings</relationshipLabel>
        <relationshipName>StoreLocation</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Dwelling</fullName>
        <active>true</active>
        <description>Used to support Dwelling</description>
        <label>Dwelling</label>
    </recordTypes>
    <recordTypes>
        <fullName>Store</fullName>
        <active>true</active>
        <description>Used to track and store data releated to Retail Locations both CORO and ARO</description>
        <label>Store</label>
    </recordTypes>
    <recordTypes>
        <fullName>Vendor</fullName>
        <active>true</active>
        <description>Used to track Vendors</description>
        <label>Vendor</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

RbA Build/src/objects/Discount__c.object
<CustomObject>
    <description>Discounts &amp; promotions for customers</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Check if this is an active discount or promotion.</description>
        <inlineHelpText>Check if this is an active discount or promotion.</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Store_Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The store or group of stores this discount is used by</description>
        <inlineHelpText>The store or group of stores this discount is used by</inlineHelpText>
        <label>Store Location</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>The selected account must be a store.</errorMessage>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Store</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Discounts</relationshipLabel>
        <relationshipName>Discounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Discount</label>
    <nameField>
        <label>Discount Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Discounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

RbA Build/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Discount__c</fullName>
        <description>The discount percent applied to the whole opportunity amount.</description>
        <inlineHelpText>The discount percent applied to the whole opportunity amount.</inlineHelpText>
        <label>Discount</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Store_Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Store Location</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>The account must be of type &quot;Store&quot;.</errorMessage>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Store</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Store Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

RbA Build/src/objects/Order.object
<CustomObject>
    <fields>
        <fullName>Discount__c</fullName>
        <formula>Discount_Amount__c/Retail_Total__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Discount %</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Store_Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This order is related to this store location.</description>
        <inlineHelpText>This order is related to this store location.</inlineHelpText>
        <label>Store Location</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Orders (Store Location)</relationshipLabel>
        <relationshipName>Orders1</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

RbA Build/src/objects/Order_Discount__c.object
<CustomObject>
    <description>Junction from the discount to the order</description>
    <fields>
        <fullName>Order__c</fullName>
        <description>The discount is applied to this order</description>
        <inlineHelpText>The discount is applied to this order</inlineHelpText>
        <label>Order</label>
        <referenceTo>Order</referenceTo>
        <relationshipName>Discount_Applied</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Store_Discount__c</fullName>
        <label>Store Discount</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Store_Discount__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>Store_Discount__c.Store_Configuration__r.Store__c</field>
                <operation>equals</operation>
                <valueField>$Source.Store_Location__c</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Store_Discount__c</referenceTo>
        <relationshipLabel>Order Discounts</relationshipLabel>
        <relationshipName>Order_Discounts</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Store_Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The store location that is creating this discount.</description>
        <inlineHelpText>The store location that is creating this discount.</inlineHelpText>
        <label>Store Location</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Store</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Order Discounts</relationshipLabel>
        <relationshipName>Order_Discounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Order Discount</label>
    <nameField>
        <displayFormat>OD-{00000000}</displayFormat>
        <label>Order Discount Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Discounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

RbA Build/src/objects/OrderItem.object
<CustomObject>
    <fields>
        <fullName>Purchase_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The purchase order that covers this sales order line item</description>
        <inlineHelpText>The purchase order that covers this sales order line item</inlineHelpText>
        <label>Purchase Order</label>
        <referenceTo>Purchase_Order__c</referenceTo>
        <relationshipLabel>Order Products</relationshipLabel>
        <relationshipName>Order_Products</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

RbA Build/src/objects/Pricebook2.object
<CustomObject>
    <fields>
        <fullName>Store_Configuration__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Links price books to store configuration.  All configuration that are store based are tied to the store configuration for that store.</description>
        <inlineHelpText>Link this to the store configuration for the store this Price Book is being created for.</inlineHelpText>
        <label>Store Configuration</label>
        <referenceTo>Store_Configuration__c</referenceTo>
        <relationshipLabel>Price Books</relationshipLabel>
        <relationshipName>Price_Books</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadSelect</sharingModel>
</CustomObject>

RbA Build/src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Vendor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Vendor</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>Products</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

RbA Build/src/objects/Purchase_Order__c.object
<CustomObject>
    <description>The purchase order header for ordering RbA and 3rd party products linked to order line items</description>
    <fields>
        <fullName>Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The parent sales order of this purchase order</description>
        <inlineHelpText>The parent sales order of this purchase order</inlineHelpText>
        <label>Order</label>
        <referenceTo>Order</referenceTo>
        <relationshipLabel>Purchase Orders</relationshipLabel>
        <relationshipName>Purchase_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Vendor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The vendor linked to the PO</description>
        <inlineHelpText>The vendor linked to the PO</inlineHelpText>
        <label>Vendor</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>The account must be of type Vendor.</errorMessage>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Vendor</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Purchase Orders</relationshipLabel>
        <relationshipName>Purchase_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Purchase Order</label>
    <nameField>
        <label>Purchase Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Purchase Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

RbA Build/src/objects/RbA_Work_Order__c.object
<CustomObject>
    <description>Custom Object used to track Work Orders related to Orders.</description>
    <fields>
        <fullName>Vendor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Vendor preforming the work.</inlineHelpText>
        <label>Vendor</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>equals</operation>
                <value>Vendor</value>
            </filterItems>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>equals</operation>
                <value>Contractor</value>
            </filterItems>
            <infoMessage>The Vendor must be associated with the Store the Order is associated to.</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Work Orders (LSWP)</relationshipLabel>
        <relationshipName>Work_Orders2</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>RbA Work Order</label>
    <nameField>
        <displayFormat>WO-{00000000}</displayFormat>
        <label>Work Order #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RbA Work Orders</pluralLabel>
    <recordTypes>
        <fullName>LSWP</fullName>
        <active>true</active>
        <description>Holds LSWP Details</description>
        <label>LSWP</label>
    </recordTypes>
    <recordTypes>
        <fullName>Permit</fullName>
        <active>true</active>
        <description>Holds Building Permit Details</description>
        <label>Permit</label>
    </recordTypes>
    <recordTypes>
        <fullName>Visit</fullName>
        <active>true</active>
        <description>Hold Work Order details that can be have a scheduled visit to the home</description>
        <label>Visit</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

RbA Build/src/objects/Store_Discount__c.object
<CustomObject>
    <description>Junctions object to assign discounts to a store through the store configuration</description>
    <fields>
        <fullName>Discount__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>a discount to link to a store</description>
        <inlineHelpText>a discount to link to a store</inlineHelpText>
        <label>Discount</label>
        <referenceTo>Discount__c</referenceTo>
        <relationshipLabel>Store Discounts</relationshipLabel>
        <relationshipName>Store_Discounts</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Store_Configuration__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>The configuration of a store to that the discount will be enabled for</description>
        <inlineHelpText>The configuration of a store to that the discount will be enabled for</inlineHelpText>
        <label>Store Configuration</label>
        <referenceTo>Store_Configuration__c</referenceTo>
        <relationshipLabel>Store Discounts</relationshipLabel>
        <relationshipName>Store_Discounts</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Store Discount</label>
    <nameField>
        <label>Store Discount Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Store Discounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

RbA Build/src/classes/RMS_cancelOrderExtensionTest.cls
/*******************************************************//**

@class  RMS_cancelOrderExtensionTest

@brief  Test class for the RMS_cancelOrderExtension Controller extension

    Test class

@author  Creston Kuenzi (Slalom.CDK)

@version    2015-10-25  Slalom.CDK
    Created. 

@see        RMS_cancelOrderExtensionTest

@copyright  (c)2015 Slalom.  All Rights Reserved.
            Unauthorized use is prohibited.

***********************************************************/
@isTest
private class RMS_cancelOrderExtensionTest {

    /*******************************************************
                    createTestRecords
    *******************************************************/
    @testSetup static void createTestRecords(){
        
        TestUtilityMethods utility = new TestUtilityMethods();
        
        utility.setUpConfigs();
        
        Account myAccount1 = utility.createVendorAccount('My Vendor Account 1 ');
        insert myAccount1;

        Account myAccount2 = new Account(   Name = 'RbA',
                                        AccountNumber = '1234567890',
                                        Phone = '(763) 555-2000'
                                    );
        insert myAccount2;

        Account dwelling = utility.createDwellingAccount('Dwelling Account');

        Account store = [SELECT Id from Account Where Name = '77 - Twin Cities, MN'];
        dwelling.Store_Location__c = store.Id;
        insert dwelling;
        
        Opportunity opp1 = utility.createOpportunity(dwelling.id, 'Closed - Won');
        insert opp1;
        
        Pricebook2 pricebook1 =  utility.createPricebook2Name('Standard Price Book');
        insert pricebook1;

        Product2 product1 = new Product2(
            Name='Test Product',
            Vendor__c = myAccount1.id
        );
        
        
        insert product1;
        
        PricebookEntry pricebookEntry1 = utility.createPricebookEntry(Test.getStandardPricebookId(), product1.id);
        insert pricebookEntry1;
        
        Order order1 = new Order(   Name='Sold Order 1', 
                                    AccountId = dwelling.id, 
                                    EffectiveDate= Date.Today(), 
                                    Store_Location__c = store.Id,
                                    Opportunity = opp1, 
                                    Status ='Draft', 
                                    Pricebook2Id = Test.getStandardPricebookId()
                                );
        insert order1;
        
        Purchase_Order__c purchaseOrder1 = new Purchase_Order__c(Order__c = Order1.id);
        insert purchaseOrder1;      

        OrderItem orderItem1 = new OrderItem(OrderId = Order1.id, PricebookentryId = pricebookEntry1.Id, Quantity = 2, UnitPrice = 100, Purchase_Order__c = purchaseOrder1.Id );
        insert orderItem1;      

        Discount__c discount1 = new Discount__c(Name = 'my discount');
        insert discount1;

        Account myStore = [select Id, Active_Store_Configuration__c from Account where Name = '77 - Twin Cities, MN' Limit 1];
        Store_Discount__c storeDiscount1 = new Store_Discount__c();
        storeDiscount1.Discount__c = discount1.Id;
        storeDiscount1.Store_Configuration__c = myStore.Active_Store_Configuration__c;
        storeDiscount1.Active__c = true;
        insert storeDiscount1;      

        Order_Discount__c orderDiscount1 = new Order_Discount__c(Order__c = Order1.id, Store_Discount__c = storeDiscount1.Id, Discount_Amount__c = 50 );
        insert orderDiscount1;      

        Id serviceOrderVisitRecordTypeId = UtilityMethods.retrieveRecordTypeId('Visit', 'RbA_Work_Order__c');
        RbA_Work_Order__c workOrder1 = new RbA_Work_Order__c(   RecordTypeId = serviceOrderVisitRecordTypeId,  Sold_Order__c = order1.id, Work_Order_Type__c = 'Historical');
        insert workOrder1;

    }
    
    /*******************************************************
                    NoOrderIdTest
    *******************************************************/
    static testmethod void NoOrderIdTest(){

        Order soldOrder = [SELECT Id FROM Order WHERE Name = 'Sold Order 1'];

        // Set up controller with an order Id and no PO Id
        PageReference pageRef = Page.RMS_cancelOrder;
        Test.setCurrentPage(pageRef);
        ApexPages.StandardController stdController = new ApexPages.StandardController(soldOrder);
        RMS_cancelOrderExtension customController  = new RMS_cancelOrderExtension(stdController);
        customController.cancelOrder();

    }
// TODO Fix this too many SOQL Queries error
    /*******************************************************
                    CancelOrderTest
    *******************************************************/
 /*   static testmethod void CancelOrderTest(){

		// Turn off the financial trigger to avoid SOQL limits in test class
		RMS_Settings__c turnOffFinancialTrigger = new RMS_Settings__c(Name='Turn Financial Transactions Off', Value__c = 'Yes');
		insert turnOffFinancialTrigger;

        Order soldOrder = [SELECT Id FROM Order WHERE Name = 'Sold Order 1'];

        // Set up controller with an order Id
        PageReference pageRef = Page.RMS_cancelOrder;
        Test.setCurrentPage(pageRef);
        ApexPages.currentPage().getParameters().put('id',soldOrder.id);
        ApexPages.StandardController stdController = new ApexPages.StandardController(soldOrder);

        Test.startTest();

        RMS_cancelOrderExtension customController  = new RMS_cancelOrderExtension(stdController);

        //Verify if related Visit RbA_Work_Order__c has open events, order is not cancelled
        List<RbA_Work_Order__c> relatedVisitWOs = [Select Id, Number_Open_Events_Formula__c from RbA_Work_Order__c WHERE Sold_Order__c =: soldOrder.Id AND RecordType.DeveloperName = 'Visit'];
        for(RbA_Work_Order__c relatedWO : relatedVisitWOs){
            relatedWo.Scheduled_Appt_Date_Time_Service__c = Datetime.now().addHours(4);
            relatedWo.Work_Order_Type__c = 'Service';
            //relatedWO.Number_Open_Events__c = 1;
        }
        update relatedVisitWOs;


        customController.cancelOrder();
        Order soldOrderResult = [SELECT Id, Status FROM Order WHERE Name = 'Sold Order 1'];
        System.AssertEquals('Draft', soldOrderResult.Status);   

        //Update related rba_Work_Orders to 0 open events, verify records are cancelled 
        for(RbA_Work_Order__c relatedWO : relatedVisitWOs){
            relatedWo.Scheduled_Appt_Date_Time_Service__c = Datetime.now().addHours(-4);
           // relatedWO.Number_Open_Events__c = 0;
        }
        update relatedVisitWOs;
        customController.cancelOrder();

        // Verify all POs are cancelled
        for (Purchase_Order__c cancelledPO :  [SELECT Id, Status__c FROM Purchase_Order__c WHERE Order__c =: soldOrder.Id]) {
            System.AssertEquals('Cancelled', cancelledPO.Status__c);        
        }

        // Verify all Order Items are cancelled
        for (OrderItem cancelledOI :  [SELECT Id, Status__c FROM OrderItem WHERE OrderId =: soldOrder.Id]) {
            System.AssertEquals('Cancelled', cancelledOI.Status__c);        
        }

        // Verify all Discounts are cancelled
        for (Order_Discount__c cancelledOD :  [SELECT Id, Status__c FROM Order_Discount__c WHERE Order__c =: soldOrder.Id]) {
            System.AssertEquals('Cancelled', cancelledOD.Status__c);        
        }

        // Verify all rba_Work_Orders of the proper types are cancelled
        for (RbA_Work_Order__c cancelledWO :  [SELECT Id, Work_Order_Status__c FROM RbA_Work_Order__c WHERE Sold_Order__c =: soldOrder.Id
                                                AND Work_Order_Type__c in ('LSWP','Bulding Permit','HOA','Historical','Tech Measure','Install','Paint/Stain')]) {
            System.AssertEquals('Cancelled', cancelledWO.Work_Order_Status__c);     
        }

        // Verify the sold order is Cancelled
        soldOrderResult = [SELECT Id, Status FROM Order WHERE Name = 'Sold Order 1'];
        System.AssertEquals('Cancelled', soldOrderResult.Status);       

        Test.stopTest();

    }*/
}