RbA Build/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Primary_Contact__c</fullName>
        <description>The primary contact on a dwelling. Updated with a declarative rollup.</description>
        <inlineHelpText>The primary contact on a dwelling</inlineHelpText>
        <label>Primary Contact</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Store_Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The store location that this dwelling is related</description>
        <inlineHelpText>The store location that this dwelling is related</inlineHelpText>
        <label>Store Location</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>The account must be of type &quot;Store&quot;</errorMessage>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Store</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Dwellings</relationshipLabel>
        <relationshipName>StoreLocation</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Dwelling</fullName>
        <active>true</active>
        <description>Used to support Dwelling</description>
        <label>Dwelling</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

RbA Build/src/objects/Store_Configuration__c.object
<CustomObject>
    <description>Holds Store Settings &amp; Configurations</description>
    <fields>
        <fullName>Store__c</fullName>
        <label>Store</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Store Configurations</relationshipLabel>
        <relationshipName>Store_Configurations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Store Configuration</label>
    <nameField>
        <displayFormat>SS-{00}</displayFormat>
        <label>Store Setting Record #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Store Configurations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

RbA Build/src/classes/testRMS_createContactHistoryMgr.cls
/*******************************************************//**

@class  testRMS_createContactHistoryMgr

@brief  Test Class for RMS_createContactHistoryManager

@author  Brianne Wilson (Slalom.CDK)

@version    2015-4-19  Slalom.CDK
Created.


@copyright  (c)2016 Slalom.  All Rights Reserved. 
Unauthorized use is prohibited.

***********************************************************/
@isTest
public with sharing class testRMS_createContactHistoryMgr {
    static testmethod void createTestRecords() {
        TestUtilityMethods utility = new TestUtilityMethods();
        utility.setUpConfigs();
        
        List<Account> dwellingsToInsert = new List<Account>();  
        Account dwelling1 = utility.createDwellingAccount('Dwelling Account');
        Account dwelling2 = utility.createDwellingAccount('Dwelling Account 2');
        Account store1 = [SELECT Id from Account Where Name = '77 - Twin Cities, MN'];
        Store_Configuration__c storeConfig1 = [SELECT id FROM Store_Configuration__c WHERE Store__c = :store1.id ];
        dwelling1.Store_Location__c = store1.Id;
        dwelling2.Store_Location__c = store1.Id; 
        dwellingsToInsert.add(dwelling1);
        dwellingsToInsert.add(dwelling2);
        insert dwellingsToInsert; 
        
        List<Contact> contactsToInsert = new List<Contact>();       
        Contact contact1 = new contact ( FirstName='Contact',LastName='1',AccountId=dwelling1.id,Primary_Contact__c=True,Primary_Dwelling_for_Contact__c=true);
        contactsToInsert.add(contact1);
        insert contactsToInsert;
        
        contact1.AccountId = dwelling2.id;
        update contact1;
    }
    
}