RbA Build/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Building_Permit__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The Building Permit is populated in Code
Matching in the Municipalities table.
Matching criteria Address City and Zip code, match is found in the Municipality Match object</inlineHelpText>
        <label>Building Permit</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>You must select a Building record. If the record for you are for isn&apos;t in the system, please contact your manager to have it created.</errorMessage>
            <filterItems>
                <field>Municipality__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Permit</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Municipality__c</referenceTo>
        <relationshipLabel>Building Permit Dwellings</relationshipLabel>
        <relationshipName>Accounts2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>HOA__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Is this Dwelling part of an HOA?</inlineHelpText>
        <label>HOA</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>You must select an HOA record.  If the record for you are for isn&apos;t in the system, please contact your manager to have it created.</errorMessage>
            <filterItems>
                <field>Municipality__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>HOA</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Municipality__c</referenceTo>
        <relationshipLabel>HOA Dwellings</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Historical__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Is this Dwelling in a Historical District?</inlineHelpText>
        <label>Historical</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>You must select a Historical record. If the record you are for is not in the system, please contact your manager to have it created.</errorMessage>
            <filterItems>
                <field>Municipality__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Historical</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Municipality__c</referenceTo>
        <relationshipLabel>Historical Dwellings</relationshipLabel>
        <relationshipName>Accounts1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Store_Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The store location that this dwelling is related</description>
        <inlineHelpText>The store location that this dwelling is related</inlineHelpText>
        <label>Store Location</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>The account must be of type &quot;Store&quot;</errorMessage>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Store</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Dwellings</relationshipLabel>
        <relationshipName>StoreLocation</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Dwelling</fullName>
        <active>true</active>
        <description>Used to support Dwelling</description>
        <label>Dwelling</label>
    </recordTypes>
    <recordTypes>
        <fullName>Store</fullName>
        <active>true</active>
        <description>Used to track and store data releated to Retail Locations both CORO and ARO</description>
        <label>Store</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

RbA Build/src/objects/Back_Office_Check__c.object
<CustomObject>
    <description>Junction Object between the Back Office Checklist Configurations and Order.  Keeps the history of items that need to checked in order for the order move through the process.</description>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <referenceTo>Order</referenceTo>
        <relationshipLabel>Back Office Checks</relationshipLabel>
        <relationshipName>Back_Office_Checks</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Back Office Check</label>
    <nameField>
        <label>Back Office Check Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Back Office Checks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

RbA Build/src/objects/Back_Office_Checklist_Configuration__c.object
<CustomObject>
    <description>Used for tracking important signed documents</description>
    <fields>
        <fullName>Store_Configuration__c</fullName>
        <label>Store Configuration</label>
        <referenceTo>Store_Configuration__c</referenceTo>
        <relationshipName>Back_Office_Checklists</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Back Office Checklist Configuration</label>
    <nameField>
        <displayFormat>BOC# - {00}</displayFormat>
        <label>Back Office Checklist Record #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Back Office Checklist Configurations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

RbA Build/src/objects/Order.object
<CustomObject>
    <fields>
        <fullName>Sold_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>When the Sold Order is Job In Progress, the Service Order must be related to the Sold Order.</inlineHelpText>
        <label>Sold Order</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>$Source.AccountId</field>
                <operation>equals</operation>
                <valueField>Order.AccountId</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Order</referenceTo>
        <relationshipLabel>Service Orders</relationshipLabel>
        <relationshipName>Sold_Order</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Store_Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This order is related to this store location.</description>
        <inlineHelpText>This order is related to this store location.</inlineHelpText>
        <label>Store Location</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Orders (Store Location)</relationshipLabel>
        <relationshipName>Orders1</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

RbA Build/src/objects/Store_Configuration__c.object
<CustomObject>
    <description>Holds Store Settings &amp; Configurations</description>
    <fields>
        <fullName>Install_Work_Order_Queue_Id__c</fullName>
        <label>Install Work Order Queue Id</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Order_Queue_Id__c</fullName>
        <label>Order Queue Id</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Store__c</fullName>
        <label>Store</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Store Configurations</relationshipLabel>
        <relationshipName>Store_Configurations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Tech_Measure_Work_Order_Queue_Id__c</fullName>
        <label>Tech Measure Work Order Queue Id</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Store Configuration</label>
    <nameField>
        <displayFormat>SS-{00}</displayFormat>
        <label>Store Setting Record #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Store Configurations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

RbA Build/src/objects/SVMXC__Service_Order__c.object
<CustomObject>
    <customHelp>SVMXC__SVMXC_LaunchHelp</customHelp>
    <description>Service Order is used to plan, execute and manage Service events for Field and Depot Service activities. Depending upon the service scenario, the order creation can be triggered by many events: When creating a Support Case, when one or more installed products require periodic service or calibration, when troubleshooting a customer problem on the field, if the field service engineer learns that the product requires specialized conditions of a factory/depot to resolve the problem, or when a new/repair shipment to customer requires specialized installation activity.</description>
    <fields>
        <fullName>SVMXC__City__c</fullName>
        <description>“City” part of the work order location.</description>
        <inlineHelpText>“City” part of the work order location.</inlineHelpText>
        <label>City</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SVMXC__Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Customer Account initiating this service order. Is a lookup to an existing salesforce account record</description>
        <inlineHelpText>Customer Company initiating this service order. Is a lookup to an existing salesforce account record</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Work Orders</relationshipLabel>
        <relationshipName>Service_Order</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SVMXC__Country__c</fullName>
        <description>“Country” part of the work order location</description>
        <inlineHelpText>“Country” part of the work order location</inlineHelpText>
        <label>Country</label>
        <picklist>
            <picklistValues>
                <fullName>Afghanistan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Albania</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Algeria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>American</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Andorra</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Anguilla</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Antarctica</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Antigua And</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Argentina</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Armenia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Aruba</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Austria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ayerbaijan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bahamas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bahrain</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bangladesh</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Barbados</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Belarus</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Belize</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Belgium</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Benin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bermuda</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bhutan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bolivia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bouvet</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bosnia and Herzegovina</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Botswana</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Brazil</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>British Indian Ocean Territory</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>SVMXC__Order_Type__c</fullName>
        <description>Type of service order: Field Service, Depot repair etc.</description>
        <inlineHelpText>Type of service order: Field Service, Depot repair etc.</inlineHelpText>
        <label>Order Type</label>
        <picklist>
            <picklistValues>
                <fullName>Tech Measure</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Install</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Service</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HOA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Historical</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Building Permit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Paint/Stain</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LSWP</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>SVMXC__State__c</fullName>
        <description>“State” part of the work order location</description>
        <inlineHelpText>“State” part of the work order location</inlineHelpText>
        <label>State</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SVMXC__Street__c</fullName>
        <description>“Street” part of the work order location</description>
        <inlineHelpText>“Street” part of the work order location</inlineHelpText>
        <label>Street</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>SVMXC__Zip__c</fullName>
        <description>“Zip code” part of the work order location</description>
        <inlineHelpText>“Zip code” part of the work order location</inlineHelpText>
        <label>Zip</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sold_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sold Order</label>
        <referenceTo>Order</referenceTo>
        <relationshipLabel>Work Orders</relationshipLabel>
        <relationshipName>Work_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Work Order</label>
    <nameField>
        <displayFormat>WO-{00000000}</displayFormat>
        <label>Work Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work Orders</pluralLabel>
    <recordTypes>
        <fullName>Actions</fullName>
        <active>true</active>
        <description>Work Order that require Action (HOA, Historical)</description>
        <label>Actions</label>
    </recordTypes>
    <recordTypes>
        <fullName>Permit</fullName>
        <active>true</active>
        <description>Holds Building Permit Details</description>
        <label>Permit</label>
    </recordTypes>
    <recordTypes>
        <fullName>Visit</fullName>
        <active>true</active>
        <description>Work Orders where a home visit is required</description>
        <label>Visit</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

RbA Build/src/classes/OrderTriggerHandler.cls
/*******************************************************//**

@class	OrderTriggerHandler

@brief	Controller to hold logic for OrderTrigger trigger

@author  Anthony Strafaccia (Slalom.ADS)

@version	2015-10/26  Slalom.ADS
	Created.

@see		OrderTriggerHandlerTest

@copyright  (c)2015 Slalom.  All Rights Reserved.
			Unauthorized use is prohibited.

***********************************************************/

public without sharing class OrderTriggerHandler{

    /*
    public void OnBeforeInsert(List<Order> listNew){
    	system.debug('ads INSIDE BEFORE INSERT');    
    } 
    */

    public void OnBeforeUpdate(List<Order> listOld, List<Order> listNew, Map<Id, Order> mapOld, Map<Id, Order> mapNew){
        system.debug('ads INSIDE BEFORE UPDATE');
    	
    	map<Id, Store_Configuration__c> accountIdtoStoreConfigMap = getAllStoreConfigs();
 
    	list<id> relatedDwellingIds = new list<id>();
    	
    	for(Order ord : listNew){
    		system.debug('ads ord: '+ ord);
    		system.debug('ads ord.AccountId: '+ ord.AccountId);
    		relatedDwellingIds.add(ord.AccountId);
    	}
    	
    	list<Account> relatedDwelling = [SELECT Id, 
    											Store_Location__c, 
    											HOA__c, Historical__c, 
    											Building_Permit__c,
    											BillingStreet,
								    			BillingCity,
								    			BillingState,
								    			BillingStateCode,
								    			BillingPostalCode, 
								    			BillingCountry,
								    			BillingCountryCode 
    									
    										FROM Account Where Id IN : relatedDwellingIds];
    	
    	map<id, Account> dwellingIdtoDwellingMap = new map<id, Account>();
    	for(Account dwel : relatedDwelling){
    		dwellingIdtoDwellingMap.put(dwel.id, dwel);
    	}
    	
    	list<SVMXC__Service_Order__c> workOrdersToAdd = new list<SVMXC__Service_Order__c>();
    	
    	for(Order ord : listNew){
    		system.debug('ads ord.Status: '+ord.Status);
    		system.debug('ads mapOld.get(ord.Id).Status: '+ mapOld.get(ord.Id).Status);
    		if(ord.Status == 'Activated' && mapOld.get(ord.Id).Status == 'Draft'){
    			
    			Account dwelling = dwellingIdtoDwellingMap.get(ord.AccountId);
    			
    			
    			Id permitWORecordType = UtilityMethods.retrieveRecordTypeId('Permit', 'SVMXC__Service_Order__c');
    			Id actionWORecordType = UtilityMethods.retrieveRecordTypeId('Actions', 'SVMXC__Service_Order__c');
    			
    			Store_Configuration__c storeConfig;
    			
    			if(dwelling.Store_Location__c == null){ 
    				ord.addError('Store has not been set on dwelling.');
    			}else if(accountIdtoStoreConfigMap.get(dwelling.Store_Location__c) == null){
    				ord.addError('Store Configuation has not been created.');
    			}else{
    				
    				storeConfig = accountIdtoStoreConfigMap.get(dwelling.Store_Location__c);
    			
	    			if(dwelling.HOA__c != null){
	    				system.debug('ads inside HOA');
	    				SVMXC__Service_Order__c hoaWorkOrder = buildWorkOrder(dwelling, ord, actionWORecordType, storeConfig.Permit_Work_Order_Queue_Id__c, 'HOA',  dwelling.HOA__c);
	    				workOrdersToAdd.add(hoaWorkOrder);
	    			}
	    			
	    			if(dwelling.Historical__c != null){
	    				system.debug('ads inside historical');
	    				SVMXC__Service_Order__c historicalWorkOrder = buildWorkOrder(dwelling, ord, actionWORecordType, storeConfig.Permit_Work_Order_Queue_Id__c, 'Historical', dwelling.Historical__c );
	    				workOrdersToAdd.add(historicalWorkOrder);
	    			}
	    			
	    			if(dwelling.Building_Permit__c != null){
	    				system.debug('ads inside building');
	    				SVMXC__Service_Order__c buildingPermitWorkOrder = buildWorkOrder(dwelling, ord, permitWORecordType, storeConfig.Permit_Work_Order_Queue_Id__c, 'Building Permit', dwelling.Building_Permit__c );
	    				workOrdersToAdd.add(buildingPermitWorkOrder);
	    			}
	    			system.debug('ads workOrdersToAdd: '+workOrdersToAdd);
	    			insert workOrdersToAdd;
	    		}
			}
   	
    	}
    
    } 
    

    /*
    public void OnBeforeDelete(List<Order> listToDelete, Map<Id, Order> mapToDelete){
        system.debug('ads INSIDE BEFORE DELETE');
    }
    */

   
    public void OnAfterInsert(List<Order> listNew, Map<Id, Order> mapNew){
        system.debug('ads INSIDE AFTER INSERT');
    	
    	list<SVMXC__Service_Order__c> workOrdersToAdd = new list<SVMXC__Service_Order__c>();
    	list<Back_Office_Check__c> checksToAdd = new list<Back_Office_Check__c>();
    	
    	//TODO: use utility methods
		RecordType serviceOrderVisitRecordType = [SELECT id FROM RecordType WHERE SobjectType = 'SVMXC__Service_Order__c' AND Name = 'Visit'];
    	RecordType accountStoreRecordType = [SELECT id FROM RecordType WHERE SobjectType = 'Account' AND Name = 'Store'];
    	
    	list<Id> relatedAccountIds = new list<Id>();
    	for(Order o : listNew){
    		relatedAccountIds.add(o.AccountId);
    	} 
    	list<Account> relatedAccounts = [SELECT BillingStreet,
								    			BillingCity,
								    			BillingState,
								    			BillingStateCode,
								    			BillingPostalCode, 
								    			BillingCountry,
								    			BillingCountryCode
								    			FROM Account WHERE Id IN :relatedAccountIds];
		map<id, Account> accountIdToAccountMap = new map<id, Account>();		
    	for(Account a : relatedAccounts){
    		accountIdToAccountMap.put(a.id, a);
    	}
    	
    	
    	//TODO: Clean this up
    	////////THIS IS BEING USED FOR DEMO UNTIL ACCOUNT IS POPULATED INSIDE THE ORDER///////////
    	Account testAccount = [SELECT id FROM Account Where Name = '77 - Twin Cities, MN'];
    	//////////////////////////////////////////////////////////////////////////////////////////
    	
    	list<Store_Configuration__c> storeConfigs = [SELECT 	Id, 
    															Store__c, 
    															Install_Work_Order_Queue_Id__c, 
    															Tech_Measure_Work_Order_Queue_Id__c, 
    															Order_Queue_Id__c
    															FROM Store_Configuration__c
    															];
    	
    	map<id, Store_Configuration__c> accountIdtoStoreConfigMap = new map<id, Store_Configuration__c>();
		
		list<Id> storeConfigIdList = new list<id>();
    	for(Store_Configuration__c sc : storeConfigs){
    		accountIdtoStoreConfigMap.put(sc.Store__c, sc);
    		storeConfigIdList.add(sc.id);
    	}
    	
    	
    	//TODO: move to method
    	map<id, Back_Office_Checklist_Configuration__c> storeConfigIdToBackOfficeChecklistMap = new map<id, Back_Office_Checklist_Configuration__c>();
    	
    	SObjectType xBOC = Schema.getGlobalDescribe().get('Back_Office_Checklist_Configuration__c');
		map<String,Schema.SObjectField> bocFieldsMap = xBOC.getDescribe().fields.getMap();
	    
	    String bocQuery = 'SELECT ';
	    for(String bocField : bocFieldsMap.KeySet()){
			bocQuery = bocQuery + bocField + ', ';
	    }
	    bocQuery = bocQuery.substring(0,bocQuery.length()-2);
	    bocQuery = bocQuery + ' FROM Back_Office_Checklist_Configuration__c WHERE Store_Configuration__c IN :storeConfigIdList';
	    
	    list<Back_Office_Checklist_Configuration__c> backOfficeCheckList = Database.query(bocQuery);
    	//TODO: Class Method Names
    	system.debug('ads backOfficeCheckList: '+backOfficeCheckList);
    	for(Back_Office_Checklist_Configuration__c boc : backOfficeCheckList){
    		storeConfigIdToBackOfficeChecklistMap.put(boc.Store_Configuration__c, boc);
    	}
    	
    	
    	for(Order ord : listNew){
    		//TODO: Clean up
    		////////THIS IS BEING USED FOR DEMO UNTIL ACCOUNT IS POPULATED INSIDE THE ORDER///////////
	    	id storeLocation = testAccount.id;
	    	//////////////////////////////////////////////////////////////////////////////////////////
    		if(accountIdtoStoreConfigMap.get(storeLocation) == null){
    			ord.addError('Store Configuation has not been created.');
    		}
    		
    		Id installQueueId = accountIdtoStoreConfigMap.get(storeLocation).Install_Work_Order_Queue_Id__c;
    		Id techMeasureQueueId = accountIdtoStoreConfigMap.get(storeLocation).Tech_Measure_Work_Order_Queue_Id__c;
			
			//TODO:relatedDwelling
    		Account relatedAccount = accountIdToAccountMap.get(ord.AccountId);
    		
    		//CREATE WORK ORDER (TECH MEASURE)
    		SVMXC__Service_Order__c techWO = new SVMXC__Service_Order__c(
    			Sold_Order__c = ord.id,
    			RecordTypeId = serviceOrderVisitRecordType.id,
    			SVMXC__Order_Type__c = 'Tech Measure',
    			SVMXC__Company__c = ord.AccountId,
    				
    			SVMXC__Street__c = relatedAccount.BillingStreet,
    			SVMXC__City__c = relatedAccount.BillingCity,
    			SVMXC__State__c = relatedAccount.BillingStateCode,
    			SVMXC__Zip__c = relatedAccount.BillingPostalCode, 
    			SVMXC__Country__c = relatedAccount.BillingCountryCode,

    			OwnerId = techMeasureQueueId
    		);
    		workOrdersToAdd.add(techWO);
    		
    		
    		//CREATE WORK ORDER (INSTALL)
    		
    		/* Currently not making this type.
    		SVMXC__Service_Order__c installWO = new SVMXC__Service_Order__c(
    			Sold_Order__c = ord.id, 
    			RecordTypeId =  serviceOrderVisitRecordType.id,
    			SVMXC__Order_Type__c = 'Install',
    			SVMXC__Company__c = ord.AccountId,
    			
    			SVMXC__Street__c = relatedAccount.BillingStreet,
    			SVMXC__City__c = relatedAccount.BillingCity,
    			SVMXC__State__c = relatedAccount.BillingStateCode,
    			SVMXC__Zip__c = relatedAccount.BillingPostalCode, 
    			SVMXC__Country__c = relatedAccount.BillingCountryCode,
    			
    			
    			OwnerId = installQueueId
    		);
    		system.debug('ads adding install WO: '+installWO);
    		workOrdersToAdd.add(installWO);	
	    	*/
	    	
	    	
	    	
	    	
	    	Store_Configuration__c storeConfig = accountIdtoStoreConfigMap.get(storeLocation);
	    	system.debug('ADS storeConfig :'+storeConfig);
	    	
	    	//TODO:rename to checklist configuration
	    	Back_Office_Checklist_Configuration__c boChecklist = storeConfigIdToBackOfficeChecklistMap.get(storeConfig.id);
	    	
	    	system.debug('ADS boChecklist :'+boChecklist);
	    	
	    	for(String bocField :bocFieldsMap.KeySet()){
	    		if(boChecklist.get(bocField) != null && boChecklist.get(bocField) == true){
	    			String checkName = bocFieldsMap.get(bocField).getDescribe().getLabel();
	    			Back_Office_Check__c boc = new Back_Office_Check__c(Name= checkName, Order__c = ord.Id);
		    		checksToAdd.add(boc);
	    		}	
	    	}
    	}

    	insert workOrdersToAdd;
        insert checksToAdd;
                 
    }
   

    /*
    public void OnAfterUpdate(List<Order> listOld, List<Order> listNew, Map<Id, Order> mapOld, Map<Id, Order> mapNew){
          system.debug('ads INSIDE AFTER UPDATE');        
    }
    /*

    /*
    public void OnAfterDelete(List<Order> listDeleted, Map<Id, Order> listNew){
         system.debug('ads INSIDE AFTER DELETE'); 
    }
    */

    /*
    public void OnUndelete(List<Order> listRestored){
         system.debug('ads INSIDE ON UNDELETE'); 
    }
    */
    
    
    
    public SVMXC__Service_Order__c buildWorkOrder(Account dwelling, Order ord, Id rtID, Id ownerId, String ordType, Id munici ){
		SVMXC__Service_Order__c wo = new SVMXC__Service_Order__c(
			Sold_Order__c = ord.id,
			RecordTypeId = rtID,
			SVMXC__Order_Type__c = ordType,
			SVMXC__Company__c = ord.AccountId,
					
			SVMXC__Street__c = dwelling.BillingStreet,
			SVMXC__City__c = dwelling.BillingCity,
			SVMXC__State__c = dwelling.BillingStateCode,
			SVMXC__Zip__c = dwelling.BillingPostalCode, 
			SVMXC__Country__c = dwelling.BillingCountryCode,
			
			Municipality__c = munici,
			
			OwnerId = ownerId
			
		);
    	
    	return wo;
    	
    }
    
    public map<Id, Store_Configuration__c> getAllStoreConfigs(){
    	map<id, Store_Configuration__c> accountIdtoStoreConfigMap = new map<id, Store_Configuration__c>();

    	list<Store_Configuration__c> storeConfigs = [SELECT 	Id, 
    															Store__c, 
    															Install_Work_Order_Queue_Id__c, 
    															Tech_Measure_Work_Order_Queue_Id__c, 
    															Order_Queue_Id__c,
    															Permit_Work_Order_Queue_Id__c
    															FROM Store_Configuration__c
    															];
    	
    	for(Store_Configuration__c sc : storeConfigs){
    		accountIdtoStoreConfigMap.put(sc.Store__c, sc);
    	}
    	
    	return accountIdtoStoreConfigMap;
    }
    
    
}