RbA Build/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Building_Permit__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The Building Permit is populated in Code
Matching in the Municipalities table.
Matching criteria Address City and Zip code, match is found in the Municipality Match object</inlineHelpText>
        <label>Building Permit</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>You must select a Building record. If the record for you are for isn&apos;t in the system, please contact your manager to have it created.</errorMessage>
            <filterItems>
                <field>Municipality__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Permit</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Municipality__c</referenceTo>
        <relationshipLabel>Building Permit Dwellings</relationshipLabel>
        <relationshipName>Accounts2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>HOA__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Is this Dwelling part of an HOA?</inlineHelpText>
        <label>HOA</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>You must select an HOA record.  If the record for you are for isn&apos;t in the system, please contact your manager to have it created.</errorMessage>
            <filterItems>
                <field>Municipality__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>HOA</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Municipality__c</referenceTo>
        <relationshipLabel>HOA Dwellings</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Historical__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Is this Dwelling in a Historical District?</inlineHelpText>
        <label>Historical</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>You must select a Historical record. If the record you are for is not in the system, please contact your manager to have it created.</errorMessage>
            <filterItems>
                <field>Municipality__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Historical</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Municipality__c</referenceTo>
        <relationshipLabel>Historical Dwellings</relationshipLabel>
        <relationshipName>Accounts1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Store_Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The store location that this dwelling is related</description>
        <inlineHelpText>The store location that this dwelling is related</inlineHelpText>
        <label>Store Location</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>The account must be of type &quot;Store&quot;</errorMessage>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Store</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Dwellings</relationshipLabel>
        <relationshipName>StoreLocation</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Year_Built__c</fullName>
        <inlineHelpText>Year the house was built</inlineHelpText>
        <label>Year Built</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Dwelling</fullName>
        <active>true</active>
        <description>Used to support Dwelling</description>
        <label>Dwelling</label>
    </recordTypes>
    <recordTypes>
        <fullName>Store</fullName>
        <active>true</active>
        <description>Used to track and store data releated to Retail Locations both CORO and ARO</description>
        <label>Store</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

RbA Build/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Store_Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Store Location</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>The account must be of type &quot;Store&quot;.</errorMessage>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Store</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Store Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

RbA Build/src/objects/Order.object
<CustomObject>
    <fields>
        <fullName>Sold_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>When the Sold Order is Job In Progress, the Service Order must be related to the Sold Order.</inlineHelpText>
        <label>Sold Order</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>$Source.AccountId</field>
                <operation>equals</operation>
                <valueField>Order.AccountId</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Order</referenceTo>
        <relationshipLabel>Service Orders</relationshipLabel>
        <relationshipName>Sold_Order</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Store_Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This order is related to this store location.</description>
        <inlineHelpText>This order is related to this store location.</inlineHelpText>
        <label>Store Location</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Orders (Store Location)</relationshipLabel>
        <relationshipName>Orders1</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

RbA Build/src/objects/RbA_Work_Order__c.object
<CustomObject>
    <description>Custom Object used to track Work Orders related to Orders.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Dwelling association to the Work Order.</inlineHelpText>
        <label>Account</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Dwelling</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>RbA Work Orders (Account)</relationshipLabel>
        <relationshipName>RbA_Work_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <description>“City” part of the work order location.</description>
        <inlineHelpText>“City” part of the work order location.</inlineHelpText>
        <label>City</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Name of the contact person from the customer account for this service order. Is a lookup to an existing salesforce contact record</description>
        <inlineHelpText>Name of the contact person from the customer account for this service order. Is a lookup to an existing salesforce contact record</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Service_Order</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Related Opportunity</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Work Orders</relationshipLabel>
        <relationshipName>Work_Orders1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Order_Type__c</fullName>
        <description>Type of service order: Field Service, Depot repair etc.</description>
        <inlineHelpText>Type of service order: Field Service, Depot repair etc.</inlineHelpText>
        <label>Order Type</label>
        <picklist>
            <picklistValues>
                <fullName>Tech Measure</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Install</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Service</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HOA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Historical</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Building Permit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Paint/Stain</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LSWP</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Sold_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sold Order</label>
        <referenceTo>Order</referenceTo>
        <relationshipLabel>Work Orders</relationshipLabel>
        <relationshipName>Work_Orders1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <description>“State” part of the work order location</description>
        <inlineHelpText>“State” part of the work order location</inlineHelpText>
        <label>State</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street__c</fullName>
        <description>“Street” part of the work order location</description>
        <inlineHelpText>“Street” part of the work order location</inlineHelpText>
        <label>Street</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Zip__c</fullName>
        <description>“Zip code” part of the work order location</description>
        <inlineHelpText>“Zip code” part of the work order location</inlineHelpText>
        <label>Zip</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>RbA Work Order</label>
    <nameField>
        <displayFormat>WO-{00000000}</displayFormat>
        <label>Work Order #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RbA Work Orders</pluralLabel>
    <recordTypes>
        <fullName>Actions</fullName>
        <active>true</active>
        <description>Holds HOA and Historical Details</description>
        <label>Actions</label>
    </recordTypes>
    <recordTypes>
        <fullName>LSWP</fullName>
        <active>true</active>
        <description>Holds LSWP Details</description>
        <label>LSWP</label>
    </recordTypes>
    <recordTypes>
        <fullName>Permit</fullName>
        <active>true</active>
        <description>Holds Building Permit Details</description>
        <label>Permit</label>
    </recordTypes>
    <recordTypes>
        <fullName>Visit</fullName>
        <active>true</active>
        <description>Hold Work Order details that can be have a scheduled visit to the home</description>
        <label>Visit</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

RbA Build/src/objects/Store_Configuration__c.object
<CustomObject>
    <description>Holds Store Settings &amp; Configurations</description>
    <fields>
        <fullName>Building_Permit_Work_Order_Queue_Id__c</fullName>
        <label>Building Permit Work Order Queue Id</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>HOA_Work_Order_Queue_Id__c</fullName>
        <label>HOA Work Order Queue Id</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Historical_Work_Order_Queue_Id__c</fullName>
        <label>Historical Work Order Queue Id</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Install_Work_Order_Queue_Id__c</fullName>
        <label>Install Work Order Queue Id</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LSWP_WO_Owner_ID__c</fullName>
        <inlineHelpText>Who will be the default owner of LSWP Work Order.  Can be a User or a Queue.  Please put in the ID of the User or Queue.</inlineHelpText>
        <label>LSWP WO Queue ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Tech_Measure_Work_Order_Queue_Id__c</fullName>
        <label>Tech Measure Work Order Queue Id</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Store Configuration</label>
    <nameField>
        <displayFormat>SS-{00}</displayFormat>
        <label>Store Setting Record #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Store Configurations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

RbA Build/src/classes/RMS_WorkOrderCreationManager.cls
public with sharing class RMS_WorkOrderCreationManager {
    
    
    /************************************************************
            createWorkOrderOnOrderActivation
    *************************************************************/
    public void createWorkOrderOnOrderActivation(List<Order> listOld, List<Order> listNew, Map<Id, Order> mapOld, Map<Id, Order> mapNew){
        system.debug('******INSIDE RMS_WorkOrderCreationManager/createWorkOrderOnActivation');

        list<Order> activatedOrders = new list<Order>();
        list<id> activatedOrderId = new list<id>();
        list<id> relatedDwellingIds = new list<id>();
        list<id> dwellingStoreLocationIds = new list<id>();
        
        //FILTERING OUT NON ACTIVATED ORDERS AS WELL AS BUILDING THE LIST OF DWELLINGS TO GET THEIR STORE CONFIGS
        for(Order ord : listNew){
            if(ord.Status == 'Activated' && mapOld.get(ord.Id).Status == 'Draft'){
                relatedDwellingIds.add(ord.AccountId);
                activatedOrders.add(ord);
                activatedOrderId.add(ord.id);
            }
        }
        
        //IF NO ORDERS HAVE BEEN ACTIVATED THEN SKIP REST OF LOGIC
        if(activatedOrders.size() > 0){
            
            //LOOPING THROUGH ALL DWELLINGS GETTING THEIR STORE LOCATIONS TO USE TO GET STORE CONFIGS
            for(Account dwelling : [SELECT id, Store_Location__c FROM Account WHERE Id IN :relatedDwellingIds]){
                dwellingStoreLocationIds.add(dwelling.Store_Location__c);
            }
            
            //GETTING ALL STORE CONFIGS FOR RELATED DWELLINGS
            map<Id, Store_Configuration__c> accountIdtoStoreConfigMap = UtilityMethods.mapStoreConfigs(dwellingStoreLocationIds);
        
            //QUERY FOR FIELDS ON DWELLING TO POPULATE WORK ORDER
            list<Account> relatedDwelling = [SELECT Id,  
                                                    Store_Location__c, 
                                                    HOA__c, Historical__c, 
                                                    Building_Permit__c,
                                                    ShippingStreet,
                                                    ShippingCity,
                                                    ShippingState,
                                                    ShippingStateCode,
                                                    ShippingPostalCode, 
                                                    ShippingCountry,
                                                    ShippingCountryCode,
                                                    Year_Built__c
                                                FROM Account Where Id IN : relatedDwellingIds];
            
            //BUILDING MAP OF ID TO DWELLING TO USE WHILE LOOPING THROUGH ORDERS
            map<id, Account> dwellingIdtoDwellingMap = new map<id, Account>();
            for(Account dwel : relatedDwelling){
                dwellingIdtoDwellingMap.put(dwel.id, dwel);
                
            }
            
            
            //RETREVING RECORD TYPES USED IN WORK ORDER CREATION
            Id permitWORecordType = UtilityMethods.retrieveRecordTypeId('Permit', 'RbA_Work_Order__c');
            Id actionWORecordType = UtilityMethods.retrieveRecordTypeId('Actions', 'RbA_Work_Order__c');
            Id LSWPWORecordType = UtilityMethods.retrieveRecordTypeId('LSWP', 'RbA_Work_Order__c');
            
            
            
            //BUILDING MAP OF ORD ID TO LIST OF LSWP WORK ORDERS TO USE WHILE LOOPING THROUGH ORDERS
            map<id, list<RbA_Work_Order__c>> ordIdtoListOfLSWPWOMap = new map<id, list<RbA_Work_Order__c>>();
            list<RbA_Work_Order__c> relatedLSWPWorkOrders = [SELECT id, Sold_Order__c, RecordTypeId FROM RbA_Work_Order__c WHERE Sold_Order__c IN :activatedOrderId AND RecordTypeId = :LSWPWORecordType];

            for(RbA_Work_Order__c wo : relatedLSWPWorkOrders){
                if(ordIdtoListOfLSWPWOMap.containsKey(wo.Sold_Order__c)){
                    ordIdtoListOfLSWPWOMap.get(wo.Sold_Order__c).add(wo);
                }else{
                    ordIdtoListOfLSWPWOMap.put(wo.Sold_Order__c, new list<RbA_Work_Order__c>{wo});
                }
            }
 
            //LIST OF ORDERS TO INSERT AFTER FOR LOOP
            list<RbA_Work_Order__c> workOrdersToAdd = new list<RbA_Work_Order__c>();
            
            //LOOP THROUGH ACTIVATED ORDERS AND CREATE WORK ORDERS
            for(Order ord : activatedOrders){
                
                Account dwelling = dwellingIdtoDwellingMap.get(ord.AccountId);
                Store_Configuration__c storeConfig;
                
                //NULL CHECKS AND ERRORS IF NO STORE LOCATION OR NO STORE CONFIGURATION
                if(dwelling.Store_Location__c == null){ 
                    ord.addError('Store has not been set on dwelling.');
                }else if(accountIdtoStoreConfigMap.get(dwelling.Store_Location__c) == null){
                    ord.addError('Store Configuation has not been created.');
                }else{
                    
                    //GET STORE CONFIG FROM MAP
                    storeConfig = accountIdtoStoreConfigMap.get(dwelling.Store_Location__c);
                
                    //CREATE HOA WORK ORDER IF DWELLING HAS HOA POPULATED
                    if(dwelling.HOA__c != null){
                        RbA_Work_Order__c hoaWorkOrder = UtilityMethods.buildWorkOrder(dwelling, ord, actionWORecordType, storeConfig.HOA_Work_Order_Queue_Id__c, 'HOA',  dwelling.HOA__c);
                        workOrdersToAdd.add(hoaWorkOrder);
                    }
                    
                    //CREATE HISTORICAL WORK ORDER IF DWELLING HAS HISTORICAL POPULATED
                    if(dwelling.Historical__c != null){
                        RbA_Work_Order__c historicalWorkOrder = UtilityMethods.buildWorkOrder(dwelling, ord, actionWORecordType, storeConfig.Historical_Work_Order_Queue_Id__c, 'Historical', dwelling.Historical__c );
                        workOrdersToAdd.add(historicalWorkOrder);
                    }
                    
                    //CREATE PERMIT WORK ORDER IF DWELLING HAS BUILDING PERMIT POPULATED
                    if(dwelling.Building_Permit__c != null){
                        RbA_Work_Order__c buildingPermitWorkOrder = UtilityMethods.buildWorkOrder(dwelling, ord, permitWORecordType, storeConfig.Building_Permit_Work_Order_Queue_Id__c, 'Building Permit', dwelling.Building_Permit__c );
                        workOrdersToAdd.add(buildingPermitWorkOrder);
                    }
                    //CREATE LSWP WORK ORDER IF NO LSWP WORK ORDER BU DWELLING Year_Built__c IS NULL OR BEFORE  1978
                    if(ordIdtoListOfLSWPWOMap.get(ord.id) == null || ordIdtoListOfLSWPWOMap.get(ord.id).size() == 0){
	                    if(dwelling.Year_Built__c == null || dwelling.Year_Built__c == ''  || Integer.valueof(Dwelling.Year_Built__c) < 1978){
	                        RbA_Work_Order__c LSWPWorkOrder = UtilityMethods.buildWorkOrder(dwelling, ord, LSWPWORecordType, storeConfig.LSWP_WO_Owner_ID__c, 'LSWP', null );
	                        workOrdersToAdd.add(LSWPWorkOrder);
	                    }
                    }
                }
            }
            
            //INSERT ALL WORK ORDERS CREATED
            system.debug('****** RMS_WorkOrderCreationManager/createWorkOrderOnActivation Inserting workOrdersToAdd: '+workOrdersToAdd);
            insert workOrdersToAdd;
            
        }// END IF activatedOrders.size() > 0
    }// END createWorkOrderOnActivation METHOD
    
    

    /************************************************************
            createWorkOrderOnOrderCreation
    *************************************************************/
    
    public void createWorkOrderOnOrderCreation(List<Order> listNew, Map<Id, Order> mapNew){
        system.debug('******INSIDE RMS_WorkOrderCreationManager/createWorkOrderOnOrderCreation');
        
        list<RbA_Work_Order__c> workOrdersToAdd = new list<RbA_Work_Order__c>();
        Id serviceOrderVisitRecordTypeId = UtilityMethods.retrieveRecordTypeId('Visit', 'RbA_Work_Order__c');
        
        
        list<Id> relatedAccountIds = new list<Id>();
        list<id> relatedOpportunityIds = new list<id>();
        
        for(Order o : listNew){
            relatedAccountIds.add(o.AccountId);
            //IF OPPORTUNITY POPULATED THEN ADD TO LIST
            	system.debug('****** order: '+o);
                if(o.OpportunityId != null){
                    relatedOpportunityIds.add(o.OpportunityId);
                }  
        } 
        
        list<Account> relatedAccounts = [SELECT ShippingStreet,
                                                ShippingCity,
                                                ShippingState,
                                                ShippingStateCode,
                                                ShippingPostalCode, 
                                                ShippingCountry,
                                                ShippingCountryCode,
                                                Store_Location__c
                                                
                                                FROM Account WHERE Id IN :relatedAccountIds];
        map<id, Account> accountIdToAccountMap = new map<id, Account>();        
        list<id> dwellingStoreLocationIds = new list<id>();
        for(Account a : relatedAccounts){
            accountIdToAccountMap.put(a.id, a);
            dwellingStoreLocationIds.add(a.Store_Location__c);
        }
        
        //IF ANY RELATED OPPS EXIST THEN QUERY FOR TECH MEASURE WORK ORDERS ON THEM
        map<id, list<RbA_Work_Order__c>> oppIdtoListOfTechMeasureWOMap = new map<id, list<RbA_Work_Order__c>>();
        if(relatedOpportunityIds.size() > 0){
            list<RbA_Work_Order__c> relatedTechMeasureWorkOrders = [SELECT    Id,  
                                                                                    Opportunity__c
                                                                    FROM RbA_Work_Order__c 
                                                                    WHERE Opportunity__c IN : relatedOpportunityIds
                                                                    AND Order_Type__c = 'Tech Measure'];
       
            //BUILDING MAP OF OPP ID TO LIST OF WORK ORDERS TO USE WHILE LOOPING THROUGH ORDERS
            
            for(RbA_Work_Order__c wo : relatedTechMeasureWorkOrders){
                if(oppIdtoListOfTechMeasureWOMap.containsKey(wo.Opportunity__c)){
                    oppIdtoListOfTechMeasureWOMap.get(wo.Opportunity__c).add(wo);
                }else{
                    oppIdtoListOfTechMeasureWOMap.put(wo.Opportunity__c, new list<RbA_Work_Order__c>{wo});
                }
            }
                
                
        }   
        
        //GETTING ALL STORE CONFIGS FOR RELATED DWELLINGS
        map<Id, Store_Configuration__c> accountIdtoStoreConfigMap = UtilityMethods.mapStoreConfigs(dwellingStoreLocationIds);
        

        for(Order ord : listNew){ 
            //CHECKING IF CURRENT ORDER'S OPPORTUNITY HAS ANY RELATED TECH MEASURES IF SO, SKIP LOGIC AND ASSIGN THOSE TO THIS WORK ORDER
            system.debug('****** ord ' + ord);
            if(ord.OpportunityId != null && oppIdtoListOfTechMeasureWOMap.get(ord.OpportunityId) != null){
                
	            list<RbA_Work_Order__c> techMeasureWorkOrders = oppIdtoListOfTechMeasureWOMap.get(ord.OpportunityId);
	            
	            for(RbA_Work_Order__c wo : techMeasureWorkOrders){
	                wo.Sold_Order__c = ord.id;
	                workOrdersToAdd.add(wo);
	            }
	            
            
            }else{
                Account relatedDwelling = accountIdToAccountMap.get(ord.AccountId);
    
                if(accountIdtoStoreConfigMap.get(relatedDwelling.Store_Location__c) == null){
                    ord.addError('Store Configuation has not been created.');
                }
                
                Id installQueueId = accountIdtoStoreConfigMap.get(relatedDwelling.Store_Location__c).Install_Work_Order_Queue_Id__c;
                Id techMeasureQueueId = accountIdtoStoreConfigMap.get(relatedDwelling.Store_Location__c).Tech_Measure_Work_Order_Queue_Id__c;
                
                //CREATE WORK ORDER (TECH MEASURE)
                RbA_Work_Order__c techWO = new RbA_Work_Order__c(
                    Sold_Order__c = ord.id,
                    RecordTypeId = serviceOrderVisitRecordTypeId,
                    Order_Type__c = 'Tech Measure',
                    Account__c = ord.AccountId,
                    Contact__c = ord.BillToContactId,
                    
                    
                    Street__c = relatedDwelling.ShippingStreet,
                    City__c = relatedDwelling.ShippingCity,
                    State__c = relatedDwelling.ShippingStateCode,
                    Zip__c = relatedDwelling.ShippingPostalCode, 
                    Country__c = relatedDwelling.ShippingCountryCode,
    
                    OwnerId = techMeasureQueueId
                );
                workOrdersToAdd.add(techWO);
                
                /*
                //TODO: Remove if not used
                //CREATE WORK ORDER (INSTALL)
                RbA_Work_Order__c installWO = new RbA_Work_Order__c(
                    Sold_Order__c = ord.id, 
                    RecordTypeId =  serviceOrderVisitRecordTypeId,
                    Order_Type__c = 'Install',
                    Account__c = ord.AccountId,
                    
                    Street__c = relatedDwelling.ShippingStreet,
                    City__c = relatedDwelling.ShippingCity,
                    State__c = relatedDwelling.ShippingStateCode,
                    Zip__c = relatedDwelling.ShippingPostalCode, 
                    Country__c = relatedDwelling.ShippingCountryCode,
                    
                    
                    OwnerId = installQueueId
                );
                system.debug('ads adding install WO: '+installWO);
                workOrdersToAdd.add(installWO); 
                */
    
                Store_Configuration__c storeConfig = accountIdtoStoreConfigMap.get(relatedDwelling.Store_Location__c);
                system.debug('ADS storeConfig :'+storeConfig);
    
            }
        }
        //INSERT ALL WORK ORDERS
        upsert workOrdersToAdd;    
           
    }// END OF createWorkOrderOnOrderCreation METHOD



}// EOF