RbA Build/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Check if this account is active</description>
        <inlineHelpText>Check if this account is active</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Inactive_Date__c</fullName>
        <description>Finds the smallest Expiration Date for all Insurance Exp Dates(Vendor/Contractor), indicating the date which a resource becomes inactive (if one date passes)</description>
        <inlineHelpText>Finds the smallest Expiration Date for all Insurance Exp Dates(Vendor/Contractor), indicating the date which a resource becomes inactive (if one date passes)</inlineHelpText>
        <label>Inactive Date</label>
        <type>Date</type>
    </fields>
    <recordTypes>
        <fullName>Vendor</fullName>
        <active>true</active>
        <description>Used to track Vendors</description>
        <label>Vendor</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

RbA Build/src/objects/Resource__c.object
<CustomObject>
    <description>Used to hold details about the recourse for scheduling</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>By default when a Resource is created they will be Active. Will be marked as inactive when any one of the liability insurance expires.</description>
        <inlineHelpText>Is this resource active?</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Inactive_Date__c</fullName>
        <formula>IF( 
AND( 
ISBLANK(Auto_Insurance_Expiration_Date__c), 
ISBLANK(General_Insurance_Expiration_Date__c), 
ISBLANK(Work_Comp_Insurance_Expiration_Date__c) 
), 
NULL, 
TODAY()- 
MAX( 
TODAY()- BLANKVALUE(Auto_Insurance_Expiration_Date__c, DATE(2999, 01, 01)), 
TODAY()- BLANKVALUE(General_Insurance_Expiration_Date__c, DATE(2999, 01, 01)), 
TODAY()- BLANKVALUE(Work_Comp_Insurance_Expiration_Date__c, DATE(2999, 01, 01)) 
) 
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Date this resource&apos;s insurance expires - the earliest of the three insurance dates. 7 days after this date, this resource will be marked inactive.</inlineHelpText>
        <label>Inactive Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>RbA_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Enter individual for Tech Measure. Enter Crew name for Installer</inlineHelpText>
        <label>RbA User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Resources</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Vendor_Account_Id__c</fullName>
        <description>Used for automation purposes</description>
        <formula>RbA_User__r.Contact.AccountId</formula>
        <label>Vendor Account Id</label>
        <type>Text</type>
    </fields>
    <label>Resource</label>
    <nameField>
        <label>Resource Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Resources</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

RbA Build/src/classes/RMS_reactivateResource.cls
/*************************************************************
@brief  When an insurance exp date is updated on a vendor account,
any inactive resources for that vendor are reactivated

@author  Brianne Wilson (Slalom.BLW)

@version    2016-5-20  Slalom.BLW
Created.


@copyright  (c)2016 Slalom.  All Rights Reserved. 
Unauthorized use is prohibited.

***********************************************************/

public class RMS_reactivateResource {
    
    public void reactivateResource(List<Account> listOld, List<Account> listNew, Map<Id, Account> mapOld, Map<Id, Account> mapNew){
        
        List<Resource__c> childRecords = [Select Id, RbA_User__c, Vendor_Account_Id__c,RbA_User__r.Contact.AccountId
                                                FROM Resource__c WHERE Active__c = FALSE and RbA_User__r.Contact.AccountId IN: Trigger.newMap.keySet()];
        
        system.debug(childRecords);
        
        Map<Id,Resource__c> resourceMap = new Map<Id,Resource__c>([select Id from Resource__c where id in:childRecords]);
        
        for(Resource__c child :childRecords){
            if(!resourceMap.IsEmpty()){   
                if(mapNew.get(child.RbA_User__r.Contact.AccountId).Inactive_Date__c != null && mapNew.get(child.RbA_User__r.Contact.AccountId).Inactive_Date__c != mapOld.get(child.RbA_User__r.Contact.AccountId).Inactive_Date__c){
                   if(mapNew.get(child.RbA_User__r.Contact.AccountId).Inactive_Date__c >= system.TODAY()){
                    child.Active__c = TRUE;                    
                    }
                }                              
            }
        }
        
        if(childRecords.size() > 0){
            update childRecords;
        }                    
    }
}