RbA Build/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Building_Permit__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The Building Permit is populated in Code
Matching in the Municipalities table.
Matching criteria Address City and Zip code, match is found in the Municipality Match object</inlineHelpText>
        <label>Building Permit</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>You must select a Building record. If the record for you are for isn&apos;t in the system, please contact your manager to have it created.</errorMessage>
            <filterItems>
                <field>Municipality__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Permit</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Municipality__c</referenceTo>
        <relationshipLabel>Building Permit Dwellings</relationshipLabel>
        <relationshipName>Accounts2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>HOA__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Is this Dwelling part of an HOA?</inlineHelpText>
        <label>HOA</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>You must select an HOA record.  If the record for you are for isn&apos;t in the system, please contact your manager to have it created.</errorMessage>
            <filterItems>
                <field>Municipality__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>HOA</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Municipality__c</referenceTo>
        <relationshipLabel>HOA Dwellings</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Historical__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Is this Dwelling in a Historical District?</inlineHelpText>
        <label>Historical</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>You must select a Historical record. If the record you are for is not in the system, please contact your manager to have it created.</errorMessage>
            <filterItems>
                <field>Municipality__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Historical</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Municipality__c</referenceTo>
        <relationshipLabel>Historical Dwellings</relationshipLabel>
        <relationshipName>Accounts1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Store_Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The store location that this dwelling is related</description>
        <inlineHelpText>The store location that this dwelling is related</inlineHelpText>
        <label>Store Location</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>The account must be of type &quot;Store&quot;</errorMessage>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Store</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Dwellings</relationshipLabel>
        <relationshipName>StoreLocation</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

RbA Build/src/objects/Order.object
<CustomObject>
    <fields>
        <fullName>Lock_Service_Request__c</fullName>
        <description>For Service Requests, if status is in a Warranty status or Closed, the Service Request is locked. This field is used for UI purposes on VF pages to hide items if the request is locked.</description>
        <formula>AND(RecordType.DeveloperName = &quot;CORO_Service&quot;,
(OR(ISPICKVAL(Status, &quot;Warranty Submitted&quot;),
 ISPICKVAL(Status, &quot;Warranty Accepted&quot;),
 ISPICKVAL(Status, &quot;Warranty Rejected&quot;),
 ISPICKVAL(Status, &quot;Closed&quot;))))</formula>
        <label>Lock Service Request</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Sold_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>When the Sold Order is Job In Progress, the Service Order must be related to the Sold Order.</inlineHelpText>
        <label>Sold Order</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>$Source.AccountId</field>
                <operation>equals</operation>
                <valueField>Order.AccountId</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Order</referenceTo>
        <relationshipLabel>Service Orders</relationshipLabel>
        <relationshipName>Sold_Order</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Store_Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This order is related to this store location.</description>
        <inlineHelpText>This order is related to this store location.</inlineHelpText>
        <label>Store Location</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Orders (Store Location)</relationshipLabel>
        <relationshipName>Orders1</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

RbA Build/src/objects/RbA_Work_Order__c.object
<CustomObject>
    <description>Custom Object used to track Work Orders related to Orders.</description>
    <fields>
        <fullName>Appointment_Duration__c</fullName>
        <inlineHelpText>Duration the Appoitment will be</inlineHelpText>
        <label>Appointment Duration</label>
        <precision>4</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Confirmed_Appt_w_Customer__c</fullName>
        <inlineHelpText>Date/Time you called the customer and confirmed the scheduled visit out to the home.</inlineHelpText>
        <label>Confirmed Appt w/Customer</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Sold_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sold Order</label>
        <referenceTo>Order</referenceTo>
        <relationshipLabel>Work Orders</relationshipLabel>
        <relationshipName>Work_Orders1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Work_Order_Status__c</fullName>
        <description>Current status of the work order</description>
        <inlineHelpText>Current status of the work order</inlineHelpText>
        <label>Work Order Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Open</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wait for Install</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>To be scheduled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Applied</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Received</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Scheduled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>JIP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On Hold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Install Complete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Final Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Final Failed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Denied</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Assignment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Scheduled &amp; Assigned</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Appt Complete / Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Suspended / On Hold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Complete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Shared Services</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Work_Order_Type__c</fullName>
        <description>Type of work order: HOA, Historical, LSWP, Building, Tech Measure, Install, Service. etc.</description>
        <inlineHelpText>Type of work order: HOA, Historical, LSWP, Building, Tech Measure, Install, Service. etc.</inlineHelpText>
        <label>Work Order Type</label>
        <picklist>
            <picklistValues>
                <fullName>Tech Measure</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Install</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Service</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HOA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Historical</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Building Permit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Paint/Stain</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LSWP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Collections</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>RbA Work Order</label>
    <nameField>
        <displayFormat>WO-{00000000}</displayFormat>
        <label>Work Order #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RbA Work Orders</pluralLabel>
    <recordTypes>
        <fullName>Actions</fullName>
        <active>true</active>
        <description>Holds HOA and Historical Details</description>
        <label>Actions</label>
    </recordTypes>
    <recordTypes>
        <fullName>Collections</fullName>
        <active>true</active>
        <label>Collections</label>
    </recordTypes>
    <recordTypes>
        <fullName>LSWP</fullName>
        <active>true</active>
        <description>Holds LSWP Details</description>
        <label>LSWP</label>
    </recordTypes>
    <recordTypes>
        <fullName>Permit</fullName>
        <active>true</active>
        <description>Holds Building Permit Details</description>
        <label>Permit</label>
    </recordTypes>
    <recordTypes>
        <fullName>Visit</fullName>
        <active>true</active>
        <description>Hold Work Order details that can be have a scheduled visit to the home</description>
        <label>Visit</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

RbA Build/src/classes/RMS_viewServiceRequestCtrlr.cls
public class RMS_viewServiceRequestCtrlr {
    
    public final Order o;
    
    Public String baseURL{get;set;}
    public String updateSTURL{get;set;}
    public String editRedirect{get;set;}
    public string serviceOrderVisitRecordTypeURL{get;set;}
    public string serviceOrderActionsRecordTypeURL{get;set;}
    public string serviceOrderLSWPRecordTypeURL{get;set;}
    public string serviceOrderPaintStainRecordTypeURL{get;set;}
    public string serviceOrderPermitRecordTypeURL{get;set;}
    public string serviceOrderCollectionsRecordTypeId{get;set;}
    public string serviceOrderCollectionsRecordTypeURL{get;set;}
    
    public id ordRecId;
    
    public RMS_viewServiceRequestCtrlr(ApexPages.StandardController stdController) {
        if(!test.isRunningTest()){
            stdController.addFields(new List<String>{'RecordType','Id','RecordType.Name','Lock_Service_Request__c'});           
        }
        
        this.o = (Order)stdController.getRecord();
        
        ordRecId = [select id, RecordType.Name, RecordTypeId from Order where id = :ApexPages.currentPage().getParameters().get('id')].id;
        
        baseUrl = URL.getSalesforceBaseUrl().toExternalForm();
        updateSTURL = '/apex/RMS_updateServiceType?id=' + o.Id;
        editRedirect ='/apex/RMS_editServiceRequest?id='+o.Id;
        
        Schema.DescribeSObjectResult r = RbA_Work_Order__c.sObjectType.getDescribe();
        String workOrderKeyPrefix = r.getKeyPrefix();
        
        String ordId = o.id;
        list<Order> theOrd = [SELECT Id, AccountId, Status, RecordType.Name, Store_Location__c, OrderNumber, OpportunityId, BillToContactId, RecordTypeId FROM Order WHERE Id =:ordId ];
        
        list<Account> relatedAccount = [SELECT  Name,
                                        ShippingStreet,
                                        ShippingCity,
                                        ShippingState,
                                        ShippingPostalCode, 
                                        ShippingCountry,
                                        Historical__c,
                                        HOA__c,
                                        Building_Permit__c
                                        
                                        FROM Account WHERE Id = :theOrd[0].AccountId];
        
        String endURL =                     '&orderId='+o.Id+
            '&storeId='+theOrd[0].Store_Location__c+
            '&accountId='+relatedAccount[0].Id+
            '&shippingStreet='+relatedAccount[0].ShippingStreet+
            '&shippingCity='+relatedAccount[0].ShippingCity+
            '&shippingState='+relatedAccount[0].ShippingState+
            '&shippingPostalCode='+relatedAccount[0].ShippingPostalCode+
            '&shippingCountry='+relatedAccount[0].ShippingCountry+
            '&relatedOpp='+theOrd[0].OpportunityId+
            '&billToContactId='+theOrd[0].BillToContactId+
            '&permit='+relatedAccount[0].Building_Permit__c+    
            '&hoa='+relatedAccount[0].HOA__c+ 
            '&historical='+relatedAccount[0].Historical__c; 
        
        serviceOrderVisitRecordTypeURL = '/apex/RMS_createVisitWorkOrder?type=visit'+endURL;
        serviceOrderActionsRecordTypeURL =  '/apex/RMS_createActionsWorkOrder?type=actions'+endURL;                
        serviceOrderLSWPRecordTypeURL = '/apex/RMS_createActionsWorkOrder?type=lswp'+endURL;        
        serviceOrderPaintStainRecordTypeURL = '/apex/RMS_createActionsWorkOrder?type=paintStain'+endURL;         
        serviceOrderPermitRecordTypeURL = '/apex/RMS_createActionsWorkOrder?type=permit'+endURL;
        serviceOrderCollectionsRecordTypeURL = '/apex/RMS_createActionsWorkOrder?type=collections'+endURL;                                    
        
    }
    
    List<RbA_Work_Order__c> visitWOs;
    public List<RbA_Work_Order__c> getvisitWOs() {
        if(ordRecId != null) {
            visitWOs = [SELECT Id, Work_Order_Status__c,Work_Order_Type__c,Confirmed_Appt_w_Customer__c,Appointment_Duration__c, Owner.Name
                        FROM RbA_Work_Order__c 
                        WHERE RecordType.DeveloperName = 'Visit' AND Sold_Order__r.id=:ordRecId];
        }
        return visitWOs;
    } 
    
    List<RbA_Work_Order__c> actionWOs;
    public List<RbA_Work_Order__c> getactionWOs() {
        if(ordRecId != null) {
            actionWOs = [SELECT Id, Work_Order_Status__c,Work_Order_Type__c,Confirmed_Appt_w_Customer__c,Owner.Name
                         FROM RbA_Work_Order__c 
                         WHERE RecordType.DeveloperName != 'Visit' AND Sold_Order__r.id=:ordRecId];
        }
        return actionWOs;
    } 
    
    
    
    public PageReference cancelOrder(){
        PageReference pageRef = null;
        try{
            o.Status = 'Cancelled';
            upsert o;
            pageRef = new PageReference('/' + o.id);
            pageRef.setRedirect(true); 
        }catch(DMLException ex){
            ApexPages.addMessages(ex);
        }
        
        return pageRef;
    }
    
    public PageReference orderRedirect(){
        PageReference newPage = null;
        
        
        
        If (o.RecordType.Name == 'CORO Service'){
            If(o.Lock_Service_Request__c == TRUE){
                newPage = new PageReference('/apex/RMS_viewServiceRequestLocked?id='+ o.Id);
            } else {
                newPage = new PageReference('/apex/RMS_viewServiceRequest?id='+ o.Id);                    
            }
        } else {
            newPage = new PageReference('/'+ o.Id);
            newPage.getParameters().put('nooverride','1');
        }
        
        newPage.setRedirect(true);
        return newPage;
        
        
    }  
    
    public PageReference updateServiceType(){
        PageReference newPage;
        newPage = new PageReference('/apex/RMS_updateServiceType?id='+o.id);
        newPage.setRedirect(true); 
        return newPage;
    } 
    
        public PageReference editServiceRequest(){
        PageReference newPage;
        newPage = new PageReference('/apex/RMS_editServiceRequest?id='+o.id);
        newPage.setRedirect(true); 
        return newPage;
    } 
    
    
}