RbA Build/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Store_Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The store location that this dwelling is related</description>
        <inlineHelpText>The store location that this dwelling is related</inlineHelpText>
        <label>Store Location</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>The account must be of type &quot;Store&quot;</errorMessage>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Store</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Dwellings</relationshipLabel>
        <relationshipName>StoreLocation</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Dwelling</fullName>
        <active>true</active>
        <description>Used to support Dwelling</description>
        <label>Dwelling</label>
    </recordTypes>
    <recordTypes>
        <fullName>Store</fullName>
        <active>true</active>
        <description>Used to track and store data releated to Retail Locations both CORO and ARO</description>
        <label>Store</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

RbA Build/src/objects/Back_Office_Check__c.object
<CustomObject>
    <description>Junction Object between the Back Office Checklist Configurations and Order.  Keeps the history of items that need to checked in order for the order move through the process.</description>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <referenceTo>Order</referenceTo>
        <relationshipLabel>Back Office Checks</relationshipLabel>
        <relationshipName>Back_Office_Checks</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Back Office Check</label>
    <nameField>
        <label>Back Office Check Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Back Office Checks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

RbA Build/src/objects/Back_Office_Checklist_Configuration__c.object
<CustomObject>
    <description>Used for tracking important signed documents</description>
    <fields>
        <fullName>Store_Configuration__c</fullName>
        <label>Store Configuration</label>
        <referenceTo>Store_Configuration__c</referenceTo>
        <relationshipName>Back_Office_Checklists</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Back Office Checklist Configuration</label>
    <nameField>
        <displayFormat>BOC# - {00}</displayFormat>
        <label>Back Office Checklist Record #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Back Office Checklist Configurations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

RbA Build/src/objects/Order.object
<CustomObject>
    <fields>
        <fullName>Store_Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This order is related to this store location.</description>
        <inlineHelpText>This order is related to this store location.</inlineHelpText>
        <label>Store Location</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Orders (Store Location)</relationshipLabel>
        <relationshipName>Orders1</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

RbA Build/src/objects/Store_Configuration__c.object
<CustomObject>
    <description>Holds Store Settings &amp; Configurations</description>
    <label>Store Configuration</label>
    <nameField>
        <displayFormat>SS-{00}</displayFormat>
        <label>Store Setting Record #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Store Configurations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

RbA Build/src/classes/RMS_backOfficeChecklistManager.cls
public with sharing class RMS_backOfficeChecklistManager {

	/***********************************************
			createWorkOrderOnOrderCreation
	*******************************************/
	
	public void createBackOfficeChecksOnOrderCreation(List<Order> listNew, Map<Id, Order> mapNew){
		system.debug('******INSIDE RMS_backOfficeChecklistManager/createBackOfficeChecksOnOrderCreation');
		
		
		
		list<Id> relatedAccountIds = new list<Id>();
    	for(Order o : listNew){
    		relatedAccountIds.add(o.AccountId);
    	} 
    	list<Account> relatedAccounts = [SELECT BillingStreet,
								    			BillingCity,
								    			BillingState,
								    			BillingStateCode,
								    			BillingPostalCode, 
								    			BillingCountry,
								    			BillingCountryCode,
								    			Store_Location__c
								    			
								    			FROM Account WHERE Id IN :relatedAccountIds];
		map<id, Account> accountIdToAccountMap = new map<id, Account>();		
    	list<id> dwellingStoreLocationIds = new list<id>();
    	for(Account a : relatedAccounts){
    		accountIdToAccountMap.put(a.id, a);
    		dwellingStoreLocationIds.add(a.Store_Location__c);
    	}


	
    	//GETTING ALL STORE CONFIGS FOR RELATED DWELLINGS
	    map<Id, Store_Configuration__c> accountIdtoStoreConfigMap = UtilityMethods.mapStoreConfigs(dwellingStoreLocationIds);

		list<Id> storeConfigIdList = new list<id>();
    	for(Store_Configuration__c sc : accountIdtoStoreConfigMap.values()){
    		storeConfigIdList.add(sc.id);
    	}

    	
    	SObjectType xBOC = Schema.getGlobalDescribe().get('Back_Office_Checklist_Configuration__c');
		map<String,Schema.SObjectField> bocFieldsMap = xBOC.getDescribe().fields.getMap();
	    
	    String bocQuery = 'SELECT ';
	    
		for(String bocField : bocFieldsMap.KeySet()){
			bocQuery = bocQuery + bocField + ', ';
	    }
	    
	    bocQuery = bocQuery.substring(0,bocQuery.length()-2);
	    bocQuery = bocQuery + ' FROM Back_Office_Checklist_Configuration__c WHERE Store_Configuration__c IN :storeConfigIdList';
	    
	    list<Back_Office_Checklist_Configuration__c> backOfficeCheckList = Database.query(bocQuery);
    
    
    
    	map<id, Back_Office_Checklist_Configuration__c> storeConfigIdToBackOfficeChecklistMap = new map<id, Back_Office_Checklist_Configuration__c>();
    	for(Back_Office_Checklist_Configuration__c boc : backOfficeCheckList){
    		storeConfigIdToBackOfficeChecklistMap.put(boc.Store_Configuration__c, boc);
    	}
    	
    	
		list<Back_Office_Check__c> checksToAdd = new list<Back_Office_Check__c>();
		for(Order ord : listNew){
			
			//GETTING BACK OFFICE CONFIG FOR CURRENT ORDER
			Account orderDwelling = accountIdToAccountMap.get(ord.AccountId);
			
			//IF THE DWELLING DOESN'T HAVE A STORE SKIP REST OF LOGIC
			if(orderDwelling.Store_Location__c != null){
				Store_Configuration__c storeConfig = accountIdtoStoreConfigMap.get(orderDwelling.Store_Location__c);
		    	
		    	//IF THE STORE CONFIG IS NOT SET SKIP REST OF LOGIC
		    	if(storeConfig.id != null){
			    	Back_Office_Checklist_Configuration__c boChecklist = storeConfigIdToBackOfficeChecklistMap.get(storeConfig.id);
			    	
			    	system.debug('ADS boChecklist :'+boChecklist);
			    	
			    	//FOR EACH FIELD ON BACK OFFICE CHECKLIST CONFIG CREATES A CHECK ON THE ORDER.
			    	for(String bocField :bocFieldsMap.KeySet()){
			    		if(boChecklist.get(bocField) != null && boChecklist.get(bocField) == true){
			    			String checkName = bocFieldsMap.get(bocField).getDescribe().getLabel();
			    			Back_Office_Check__c boc = new Back_Office_Check__c(Name= checkName, Order__c = ord.Id);
				    		checksToAdd.add(boc);
			    		}	
			    	}
			
					insert checksToAdd;
		    	}
			}
		}
	}//END OF createBackOfficeChecksOnOrderCreation METHOD
	
	
}// EOF