RbA Build/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Store_Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The store location that this dwelling is related</description>
        <inlineHelpText>The store location that this dwelling is related</inlineHelpText>
        <label>Store Location</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>The account must be of type &quot;Store&quot;</errorMessage>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Store</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Dwellings</relationshipLabel>
        <relationshipName>StoreLocation</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Store</fullName>
        <active>true</active>
        <description>Used to track and store data releated to Retail Locations both CORO and ARO</description>
        <label>Store</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

RbA Build/src/objects/Labor__c.object
<CustomObject>
    <description>Used for logging Labor against a Work Order</description>
    <fields>
        <fullName>Hours_Applied__c</fullName>
        <inlineHelpText>Hours Applied</inlineHelpText>
        <label>Hours Applied</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Internal_Cost__c</fullName>
        <description>The internal cost calculated by taking the hours applied times the hourly rate.</description>
        <formula>Hours_Applied__c *  Hourly_Rate__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>The internal cost calculated by taking the hours applied times the hourly rate.</inlineHelpText>
        <label>Internal Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Store_Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Store Location</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$User.Store_Location_Text__c</field>
                <operation>contains</operation>
                <valueField>Account.Name</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Labor</relationshipLabel>
        <relationshipName>Labor</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Labor</label>
    <nameField>
        <displayFormat>Labor Record # - {00}</displayFormat>
        <label>Labor Record #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Labor</pluralLabel>
    <recordTypes>
        <fullName>Labor</fullName>
        <active>true</active>
        <description>Used to track Labor against the Work Order</description>
        <label>Labor</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

RbA Build/src/objects/RMS_Settings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>A name value list of RMS settings</description>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>RMS Settings</label>
</CustomObject>

RbA Build/src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Store_Location__c</fullName>
        <label>Store Location</label>
        <picklist>
            <picklistValues>
                <fullName>77 - Twin Cities, MN</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

RbA Build/src/classes/LaborTriggerHandlerTest.cls
/*******************************************************//**

@class	  LaborTriggerHandlerTest

@brief	 Test class for Handler for the labor trigger

@author	 Creston Kuenzi (Slalom.CDK)

@version	2016-6-23  Slalom.CDK
	Created

@see		LaborTriggerHandler

@copyright  (c)2016 Slalom.  All Rights Reserved.
			Unauthorized use is prohibited.

***********************************************************/
@isTest
private class LaborTriggerHandlerTest {

	// Tests the entire trigger by inserting updating user records
	static testMethod void testTrigger() {
		// Turn off the financial trigger to avoid SOQL limits in test class
		RMS_Settings__c turnOffFinancialTrigger = new RMS_Settings__c(Name='Turn Financial Transactions Off', Value__c = 'Yes');
		insert turnOffFinancialTrigger;

		// Set up the test utilities
		TestUtilityMethods tUtil = new TestUtilityMethods();
		tUtil.setUpConfigs();

		// Find the store account record
		Account store = [SELECT Id FROM Account Where Name = '77 - Twin Cities, MN'];

		// Create a labor record
		Labor__c labRecord = new Labor__c(Store_Location__c = store.Id, Hours_Applied__c = 5);		
		Test.startTest();

		// Insert the labor record
		insert labRecord;
		
		// Retrieve the inserted labor record and verify the internal cost has been calculated correctly
		Labor__c resultInsert = [SELECT Id, Internal_Cost__c FROM Labor__c Where Id = : labRecord.Id];

		// The result should be 250 because the hourly rate is set to 50 in the 
		// setupconfigs and the hours applied is 5
		System.AssertEquals(250, resultInsert.Internal_Cost__c);


		Test.stopTest();
	}
}