RbA Build/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Store_Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The store location that this dwelling is related</description>
        <inlineHelpText>The store location that this dwelling is related</inlineHelpText>
        <label>Store Location</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>The account must be of type &quot;Store&quot;</errorMessage>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Store</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Dwellings</relationshipLabel>
        <relationshipName>StoreLocation</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Store</fullName>
        <active>true</active>
        <description>Used to track and store data releated to Retail Locations both CORO and ARO</description>
        <label>Store</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

RbA Build/src/objects/Labor__c.object
<CustomObject>
    <description>Used for logging Labor against a Work Order</description>
    <fields>
        <fullName>Related_Work_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related Work Order</label>
        <referenceTo>RbA_Work_Order__c</referenceTo>
        <relationshipLabel>Labor</relationshipLabel>
        <relationshipName>Labor1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Store_Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Store Location</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$User.Store_Location_Text__c</field>
                <operation>contains</operation>
                <valueField>Account.Name</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Labor</relationshipLabel>
        <relationshipName>Labor</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Labor</label>
    <nameField>
        <displayFormat>Labor Record # - {00}</displayFormat>
        <label>Labor Record #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Labor</pluralLabel>
    <recordTypes>
        <fullName>Labor</fullName>
        <active>true</active>
        <description>Used to track Labor against the Work Order</description>
        <label>Labor</label>
    </recordTypes>
    <recordTypes>
        <fullName>Misc_Reimbursement</fullName>
        <active>true</active>
        <description>Used to enter miscellaneous reimbursements to contractor. This was formerly called misc sub payments.</description>
        <label>Misc Reimbursement</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

RbA Build/src/objects/Order.object
<CustomObject>
    <fields>
        <fullName>Labor__c</fullName>
        <label>Labor</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Sold_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>When the Sold Order is Job In Progress, the Service Order must be related to the Sold Order.</inlineHelpText>
        <label>Sold Order</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>$Source.AccountId</field>
                <operation>equals</operation>
                <valueField>Order.AccountId</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Order</referenceTo>
        <relationshipLabel>Service Orders</relationshipLabel>
        <relationshipName>Sold_Order</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Store_Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This order is related to this store location.</description>
        <inlineHelpText>This order is related to this store location.</inlineHelpText>
        <label>Store Location</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Orders (Store Location)</relationshipLabel>
        <relationshipName>Orders1</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

RbA Build/src/objects/RbA_Work_Order__c.object
<CustomObject>
    <description>Custom Object used to track Work Orders related to Orders.</description>
    <fields>
        <fullName>Sold_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sold Order</label>
        <referenceTo>Order</referenceTo>
        <relationshipLabel>Work Orders</relationshipLabel>
        <relationshipName>Work_Orders1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>RbA Work Order</label>
    <nameField>
        <displayFormat>WO-{00000000}</displayFormat>
        <label>Work Order #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RbA Work Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

RbA Build/src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Store_Location__c</fullName>
        <label>Store Location</label>
        <picklist>
            <picklistValues>
                <fullName>77 - Twin Cities, MN</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

RbA Build/src/classes/RMS_newMiscLaborExtension.cls
/*******************************************************//**

@class	  RMS_newMiscLaborExtension

@brief	  Extension for redirecting the user when clicking the New Misc Labor button

	Redirects the user directly to a labor or misc reimbursement page depending on if it's linked
	to a work order, bypassing the record type selector

@author	 Creston Kuenzi (Slalom.CDK)

@version	2015-2-12  Slalom.CDK
	Created

@see		RMS_newMiscLaborExtensionTest

@copyright  (c)2015 Slalom.  All Rights Reserved.
			Unauthorized use is prohibited.

***********************************************************/

public with sharing class RMS_newMiscLaborExtension {

	/******* Set up Standard Controller for Labor__c  *****************/
	private final Labor__c theLabor;
	
	public RMS_newMiscLaborExtension(ApexPages.StandardSetController stdController) {
		this.theLabor = (Labor__c)stdController.getRecord();
		if (this.theLabor == null)
			this.theLabor = new Labor__c(); 
	}

	public String testStoreLocation;

	/******* redirect method  *****************/
	public PageReference redirect() {

		// Retrieve the key prefix for the labor object and insert it into the page reference
		Schema.DescribeSObjectResult r = Labor__c.sObjectType.getDescribe();
		String keyPrefix = r.getKeyPrefix();        
		PageReference p = new PageReference('/' +keyPrefix +'/e');

		// Get all of the url parameters from the current url and put them in the new url
        Map<String, String> m = p.getParameters();
        m.putAll(ApexPages.currentPage().getParameters());

		// If there is a work order, redirect to labor, otherwise redirect to misc reimbursement
		if (theLabor.Related_Work_Order__c == null) {
        	m.put('RecordType', UtilityMethods.RecordTypeFor('Labor__c', 'Misc_Reimbursement'));

			// If a test is running just set the store name, otherwise get it from the current user
			String storeLocationName = (Test.isRunningTest()) ? 	testStoreLocation :
																	[SELECT Store_Location__c FROM User WHERE Id =: UserInfo.getUserId()].Store_Location__c;


			if (String.isBlank(storeLocationName)) {
				ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, RMS_errorMessages.STORE_LOCATION_IS_BLANK_USER)); //
				return null;
			}
			
			for (Account thisStore : [SELECT Id, Name FROM Account WHERE Name =: storeLocationName]) {
        			// TODO:   This parameter will need to be updated after pushing to build and production
         			m.put('CF00N6100000Br7TE', thisStore.Name);	
         			m.put('CF00N6100000Br7TE_lkid', thisStore.Id);	
			}
			
			if (m.get('CF00N6100000Br7TE') == null) {
				ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, RMS_errorMessages.STORE_LOCATION_IS_BLANK_USER)); //
				return null;
			}

		} else {
        	m.put('RecordType', UtilityMethods.RecordTypeFor('Labor__c', 'Labor'));			

/*        	for (RbA_Work_Order__c theWorkOrder : [SELECT Sold_Order__r.Store_Location__r.Name, Sold_Order__r.Store_Location__c FROM RbA_Work_Order__c WHERE Id =: theLabor.Related_Work_Order__c]) {
        		if (theWorkOrder.Sold_Order__r.Store_Location__c == null) {
					ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, RMS_errorMessages.STORE_LOCATION_IS_BLANK_LABOR)); //
					return null;
        		} 
        		else { 
        			// TODO:   This parameter will need to be updated after pushing to build and production
         			m.put('CF00N3B000000On7g', theWorkOrder.Sold_Order__r.Store_Location__r.Name);	
         			m.put('CF00N3B000000On7g_lkid', theWorkOrder.Sold_Order__r.Store_Location__c);	
        		}
        	}		*/
		}
        m.put('nooverride', '1');
        return p;
	}
	
}