RbA Build/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Building_Permit__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The Building Permit is populated in Code
Matching in the Municipalities table.
Matching criteria Address City and Zip code, match is found in the Municipality Match object</inlineHelpText>
        <label>Building Permit</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>You must select a Building record. If the record for you are for isn&apos;t in the system, please contact your manager to have it created.</errorMessage>
            <filterItems>
                <field>Municipality__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Permit</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Municipality__c</referenceTo>
        <relationshipLabel>Building Permit Dwellings</relationshipLabel>
        <relationshipName>Accounts2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Store_Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The store location that this dwelling is related</description>
        <inlineHelpText>The store location that this dwelling is related</inlineHelpText>
        <label>Store Location</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>The account must be of type &quot;Store&quot;</errorMessage>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Store</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Dwellings</relationshipLabel>
        <relationshipName>StoreLocation</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Dwelling</fullName>
        <active>true</active>
        <description>Used to support Dwelling</description>
        <label>Dwelling</label>
    </recordTypes>
    <recordTypes>
        <fullName>Store</fullName>
        <active>true</active>
        <description>Used to track and store data releated to Retail Locations both CORO and ARO</description>
        <label>Store</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

RbA Build/src/objects/Back_Office_Check__c.object
<CustomObject>
    <description>Junction Object between the Back Office Checklist Configurations and Order.  Keeps the history of items that need to checked in order for the order move through the process.</description>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <referenceTo>Order</referenceTo>
        <relationshipLabel>Back Office Checks</relationshipLabel>
        <relationshipName>Back_Office_Checks</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Back Office Check</label>
    <nameField>
        <label>Back Office Check Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Back Office Checks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

RbA Build/src/objects/Back_Office_Checklist_Configuration__c.object
<CustomObject>
    <description>Used for tracking important signed documents</description>
    <fields>
        <fullName>Contract_Signed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Contract Signed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Lien_Rights_Signed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Lien Rights Signed</label>
        <type>Checkbox</type>
    </fields>
    <label>Back Office Checklist Configuration</label>
    <nameField>
        <displayFormat>BOC# - {00}</displayFormat>
        <label>Back Office Checklist Record #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Back Office Checklist Configurations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

RbA Build/src/objects/Municipality__c.object
<CustomObject>
    <description>Holds Municipality information that will help with HOA, Historical and Permitting details.</description>
    <label>Municipality</label>
    <nameField>
        <label>Agency Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Municipalities</pluralLabel>
    <recordTypes>
        <fullName>Permit</fullName>
        <active>true</active>
        <description>Hold information for Building Permits (not Building)</description>
        <label>Permit</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

RbA Build/src/objects/Order.object
<CustomObject>
    <fields>
        <fullName>Store_Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This order is related to this store location.</description>
        <inlineHelpText>This order is related to this store location.</inlineHelpText>
        <label>Store Location</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Orders (Store Location)</relationshipLabel>
        <relationshipName>Orders1</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

RbA Build/src/classes/RMS_backOfficeChecklistManagerTest.cls
@isTest
public with sharing class RMS_backOfficeChecklistManagerTest {
	
	
	
	static testmethod void matchingBackOfficeChecks(){
		TestUtilityMethods utility = new TestUtilityMethods();
		utility.setUpConfigs();

		id dwellingRT = UtilityMethods.retrieveRecordTypeId('Dwelling', 'Account');
		id muniPermitRT = UtilityMethods.retrieveRecordTypeId('Permit', 'Municipality__c');
		
		Account store = [SELECT id FROM Account WHERE Name ='77 - Twin Cities, MN'];
		
		Account newDwelling = new Account(Name='test1', Store_Location__c = store.id, RecordTypeId = dwellingRT, BillingPostalCode = '55429' , BillingCity = 'Blaine' );
		insert newDwelling;
		
		Order ord1 = new Order( AccountId = newDwelling.id ,
								Status = 'Draft', 
								EffectiveDate = Date.Today()
								);
		insert ord1;
		
		list<Back_Office_Check__c> checks = [SELECT Id, Order__c FROM Back_Office_Check__c WHERE Order__c = :ord1.id];
		
		System.assertEquals(checks.size(), 2);

	} 
	
	static testmethod void notMatchingBackOfficeChecks(){
		TestUtilityMethods utility = new TestUtilityMethods();
		utility.setUpConfigs();

		id dwellingRT = UtilityMethods.retrieveRecordTypeId('Dwelling', 'Account');
		id muniPermitRT = UtilityMethods.retrieveRecordTypeId('Permit', 'Municipality__c');
		
		Account store = [SELECT id FROM Account WHERE Name ='77 - Twin Cities, MN'];

		Account newDwelling = new Account(Name='test1', Store_Location__c = store.id, RecordTypeId = dwellingRT, BillingPostalCode = '55429' , BillingCity = 'Blaine' );
		insert newDwelling;
		
		
		Account dwelling = [SELECT Id, Building_Permit__c FROM Account WHERE Id = :newDwelling.id];
		
		Back_Office_Checklist_Configuration__c bocc = [SELECT id, Contract_Signed__c, Lien_Rights_Signed__c FROM Back_Office_Checklist_Configuration__c];
		
		bocc.Contract_Signed__c = false;
		bocc.Lien_Rights_Signed__c = false;
		update bocc;
		
		Order ord1 = new Order( AccountId = newDwelling.id ,
								Status = 'Draft', 
								EffectiveDate = Date.Today()
								);
		insert ord1;
		
		list<Back_Office_Check__c> checks = [SELECT Id, Order__c FROM Back_Office_Check__c WHERE Order__c = :ord1.id];
		
		System.assertEquals(checks.size(), 0);
	}


}