RbA Build/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Building_Permit__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The Building Permit is populated in Code
Matching in the Municipalities table.
Matching criteria Address City and Zip code, match is found in the Municipality Match object</inlineHelpText>
        <label>Building Permit</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>You must select a Building record. If the record for you are for isn&apos;t in the system, please contact your manager to have it created.</errorMessage>
            <filterItems>
                <field>Municipality__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Permit</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Municipality__c</referenceTo>
        <relationshipLabel>Building Permit Dwellings</relationshipLabel>
        <relationshipName>Accounts2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>HOA__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Is this Dwelling part of an HOA?</inlineHelpText>
        <label>HOA</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>You must select an HOA record.  If the record for you are for isn&apos;t in the system, please contact your manager to have it created.</errorMessage>
            <filterItems>
                <field>Municipality__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>HOA</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Municipality__c</referenceTo>
        <relationshipLabel>HOA Dwellings</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Historical__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Is this Dwelling in a Historical District?</inlineHelpText>
        <label>Historical</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>You must select a Historical record. If the record you are for is not in the system, please contact your manager to have it created.</errorMessage>
            <filterItems>
                <field>Municipality__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Historical</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Municipality__c</referenceTo>
        <relationshipLabel>Historical Dwellings</relationshipLabel>
        <relationshipName>Accounts1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Store_Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The store location that this dwelling is related</description>
        <inlineHelpText>The store location that this dwelling is related</inlineHelpText>
        <label>Store Location</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>The account must be of type &quot;Store&quot;</errorMessage>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Store</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Dwellings</relationshipLabel>
        <relationshipName>StoreLocation</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Dwelling</fullName>
        <active>true</active>
        <description>Used to support Dwelling</description>
        <label>Dwelling</label>
    </recordTypes>
    <recordTypes>
        <fullName>Store</fullName>
        <active>true</active>
        <description>Used to track and store data releated to Retail Locations both CORO and ARO</description>
        <label>Store</label>
    </recordTypes>
    <recordTypes>
        <fullName>Vendor</fullName>
        <active>true</active>
        <description>Used to track Vendors</description>
        <label>Vendor</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

RbA Build/src/objects/Municipality__c.object
<CustomObject>
    <description>Holds Municipality information that will help with HOA, Historical and Permitting details.</description>
    <fields>
        <fullName>City_Township__c</fullName>
        <label>City/Township</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>For_Retail_Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>What Retail Location is this for?</inlineHelpText>
        <label>For Retail Location</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Store</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Municipalities</relationshipLabel>
        <relationshipName>Municipalities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zip_Code__c</fullName>
        <label>Zip Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Municipality</label>
    <nameField>
        <label>Agency Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Municipalities</pluralLabel>
    <recordTypes>
        <fullName>HOA</fullName>
        <active>true</active>
        <description>Homeowner Association Details</description>
        <label>HOA</label>
    </recordTypes>
    <recordTypes>
        <fullName>Historical</fullName>
        <active>true</active>
        <description>Holds information on Historial requirements</description>
        <label>Historical</label>
    </recordTypes>
    <recordTypes>
        <fullName>Permit</fullName>
        <active>true</active>
        <description>Hold information for Building Permits (not Building)</description>
        <label>Permit</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

RbA Build/src/objects/Municipality_Match__c.object
<CustomObject>
    <fields>
        <fullName>Agency_Name__c</fullName>
        <label>Agency Name</label>
        <referenceTo>Municipality__c</referenceTo>
        <relationshipLabel>Municipalities Match</relationshipLabel>
        <relationshipName>Municipalities_Match</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>City_Township__c</fullName>
        <label>City/Township</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zip_Code__c</fullName>
        <label>Zip Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Municipality Match</label>
    <nameField>
        <displayFormat>MM-{00}</displayFormat>
        <label>Municipality Match Record Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Municipalities Match</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

RbA Build/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Store_Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Store Location</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>The account must be of type &quot;Store&quot;.</errorMessage>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Store</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Store Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

RbA Build/src/objects/Order.object
<CustomObject>
    <fields>
        <fullName>Sold_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>When the Sold Order is Job In Progress, the Service Order must be related to the Sold Order.</inlineHelpText>
        <label>Sold Order</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>$Source.AccountId</field>
                <operation>equals</operation>
                <valueField>Order.AccountId</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Order</referenceTo>
        <relationshipLabel>Service Orders</relationshipLabel>
        <relationshipName>Sold_Order</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Store_Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This order is related to this store location.</description>
        <inlineHelpText>This order is related to this store location.</inlineHelpText>
        <label>Store Location</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Orders (Store Location)</relationshipLabel>
        <relationshipName>Orders1</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

RbA Build/src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Vendor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Vendor</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>Products</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

RbA Build/src/objects/RbA_Work_Order__c.object
<CustomObject>
    <description>Custom Object used to track Work Orders related to Orders.</description>
    <fields>
        <fullName>Municipality__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>What Municipality does this Dwelling fall into?</inlineHelpText>
        <label>Municipality</label>
        <referenceTo>Municipality__c</referenceTo>
        <relationshipLabel>Permit Work Orders</relationshipLabel>
        <relationshipName>Work_Orders_Permits1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Related Opportunity</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Work Orders</relationshipLabel>
        <relationshipName>Work_Orders1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Order_Type__c</fullName>
        <description>Type of service order: Field Service, Depot repair etc.</description>
        <inlineHelpText>Type of service order: Field Service, Depot repair etc.</inlineHelpText>
        <label>Order Type</label>
        <picklist>
            <picklistValues>
                <fullName>Tech Measure</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Install</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Service</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HOA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Historical</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Building Permit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Paint/Stain</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LSWP</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Sold_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sold Order</label>
        <referenceTo>Order</referenceTo>
        <relationshipLabel>Work Orders</relationshipLabel>
        <relationshipName>Work_Orders1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <description>“State” part of the work order location</description>
        <inlineHelpText>“State” part of the work order location</inlineHelpText>
        <label>State</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vendor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Vendor preforming the work.</inlineHelpText>
        <label>Vendor</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>equals</operation>
                <value>Vendor</value>
            </filterItems>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>equals</operation>
                <value>Contractor</value>
            </filterItems>
            <infoMessage>The Vendor must be associated with the Store the Order is associated to.</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Work Orders (LSWP)</relationshipLabel>
        <relationshipName>Work_Orders2</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>RbA Work Order</label>
    <nameField>
        <displayFormat>WO-{00000000}</displayFormat>
        <label>Work Order #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RbA Work Orders</pluralLabel>
    <recordTypes>
        <fullName>Permit</fullName>
        <active>true</active>
        <description>Holds Building Permit Details</description>
        <label>Permit</label>
    </recordTypes>
    <recordTypes>
        <fullName>Visit</fullName>
        <active>true</active>
        <description>Hold Work Order details that can be have a scheduled visit to the home</description>
        <label>Visit</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

RbA Build/src/objects/RMS_Queue_Settings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>Settings that dictate what queue objects will go in.</description>
    <label>RMS Queue Settings</label>
</CustomObject>

RbA Build/src/classes/RMS_WorkOrderCreationManagerTest.cls
@isTest
public with sharing class RMS_WorkOrderCreationManagerTest {
		
	static testMethod void testWorkOrderMovingFromOppOnCreationOfWorkOrder(){
		TestUtilityMethods utility = new TestUtilityMethods();
		utility.setUpConfigs();

		id dwellingRT = UtilityMethods.retrieveRecordTypeId('Dwelling', 'Account');
		id muniPermitRT = UtilityMethods.retrieveRecordTypeId('Permit', 'Municipality__c');
		
		Account store = [SELECT id FROM Account WHERE Name ='77 - Twin Cities, MN'];
		
		Municipality__c muni1 = utility.createMunicipality(store.id, muniPermitRT);
		insert muni1;
		
		Municipality__c muni2 = utility.createMunicipality(store.id, muniPermitRT);
		insert muni2;
		
		Municipality_Match__c mm1 = utility.createMunicipalityMatch(muni1.id, '55429', 'Blaine');
		insert mm1;
		
		Municipality_Match__c mm2 = utility.createMunicipalityMatch(muni1.id, '55444', 'Blaine');
		insert mm2;

		Account newDwelling = new Account(Name='test1', Store_Location__c = store.id, RecordTypeId = dwellingRT, BillingPostalCode = '55429' , BillingCity = 'Blaine' );
		insert newDwelling;
		
		//CREATE OPPORTUNITY
		Opportunity opp1 = new Opportunity(Name='Opp1', AccountId=newDwelling.id, StageName = 'New', CloseDate = Date.today().addYears(1) );
		
		//CREATE A WORKORDER ON OPP
		Id serviceOrderVisitRecordTypeId = UtilityMethods.retrieveRecordTypeId('Visit', 'RbA_Work_Order__c');
		RbA_Work_Order__c workOrderOnOpp = new RbA_Work_Order__c(  	RecordTypeId = serviceOrderVisitRecordTypeId,  
																				Order_Type__c = 'Tech Measure',
															                    Opportunity__c = opp1.id
															                    );
		
		//CREATE AN ORDER RELATED TO OPPORTUNITY
		Order ord1 = new Order( AccountId = newDwelling.id ,
								Status = 'Draft', 
								OpportunityId = opp1.id,
								EffectiveDate = Date.Today(),
								Pricebook2Id = Test.getStandardPricebookId()
								);
		insert ord1;
		
		
		//CHECK NO WORK ORDERS CREATED AND MOVED WORK ORDER THAT IS ON OPP TO ORDER
		list<RbA_Work_Order__c> workOrdersOnOrder = [SELECT Id, Opportunity__c FROM RbA_Work_Order__c WHERE Sold_Order__c = :ord1.id];
		
		System.assertEquals(workOrdersOnOrder.size() , 1);
		System.assertEquals(workOrdersOnOrder[0].Opportunity__c, opp1.id);
	}
	
	
	
	
	
	static testMethod void testWorkOrderCreationOnCreationOfWorkOrder(){
		TestUtilityMethods utility = new TestUtilityMethods();
		utility.setUpConfigs();

		id dwellingRT = UtilityMethods.retrieveRecordTypeId('Dwelling', 'Account');
		id muniPermitRT = UtilityMethods.retrieveRecordTypeId('Permit', 'Municipality__c');
		
		Account store = [SELECT id FROM Account WHERE Name ='77 - Twin Cities, MN'];
		
		Municipality__c muni1 = utility.createMunicipality(store.id, muniPermitRT);
		insert muni1;
		
		Municipality__c muni2 = utility.createMunicipality(store.id, muniPermitRT);
		insert muni2;
		
		Municipality_Match__c mm1 = utility.createMunicipalityMatch(muni1.id, '55429', 'Blaine');
		insert mm1;
		
		Municipality_Match__c mm2 = utility.createMunicipalityMatch(muni1.id, '55444', 'Blaine');
		insert mm2;

		Account newDwelling = new Account(Name='test1', Store_Location__c = store.id, RecordTypeId = dwellingRT, BillingPostalCode = '55429' , BillingCity = 'Blaine' );
		insert newDwelling;

		//CREATE AN ORDER RELATED TO OPPORTUNITY
		Order ord1 = new Order( AccountId = newDwelling.id ,
								Status = 'Draft', 
								EffectiveDate = Date.Today(),
								Pricebook2Id = Test.getStandardPricebookId()
								);
		insert ord1;

		//CHECK NO WORK ORDERS CREATED AND MOVED WORK ORDER THAT IS ON OPP TO ORDER
		list<RbA_Work_Order__c> workOrdersOnOrder = [SELECT Id, Sold_Order__c FROM RbA_Work_Order__c WHERE Sold_Order__c = :ord1.id];
		
		System.assertEquals(workOrdersOnOrder.size() , 1);
		System.assertEquals(workOrdersOnOrder[0].Sold_Order__c, ord1.id);
	}
		
		
	
	
	
	static testmethod void testCreationOfWorkOrdersOnOrderActivation(){ 
		TestUtilityMethods utilities = new TestUtilityMethods();
		utilities.setUpConfigs();
		
		Account store = [SELECT Id FROM account WHERE Name ='77 - Twin Cities, MN'];
		
		//TODO TestutilityMethods
		Municipality__c muniHOA = new Municipality__c(Name ='HOAMuni', RecordTypeId = UtilityMethods.retrieveRecordTypeId('HOA', 'Municipality__c'), For_Retail_Location__c = store.id );
		insert muniHOA;
		Municipality__c muniHistorical = new Municipality__c(Name ='HistoricalMuni', RecordTypeId = UtilityMethods.retrieveRecordTypeId('Historical', 'Municipality__c'), For_Retail_Location__c = store.id );
		insert muniHistorical;
		Municipality__c muniPermit = new Municipality__c(Name ='PermitMuni', RecordTypeId = UtilityMethods.retrieveRecordTypeId('Permit', 'Municipality__c'), For_Retail_Location__c = store.id );
		insert muniPermit;
		
		Municipality_Match__c muniMatchHOA = new Municipality_Match__c(City_Township__c= 'Sunshine1', State__c = 'Minnesota', Zip_Code__c = '55449', Agency_Name__c = muniHOA.id );
		insert muniMatchHOA;
		Municipality_Match__c muniMatchHistorical = new Municipality_Match__c(City_Township__c= 'Sunshine1', State__c = 'Minnesota', Zip_Code__c = '55449', Agency_Name__c = muniHistorical.id );
		insert muniMatchHistorical;
		Municipality_Match__c muniMatchPermit = new Municipality_Match__c(City_Township__c= 'Sunshine', State__c = 'Minnesota', Zip_Code__c = '55449', Agency_Name__c = muniPermit.id );
		insert muniMatchPermit;

		//Creating Account (Needed for RMS_Queue_Settings__c)
		Account account1 =  new Account(Name = 'Test Account1',
	        AccountNumber = '1234567890',
	        Phone = '(763) 555-2000',
		 	Store_Location__c = store.id, 
			HOA__c = muniHOA.id, 
			Historical__c = muniHistorical.id, 
			Building_Permit__c = muniPermit.id,
			BillingStreet = '123 happy Ln',
			BillingCity = 'Sunshine',
			BillingState = 'Minnesota',
			BillingStateCode = 'MN',
			BillingPostalCode = '55449', 
			BillingCountry = 'United States',
			RecordTypeId = UtilityMethods.retrieveRecordTypeId('Dwelling', 'Account') ); 
	 	insert account1;

		Order ord2 = new Order( AccountId = account1.id ,
								Status = 'Draft', 
								EffectiveDate = Date.Today(),
								Pricebook2Id = Test.getStandardPricebookId()
								);
		insert ord2;
		
		Account vend1 = utilities.createVendorAccount('Vendor Account 1');
		insert vend1;

		Pricebook2 pricebook1 =  utilities.createPricebook2Name('Standard Price Book');
		insert pricebook1;

		Product2 product1 = new Product2(
			Name='Test Product',
			Vendor__c = vend1.id
		);

		insert product1;
		
		PricebookEntry pricebookEntry1 = utilities.createPricebookEntry(Test.getStandardPricebookId(), product1.id);
		insert pricebookEntry1;
		
		OrderItem orderItem1 = new OrderItem(OrderId = ord2.id, PricebookentryId = pricebookEntry1.Id, Quantity = 2, UnitPrice = 100 );
		insert orderItem1;	

		list<RbA_Work_Order__c> relatedWorkOrders = [SELECT id, Order_Type__c FROM RbA_Work_Order__c WHERE Sold_Order__c = :ord2.id];
		system.debug('ads remove relatedWorkOrders1: '+relatedWorkOrders);
		ord2.Status = 'Activated';
		update ord2;
		
		relatedWorkOrders = [SELECT id, Order_Type__c FROM RbA_Work_Order__c WHERE Sold_Order__c = :ord2.id];
		System.assertEquals(5, relatedWorkOrders.size());
		
		ord2.Status = 'Draft';
		update ord2;
		
		delete ord2;
	}



}