RbA Build/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Active_Store_Configuration__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>currently active store configuration</description>
        <label>Active Store Configuration</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Store_Configuration__c.Store__c</field>
                <operation>equals</operation>
                <valueField>$Source.Id</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Store_Configuration__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Check if this account is active</description>
        <inlineHelpText>Check if this account is active</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <recordTypes>
        <fullName>Dwelling</fullName>
        <active>true</active>
        <description>Used to support Dwelling</description>
        <label>Dwelling</label>
    </recordTypes>
    <recordTypes>
        <fullName>Store</fullName>
        <active>true</active>
        <description>Used to track and store data releated to Retail Locations both CORO and ARO</description>
        <label>Store</label>
    </recordTypes>
    <recordTypes>
        <fullName>Vendor</fullName>
        <active>true</active>
        <description>Used to track Vendors</description>
        <label>Vendor</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

RbA Build/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Discount_Amount__c</fullName>
        <description>The rollup of discounts applied to the opportunity</description>
        <inlineHelpText>The rollup of discounts applied to the opportunity</inlineHelpText>
        <label>Discount Amount</label>
        <summarizedField>Opportunity_Discount__c.Discount_Amount__c</summarizedField>
        <summaryFilterItems>
            <field>Opportunity_Discount__c.Status__c</field>
            <operation>notEqual</operation>
            <value>Cancelled</value>
        </summaryFilterItems>
        <summaryForeignKey>Opportunity_Discount__c.Opportunity__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

RbA Build/src/objects/Order.object
<CustomObject>
    <fields>
        <fullName>Discount_Amount__c</fullName>
        <description>A roll-up sum of all discounts applied to this order (see the order discount related list).</description>
        <inlineHelpText>A roll-up sum of all discounts applied to this order (see the order discount related list).</inlineHelpText>
        <label>Discount Amount</label>
        <summarizedField>Order_Discount__c.Discount_Amount__c</summarizedField>
        <summaryFilterItems>
            <field>Order_Discount__c.Status__c</field>
            <operation>equals</operation>
            <value>Applied</value>
        </summaryFilterItems>
        <summaryForeignKey>Order_Discount__c.Order__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>rSuite_Id__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>an identifier used by rSuite to help them manage jobs in the mobile apps - meets RFC 4122 version 4</description>
        <externalId>true</externalId>
        <inlineHelpText>an identifier used by rSuite to help them manage jobs in the mobile apps</inlineHelpText>
        <label>rSuite Id</label>
        <length>36</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

RbA Build/src/objects/Order_Discount__c.object
<CustomObject>
    <description>Junction from the discount to the order</description>
    <fields>
        <fullName>Discount_Amount__c</fullName>
        <defaultValue>0</defaultValue>
        <description>The amount in dollars discounted from the order.</description>
        <inlineHelpText>The amount in dollars discounted from the order.</inlineHelpText>
        <label>Discount Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Per_Unit_Discount__c</fullName>
        <description>This field is used by rSuite for custom disounts that are per unit or window or door - its is the custom amount per unit. It is used by rSuite to calculate Discount Amount</description>
        <inlineHelpText>This field is used by rSuite for custom disounts that are per unit or window or door - its is the custom amount per unit. It is used by rSuite to calculate Discount Amount</inlineHelpText>
        <label>Per Unit Discount</label>
        <precision>8</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>The status of the order discount.</description>
        <inlineHelpText>The status of the order discount.</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Applied</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Store_Discount__c</fullName>
        <label>Store Discount</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Store_Discount__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>Store_Discount__c.Store_Configuration__r.Store__c</field>
                <operation>equals</operation>
                <valueField>$Source.Store_Location__c</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Store_Discount__c</referenceTo>
        <relationshipLabel>Order Discounts</relationshipLabel>
        <relationshipName>Order_Discounts</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>rSuite_Id__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>an identifier used by rSuite to help them manage jobs in the mobile apps - meets RFC 4122 version 4</description>
        <externalId>true</externalId>
        <inlineHelpText>an identifier used by rSuite to help them manage jobs in the mobile apps</inlineHelpText>
        <label>rSuite Id</label>
        <length>36</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Order Discount</label>
    <nameField>
        <displayFormat>OD-{00000000}</displayFormat>
        <label>Order Discount Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Discounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

RbA Build/src/objects/OrderItem.object
<CustomObject>
    <fields>
        <fullName>Discount_Amount__c</fullName>
        <description>The discount (in currency) applied to the purchase order (used for AROs)</description>
        <inlineHelpText>The discount (in currency) applied to the purchase order (used for AROs).</inlineHelpText>
        <label>Discount Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>The status of the order line item.</description>
        <inlineHelpText>The status of the order line item.</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Configured</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Verified</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Partially Received</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Received</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

RbA Build/src/objects/Pricebook2.object
<CustomObject>
    <fields>
        <fullName>Store_Configuration__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Links price books to store configuration.  All configuration that are store based are tied to the store configuration for that store.</description>
        <inlineHelpText>Link this to the store configuration for the store this Price Book is being created for.</inlineHelpText>
        <label>Store Configuration</label>
        <referenceTo>Store_Configuration__c</referenceTo>
        <relationshipLabel>Price Books</relationshipLabel>
        <relationshipName>Price_Books</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadSelect</sharingModel>
</CustomObject>

RbA Build/src/objects/Quote.object
<CustomObject>
    <fields>
        <fullName>Discount_Amount__c</fullName>
        <description>The rollup of discounts applied to the quote</description>
        <inlineHelpText>The rollup of discounts applied to the quote</inlineHelpText>
        <label>Discount Amount</label>
        <summarizedField>Quote_Discount__c.Discount_Amount__c</summarizedField>
        <summaryFilterItems>
            <field>Quote_Discount__c.Status__c</field>
            <operation>notEqual</operation>
            <value>Cancelled</value>
        </summaryFilterItems>
        <summaryForeignKey>Quote_Discount__c.Quote__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>isSold__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Checked if it is the primary/sold quote.</description>
        <inlineHelpText>Checked if it is the primary/sold quote.</inlineHelpText>
        <label>Is Sold?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>rSuite_Id__c</fullName>
        <description>an identifier used by rSuite to help them manage jobs in the mobile apps - meets RFC 4122 version 4</description>
        <externalId>true</externalId>
        <inlineHelpText>an identifier used by rSuite to help them manage jobs in the mobile apps</inlineHelpText>
        <label>rSuite Id</label>
        <length>36</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

RbA Build/src/objects/Quote_Discount__c.object
<CustomObject>
    <description>Junction from the discount to the quote</description>
    <fields>
        <fullName>Discount_Amount__c</fullName>
        <defaultValue>0</defaultValue>
        <description>The amount in dollars discounted from the quote.</description>
        <inlineHelpText>The amount in dollars discounted from the quote.</inlineHelpText>
        <label>Discount Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Quote__c</fullName>
        <description>The discount is applied to this quote</description>
        <inlineHelpText>The discount is applied to this quote</inlineHelpText>
        <label>Quote</label>
        <referenceTo>Quote</referenceTo>
        <relationshipName>Discount_Applied</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>The status of the quote discount.</description>
        <inlineHelpText>The status of the quote discount.</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Applied</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Quote Discount</label>
    <nameField>
        <displayFormat>OD-{00000000}</displayFormat>
        <label>Quote Discount Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Discounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

RbA Build/src/objects/RMS_Settings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>A name value list of RMS settings</description>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>RMS Settings</label>
</CustomObject>

RbA Build/src/objects/Store_Discount__c.object
<CustomObject>
    <description>Junctions object to assign discounts to a store through the store configuration</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Store_Configuration__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>The configuration of a store to that the discount will be enabled for</description>
        <inlineHelpText>The configuration of a store to that the discount will be enabled for</inlineHelpText>
        <label>Store Configuration</label>
        <referenceTo>Store_Configuration__c</referenceTo>
        <relationshipLabel>Store Discounts</relationshipLabel>
        <relationshipName>Store_Discounts</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Store Discount</label>
    <nameField>
        <label>Store Discount Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Store Discounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

RbA Build/src/objects/Store_Finance_Program__c.object
<CustomObject>
    <description>Junction object to link a Store to a Finance Program</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Store_Configuration__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Store Configuration</label>
        <referenceTo>Store_Configuration__c</referenceTo>
        <relationshipLabel>Store Finance Programs</relationshipLabel>
        <relationshipName>Store_Finance_Programs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Store Finance Program</label>
    <nameField>
        <label>Store Finance Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Store Finance Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

RbA Build/src/classes/RMS_salesOrderManagerTest.cls
@isTest
public with sharing class RMS_salesOrderManagerTest {

	static testmethod void positiveActivationOfOpportunity(){ 
		// Turn off the financial trigger to avoid SOQL limits in test class
		RMS_Settings__c turnOffFinancialTrigger = new RMS_Settings__c(Name='Turn Financial Transactions Off', Value__c = 'Yes');
		insert turnOffFinancialTrigger;
		
		TestUtilityMethods tUtil = new TestUtilityMethods();
		tUtil.setUpConfigs();
		Profile p = [SELECT Id FROM Profile WHERE Name='RMS-Sales']; 
		// setup configuration stuff
		Datetime tmApptTime = Datetime.now().addDays(5);

		User u = tUtil.createUser(p.id);
		insert u;
		tUtil.createSalesAppt(u.Id, tmApptTime, false, false);
		// build out the container
		Account store1 = [SELECT id, Active_Store_Configuration__c FROM Account Where Name = '77 - Twin Cities, MN'][0];
		Id dwellingRT = UtilityMethods.retrieveRecordTypeId('Dwelling', 'Account');
        Account dwelling = [Select Id from Account where Name != 'RbA' AND Name != 'Unassigned Account' AND RecordTypeId =: dwellingRT];
		Opportunity opp = [select Id, StageName, rSuite_Id__c from Opportunity where AccountId =: dwelling.id];
		opp.StageName = 'Sold';

		// create pricebook
		Pricebook2 pb = tutil.createPricebook2('SATestPB2', store1.Active_Store_Configuration__c);
		insert pb;
		
		// create store finance programs and store discounts
		Store_Discount__c sd = new Store_Discount__c(Name='testStoreDiscount', Active__c = true, Buy_Number__c = 1, Discount_Amount__c = 1, 
			Store_Configuration__c = store1.Active_Store_Configuration__c, Discount_Product__c = 'Unit', 
			RecordTypeId = UtilityMethods.retrieveRecordTypeId('dollar_off', 'Store_Discount__c'));
		insert sd;
		//Store_Finance_Program__c sf = new Store_Finance_Program__c(Name = 'testStoreFinanceProgram', Active__c = true, );
		
		//create existing quote
		Quote quoteToUpdate = tUtil.createQuote(opp.Id, pb.Id);
		quoteToUpdate.isSold__c = true;
		insert quoteToUpdate;
		// create existing quote lines
		QuoteLineItem qli1 = tUtil.createQLIMasterChildProducts(pb.Id, quotetoUpdate.Id);
		insert qli1;
		QuoteLineItem qli2 = tUtil.createQLIMasterChildProducts(pb.Id, quotetoUpdate.Id);
		insert qli2;
		// create the existing quote discount
		Quote_Discount__c qd = new Quote_Discount__c(Discount_Amount__c = 1.0, Per_Unit_Discount__c = 1.0,
			rSuite_Id__c = 'qd-1234-rsuiteId', Status__c = 'Applied', Quote__c = quoteToUpdate.Id, Store_Discount__c = sd.id);
		insert qd;
		System.assert(qd.Id != null);
		
		Test.startTest();
		update opp;
		Test.stopTest();
		List<Order> allOrders = [select Id, Name, OpportunityId from Order];
		System.debug('$$$$$ ' + allOrders);
		List<Order> orders = [SELECT Id FROM Order WHERE OpportunityId = :opp.id];
		List<OrderItem> ioList = [select Id from OrderItem where Order.OpportunityId = :opp.Id];
		List<Order_Discount__c> odList = [select Id, Per_Unit_Discount__c, rSuite_Id__c, Status__c, Store_Discount__c from Order_Discount__c where Order__r.OpportunityId = :opp.Id];
		
		System.assertEquals(orders.size(), 1);
		System.assert(ioList.size() == 2);
		System.assert(odList.size() == 1);
		System.assert(odList[0].Per_Unit_Discount__c == qd.Per_Unit_Discount__c);
		System.assert(odList[0].Store_Discount__c == qd.Store_Discount__c);
		System.assert(odList[0].rSuite_Id__c == qd.rSuite_Id__c);
		
		
	}
	
	
	static testmethod void noDiscountActivationOfOpportunity(){ 
		Profile p = [SELECT Id FROM Profile WHERE Name='Standard User']; 
		TestUtilityMethods utilities = new TestUtilityMethods();
		utilities.setUpConfigs();
		Account store = [SELECT Id FROM account WHERE Name ='77 - Twin Cities, MN'];

		//Creating Account (Needed for RMS_Queue_Settings__c)
		Account account1 =  new Account(Name = 'Test Account1',
	        AccountNumber = '1234567890',
	        Phone = '(763) 555-2000',
		 	Store_Location__c = store.id, 
			BillingStreet = '123 happy Ln',
			BillingCity = 'Sunshine',
			BillingState = 'Minnesota',
			BillingStateCode = 'MN',
			BillingPostalCode = '55449', 
			BillingCountry = 'United States',
			RecordTypeId = UtilityMethods.retrieveRecordTypeId('Dwelling', 'Account') ); 
	 	insert account1;	
		
		Account vend1 = utilities.createVendorAccount('Vendor Account 1');
		insert vend1;

		Product2 product1 = new Product2(
			Name='Test Product', 
			Vendor__c = vend1.id
		);

		insert product1;
		
		PricebookEntry pricebookEntry1 = utilities.createPricebookEntry(Test.getStandardPricebookId(), product1.id);
		insert pricebookEntry1;

		Opportunity opp = new Opportunity(
											Name = 'Test Opportunity',
											StageName = 'New',
											AccountId = account1.id,
											Store_Location__c = store.id,
											Pricebook2Id = Test.getStandardPricebookId(),
											CloseDate = Date.Today()
										);
		insert opp;
		
		Quote quote = utilities.createQuote(opp.id,Test.getStandardPricebookId());
		insert quote;
				
		Contact contact1 = utilities.createContact(account1.id, '1');
		insert contact1;
		
		OpportunityContactRole ocr = new OpportunityContactRole(IsPrimary = true, 
																OpportunityId = opp.id, 
																ContactId = contact1.id
																);
		insert ocr;
		
		OpportunityLineItem oli = utilities.createOpportunityLineItem(opp.id, pricebookEntry1.id);
		insert oli;

		opp.StageName = 'Sold';
		update opp;
		
		list<Order> orders = [SELECT Id FROM Order WHERE OpportunityId = :opp.id];
		
		System.assertEquals(orders.size(), 1);
		
	}
	
	
	
	
	static testmethod void noPrimaryContactActivationOfOpportunity(){ 
		Profile p = [SELECT Id FROM Profile WHERE Name='Standard User']; 
		TestUtilityMethods utilities = new TestUtilityMethods();
		utilities.setUpConfigs();
		Account store = [SELECT Id FROM account WHERE Name ='77 - Twin Cities, MN'];

		//Creating Account (Needed for RMS_Queue_Settings__c)
		Account account1 =  new Account(Name = 'Test Account1',
	        AccountNumber = '1234567890',
	        Phone = '(763) 555-2000',
		 	Store_Location__c = store.id, 
			BillingStreet = '123 happy Ln',
			BillingCity = 'Sunshine',
			BillingState = 'Minnesota',
			BillingStateCode = 'MN',
			BillingPostalCode = '55449', 
			BillingCountry = 'United States',
			RecordTypeId = UtilityMethods.retrieveRecordTypeId('Dwelling', 'Account') ); 
	 	insert account1;	
		
		Account vend1 = utilities.createVendorAccount('Vendor Account 1');
		insert vend1;

		Product2 product1 = new Product2(
			Name='Test Product',
			Vendor__c = vend1.id
		);

		insert product1;
		
		PricebookEntry pricebookEntry1 = utilities.createPricebookEntry(Test.getStandardPricebookId(), product1.id);
		insert pricebookEntry1;

		Opportunity opp = new Opportunity(
											Name = 'Test Opportunity',
											StageName = 'New',
											AccountId = account1.id,
											Store_Location__c = store.id,
											Pricebook2Id = Test.getStandardPricebookId(),
											CloseDate = Date.Today()
										);
		insert opp;
		
		Quote quote = utilities.createQuote(opp.id,Test.getStandardPricebookId());
		insert quote;
		
		Contact contact1 = utilities.createContact(account1.id, '1');
		insert contact1;
		
		OpportunityContactRole ocr = new OpportunityContactRole(IsPrimary = false, 
																OpportunityId = opp.id, 
																ContactId = contact1.id
																);
		insert ocr;
						
		opp.StageName = 'Sold';
		update opp;
		
		list<Order> orders = [SELECT Id FROM Order WHERE OpportunityId = :opp.id];
		
		System.assertEquals(orders.size(), 1);
		
	}
	
	static testmethod void noContactActivationOfOpportunity(){ 
		Profile p = [SELECT Id FROM Profile WHERE Name='Standard User']; 
		TestUtilityMethods utilities = new TestUtilityMethods();
		utilities.setUpConfigs();
		Account store = [SELECT Id FROM account WHERE Name ='77 - Twin Cities, MN'];

		//Creating Account (Needed for RMS_Queue_Settings__c)
		Account account1 =  new Account(Name = 'Test Account1',
	        AccountNumber = '1234567890',
	        Phone = '(763) 555-2000',
		 	Store_Location__c = store.id, 
			BillingStreet = '123 happy Ln',
			BillingCity = 'Sunshine',
			BillingState = 'Minnesota',
			BillingStateCode = 'MN',
			BillingPostalCode = '55449', 
			BillingCountry = 'United States',
			RecordTypeId = UtilityMethods.retrieveRecordTypeId('Dwelling', 'Account') ); 
	 	insert account1;	
		
		Account vend1 = utilities.createVendorAccount('Vendor Account 1');
		insert vend1;

		Product2 product1 = new Product2(
			Name='Test Product',
			Vendor__c = vend1.id
		);

		insert product1;
		
		PricebookEntry pricebookEntry1 = utilities.createPricebookEntry(Test.getStandardPricebookId(), product1.id);
		insert pricebookEntry1;

		Opportunity opp = new Opportunity(
											Name = 'Test Opportunity',
											StageName = 'New',
											AccountId = account1.id,
											Store_Location__c = store.id,
											Pricebook2Id = Test.getStandardPricebookId(),
											CloseDate = Date.Today()
										);
		insert opp;
		
		Quote quote = utilities.createQuote(opp.id,Test.getStandardPricebookId());
		insert quote;
		
		opp.StageName = 'Sold';
		update opp;
		
		list<Order> orders = [SELECT Id FROM Order WHERE OpportunityId = :opp.id];
		
		System.assertEquals(1, orders.size());
		
	}
	
	static testmethod void testReparentAttachment(){ 
		Profile p = [SELECT Id FROM Profile WHERE Name='Standard User']; 
		TestUtilityMethods utilities = new TestUtilityMethods();
		utilities.setUpConfigs();
		Account store = [SELECT Id FROM account WHERE Name ='77 - Twin Cities, MN'];

		//Creating Account (Needed for RMS_Queue_Settings__c)
		Account account1 =  new Account(Name = 'Test Account1',
	        AccountNumber = '1234567890',
	        Phone = '(763) 555-2000',
		 	Store_Location__c = store.id, 
			BillingStreet = '123 happy Ln',
			BillingCity = 'Sunshine',
			BillingState = 'Minnesota',
			BillingStateCode = 'MN',
			BillingPostalCode = '55449', 
			BillingCountry = 'United States',
			RecordTypeId = UtilityMethods.retrieveRecordTypeId('Dwelling', 'Account') ); 
	 	insert account1;	
		
		Account vend1 = utilities.createVendorAccount('Vendor Account 1');
		insert vend1;

		Product2 product1 = new Product2(
			Name='Test Product',
			Vendor__c = vend1.id
		);

		insert product1;
		
		PricebookEntry pricebookEntry1 = utilities.createPricebookEntry(Test.getStandardPricebookId(), product1.id);
		insert pricebookEntry1;

		Opportunity opp = new Opportunity(
											Name = 'Test Opportunity',
											StageName = 'New',
											AccountId = account1.id,
											Store_Location__c = store.id,
											Pricebook2Id = Test.getStandardPricebookId(),
											CloseDate = Date.Today()
										);
		insert opp;
		
		Attachment attach = new Attachment(Name = 'TestAtt', ParentId = opp.Id, Body=Blob.valueOf('Test PDF'), IsPrivate = false, Description = 'Test Description');
		insert attach;
		Attachment attach2 = new Attachment(Name = 'TestAtt2', ParentId = opp.Id, Body=Blob.valueOf('Test PDF2'), IsPrivate = true, Description = 'Test Description2');
		insert attach2;

		Quote quote = utilities.createQuote(opp.id,Test.getStandardPricebookId());
		insert quote;
				
		Contact contact1 = utilities.createContact(account1.id, '1');
		insert contact1;
		
		OpportunityContactRole ocr = new OpportunityContactRole(IsPrimary = true, 
																OpportunityId = opp.id, 
																ContactId = contact1.id
																);
		insert ocr;
				
		opp.StageName = 'Sold';
		update opp;
		
		list<Order> orders = [SELECT Id FROM Order WHERE OpportunityId = :opp.id];
		
		System.assertEquals(orders.size(), 1);

		List<Attachment> attList = [Select Id, ParentId, Name, Body, IsPrivate, Description from Attachment order by Name];
		System.assertEquals(attList.size(),2);
		System.assertEquals(attList[0].ParentId,orders[0].Id);
		System.assertEquals(attList[1].ParentId,orders[0].Id);
		Blob att1Body = attList[0].Body; 
		System.assertEquals(att1Body.toString(),'Test PDF');
		System.assertEquals(attList[0].Description,'Test Description');
		System.assertEquals(attList[0].IsPrivate,false);
		System.assertEquals(attList[0].Name,'TestAtt');
		Blob att2Body = attList[1].Body; 
		System.assertEquals(att2Body.toString(),'Test PDF2');
		System.assertEquals(attList[1].Description,'Test Description2');
		System.assertEquals(attList[1].IsPrivate,true);
		System.assertEquals(attList[1].Name,'TestAtt2');
		
	}

	/* 
	 * testOrderItemLinking
	 */
	static testmethod void testOrderItemLinking(){

		// Turn off the financial trigger to avoid SOQL limits in test class
		RMS_Settings__c turnOffFinancialTrigger = new RMS_Settings__c(Name='Turn Financial Transactions Off', Value__c = 'Yes');
		insert turnOffFinancialTrigger;

		TestUtilityMethods tUtil = new TestUtilityMethods();
		tUtil.setUpConfigs();
		Profile p = [SELECT Id FROM Profile WHERE Name='Sys Admin']; 

		Datetime newApptTime = Datetime.now().addDays(1);
		Datetime tmApptTime = Datetime.now().addDays(5);

		User u = tUtil.createUser(p.id);
		insert u;

		tUtil.createSalesAppt(u.Id, newApptTime, false, false);

		Account store1 = [SELECT id, Name, Active_Store_Configuration__c FROM Account Where Name = '77 - Twin Cities, MN'][0];
		Account dwelling1 = tUtil.createDwellingAccount('456');
		dwelling1.Store_Location__c = store1.id;
		dwelling1.OwnerId = u.Id;
		insert dwelling1;

		List<SObject> itemsToInsert = new List<SObject>();		
		
		Opportunity opp1 = tutil.createOpportunity('aaaTMAppt',dwelling1.id, 'New', u.Id);
		opp1.OwnerId = u.Id;
		itemsToInsert.add(opp1);
		insert itemsToInsert;

		//clean out the list
		itemsToInsert.clear();
		
		Pricebook2 pb = tutil.createPricebook2('bbbsaveQuoteTest', store1.Active_Store_Configuration__c);
		itemsToInsert.add(pb);
		insert itemsToInsert;
		itemsToInsert.clear();

		Quote quote1 = tutil.createQuote(opp1.id, pb.Id);
		quote1.isSold__c = true;
		itemsToInsert.add(quote1);
		insert itemsToInsert;
		//clean out the list
		itemsToInsert.clear();
			
		// qli to update
		QuoteLineItem qli1 = tutil.createQLIMasterChildProducts(pb.Id, quote1.Id);
		qli1.Description = 'original description';
		qli1.rSuite_Id__c = 'rsuite-id-1234';
		itemsToInsert.add(qli1);
		QuoteLineItem qli2 = tutil.createQLIMasterChildProducts(pb.Id, quote1.Id);
		qli2.Description = 'original description';
		qli2.rSuite_Id__c = 'rsuite-id-2234';
		itemsToInsert.add(qli2);
		QuoteLineItem qli3 = tutil.createQLIMasterChildProducts(pb.Id, quote1.Id);
		qli3.Description = 'original description';
		qli3.rSuite_Id__c = 'rsuite-id-3234';
		qli3.Parent_Unit_rSuite_Id__c = qli1.rSuite_Id__c;
		itemsToInsert.add(qli3);
		insert itemsToInsert;
		//clean out the list
		itemsToInsert.clear();
		// updates
		opp1.StageName = 'Sold';


        System.runAs(u) {
        	Test.StartTest();
        	update opp1;
			Test.StopTest();
			// we should have 3 order line items
			// 1. parent
			// 1. childd
			// 1 not a child
			List<OrderItem> oiList = [select Id, rSuite_Id__c, Parent_Order_Item__c, Parent_Unit_rSuite_Id__c from OrderItem where Order.OpportunityId = : opp1.Id order by rSuite_Id__c ASC];
			System.assert(oiList.size() == 3);
			System.assert(oiList[0].rSuite_Id__c == 'rsuite-id-1234');
			System.assert(oiList[1].rSuite_Id__c == 'rsuite-id-2234');
			System.assert(oiList[2].rSuite_Id__c == 'rsuite-id-3234');
			System.assert(oiList[0].Parent_Unit_rSuite_Id__c == null);
			System.assert(oiList[1].Parent_Unit_rSuite_Id__c == null);
			System.assert(oiList[2].Parent_Unit_rSuite_Id__c == 'rsuite-id-1234');
			System.assert(oiList[0].Parent_Order_Item__c == null);
			System.assert(oiList[1].Parent_Order_Item__c == null);
			System.assert(oiList[2].Parent_Order_Item__c == oiList[0].Id);
        }
	
	} 

}