RbA Build/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Active_Store_Configuration__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>currently active store configuration</description>
        <label>Active Store Configuration</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Store_Configuration__c.Store__c</field>
                <operation>equals</operation>
                <valueField>$Source.Id</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Store_Configuration__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Store_Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The store location that this dwelling is related</description>
        <inlineHelpText>The store location that this dwelling is related</inlineHelpText>
        <label>Store Location</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>The account must be of type &quot;Store&quot;</errorMessage>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Store</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Dwellings</relationshipLabel>
        <relationshipName>StoreLocation</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Store</fullName>
        <active>true</active>
        <description>Used to track and store data releated to Retail Locations both CORO and ARO</description>
        <label>Store</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

RbA Build/src/objects/Business_Adjustment__c.object
<CustomObject>
    <fields>
        <fullName>Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order</label>
        <referenceTo>Order</referenceTo>
        <relationshipLabel>Business Adjustments</relationshipLabel>
        <relationshipName>Business_Adjustments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Store_Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Store Location</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Business Adjustments</relationshipLabel>
        <relationshipName>Business_Adjustments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>AR write-off</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Install Adjustment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non-sufficient Funds</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Business Adjustment</label>
    <nameField>
        <displayFormat>BA-{000000}</displayFormat>
        <label>Business Adjustment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Business Adjustments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

RbA Build/src/objects/Financial_Account_Number__c.object
<CustomObject>
    <description>Stores financial account numbers used in the journal entries and Baan ERP integration</description>
    <fields>
        <fullName>Store_Configuration__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Select which store configuration to relate this account number.</description>
        <inlineHelpText>Select which store configuration to relate this account number.</inlineHelpText>
        <label>Store Configuration</label>
        <referenceTo>Store_Configuration__c</referenceTo>
        <relationshipLabel>Financial Account Numbers</relationshipLabel>
        <relationshipName>Financial_Account_Numbers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Financial Account Number</label>
    <nameField>
        <label>Financial Account Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Account Numbers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

RbA Build/src/objects/Journal_Entry__c.object
<CustomObject>
    <description>Holds the Financial Transactions that are sent to an Accounting System.
Baan ERP, etc.</description>
    <fields>
        <fullName>Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order</label>
        <referenceTo>Order</referenceTo>
        <relationshipLabel>Journal Entries</relationshipLabel>
        <relationshipName>Journal_Entries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Payment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Payment</label>
        <referenceTo>Payment__c</referenceTo>
        <relationshipLabel>Journal Entries</relationshipLabel>
        <relationshipName>Journal_Entries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Store_Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Store Location</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Journal Entries</relationshipLabel>
        <relationshipName>Journal_Entries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Deposit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Final Payment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Misc Cash Receipt</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>External Labor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Service External Labor - JIP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Service External Labor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Internal Labor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Post Recognized Service External Labor - JIP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Post Recognized Service External Labor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Post Recognized External Labor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Post Recognized Internal Labor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Misc Reimbursement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rev Recognized - Deposit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rev Recognized - External Labor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rev Recognized - Service External Labor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rev Recognized - Service External Labor - JIP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rev Recognized - Refund Deposit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rev Recognized - COGS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rev Recognized - Discount</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rev Recognized - AR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rev Recognized - Service AR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rev Recognized - Finance Fees</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rev Recognized - Service Tax</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rev Recognized - Install Adjustment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Refund - Deposit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Refund - Final Payment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cost Product Received</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Service Inventory Received - Intercompany Consolidation Center</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Service Inventory Received - External Vendor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Service Inventory Received - Remake External Vendor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AR write-off</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Install Adjustment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Post Recognized Install Adjustment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non-sufficient Funds - Deposit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non-sufficient Funds - Final Payment</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Journal Entry</label>
    <nameField>
        <displayFormat>JEN-{000000}</displayFormat>
        <label>Journal Entry Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Journal Entries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

RbA Build/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Store_Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Store Location</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>The account must be of type &quot;Store&quot;.</errorMessage>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Store</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Store Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

RbA Build/src/objects/Order.object
<CustomObject>
    <fields>
        <fullName>Store_Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This order is related to this store location.</description>
        <inlineHelpText>This order is related to this store location.</inlineHelpText>
        <label>Store Location</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Orders (Store Location)</relationshipLabel>
        <relationshipName>Orders1</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

RbA Build/src/objects/Payment__c.object
<CustomObject>
    <description>The object used to store payment records</description>
    <fields>
        <fullName>Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The payment record is related to this order.</description>
        <inlineHelpText>The payment record is related to this order.</inlineHelpText>
        <label>Order</label>
        <referenceTo>Order</referenceTo>
        <relationshipLabel>Payments</relationshipLabel>
        <relationshipName>Payments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Payment_Type__c</fullName>
        <description>The type of payment. What would make sense here? Things like Permit Refunds, Install Materials, etc?</description>
        <inlineHelpText>The type of payment. What would make sense here? Things like Permit Refunds, Install Materials, etc?</inlineHelpText>
        <label>Payment Type</label>
        <picklist>
            <picklistValues>
                <fullName>Deposit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Final Payment</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Store_Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The store location where this payment was received.</description>
        <inlineHelpText>The store location where this payment was received.</inlineHelpText>
        <label>Store Location</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Payments</relationshipLabel>
        <relationshipName>Payments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Payment</label>
    <nameField>
        <displayFormat>P-{00000000}</displayFormat>
        <label>Payment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <recordTypes>
        <fullName>Deposit</fullName>
        <active>true</active>
        <description>Deposit record type</description>
        <label>Deposit</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

RbA Build/src/objects/Pricebook2.object
<CustomObject>
    <fields>
        <fullName>Store_Configuration__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Links price books to store configuration.  All configuration that are store based are tied to the store configuration for that store.</description>
        <inlineHelpText>Link this to the store configuration for the store this Price Book is being created for.</inlineHelpText>
        <label>Store Configuration</label>
        <referenceTo>Store_Configuration__c</referenceTo>
        <relationshipLabel>Price Books</relationshipLabel>
        <relationshipName>Price_Books</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadSelect</sharingModel>
</CustomObject>

RbA Build/src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Vendor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Vendor</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>Products</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

RbA Build/src/objects/Store_Configuration__c.object
<CustomObject>
    <description>Holds Store Settings &amp; Configurations</description>
    <fields>
        <fullName>Store__c</fullName>
        <label>Store</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Store Configurations</relationshipLabel>
        <relationshipName>Store_Configurations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Store Configuration</label>
    <nameField>
        <displayFormat>SS-{00}</displayFormat>
        <label>Store Setting Record #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Store Configurations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

RbA Build/src/classes/RMS_financialTransManBusAdjTest.cls
/*******************************************************//**

@class	RMS_financialTransManBusAdjTest

@brief	Test Class for RMS_financialTransactionManager. 

		Separated the original test class into multiple test classes. This one focuses
		on the business adjustment test classes (ar-write off, install adjustments, non-sufficient funds)

@author  Creston Kuenzi (Slalom.CDK)

@version	2016-10-5  Slalom.CDK
	Created.

@see		RMS_financialTransactionManager

@copyright  (c)2016 Slalom.  All Rights Reserved. 
			Unauthorized use is prohibited.

***********************************************************/
@isTest
private class RMS_financialTransManBusAdjTest {

	/*******************************************************
					setupData
	*******************************************************/
	@testSetup static void setupData(){

		TestUtilityMethods testMethods = new TestUtilityMethods();
		testMethods.setUpConfigs();
		
		Account store1 = [SELECT id, Active_Store_Configuration__c FROM Account WHERE Name='77 - Twin Cities, MN'];
		Store_Configuration__c storeConfig1 = [SELECT id FROM Store_Configuration__c WHERE Store__c = :store1.id ];
		
		Account dwelling1 = testMethods.createDwellingAccount('dwelling1');
		dwelling1.Store_Location__c = store1.id;
		insert dwelling1;
		
		Contact contact1 = testMethods.createContact(dwelling1.id, 'contact1');
		insert contact1;
		
		Opportunity opp1 = testMethods.createOpportunity(dwelling1.id, 'Draft');
		insert opp1;
		
		Order order1 = new Order(	Name='Sold Order 1', 
									AccountId = dwelling1.id, 
									EffectiveDate= Date.Today(), 
									Store_Location__c = store1.Id,
									Opportunity = opp1, 									
									Status ='Draft',
									BillToContactId = contact1.id, 
									Pricebook2Id = Test.getStandardPricebookId()
								);
		insert order1;

			
		
		Account vend1 = testMethods.createIntercompanyVendorAccount('Intercompany');
		Account vend2 = testMethods.createIntercompanyCCVendorAccount('IntercompanyCC');
		Account vend3 = testMethods.createExternalVendorAccount('External');
		List<Account> vendsToInsert = new List<Account>{vend1,vend2,vend3};
		
		insert vendsToInsert;
		
		Pricebook2 pricebook1 =  testMethods.createPricebook2Name('Standard Price Book');
		insert pricebook1;

		Product2 product1 = new Product2(
			Name='Test Product',
			Vendor__c = vend1.id
		);

		insert product1;
		
		PricebookEntry pricebookEntry1 = testMethods.createPricebookEntry(Test.getStandardPricebookId(), product1.id);
		insert pricebookEntry1;
		
		OrderItem orderItem1 = new OrderItem(OrderId = order1.id, PricebookentryId = pricebookEntry1.Id, Quantity = 2, UnitPrice = 10000 );
		insert orderItem1;	

		testMethods.createAllFinancialRecords(storeConfig1);

	}
	/*******************************************************
					positiveCreateEditARWriteOff
	*******************************************************/
	static testmethod void positiveCreateEditARWriteOff(){
		Order soldOrder = [SELECT Id, AccountId, BillToContactId FROM Order where Name='Sold Order 1'];		
		Account store = [SELECT id FROM Account WHERE Name='77 - Twin Cities, MN'];				

		Id paymentDepositRecordTypeId = UtilityMethods.retrieveRecordTypeId('Deposit', 'Payment__c');
		Payment__c payment1 = new Payment__c(	Order__c = soldOrder.id,
												RecordTypeId = paymentDepositRecordTypeId,
												Payment_Type__c = 'Deposit',
												Store_Location__c = store.id,
												Payment_Amount__c = 100,
												Payment_Date__c = Date.Today()
												);
		insert payment1;

		Business_Adjustment__c busAdj = new Business_Adjustment__c(	Order__c = soldOrder.id, 
																	Amount__c = 10, 
																	Store_Location__c = store.id, 
																	Type__c = 'AR write-off'
																	);
		insert busAdj;
		Journal_Entry__c je = [SELECT Id, Amount__c, Type__c, Order__c, Store_Location__c, Date__c FROM Journal_Entry__c 
								WHERE Order__c =: soldOrder.Id AND Type__c = 'AR write-off']; 
		System.AssertEquals(10, je.Amount__c);
		System.AssertEquals(System.today(), je.Date__c.date());
		busAdj.Amount__c = 5;

		update busAdj;
		je = [SELECT Id, Amount__c, Type__c, Order__c, Store_Location__c, Date__c FROM Journal_Entry__c 
								WHERE Order__c =: soldOrder.Id AND Type__c = 'AR write-off']; 
		System.AssertEquals(5, je.Amount__c);
		System.AssertEquals(System.today(), je.Date__c.date());

		delete busAdj;
	}

	/*******************************************************
					positiveCreateEditInstallAdjustment
	*******************************************************/
	static testmethod void positiveCreateEditInstallAdjustment(){
		Order soldOrder = [SELECT Id, AccountId, BillToContactId FROM Order where Name='Sold Order 1'];		
		Account store = [SELECT id FROM Account WHERE Name='77 - Twin Cities, MN'];				

		Id paymentDepositRecordTypeId = UtilityMethods.retrieveRecordTypeId('Deposit', 'Payment__c');
		Payment__c payment1 = new Payment__c(	Order__c = soldOrder.id,
												RecordTypeId = paymentDepositRecordTypeId,
												Payment_Type__c = 'Deposit',
												Store_Location__c = store.id,
												Payment_Amount__c = 100,
												Payment_Date__c = Date.Today()
												);
		insert payment1;

		Business_Adjustment__c busAdj = new Business_Adjustment__c(	Order__c = soldOrder.id, 
																	Amount__c = 10, 
																	Store_Location__c = store.id, 
																	Type__c = 'Install Adjustment'
																	);
		insert busAdj;

		Financial_Account_Number__c installAdjustmentDebit = [Select Id, Name From Financial_Account_Number__c Where Name = 'FANInstallAdjustmentDebit'];
		Financial_Account_Number__c installAdjustmentCredit = [Select Id, Name From Financial_Account_Number__c Where Name = 'FANInstallAdjustmentCredit'];

		Journal_Entry__c je = [SELECT Id, Amount__c, Type__c, Order__c, Store_Location__c, Date__c, Debit_General_Ledger_Account__c, Credit_General_Ledger_Account__c 
		 FROM Journal_Entry__c WHERE Order__c =: soldOrder.Id AND Type__c = 'Install Adjustment']; 
		System.AssertEquals(10, je.Amount__c);
		System.AssertEquals(System.today(), je.Date__c.date());

		// Verify the account number is the store location number inserted in the the gl account number
		System.AssertEquals(installAdjustmentDebit.Name, je.Debit_General_Ledger_Account__c);
		System.AssertEquals(installAdjustmentCredit.Name, je.Credit_General_Ledger_Account__c);

		busAdj.Amount__c = 5;

		update busAdj;
		je = [SELECT Id, Amount__c, Type__c, Order__c, Store_Location__c, Date__c, Debit_General_Ledger_Account__c, Credit_General_Ledger_Account__c 
		 FROM Journal_Entry__c WHERE Order__c =: soldOrder.Id AND Type__c = 'Install Adjustment']; 
		System.AssertEquals(5, je.Amount__c);
		System.AssertEquals(System.today(), je.Date__c.date());

		// Verify the account number is the store location number inserted in the the gl account number
		System.AssertEquals(installAdjustmentDebit.Name, je.Debit_General_Ledger_Account__c);
		System.AssertEquals(installAdjustmentCredit.Name, je.Credit_General_Ledger_Account__c);

		delete busAdj;
	}	

	/*******************************************************
					positiveCreateEditPostRecognizedInstallAdjustment
	*******************************************************/
	static testmethod void positiveCreateEditPostRecognizedInstallAdjustment(){

		test.startTest();
		Order soldOrder = [SELECT Id, AccountId, BillToContactId FROM Order where Name='Sold Order 1'];		
		soldOrder.Revenue_Recognized_Date__c = System.today();
		update soldOrder;

		Account store = [SELECT id FROM Account WHERE Name='77 - Twin Cities, MN'];				

		Id paymentDepositRecordTypeId = UtilityMethods.retrieveRecordTypeId('Deposit', 'Payment__c');
		Payment__c payment1 = new Payment__c(	Order__c = soldOrder.id,
												RecordTypeId = paymentDepositRecordTypeId,
												Payment_Type__c = 'Deposit',
												Store_Location__c = store.id,
												Payment_Amount__c = 100,
												Payment_Date__c = Date.Today()
												);
		insert payment1;

		Business_Adjustment__c busAdj = new Business_Adjustment__c(	Order__c = soldOrder.id, 
																	Amount__c = 10, 
																	Store_Location__c = store.id, 
																	Type__c = 'Install Adjustment'
																	);
		insert busAdj;

		Financial_Account_Number__c installAdjustmentPRDebit = [Select Id, Name From Financial_Account_Number__c Where Name = 'FANPRInstallAdjustmentDebit'];
		Financial_Account_Number__c installAdjustmentPRCredit = [Select Id, Name From Financial_Account_Number__c Where Name = 'FANPRInstallAdjustmentCredit'];

		Journal_Entry__c je = [SELECT Id, Amount__c, Type__c, Order__c, Store_Location__c, Date__c, Debit_General_Ledger_Account__c, Credit_General_Ledger_Account__c 
		 FROM Journal_Entry__c WHERE Order__c =: soldOrder.Id AND Type__c = 'Post Recognized Install Adjustment']; 
		System.AssertEquals(10, je.Amount__c);
		System.AssertEquals(System.today(), je.Date__c.date());

		// Verify the account number is the store location number inserted in the the gl account number
		System.AssertEquals(installAdjustmentPRDebit.Name, je.Debit_General_Ledger_Account__c);
		System.AssertEquals(installAdjustmentPRCredit.Name, je.Credit_General_Ledger_Account__c);

		busAdj.Amount__c = 5;

		update busAdj;
		je = [SELECT Id, Amount__c, Type__c, Order__c, Store_Location__c, Date__c , Debit_General_Ledger_Account__c, Credit_General_Ledger_Account__c 
		FROM Journal_Entry__c WHERE Order__c =: soldOrder.Id AND Type__c = 'Post Recognized Install Adjustment']; 
		System.AssertEquals(5, je.Amount__c);
		System.AssertEquals(System.today(), je.Date__c.date());

		// Verify the account number is the store location number inserted in the the gl account number
		System.AssertEquals(installAdjustmentPRDebit.Name, je.Debit_General_Ledger_Account__c);
		System.AssertEquals(installAdjustmentPRCredit.Name, je.Credit_General_Ledger_Account__c);

		delete busAdj;
		test.stopTest();
	}	


	/*******************************************************
					positiveCreateEditNonSufficientDeposit
	*******************************************************/
	static testmethod void positiveCreateEditNonSufficientDeposit(){
		Order soldOrder = [SELECT Id, AccountId, BillToContactId FROM Order where Name='Sold Order 1'];		
		Account store = [SELECT id FROM Account WHERE Name='77 - Twin Cities, MN'];				

		Id paymentDepositRecordTypeId = UtilityMethods.retrieveRecordTypeId('Deposit', 'Payment__c');
		Payment__c payment1 = new Payment__c(	Order__c = soldOrder.id,
												RecordTypeId = paymentDepositRecordTypeId,
												Payment_Type__c = 'Deposit',
												Store_Location__c = store.id,
												Payment_Amount__c = 100,
												Payment_Date__c = Date.Today()
												);
		insert payment1;

		Business_Adjustment__c busAdj = new Business_Adjustment__c(	Order__c = soldOrder.id, 
																	Amount__c = 10, 
																	Store_Location__c = store.id, 
																	Type__c = 'Non-sufficient Funds - Deposit'
																	);
		insert busAdj;
		Journal_Entry__c je = [SELECT Id, Amount__c, Type__c, Order__c, Store_Location__c, Date__c FROM Journal_Entry__c 
								WHERE Order__c =: soldOrder.Id AND Type__c = 'Non-sufficient Funds - Deposit']; 
		System.AssertEquals(10, je.Amount__c);
		System.AssertEquals(System.today(), je.Date__c.date());
		busAdj.Amount__c = 5;

		update busAdj;
		je = [SELECT Id, Amount__c, Type__c, Order__c, Store_Location__c, Date__c FROM Journal_Entry__c 
								WHERE Order__c =: soldOrder.Id AND Type__c = 'Non-sufficient Funds - Deposit']; 
		System.AssertEquals(5, je.Amount__c);
		System.AssertEquals(System.today(), je.Date__c.date());

		delete busAdj;
	}	

	/*******************************************************
					positiveCreateEditNonSufficientFinalPayment
	*******************************************************/
	static testmethod void positiveCreateEditNonSufficientFinalPayment(){
		Order soldOrder = [SELECT Id, Revenue_Recognized_Date__c FROM Order where Name='Sold Order 1'];		
		soldOrder.Revenue_Recognized_Date__c = System.today();
		update soldOrder;
		Account store = [SELECT id FROM Account WHERE Name='77 - Twin Cities, MN'];				

		Id paymentDepositRecordTypeId = UtilityMethods.retrieveRecordTypeId('Deposit', 'Payment__c');
		Payment__c payment1 = new Payment__c(	Order__c = soldOrder.id,
												RecordTypeId = paymentDepositRecordTypeId,
												Payment_Type__c = 'Final Payment',
												Store_Location__c = store.id,
												Payment_Amount__c = 100,
												Payment_Date__c = Date.Today()
												);
		insert payment1;

		Business_Adjustment__c busAdj = new Business_Adjustment__c(	Order__c = soldOrder.id, 
																	Amount__c = 10, 
																	Store_Location__c = store.id, 
																	Type__c = 'Non-sufficient Funds - Final Payment'
																	);
		insert busAdj;
		Journal_Entry__c je = [SELECT Id, Amount__c, Type__c, Order__c, Store_Location__c, Date__c FROM Journal_Entry__c 
								WHERE Order__c =: soldOrder.Id AND Type__c = 'Non-sufficient Funds - Final Payment']; 
		System.AssertEquals(10, je.Amount__c);
		System.AssertEquals(System.today(), je.Date__c.date());
		busAdj.Amount__c = 5;

		update busAdj;
		je = [SELECT Id, Amount__c, Type__c, Order__c, Store_Location__c, Date__c FROM Journal_Entry__c 
								WHERE Order__c =: soldOrder.Id AND Type__c = 'Non-sufficient Funds - Final Payment']; 
		System.AssertEquals(5, je.Amount__c);
		System.AssertEquals(System.today(), je.Date__c.date());

		delete busAdj;
	}	

	public class anException extends Exception {}


}