RbA Build/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Store_Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The store location that this dwelling is related</description>
        <inlineHelpText>The store location that this dwelling is related</inlineHelpText>
        <label>Store Location</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>The account must be of type &quot;Store&quot;</errorMessage>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Store</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Dwellings</relationshipLabel>
        <relationshipName>StoreLocation</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Dwelling</fullName>
        <active>true</active>
        <description>Used to support Dwelling</description>
        <label>Dwelling</label>
    </recordTypes>
    <recordTypes>
        <fullName>Vendor</fullName>
        <active>true</active>
        <description>Used to track Vendors</description>
        <label>Vendor</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

RbA Build/src/objects/Asset.object
<CustomObject>
    <fields>
        <fullName>Sold_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Related Sold Order</inlineHelpText>
        <label>Sold Order</label>
        <referenceTo>Order</referenceTo>
        <relationshipLabel>Assets</relationshipLabel>
        <relationshipName>Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Store_Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Store Location</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Assets</relationshipLabel>
        <relationshipName>Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Variant_Number__c</fullName>
        <description>The variant number for this asset.</description>
        <inlineHelpText>The variant number for this asset.</inlineHelpText>
        <label>Variant Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

RbA Build/src/objects/Financial_Account_Number__c.object
<CustomObject>
    <description>Stores financial account numbers used in the journal entries and Baan ERP integration</description>
    <fields>
        <fullName>Store_Configuration__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Select which store configuration to relate this account number.</description>
        <inlineHelpText>Select which store configuration to relate this account number.</inlineHelpText>
        <label>Store Configuration</label>
        <referenceTo>Store_Configuration__c</referenceTo>
        <relationshipLabel>Financial Account Numbers</relationshipLabel>
        <relationshipName>Financial_Account_Numbers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Financial Account Number</label>
    <nameField>
        <label>Financial Account Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Account Numbers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

RbA Build/src/objects/Financial_Transaction__c.object
<CustomObject>
    <description>Object to store financial transaction records</description>
    <fields>
        <fullName>Credit_Account_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Select the account number to credit in this financial transaction</description>
        <inlineHelpText>Select the account number to credit in this financial transaction</inlineHelpText>
        <label>Credit Account Number</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Only account numbers related to this financial transaction&apos;s store location can be selected.</errorMessage>
            <filterItems>
                <field>Financial_Account_Number__c.Store_Configuration__c</field>
                <operation>equals</operation>
                <valueField>$Source.Store_Configuration__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Financial_Account_Number__c</referenceTo>
        <relationshipLabel>Financial Transactions Credit</relationshipLabel>
        <relationshipName>Financial_Transactions_Credit</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Debit_Account_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Select the account number to debit in this financial transaction</description>
        <inlineHelpText>Select the account number to debit in this financial transaction</inlineHelpText>
        <label>Debit Account Number</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Only account numbers related to this financial transaction&apos;s store location can be selected.</errorMessage>
            <filterItems>
                <field>Financial_Account_Number__c.Store_Configuration__c</field>
                <operation>equals</operation>
                <valueField>$Source.Store_Configuration__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Financial_Account_Number__c</referenceTo>
        <relationshipLabel>Financial Transactions Debit</relationshipLabel>
        <relationshipName>Financial_Transactions_Debit</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Store_Configuration__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>The store configuration this transaction is related to</description>
        <inlineHelpText>The store configuration this transaction is related to</inlineHelpText>
        <label>Store Configuration</label>
        <referenceTo>Store_Configuration__c</referenceTo>
        <relationshipLabel>Financial Transactions</relationshipLabel>
        <relationshipName>Financial_Transactions</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Transaction_Type__c</fullName>
        <description>Select the transaction type for this record. This will determine when these accounts will be debited/credited.</description>
        <inlineHelpText>Select the transaction type for this record. This will determine when these accounts will be debited/credited.</inlineHelpText>
        <label>Transaction Type</label>
        <picklist>
            <picklistValues>
                <fullName>Deposit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Final Payment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inventory Received</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inventory Installed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Misc Sub-Payment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>External Labor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Internal Labor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Misc Cash Receipt</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Misc Reimbursement</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Financial Transaction</label>
    <nameField>
        <displayFormat>FT-{00000}</displayFormat>
        <label>Financial Transaction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Financial Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

RbA Build/src/objects/Order.object
<CustomObject>
    <fields>
        <fullName>Service_Type__c</fullName>
        <inlineHelpText>Job In Progress should be selected if the Installation Date of the original product was in the last 30 days. Select Save if the request is solved during the initial phone call. Field Service is the default and only option for Cottage Grove users.</inlineHelpText>
        <label>Service Type</label>
        <picklist>
            <picklistValues>
                <fullName>Job in Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Field Service</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Service</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Save</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Sold_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>When the Sold Order is Job In Progress, the Service Order must be related to the Sold Order.</inlineHelpText>
        <label>Sold Order</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>$Source.AccountId</field>
                <operation>equals</operation>
                <valueField>Order.AccountId</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Order</referenceTo>
        <relationshipLabel>Service Orders</relationshipLabel>
        <relationshipName>Sold_Order</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Store_Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This order is related to this store location.</description>
        <inlineHelpText>This order is related to this store location.</inlineHelpText>
        <label>Store Location</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Orders (Store Location)</relationshipLabel>
        <relationshipName>Orders1</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

RbA Build/src/objects/OrderItem.object
<CustomObject>
    <fields>
        <fullName>Charge_Cost_To__c</fullName>
        <label>Charge Cost To:</label>
        <picklist>
            <picklistValues>
                <fullName>Manufacturer - Replace</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Local - Remake</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer - Replace</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Variant_Number__c</fullName>
        <description>The variant number received for the product from manufacturing</description>
        <inlineHelpText>The variant number received for the product from manufacturing</inlineHelpText>
        <label>Variant Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

RbA Build/src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Master_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Master Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Sub Products</relationshipLabel>
        <relationshipName>SubProducts</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Master_Product</fullName>
        <active>true</active>
        <label>Master Product</label>
    </recordTypes>
</CustomObject>

RbA Build/src/objects/RMS_Settings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>A name value list of RMS settings</description>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>RMS Settings</label>
</CustomObject>

RbA Build/src/objects/Service_Product__c.object
<CustomObject>
    <description>Junction Object linking Master Products to Service Products</description>
    <fields>
        <fullName>Master_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Master Product</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Product2.Master_Legacy_Product__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Service Products</relationshipLabel>
        <relationshipName>Service_Products1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Service_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service Product</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Product2.RecordTypeId</field>
                <operation>equals</operation>
                <value>Service Product</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Master Products</relationshipLabel>
        <relationshipName>Service_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Service Product</label>
    <nameField>
        <displayFormat>SPA-{000000}</displayFormat>
        <label>Service Product Assignment</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

RbA Build/src/objects/Service_Symptom__c.object
<CustomObject>
    <description>The actual Service Symptom code added to the Order Item. Junction Object between Order Item and Service Symptom List</description>
    <fields>
        <fullName>Service_Product__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Service Product</label>
        <referenceTo>OrderItem</referenceTo>
        <relationshipLabel>Service Symptoms</relationshipLabel>
        <relationshipName>Service_Symptoms</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Service Symptom</label>
    <nameField>
        <displayFormat>SS-{000}</displayFormat>
        <label>Service Symptom #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Symptoms</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

RbA Build/src/objects/Store_Configuration__c.object
<CustomObject>
    <description>Holds Store Settings &amp; Configurations</description>
    <fields>
        <fullName>Store__c</fullName>
        <label>Store</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Store Configurations</relationshipLabel>
        <relationshipName>Store_Configurations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Store Configuration</label>
    <nameField>
        <displayFormat>SS-{00}</displayFormat>
        <label>Store Setting Record #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Store Configurations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

RbA Build/src/classes/testRMS_OrderItemExtension.cls
/*******************************************************//**

@class  testRMS_OrderItemExtension

@brief  Test Class for RMS_OrderItemExtension

@author  Brianne Wilson (Slalom.CDK)

@version    2015-3-15  Slalom.CDK
Created.


@copyright  (c)2016 Slalom.  All Rights Reserved. 
Unauthorized use is prohibited.

***********************************************************/
@isTest 
public with sharing class testRMS_OrderItemExtension {
    
    static testmethod void createTestRecords() {  
        RMS_Settings__c turnOffFinancialTrigger = new RMS_Settings__c(Name = 'Turn Financial Transactions Off', Value__c = 'Yes');
        insert turnOffFinancialTrigger;
        
        TestUtilityMethods utility = new TestUtilityMethods();
        utility.setUpConfigs();
        
        
        Account dwelling1 = utility.createDwellingAccount('Dwelling Account');       
        Account store1 = [SELECT Id from Account Where Name = '77 - Twin Cities, MN'];
        Store_Configuration__c storeConfig1 = [SELECT id FROM Store_Configuration__c WHERE Store__c = :store1.id ];
        dwelling1.Store_Location__c = store1.Id;         
        insert dwelling1;       
        
        Contact contact1 = new contact ( FirstName='Contact',LastName='1',AccountId=dwelling1.id);
        insert contact1;
        
        Financial_Account_Number__c finacialAccountNumber1 = new Financial_Account_Number__c (  Store_Configuration__c = storeConfig1.id, Name = '1');
        insert finacialAccountNumber1;
        Financial_Account_Number__c finacialAccountNumber2 = new Financial_Account_Number__c (  Store_Configuration__c = storeConfig1.id, Name = '2');
        insert finacialAccountNumber2;
        
        Financial_Transaction__c finacialTransaction1 = new Financial_Transaction__c(  Store_Configuration__c = storeConfig1.id,
                                                                                     Transaction_Type__c = 'Inventory Received - External Vendor',
                                                                                     Debit_Account_Number__c = finacialAccountNumber1.id,
                                                                                     Credit_Account_Number__c = finacialAccountNumber2.id);
        insert finacialTransaction1;
        
        Product2 masterProduct = new Product2( name = 'master',IsActive = true, recordTypeId=UtilityMethods.GetRecordTypeIdsMapForSObject(Product2.sObjectType).get('Master_Product'));
        Product2 servProduct = new Product2( name = 'service',IsActive = true, recordTypeId=UtilityMethods.GetRecordTypeIdsMapForSObject(Product2.sObjectType).get('Service_Product'),Master_Product__c = masterProduct.Id);
        Product2 servProduct2 = new Product2(name = 'service2',IsActive = true, recordTypeId=UtilityMethods.GetRecordTypeIdsMapForSObject(Product2.sObjectType).get('Service_Product'),Master_Product__c = masterProduct.Id);
        
        Id pricebookId = Test.getStandardPricebookId();
        system.debug(pricebookId);
        
        List<Product2> products = new List<Product2>{masterProduct,servProduct,servProduct2};
            insert products;
        PricebookEntry pricebookEntryMaster= utility.createPricebookEntry(pricebookId, masterProduct.id);     
        PricebookEntry pricebookEntryServ = utility.createPricebookEntry(pricebookId, servProduct.id);    
        PricebookEntry pricebookEntryServ2 = utility.createPricebookEntry(pricebookId, servProduct2.id);      
        List<PriceBookEntry> pbEntries = new List<PricebookEntry>{pricebookEntryMaster,pricebookEntryServ,pricebookEntryServ2};
            insert pbEntries;
        //utility.createOrderTestRecords();
        //
        
        Service_Product__c servProd1 = new Service_Product__c(name = 'service', Service_Product__c = servProduct.Id, Master_Product__c = masterProduct.Id);
        Service_Product__c servProd2 = new Service_Product__c(name = 'service2', Service_Product__c = servProduct2.Id, Master_Product__c = masterProduct.Id);
        List<Service_Product__c> sprods = new List<Service_Product__c>{servProd1,servProd2};
            insert sprods;
        
        
        List<Order> ordersToInsert = new List<Order>();
        Order order =  new Order(   Name='Sold Order 1', 
                                 AccountId = dwelling1.id, 
                                 BilltoContactId = contact1.id,
                                 EffectiveDate= Date.Today(), 
                                 Store_Location__c = store1.Id,                           
                                 Status ='Draft', 
                                 Pricebook2Id = pricebookId
                                );
        ordersToInsert.add(order);
        Order o =  new Order(     Name='Service Order 1', 
                             AccountId = dwelling1.id, 
                             EffectiveDate= Date.Today(), 
                             Store_Location__c = store1.Id,                               
                             Status ='Draft', 
                             Sold_Order__c = order.Id,
                             BilltoContactId = contact1.id,
                             Service_Type__c = 'Job in Progress',                                             
                             Pricebook2Id = pricebookId
                            );
        ordersToInsert.add(o);
        insert ordersToInsert;
        
        
        OrderItem orderItemMaster = new OrderItem(OrderId = Order.id, PricebookentryId = pricebookEntryMaster.Id, Quantity = 2, UnitPrice = 100, Charge_Cost_To__c = 'Customer-Replace' );
        insert orderItemMaster;
        
        Asset asset = new Asset (     Name='Asset1',
                                 Original_Order_Product__c = orderItemMaster.Id,
                                 Product2Id= masterProduct.Id,
                                 AccountId = dwelling1.id,
                                 ContactId = contact1.id,
                                 Variant_Number__c = '1234ABC',
                                 Unit_Wholesale_Cost__c = 200,
                                 Store_Location__c = store1.id,
                                 Quantity = 1,
                                 Price = 100,
                                 Status = 'Installed',
                                 Sold_Order__c = order.Id,
                                 PurchaseDate = Date.Today()
                                );
        
        insert asset;  
        
        
        
        OrderItem serviceOrderItem = new OrderItem(Sold_Order_Product_Asset__c = asset.Id, Installed_Product_Asset__c = asset.Id,OrderId = o.id, Parent_Order_Item__c = orderItemMaster.id, PricebookentryId = pricebookEntryServ.Id, Quanity_Ordered__c = 2, Service__c = true, Quantity = 2, UnitPrice = 100, Charge_Cost_To__c = 'Local - Remake', Primary_Reason__c = 'Goodwill', Secondary_Reason__c = 'Customer Satisfaction' );
        insert serviceOrderItem;
        
        List<Service_Symptom_List__c> ssToInsert = new List<Service_Symptom_List__c>();
        Service_Symptom_List__c ssl1 = new Service_Symptom_List__c(name='SS1');
        ssToInsert.add(ssl1);
        Service_Symptom_List__c ssl2 = new Service_Symptom_List__c(name='SS2');
        ssToInsert.add(ssl2);
        Service_Symptom_List__c ssl3 = new Service_Symptom_List__c(name='SS3');
        ssToInsert.add(ssl3);        
        insert ssToInsert;
        System.assertEquals(ssToInsert.size() , 3); 
        
        List <Service_Symptom__c> servSympToInsert = new List<Service_Symptom__c>();
        Service_Symptom__c ss1 = new Service_Symptom__c(Service_Product__c = serviceOrderItem.Id, Service_Symptom__c = ssl1.Id);
        servSympToInsert.add(ss1);
        Service_Symptom__c ss2 = new Service_Symptom__c(Service_Product__c = serviceOrderItem.Id, Service_Symptom__c = ssl2.Id);
        servSympToInsert.add(ss2);
        insert servSympToInsert;
        System.assertEquals(servSympToInsert.size(),2);      
    }
    
    static testmethod void saveCloseTabTest(){
        createTestRecords();
        Test.startTest();
        Order order = [SELECT Id,AccountId FROM Order WHERE Name = 'Service Order 1'];
        OrderItem orderItem = [SELECT Id,OrderId,Charge_Cost_To__c FROM OrderItem WHERE OrderId =: order.id];        
        
        Test.setCurrentPage(Page.RMS_editServiceProduct);
        ApexPages.StandardController sc = new ApexPages.StandardController(OrderItem);
        RMS_OrderItemExtension TE = new RMS_OrderItemExtension(sc);
        Pagereference pr = TE.saveCloseTab();        
        OrderItem oi = [select id,Charge_Cost_To__c from OrderItem where id =: orderItem.id All rows];
        System.Assertequals(oi.Charge_Cost_To__c, 'Local - Remake');
        system.assertEquals(false, ApexPages.hasMessages());
        Test.stopTest();              
    }
    
    static testmethod void orderRedirectTest(){
        createTestRecords();
        Test.startTest();
        Order order = [SELECT Id,AccountId FROM Order WHERE Name = 'Service Order 1'];
        OrderItem orderItem = [SELECT Id,OrderId,Charge_Cost_To__c,Service__c FROM OrderItem WHERE OrderId =: order.id];        
        
        Test.setCurrentPage(Page.RMS_viewOrderItemRedirect);
        ApexPages.StandardController sc = new ApexPages.StandardController(OrderItem);
        RMS_OrderItemExtension TE = new RMS_OrderItemExtension(sc);
        Pagereference pr = TE.orderItemRedirect();        
        OrderItem oi = [select id,OrderId from OrderItem where id =: orderItem.id All rows];
        System.Assertequals(oi.OrderId, order.Id);
        system.assertEquals(false, ApexPages.hasMessages());
        Test.stopTest();              
    }
    
    
    static testmethod void orderRedirectTest2(){
        createTestRecords();
        Test.startTest();
        Order order = [SELECT Id,AccountId FROM Order WHERE Name = 'Service Order 1'];
        OrderItem orderItem = [SELECT Id,OrderId,Service__c FROM OrderItem WHERE OrderId =: order.id];        
        
        Test.setCurrentPage(Page.RMS_viewOrderItemRedirect);
        ApexPages.StandardController sc = new ApexPages.StandardController(OrderItem);
        RMS_OrderItemExtension TE = new RMS_OrderItemExtension(sc);
        orderItem.Service__c = false;
        update orderItem;
        Pagereference pr = TE.orderItemRedirect();        
        OrderItem oi = [select id,OrderId from OrderItem where id =: orderItem.id All rows];
        System.Assertequals(oi.OrderId, order.Id);
        system.assertEquals(false, ApexPages.hasMessages());
        Test.stopTest();              
    }
    
    static testmethod void saveCloseTabTestError(){
        createTestRecords();
        
        Test.startTest();
        Order order = [SELECT Id,AccountId FROM Order WHERE Name = 'Service Order 1'];
        Asset asset = [Select Id FROM Asset WHERE Variant_Number__c = '1234ABC'];
        Id pricebookId = Test.getStandardPricebookId();
        Product2 masterProduct = new Product2( name = 'master',IsActive = true, recordTypeId=UtilityMethods.GetRecordTypeIdsMapForSObject(Product2.sObjectType).get('Master_Product'));
        Product2 servProduct = [SELECT Id from Product2 WHERE name = 'service'];
        PricebookEntry pricebookEntryServ = [SELECT Id FROM PricebookEntry WHERE Product2Id = :servProduct.id];
        OrderItem orderItem = new OrderItem(Installed_Product_Asset__c = asset.Id,OrderId = order.id, PricebookentryId = pricebookEntryServ.Id, Quanity_Ordered__c = 2, Service__c = true, Quantity = 2, UnitPrice = 100);
        
        
        Test.setCurrentPage(Page.RMS_editServiceProduct);
        ApexPages.StandardController sc = new ApexPages.StandardController(OrderItem);
        RMS_OrderItemExtension TE = new RMS_OrderItemExtension(sc);
        Pagereference pr = TE.saveCloseTab(); 
        Test.stopTest();
        // TODO: fix assertion
        //        system.assertEquals(true, ApexPages.hasMessages());
        
        
        
    }
    
    static testmethod void editOrderItemTest(){
        createTestRecords();
        Test.startTest();
        Order order = [SELECT Id,AccountId FROM Order WHERE Name = 'Service Order 1'];
        OrderItem orderItem = [SELECT Id,OrderId,Charge_Cost_To__c,Service__c FROM OrderItem WHERE OrderId =: order.id];        
        
        Test.setCurrentPage(Page.RMS_viewServiceOrderItem);
        ApexPages.StandardController sc = new ApexPages.StandardController(OrderItem);
        RMS_OrderItemExtension TE = new RMS_OrderItemExtension(sc);
        Pagereference pr = TE.editOrderItem();        
        OrderItem oi = [select id,OrderId from OrderItem where id =: orderItem.id All rows];
        System.Assertequals(oi.OrderId, order.Id);
        system.assertEquals(false, ApexPages.hasMessages());
        Test.stopTest();              
    }
    
    static testmethod void cancelOrderItemTest(){
        createTestRecords();
        Test.startTest();
        Order order = [SELECT Id,AccountId FROM Order WHERE Name = 'Service Order 1'];
        OrderItem orderItem = [SELECT Id,OrderId,Charge_Cost_To__c,Service__c FROM OrderItem WHERE OrderId =: order.id];        
        
        Test.setCurrentPage(Page.RMS_editServiceProduct);
        ApexPages.StandardController sc = new ApexPages.StandardController(OrderItem);
        RMS_OrderItemExtension TE = new RMS_OrderItemExtension(sc);
        Pagereference pr = TE.cancelOrderItem();        
        OrderItem oi = [select id,OrderId from OrderItem where id =: orderItem.id All rows];
        System.Assertequals(oi.OrderId, order.Id);
        system.assertEquals(false, ApexPages.hasMessages());
        Test.stopTest();              
    }
    
    static testmethod void addResponsibilityTest(){
        createTestRecords();
        Test.startTest();
        Order order = [SELECT Id,AccountId FROM Order WHERE Name = 'Service Order 1'];
        OrderItem orderItem = [SELECT Id,OrderId,Charge_Cost_To__c,Service__c FROM OrderItem WHERE OrderId =: order.id];        
        
        Test.setCurrentPage(Page.RMS_viewServiceOrderItem);
        ApexPages.StandardController sc = new ApexPages.StandardController(OrderItem);
        RMS_OrderItemExtension TE = new RMS_OrderItemExtension(sc);
        Pagereference pr = TE.addResponsibility();        
        OrderItem oi = [select id,OrderId from OrderItem where id =: orderItem.id All rows];
        System.Assertequals(oi.OrderId, order.Id);
        system.assertEquals(false, ApexPages.hasMessages());
        Test.stopTest();              
    }
    
    static testmethod void addWarrantyTest(){
        createTestRecords();
        Test.startTest();
        Order order = [SELECT Id,AccountId FROM Order WHERE Name = 'Service Order 1'];
        OrderItem orderItem = [SELECT Id,OrderId,Charge_Cost_To__c,Service__c FROM OrderItem WHERE OrderId =: order.id];        
        
        Test.setCurrentPage(Page.RMS_viewServiceOrderItem);
        ApexPages.StandardController sc = new ApexPages.StandardController(OrderItem);
        RMS_OrderItemExtension TE = new RMS_OrderItemExtension(sc);
        Pagereference pr = TE.addWarranty();        
        OrderItem oi = [select id,OrderId from OrderItem where id =: orderItem.id All rows];
        System.Assertequals(oi.OrderId, order.Id);
        system.assertEquals(false, ApexPages.hasMessages());
        Test.stopTest();              
    }
    
    static testmethod void addServiceSymptomTest(){
        createTestRecords();
        Test.startTest();
        Order order = [SELECT Id,AccountId FROM Order WHERE Name = 'Service Order 1'];
        OrderItem orderItem = [SELECT Id,Product_Name__c,Sold_Order_Product_Asset__c,Installed_Product_Name__c,OrderId,Charge_Cost_To__c,Service__c FROM OrderItem WHERE OrderId =: order.id];        
        
        Test.setCurrentPage(Page.RMS_viewServiceOrderItem);
        ApexPages.StandardController sc = new ApexPages.StandardController(OrderItem);
        RMS_OrderItemExtension TE = new RMS_OrderItemExtension(sc);
        String ssSp = orderItem.Id;
        String oiLabel = orderItem.Installed_Product_Name__c;
        Pagereference pr = TE.addServiceSymptom();        
        OrderItem oi = [select id,OrderId from OrderItem where id =: orderItem.id All rows];
        System.Assertequals(oi.OrderId, order.Id);
        system.assertEquals(false, ApexPages.hasMessages());
        Test.stopTest();              
    }
    
    
    
    
    
}