RbA Build/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Store_Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The store location that this dwelling is related</description>
        <inlineHelpText>The store location that this dwelling is related</inlineHelpText>
        <label>Store Location</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>The account must be of type &quot;Store&quot;</errorMessage>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Store</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Dwellings</relationshipLabel>
        <relationshipName>StoreLocation</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Store</fullName>
        <active>true</active>
        <description>Used to track and store data releated to Retail Locations both CORO and ARO</description>
        <label>Store</label>
    </recordTypes>
    <recordTypes>
        <fullName>Vendor</fullName>
        <active>true</active>
        <description>Used to track Vendors</description>
        <label>Vendor</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

RbA Build/src/objects/Charge__c.object
<CustomObject>
    <description>Also known as &quot;Responsibility&quot;</description>
    <fields>
        <fullName>Category__c</fullName>
        <description>Categorizes the problem in the service request</description>
        <inlineHelpText>Categorizes the problem in the service request</inlineHelpText>
        <label>Source of Defect</label>
        <picklist>
            <controllingField>Charge_Cost_To__c</controllingField>
            <picklistValues>
                <fullName>Aesthetics/Function (C)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Aesthetics/Function (R)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AW Logistics</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bayworld</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EMCO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Glass(Sash/Panel) (C)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Glass(Sash/Panel) (R)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Goodwill</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Grilles (C)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Grilles (R)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hardware (C)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hardware (R)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Renewal by Andersen</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Screens (C)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Screens (R)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unit (C)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unit (R)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Provia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Charge_Cost_To__c</fullName>
        <description>The responsible party for the service</description>
        <inlineHelpText>The responsible party for the service</inlineHelpText>
        <label>Responsibility</label>
        <picklist>
            <picklistValues>
                <fullName>Manufacturing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Retailer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Installed_Product_Id__c</fullName>
        <formula>Service_Product__r.Sold_Order_Product_Asset__r.Original_Order_Product__r.PricebookEntry.Product2Id</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Installed Product Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Installed_Product__c</fullName>
        <description>Used for UI purposes on VF page to display Installed Product Name</description>
        <formula>Service_Product__r.Sold_Order_Product_Asset__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Installed Product</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Connects the Charge record to the Order Item</description>
        <label>Service Product</label>
        <referenceTo>OrderItem</referenceTo>
        <relationshipLabel>Responsibility</relationshipLabel>
        <relationshipName>Charges</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Service_Request__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service Request</label>
        <referenceTo>Order</referenceTo>
        <relationshipLabel>Charges</relationshipLabel>
        <relationshipName>Charges</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Variant_Number__c</fullName>
        <description>The original order product&apos;s variant number.</description>
        <formula>Service_Product__r.Sold_Order_Product_Asset__r.Variant_Number__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>The original order product&apos;s variant number.</inlineHelpText>
        <label>Variant Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>What_Where__c</fullName>
        <description>Based on Responsibility and Source of Defect</description>
        <inlineHelpText>Based on Responsibility and Source of Defect</inlineHelpText>
        <label>Defect</label>
        <picklist>
            <controllingField>Category__c</controllingField>
            <picklistValues>
                <fullName>Addition</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Caulk</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Color</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Satisfaction</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Damage</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Data Entry</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Finish</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Handing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Operation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Out of Warranty</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pattern</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Size</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Stain</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Style</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Trim</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wrap</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Charge</label>
    <nameField>
        <displayFormat>CCT-{000}</displayFormat>
        <label>Charge Cost Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Charges</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

RbA Build/src/objects/Order.object
<CustomObject>
    <fields>
        <fullName>Store_Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This order is related to this store location.</description>
        <inlineHelpText>This order is related to this store location.</inlineHelpText>
        <label>Store Location</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Orders (Store Location)</relationshipLabel>
        <relationshipName>Orders1</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

RbA Build/src/objects/OrderItem.object
<CustomObject>
    <fields>
        <fullName>Charge_Cost_To__c</fullName>
        <label>Charge Cost To:</label>
        <picklist>
            <picklistValues>
                <fullName>Manufacturer - Replace</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Local - Remake</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer - Replace</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Purchase_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The purchase order that covers this sales order line item</description>
        <inlineHelpText>The purchase order that covers this sales order line item</inlineHelpText>
        <label>Purchase Order</label>
        <referenceTo>Purchase_Order__c</referenceTo>
        <relationshipLabel>Order Products</relationshipLabel>
        <relationshipName>Order_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Variant_Number__c</fullName>
        <description>The variant number received for the product from manufacturing</description>
        <inlineHelpText>The variant number received for the product from manufacturing</inlineHelpText>
        <label>Variant Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

RbA Build/src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Vendor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Vendor</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>Products</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

RbA Build/src/objects/Purchase_Order__c.object
<CustomObject>
    <description>The purchase order header for ordering RbA and 3rd party products linked to order line items</description>
    <fields>
        <fullName>Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The parent sales order of this purchase order</description>
        <inlineHelpText>The parent sales order of this purchase order</inlineHelpText>
        <label>Order</label>
        <referenceTo>Order</referenceTo>
        <relationshipLabel>Purchase Orders</relationshipLabel>
        <relationshipName>Purchase_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Vendor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The vendor linked to the PO</description>
        <inlineHelpText>The vendor linked to the PO</inlineHelpText>
        <label>Vendor</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>The account must be of type Vendor.</errorMessage>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Vendor</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Purchase Orders</relationshipLabel>
        <relationshipName>Purchase_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Purchase Order</label>
    <nameField>
        <label>Purchase Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Purchase Orders</pluralLabel>
    <recordTypes>
        <fullName>Service_Purchase_Order</fullName>
        <active>true</active>
        <label>Service Purchase Order</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

RbA Build/src/objects/Service_Product__c.object
<CustomObject>
    <description>Junction Object linking Master Products to Service Products</description>
    <fields>
        <fullName>Service_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service Product</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Product2.RecordTypeId</field>
                <operation>equals</operation>
                <value>Service Product</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Master Products</relationshipLabel>
        <relationshipName>Service_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Service Product</label>
    <nameField>
        <displayFormat>SPA-{000000}</displayFormat>
        <label>Service Product Assignment</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

RbA Build/src/objects/Vendor_Product__c.object
<CustomObject>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Select the product that you want to associate with the vendor.</description>
        <inlineHelpText>Select the product that you want to associate with the vendor.</inlineHelpText>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Vendor Products</relationshipLabel>
        <relationshipName>Vendor_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Vendor__c</fullName>
        <description>Select the vendor that should be related to the product.</description>
        <inlineHelpText>Select the vendor that should be related to the product.</inlineHelpText>
        <label>Vendor</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Vendor Products</relationshipLabel>
        <relationshipName>Vendor_Products</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Vendor Product</label>
    <nameField>
        <displayFormat>VP-{000000}</displayFormat>
        <label>Vendor Product Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vendor Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

RbA Build/src/classes/RMS_createServicePurchaseOrdersExtension.cls
/*******************************************************//**

@class  RMS_createServicePurchaseOrdersExtension

@brief  Controller Extension for RMS_createServicePurchaseOrders visualforce page

@author  Creston Kuenzi (Slalom.CDK)

@version    2016-9-16  Slalom.CDK
Created.

@copyright  (c)2016 Slalom.  All Rights Reserved. 
Unauthorized use is prohibited.

***********************************************************/
public with sharing class RMS_createServicePurchaseOrdersExtension {

	/******* Variables  *****************/
	public String errorOccurred {get; set;}   
	public String newpoId {get;set;}
	public String orderId {get;set;}

	// The map of Charge Vendors to existing PO Ids
	public Map<String,Id> chargeVendorExistingPOMap = new Map<String,Id>();

	// The list of Charge Wrappers
	public List<ChargeWrapper> chargesWrapperList
	{
		get	{
			if ( chargesWrapperList != null) return chargesWrapperList;
			chargesWrapperList = new List<ChargeWrapper>();
			for (Charge__c c : [SELECT Id, Service_Request__c, Service_Product__r.Product_Name__c, Service_Product__c, 
								Service_Product__r.Purchase_Order__c, Installed_Product_Id__c, Charge_Cost_To__c, Installed_Product__c,
								Variant_Number__c, Category__c, What_Where__c, Service_Product__r.Purchase_Order__r.Vendor__c,
								Service_Product__r.Order.Store_Location__c, Service_Product__r.Purchase_Order__r.Charge_Cost_To__c,
								Service_Product__r.Sold_Order_Product_Asset__r.Original_Order_Product__c
								from Charge__c Where Service_Request__c =: serviceRequest.Id AND Service_Product__c != null]) {
				boolean poExists = false;
				boolean isChecked = false;
	
				if (c.Service_Product__r.Purchase_Order__c != null) {
					poExists = true;
					chargeVendorExistingPOMap.put(c.Service_Product__r.Purchase_Order__r.Charge_Cost_To__c + c.Service_Product__r.Purchase_Order__r.Vendor__c, c.Service_Product__r.Purchase_Order__c);
					if (c.Charge_Cost_To__c == c.Service_Product__r.Purchase_Order__r.Charge_Cost_To__c)
						isChecked = true;
				}
				chargesWrapperList.add(new chargeWrapper(isChecked, poExists, c));
			}
			System.Debug('*****************chargesWrapperList=' +chargesWrapperList);
			return chargesWrapperList;
		}
		set;
	}

	// The set of installed product Ids
	public set<Id> installedProductIds 
	{
		get	{
			if ( installedProductIds != null) return installedProductIds;
			installedProductIds = new set<Id>();
			for (chargeWrapper cw : chargesWrapperList) {
				installedProductIds.add(cw.charge.Service_Product__r.Sold_Order_Product_Asset__r.Original_Order_Product__c);	
			}
			return installedProductIds;
		}
		set;
	}

	// The map of service product id to vendor id
	public map<Id,Id> productToVendorMap 
	{
		get	{
			if ( productToVendorMap != null) return productToVendorMap;
			productToVendorMap = new map<Id,Id>();
			for (OrderItem oi : [SELECT Id, PricebookEntry.Product2Id, Purchase_Order__r.Vendor__c FROM OrderItem
										WHERE Id IN : InstalledProductIds]) 
			{
				if (oi.PricebookEntry.Product2Id != null && oi.Purchase_Order__r.Vendor__c != null)
					productToVendorMap.put(oi.PricebookEntry.Product2Id,oi.Purchase_Order__r.Vendor__c);
			}
/*			for (Vendor_Product__c vp : [SELECT Product__c, Vendor__c FROM Vendor_Product__c 
										WHERE Product__c IN : InstalledProductIds]) 
			{
				productToVendorMap.put(vp.Product__c,vp.Vendor__c);
			}*/


			return productToVendorMap;
		}
		set;
	}

	// The set of installed product Ids
	public set<Id> serviceProductIds 
	{
		get	{
			if ( serviceProductIds != null) return serviceProductIds;
			serviceProductIds = new set<Id>();
			for (chargeWrapper cw : chargesWrapperList) {
				serviceProductIds.add(cw.charge.Service_Product__c);	
			}
			return serviceProductIds; 
		}
		set;
	}

	// The map of service product id to vendor id
	public map<Id,OrderItem> serviceProductMap 
	{
		get	{
			if ( serviceProductMap != null) return serviceProductMap;
			serviceProductMap = new map<Id,OrderItem>();
			for (OrderItem oi : [SELECT Id, Purchase_Order__c, Sold_Order_Product_Asset__r.Variant_Number__c,
									Sold_Order_Product_Asset__r.Product_Name__c 
								FROM OrderItem
								WHERE Id IN : serviceProductIds])
			{
				serviceProductMap.put(oi.Id, oi );
			}
			return serviceProductMap;
		}
		set;
	}

	/******* Set up Standard Controller for Order  *****************/
	private Apexpages.StandardController standardController;
	@testVisible private final order serviceRequest;

	/******* Constructor  *****************/
	public RMS_createServicePurchaseOrdersExtension(ApexPages.StandardController stdController) {
		this.serviceRequest = (Order)stdController.getRecord();
		orderId = this.serviceRequest.Id;
	}


    public PageReference cancel(){
        return null;
    } 

	public PageReference save(){
		system.debug('*****Saving the POs: ');

		// Set this flag to true so we know to exit the javascript before redirecting
		errorOccurred = 'true';

	    //list<OrderItem> orderItemsToUpdateList = new list<OrderItem>();
//		map<Id, Id> orderItemsToUpdateMap = new map<Id,Id>();
//		list<Purchase_Order__c> posToInsert = new list<Purchase_Order__c>();
		Set<Id> serviceProductsSelected = new Set<Id>();
		List<OrderItem> orderItemsToUpdate = new List<OrderItem>();
//		Map<OrderItem, Purchase_Order__c> orderItemPOMap = new Map<OrderItem, Purchase_Order__c>();
		// The map of Charge Vendors to new POs
		Map<String,Purchase_Order__c> chargeVendorNewPOMap = new Map<String,Purchase_Order__c>();
		Map<OrderItem, String> orderItemChargeVendorMap = new Map<OrderItem, String>();
		Id poId;
		// Loop through all of the charge wrappers
		for(ChargeWrapper cw : chargesWrapperList){
			// If the charge was not selected, just continue
			if (!cw.isSelected) continue;
		
			// Check and see if a charge has already been selected for this product,
			// and if so, throw an error and return
			if (serviceProductsSelected.contains(cw.charge.Service_Product__c)) {
				ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, RMS_ErrorMessages.DUPLICATE_SERVICE_PRODUCTS + cw.charge.Service_Product__r.Product_Name__c));
				return null;
			}

			// Put the service product id in the set for checking against other selected charges.
			serviceProductsSelected.add(cw.charge.Service_Product__c);
		
			// If the charge is disabled (meaning a PO has already been created) just continue
			if (cw.isDisabled) continue;

			System.Debug('*************chargeVendorExistingPOMap)=' +chargeVendorExistingPOMap);
			System.Debug('*************cw.charge.Charge_Cost_To__c)=' +cw.charge.Charge_Cost_To__c);
			System.Debug('*************cw.charge.Service_Product__r.Purchase_Order__r.Vendor__c)=' +cw.charge.Service_Product__r.Purchase_Order__r.Vendor__c);
			System.Debug('*************cw.charge.Installed_Product_Id__c=' +cw.charge.Installed_Product_Id__c);
			System.Debug('*************productToVendorMap.get(cw.charge.Installed_Product_Id__c)=' +productToVendorMap.get(cw.charge.Installed_Product_Id__c));

			if (cw.charge.Installed_Product_Id__c == null || productToVendorMap.get(cw.charge.Installed_Product_Id__c) == null)	{
				ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, RMS_ErrorMessages.VENDOR_NOT_FOUND +cw.charge.Service_Product__r.Product_Name__c));
				return null;				
			}	
		
			System.Debug('*************here 1');

			// Attempt to retrieve the purchase order from the charge vendor map
			poId = chargeVendorExistingPOMap.get(cw.charge.Charge_Cost_To__c + productToVendorMap.get(cw.charge.Installed_Product_Id__c));
			
			// If we were able to find an existing purchase order then add the service
			// product in a map so we can update it with the Purchase Order later
			if (poId != null) {
				OrderItem itemToUpdate = serviceProductMap.get(cw.charge.Service_Product__c);
				itemToUpdate.Purchase_Order__c = poId;
				orderItemsToUpdate.add(itemToUpdate);
				continue;
			}
			System.Debug('*************here 2');

			// Now check if there is a new PO already pending for this charge cost to and vendor
			if (chargeVendorNewPOMap.containsKey(cw.charge.Charge_Cost_To__c + productToVendorMap.get(cw.charge.Installed_Product_Id__c))) {
				//Put the order item in a map to the charge cost to and vendor
				OrderItem itemToUpdate = serviceProductMap.get(cw.charge.Service_Product__c);
				orderItemChargeVendorMap.put(itemToUpdate, cw.charge.Charge_Cost_To__c + productToVendorMap.get(cw.charge.Installed_Product_Id__c));
				continue;
			}

			String storeAbbreviation = returnStoreAbbreviation();
			
			// There was not a pending PO already so now create one and put it in the newPO map
			Purchase_Order__c newPurchaseOrder = new Purchase_Order__c(
													Vendor__c = ProductToVendorMap.get(cw.charge.Installed_Product_Id__c),
													Order__c = this.serviceRequest.Id,
													Store_Location__c = cw.charge.Service_Product__r.Order.Store_Location__c, 
													Status__c = 'In Progress',
													Charge_Cost_To__c = cw.charge.Charge_Cost_To__c,
													Store_Abbreviation__c = storeAbbreviation,
													RecordTypeId = UtilityMethods.RecordTypeFor('Purchase_Order__c', 'Service_Purchase_Order')
												);

			System.Debug('*************here 3');

			// Now put the new purchase order in the charge vendor map
			chargeVendorNewPOMap.put(cw.charge.Charge_Cost_To__c + productToVendorMap.get(cw.charge.Installed_Product_Id__c), newPurchaseOrder);
			// Pull the order item from the serviceproduct map and put it in a different map with charge vendor
			OrderItem itemToUpdate = serviceProductMap.get(cw.charge.Service_Product__c);
			orderItemChargeVendorMap.put(itemToUpdate, cw.charge.Charge_Cost_To__c + productToVendorMap.get(cw.charge.Installed_Product_Id__c));
//			orderItemPOMap.put(itemToUpdate, newPurchaseOrder);
			
		// then create a po and a map with the actual po
		// also create a map of po to list of service products		

		// if we don't find the po, create a po then put in a different map with charge cost to and vendor?
		// Which means we have to check that map before creating it

		// Create a PO and put it in the list to insert

		}
        try{
//       		insert orderItemPOMap.values();
			// Now insert the new POs first
			System.Debug('*************here 4');
       		insert chargeVendorNewPOMap.values();
			System.Debug('*************here 5');

			// Then loop through the order items with a new po
       		for(OrderItem oi : orderItemChargeVendorMap.keyset()) {
				// Retrieve the charge vendor for the order item and then use that to 
				// retrieve the new PO
       			String chargeVendor = orderItemChargeVendorMap.get(oi);
       			Purchase_Order__c po = chargeVendorNewPOMap.get(chargeVendor);
//       			Purchase_Order__c po = orderItemPOMap.get(oi);

				// Set the order item purchase order lookup to the po id
       			oi.Purchase_Order__c = po.Id;
       			
       			// Set the remake flag on the order item if the charge cost to is local
				oi.Remake__c = (po.Charge_Cost_To__c == 'Retailer') ? true : false;
				// Set the order item description
				oi.Description = (oi.Sold_Order_Product_Asset__r.Product_Name__c == null) ? '' : oi.Sold_Order_Product_Asset__r.Product_Name__c + ' - ';
				oi.Description = (oi.Sold_Order_Product_Asset__r.Variant_Number__c == null) ? oi.Description : oi.Description + oi.Sold_Order_Product_Asset__r.Variant_Number__c;
       			newpoId = oi.Purchase_Order__c;
       			orderItemsToUpdate.add(oi);
       		}
       		if (newpoId == null) newpoId = poId;
          	upsert orderItemsToUpdate;
        } catch (Exception e){
          System.debug('************The following exception occurred in the RMS_createServicePurchaseOrderExtension in the save method inserting records:' + e);
          ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, RMS_ErrorMessages.SAVE_PO_EXCEPTION));
          return null;
        }

		errorOccurred = 'false';
		return null;    
	} 


/*	public PageReference save(){
		system.debug('*****Saving the POs: ');

		// Set this flag to true so we know to exit the javascript before redirecting
		errorOccurred = 'true';

	    //list<OrderItem> orderItemsToUpdateList = new list<OrderItem>();
		map<Id, Id> orderItemsToUpdateMap = new map<Id,Id>();
		list<Purchase_Order__c> posToInsert = new list<Purchase_Order__c>();
		Set<Id> serviceProductsSelected = new Set<Id>();
		List<OrderItem> orderItemsToUpdate = new List<OrderItem>();
		Map<OrderItem, Purchase_Order__c> orderItemPOMap = new Map<OrderItem, Purchase_Order__c>();
		Id poId;
		// Loop through all of the charge wrappers
		for(ChargeWrapper cw : chargesWrapperList){
			// If the charge was not selected, just continue
			if (!cw.isSelected) continue;
		
			// Check and see if a charge has already been selected for this product,
			// and if so, throw an error and return
			if (serviceProductsSelected.contains(cw.charge.Service_Product__c)) {
				ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, RMS_ErrorMessages.DUPLICATE_SERVICE_PRODUCTS + cw.charge.Service_Product__r.Product_Name__c));
				return null;
			}
		
			// Put the service product id in the set for checking against other selected charges.
			serviceProductsSelected.add(cw.charge.Service_Product__c);
		
			// If the charge is disabled (meaning a PO has already been created) just continue
			if (cw.isDisabled) continue;
		
			System.Debug('*************chargeVendorExistingPOMap)=' +chargeVendorExistingPOMap);
			System.Debug('*************cw.charge.Charge_Cost_To__c)=' +cw.charge.Charge_Cost_To__c);
			System.Debug('*************cw.charge.Service_Product__r.Purchase_Order__r.Vendor__c)=' +cw.charge.Service_Product__r.Purchase_Order__r.Vendor__c);

			// Attempt to retrieve the purchase order from the charge vendor map
			poId = chargeVendorExistingPOMap.get(cw.charge.Charge_Cost_To__c + cw.charge.Service_Product__r.Purchase_Order__r.Vendor__c);
			
			// If we were able to find an existing purchase order then add the service
			// product in a map so we can update it with the Purchase Order later
			if (poId != null) {
				OrderItem itemToUpdate = serviceProductMap.get(cw.charge.Service_Product__c);
				itemToUpdate.Purchase_Order__c = poId;
				orderItemsToUpdate.add(itemToUpdate);
				continue;
			}

			// Loop through 
			String storeAbbreviation = returnStoreAbbreviation();
			
			Purchase_Order__c newPurchaseOrder = new Purchase_Order__c(
													Vendor__c = ProductToVendorMap.get(cw.charge.Installed_Product_Id__c),
													Order__c = this.serviceRequest.Id,
													Store_Location__c = cw.charge.Service_Product__r.Order.Store_Location__c, 
													Status__c = 'In Progress',
													Charge_Cost_To__c = cw.charge.Charge_Cost_To__c,
													Store_Abbreviation__c = storeAbbreviation,
													RecordTypeId = UtilityMethods.RecordTypeFor('Purchase_Order__c', 'Service_Purchase_Order')
												);
			OrderItem itemToUpdate = serviceProductMap.get(cw.charge.Service_Product__c);
			orderItemPOMap.put(itemToUpdate, newPurchaseOrder);
			
		// then create a po and a map with the actual po
		// also create a map of po to list of service products		

		// if we don't find the po, create a po then put in a different map with charge cost to and vendor?
		// Which means we have to check that map before creating it

		// Create a PO and put it in the list to insert

		}
        try{
       		insert orderItemPOMap.values();
       		for(OrderItem oi : orderItemPOMap.keyset()) {
       			System.Debug('*************orderItemPOMap.get(oi)=' +orderItemPOMap.get(oi).Charge_Cost_To__c);
       			Purchase_Order__c po = orderItemPOMap.get(oi);
       			oi.Purchase_Order__c = po.Id;
       			
       			// Set the remake flag on the order item if the charge cost to is local
				oi.Remake__c = (po.Charge_Cost_To__c == 'Retailer') ? true : false;
				// Set the order item description
				oi.Description = (oi.Sold_Order_Product_Asset__r.Product_Name__c == null) ? '' : oi.Sold_Order_Product_Asset__r.Product_Name__c + ' - ';
				oi.Description = (oi.Sold_Order_Product_Asset__r.Variant_Number__c == null) ? oi.Description : oi.Description + oi.Sold_Order_Product_Asset__r.Variant_Number__c;
       			newpoId = oi.Purchase_Order__c;
       			orderItemsToUpdate.add(oi);
       		}
       		if (newpoId == null) newpoId = poId;
          	upsert orderItemsToUpdate;
        } catch (Exception e){
          System.debug('************The following exception occurred in the RMS_createServicePurchaseOrderExtension in the save method inserting records:' + e);
          ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, RMS_ErrorMessages.SAVE_PO_EXCEPTION));
          return null;
        }

		errorOccurred = 'false';
		return null;    
	} */
	/*******************************************************
			setStoreAbbreviation method
	*******************************************************/
	public String returnStoreAbbreviation() {
 
		// Retrive the current user
		User currentUser = [SELECT User_Abbreviation__c FROM User WHERE Id =: UserInfo.getUserId()];

		// If a test is running just set the user's abbreviation, otherwise get it from the current user
		String userAbbreviation = (Test.isRunningTest()) ?   'A' 
								: 	String.isBlank(currentUser.User_Abbreviation__c) ? 'X'
								:	currentUser.User_Abbreviation__c;

		// Set the type of PO
		String typeAbbreviation = 'S';

		String storeAbbreviation;
			
		// Query the store location to retrieve the store abbreviation and location number
		for (Account storeLocAccount : [SELECT 	Id, Name, Active_Store_Configuration__r.Store_Abbreviation__c, 
										Active_Store_Configuration__c, Active_Store_Configuration__r.Location_Number__c
										FROM Account WHERE Id = :serviceRequest.Store_Location__c]){
			if (storeLocAccount.Active_Store_Configuration__c != null) {
				storeAbbreviation = storeLocAccount.Active_Store_Configuration__r.Store_Abbreviation__c;
			}
		}
		// Set a default store abbreviation if it's null
		if (storeAbbreviation == null) storeAbbreviation = 'X';
		
		// concatanate the store abbreviation and return it
		return storeAbbreviation + userAbbreviation + typeAbbreviation;
	}
	/*******************************************************
			chargesWrapper Class
	*******************************************************/
	public class ChargeWrapper{
		public boolean isSelected {get; set;}
		public boolean isDisabled {get; set;}
		public Charge__c charge {get; set;}

		public ChargeWrapper(boolean sel, boolean dis, Charge__c ch) {
			isSelected =sel;
			isDisabled = dis;
			charge = ch;
		}
		public ChargeWrapper() {}
	} 

}