RbA Build/src/objects/Asset.object
<CustomObject>
    <fields>
        <fullName>Variant_Number__c</fullName>
        <description>The variant number for this asset.</description>
        <inlineHelpText>The variant number for this asset.</inlineHelpText>
        <label>Variant Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

RbA Build/src/objects/Order.object
<CustomObject>
    <recordTypes>
        <fullName>CORO_Service</fullName>
        <active>true</active>
        <description>CORO Service Records</description>
        <label>CORO Service</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

RbA Build/src/objects/OrderItem.object
<CustomObject>
    <fields>
        <fullName>Defect_Code__c</fullName>
        <label>Defect Code</label>
        <picklist>
            <picklistValues>
                <fullName>Bowed/Warped/Twisted/Bent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Broken</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cracked</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dented</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Color/Finish</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fillet Bead</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gouged</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hard Operating</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Imperfection</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hour Glass</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rattle</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>M &amp; T</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NEED TO ADD ADDTIONAL VALUES</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Installed_Product_Asset__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Installed Product Asset</label>
        <referenceTo>Asset</referenceTo>
        <relationshipLabel>Order Products</relationshipLabel>
        <relationshipName>Order_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MTO_Source_Code__c</fullName>
        <label>MTO Source Code</label>
        <picklist>
            <picklistValues>
                <fullName>Astraga/Interlock</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Balancer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Stop Covers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GBG</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Exterior Grille</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Frame</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Glass</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sash (Rails and Stiles)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Interior Grille</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Liner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Screen</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Specialty Window Trim/EJ/Casing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ALL VALUES ENTERED FROM PIVOTAL</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Purchase_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The purchase order that covers this sales order line item</description>
        <inlineHelpText>The purchase order that covers this sales order line item</inlineHelpText>
        <label>Purchase Order</label>
        <referenceTo>Purchase_Order__c</referenceTo>
        <relationshipLabel>Order Products</relationshipLabel>
        <relationshipName>Order_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quanity_Ordered__c</fullName>
        <label>Quanity Ordered</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Variant_Number__c</fullName>
        <description>The variant number received for the product from manufacturing</description>
        <inlineHelpText>The variant number received for the product from manufacturing</inlineHelpText>
        <label>Variant Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

RbA Build/src/objects/Product2.object
<CustomObject>
    <recordTypes>
        <fullName>Master_Product</fullName>
        <active>true</active>
        <label>Master Product</label>
    </recordTypes>
</CustomObject>

RbA Build/src/objects/Purchase_Order__c.object
<CustomObject>
    <description>The purchase order header for ordering RbA and 3rd party products linked to order line items</description>
    <label>Purchase Order</label>
    <nameField>
        <label>Purchase Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Purchase Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

RbA Build/src/classes/RMS_viewServiceOrderProductsCtlr.cls
/*******************************************************//**

@class  RMS_viewServiceOrderProductsCtlr

@brief  Controller for RMS_viewServiceOrderProducts visualforce page
which is embedded in the View Service Request page.

@author  Brianne Wilson (Slalom.CDK)

@version    2016-2-18  Slalom.CDK
Created.

@copyright  (c)2016 Slalom.  All Rights Reserved. 
Unauthorized use is prohibited.

***********************************************************/
public with sharing class RMS_viewServiceOrderProductsCtlr {
    
    public final Order ord;
    public Map<Id,OrderItem> orderItems {get;set;}
    public List<OrderItemWrapper> orderItemWrappers{get;set;}
    public Id masterProductId = UtilityMethods.GetRecordTypeIdsMapForSObject(Product2.sObjectType).get('Master_Product');    
    public Id servProd = UtilityMethods.GetRecordTypeIdsMapForSObject(Product2.sObjectType).get('Service_Product');    
    public Id serviceOrderId = UtilityMethods.GetRecordTypeIdsMapForSObject(Order.sObjectType).get('CORO_Service');
    public String baseURL{get;set;}
    public String addProductURL{get;set;}
    public String editOIURL{get;set;}
    public Id orderItemToToggle{get;set;}
    public integer num_assets;
    public String orderURL{get;set;}
    public String accountURL{get;set;}
    
    public RMS_viewServiceOrderProductsCtlr(ApexPages.StandardController stdController) {
        /*if(!test.isRunningTest()){
stdController.addFields(new List<String>{'PriceBook2Id','RecordTypeId'});
}*/
        this.ord = (Order)stdController.getRecord();
        
        baseUrl = URL.getSalesforceBaseUrl().toExternalForm();
        orderURL = '/'+'{!ord.Id}';
            accountURL = '/'+'{!ord.AccountId}';
        
                orderItems =  new Map<Id,OrderItem>([select Id, PricebookEntry.Product2Id, PricebookEntry.Product2.Name, Purchase_Order__c, 
                                             Variant_Number__c,
                    //                         Quanity_Ordered__c, MTO_Source_Code__c, Sold_Order_Product_Asset__r.Name, Defect_Code__c, Installed_Product_Asset__c, Installed_Product_Asset__r.Name 
                                             Quanity_Ordered__c, Sold_Order_Product_Asset__r.Name, Installed_Product_Asset__c, Installed_Product_Asset__r.Name 
                                             from OrderItem 
                                             where OrderId =: ord.Id 
                                             and PricebookEntry.Product2.RecordTypeId =: servProd
                                             ORDER BY Sold_Order_Product_Asset__r.Name , PricebookEntry.Product2.Name]);
        
        orderItemWrappers = new List<OrderItemWrapper>();
        for(OrderItem oi: orderItems.values()){
            orderItemWrappers.add(new OrderItemWrapper(oi));
        }
        system.debug(orderItemWrappers);
        
        List<AggregateResult> results2=[select COUNT (Id) 
                                        FROM Asset 
                                        WHERE AccountId = :ord.AccountId];
        num_assets = (Integer) results2[0].get('expr0');
        
        system.debug(orderItemWrappers);  
        
        
        if(ord.RecordTypeId == serviceOrderId){
            if(num_assets > 0){
                addProductURL = '/apex/RMS_addServiceProduct?id=' + ord.Id;                
            } else {
                addProductURL = '/apex/RMS_addServiceProductLegacy?id=' + ord.Id;                  
            }
            
        }else{
            addProductURL = '/apex/rms_ProdConfigEdit?oid='+ord.Id+'&pid='+ord.Pricebook2Id +'&mode=e';
        }
        
        
    }
    
    
    public class OrderItemWrapper{
        public OrderItem orderItem{get;set;}
        
        
        public OrderItemWrapper(OrderItem oi){
            orderItem = oi;
            
        }
    }
    
    public PageReference addProductPage(){
        PageReference newPage;
        
        if(ord.RecordTypeId == serviceOrderId){
            if(num_assets > 0){
                newPage = new PageReference('/apex/RMS_addServiceProduct?id=' + ord.Id);                
            } else {
                newPage = new PageReference('/apex/RMS_addServiceProductLegacy?id=' + ord.Id);                  
            }
            
        }else{
            newPage = new PageReference('/apex/rms_ProdConfigEdit?oid='+ord.Id+'&pid='+ord.Pricebook2Id +'&mode=e');
        }
        newPage.setRedirect(true); 
        return newPage;
    }
    
    
}