RbA Build/src/objects/Back_Office_Check__c.object
<CustomObject>
    <description>Junction Object between the Back Office Checklist Configurations and Order.  Keeps the history of items that need to checked in order for the order move through the process.</description>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <referenceTo>Order</referenceTo>
        <relationshipLabel>Back Office Checks</relationshipLabel>
        <relationshipName>Back_Office_Checks</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Back Office Check</label>
    <nameField>
        <label>Back Office Check Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Back Office Checks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

RbA Build/src/classes/RMS_editBackOfficeCheckRedirectExtTest.cls
/*******************************************************//**

@class	RMS_editBackOfficeCheckRedirectExtTest

@brief	Test Class for RMS_editBackOfficeCheckRedirectExt

@author  Creston Kuenzi (Slalom.CDK)

@version	2016-10-13  Slalom.CDK
	Created.

@see		RMS_editBackOfficeCheckRedirectExt

@copyright  (c)2016 Slalom.  All Rights Reserved. 
			Unauthorized use is prohibited.

***********************************************************/
@isTest
private class RMS_editBackOfficeCheckRedirectExtTest {

	/*******************************************************
					redirectTestWithOrder
	*******************************************************/
	static testmethod void redirectTestFromOrder(){
		TestUtilityMethods utility = new TestUtilityMethods();
		
		utility.createOrderTestRecords();

		Back_Office_Check__c b = new Back_Office_Check__c();
		Order soldOrder = [SELECT Id FROM Order WHERE Name = 'Sold Order 1'];
		b.Order__c = soldOrder.Id;


		PageReference pageRef = Page.RMS_editBackOfficeCheckRedirect;
		Test.setCurrentPage(pageRef);

		ApexPages.StandardController stdController = new ApexPages.StandardController(b);
		RMS_editBackOfficeCheckRedirectExtension customController  = new RMS_editBackOfficeCheckRedirectExtension(stdController);
				
		customController.redirect();
		
	}
	/*******************************************************
					redirectTestWithoutOrder
	*******************************************************/
	static testmethod void redirectTestWithoutOrder(){
		TestUtilityMethods utility = new TestUtilityMethods();
		
		utility.createOrderTestRecords();

		Back_Office_Check__c b = new Back_Office_Check__c();

		PageReference pageRef = Page.RMS_editBackOfficeCheckRedirect;
		Test.setCurrentPage(pageRef);
		ApexPages.StandardController stdController = new ApexPages.StandardController(b);
		RMS_editBackOfficeCheckRedirectExtension customController  = new RMS_editBackOfficeCheckRedirectExtension(stdController);
		
		customController.redirect();

	}
}