RbA Build/src/objects/Back_Office_Check__c.object
<CustomObject>
    <description>Junction Object between the Back Office Checklist Configurations and Order.  Keeps the history of items that need to checked in order for the order move through the process.</description>
    <fields>
        <fullName>Completed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Completed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <referenceTo>Order</referenceTo>
        <relationshipLabel>Back Office Checks</relationshipLabel>
        <relationshipName>Back_Office_Checks</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Signed_Date__c</fullName>
        <inlineHelpText>Date the document was signed.</inlineHelpText>
        <label>Signed Date</label>
        <type>Date</type>
    </fields>
    <label>Back Office Check</label>
    <nameField>
        <label>Back Office Check Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Back Office Checks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

RbA Build/src/classes/RMS_completeOrderChecksController.cls
public with sharing class RMS_completeOrderChecksController {

    public list<Back_Office_Check__c> selectedChecks {get;set;}
    public Id ordId;
    //selected
    public RMS_completeOrderChecksController(ApexPages.StandardSetController controller) {
        //controller.setPageSize(20);
        
        ordId = ApexPages.currentPage().getParameters().get('Id');
        List<Back_Office_Check__c> relatedBOC = [SELECT Id, Name, Completed__c, Signed_Date__c, Order__c FROM Back_Office_Check__c WHERE Order__c = :ordId ];
        selectedChecks = relatedBOC;

    }
    
    public pageReference save(){
    	update selectedChecks;
    	
    	PageReference newPage = New PageReference('/'+ordId);
		newPage.setRedirect(true);
		return newPage;
    }
}