RbA Build/src/objects/Back_Office_Check__c.object
<CustomObject>
    <description>Junction Object between the Back Office Checklist Configurations and Order.  Keeps the history of items that need to checked in order for the order move through the process.</description>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <referenceTo>Order</referenceTo>
        <relationshipLabel>Back Office Checks</relationshipLabel>
        <relationshipName>Back_Office_Checks</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Back Office Check</label>
    <nameField>
        <label>Back Office Check Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Back Office Checks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

RbA Build/src/classes/RMS_editBackOfficeCheckRedirectExtension.cls
/*******************************************************//**

@class	  RMS_editBackOfficeCheckRedirectExtension

@brief	  Extension for redirecting the user when clicking the Edit Back Office Check links

	Redirects the user to the Back Office Checklist visualforce page

@author	 Creston Kuenzi (Slalom.CDK)

@version	2016-10-13  Slalom.CDK
	Created

@see		RMS_editBackOfficeCheckRedirectExtension

@copyright  (c)2016 Slalom.  All Rights Reserved.
			Unauthorized use is prohibited.

***********************************************************/

public with sharing class RMS_editBackOfficeCheckRedirectExtension {

	/******* Set up Standard Controller for Back_Office_Check__c  *****************/
	private final Back_Office_Check__c theCheck;
	
	public RMS_editBackOfficeCheckRedirectExtension(ApexPages.StandardController stdController) {
		this.theCheck = (Back_Office_Check__c)stdController.getRecord();
		if (this.theCheck == null)
			this.theCheck = new Back_Office_Check__c(); 
	}

	/******* redirect method  *****************/
	public PageReference redirect() {

		String newPageUrl = '/apex/RMS_completeOrderChecks?Id=' +theCheck.Order__c;
		PageReference newPage = new PageReference(newPageUrl);
		newPage.setRedirect(true);
		return newPage;
	}
	
}