RbA Build/src/objects/Change_History__c.object
<CustomObject>
    <fields>
        <fullName>Changes__c</fullName>
        <label>Changes</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>RbA_Work_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>RbA Work Order</label>
        <referenceTo>RbA_Work_Order__c</referenceTo>
        <relationshipLabel>Change Histories</relationshipLabel>
        <relationshipName>Change_Histories</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Change History</label>
    <nameField>
        <displayFormat>CH-{0000000}</displayFormat>
        <label>Change History Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Change Histories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

RbA Build/src/objects/RbA_Work_Order__c.object
<CustomObject>
    <description>Custom Object used to track Work Orders related to Orders.</description>
    <fields>
        <fullName>Cancel_Date__c</fullName>
        <label>Cancel Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Cancel_Reason__c</fullName>
        <label>Cancel Reason</label>
        <picklist>
            <picklistValues>
                <fullName>Weather</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Family Emergency</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Schedule Conflict</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Resource Constraint</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Order Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Project On Hold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Homeowner Request</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Duplicate</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>RbA Work Order</label>
    <nameField>
        <displayFormat>WO-{00000000}</displayFormat>
        <label>Work Order #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RbA Work Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

RbA Build/src/classes/RMS_eventManager.cls
public with sharing class RMS_eventManager {
	
	public void createChangeHistoryOnDelete(list<Event> listOld, map<Id, Event> mapOld){
		list<Change_History__c> changeHistroyToInsert = new list<Change_History__c>();
		

		list<Event> extraFieldsEvents = [SELECT Id, 
												StartDateTime, 
												EndDateTime, 
												OwnerId, 
												RecordTypeId, 
												WhatId 
												FROM Event Where Id IN: mapOld.keySet()];
		
		list<id> relatedWhatIds = new list<id>();
		list<id> relatedOwnerIds = new list<id>();
		for(Event e : extraFieldsEvents){
			relatedWhatIds.add(e.WhatId);
			relatedOwnerIds.add(e.OwnerId);
		}
		
		list<RbA_Work_Order__c> relatedWorkOrdersList = [SELECT id, Cancel_Reason__c, Cancel_Date__c FROM RbA_Work_Order__c WHERE id IN:relatedWhatIds AND Cancel_Reason__c != null AND Cancel_Date__c != null];
		set<id> relatedWorkOrderIdSet = new set<id>();
		map<id, RbA_Work_Order__c> idToWorkOrder = new map<id, RbA_Work_Order__c>();
		for(RbA_Work_Order__c wo : relatedWorkOrdersList){
			relatedWorkOrderIdSet.add(wo.id);
			idToWorkOrder.put(wo.id, wo);
		}
		
		list<User> relatedUserList = [SELECT id, FirstName, LastName FROM User WHERE id IN :relatedOwnerIds];
		map<id, String> userIdToNameMap = new map<id, String>();
		for(User u : relatedUserList){
			userIdToNameMap.put(u.id, u.FirstName+' '+u.LastName);
		}

		Id workOrderEventRecordTypeId = UtilityMethods.retrieveRecordTypeId('Work_Order_Event', 'Event');
		for(Event e : extraFieldsEvents){
			if(e.RecordTypeId == workOrderEventRecordTypeId && relatedWorkOrderIdSet.contains(e.WhatId) ){
				RbA_Work_Order__c rWO = idToWorkOrder.get(e.WhatId);
				//String cancelDate = rWO.Cancel_Date__c.substring(0,9);
				Change_History__c ch = new Change_History__c();
				ch.RbA_Work_Order__c = e.WhatId;
				ch.Changes__c = 'Cancel Reason: '+rWO.Cancel_Reason__c+'\r\n'+
								'Cancel Date: '+rWO.Cancel_Date__c.format()+'\r\n'+
								'Start Date Time: '+e.StartDateTime.format()+'\r\n'+ 
								'End Date Time: '+e.EndDateTime.format()+'\r\n'+
				 				'Assigned To: '+userIdToNameMap.get(e.OwnerId)+'\r\n';
 				changeHistroyToInsert.add(ch);
			} 
		}
		insert changeHistroyToInsert;
	} 
	
}