RbA Build/src/objects/Change_History__c.object
<CustomObject>
    <fields>
        <fullName>Changes__c</fullName>
        <label>Changes</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>RbA_Work_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>RbA Work Order</label>
        <referenceTo>RbA_Work_Order__c</referenceTo>
        <relationshipLabel>Change Histories</relationshipLabel>
        <relationshipName>Change_Histories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Subtype__c</fullName>
        <description>This picklist designates if this change history record was created when a record was initially created or after it was changed.</description>
        <inlineHelpText>This picklist designates if this change history record was created when a record was initially created or after it was changed.</inlineHelpText>
        <label>Subtype</label>
        <picklist>
            <picklistValues>
                <fullName>Initial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Change</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Change History</label>
    <nameField>
        <displayFormat>CH-{0000000}</displayFormat>
        <label>Change History Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Change Histories</pluralLabel>
    <recordTypes>
        <fullName>RbA_Work_Order</fullName>
        <active>true</active>
        <label>RbA Work Order</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

RbA Build/src/objects/RbA_Work_Order__c.object
<CustomObject>
    <description>Custom Object used to track Work Orders related to Orders.</description>
    <fields>
        <fullName>Cancel_Date__c</fullName>
        <label>Cancel Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Cancel_Reason__c</fullName>
        <label>Cancel Reason</label>
        <picklist>
            <picklistValues>
                <fullName>Weather</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Family Emergency</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Schedule Conflict</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Resource Constraint</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Order Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Project On Hold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Homeowner Request</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Duplicate</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>RbA Work Order</label>
    <nameField>
        <displayFormat>WO-{00000000}</displayFormat>
        <label>Work Order #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RbA Work Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

RbA Build/src/classes/RMS_eventManagerTest.cls
@isTest
public with sharing class RMS_eventManagerTest {


	static testmethod void positiveDelete(){
		TestUtilityMethods testMethods = new TestUtilityMethods();
		testMethods.setUpConfigs();
		
		Id workOrderEventRecordTypeId = UtilityMethods.retrieveRecordTypeId('Work_Order_Event', 'Event');
		RbA_Work_Order__c rbaWO1 = new RbA_Work_Order__c(Cancel_Reason__c = 'Bad Reviews', Cancel_Date__c = Date.Today() );
		insert rbaWO1;
		
		Event e1 = new Event(	WhatId = rbaWO1.id, 
								StartDateTime = System.now(), 
								EndDateTime = System.now(), 
								RecordTypeId = workOrderEventRecordTypeId 
							);
		insert e1;
		delete e1;
		
		List<Change_History__c> chResults = [SELECT Id, RecordTypeId, RbA_Work_Order__c, Subtype__c, Changes__c FROM Change_History__c ];
		System.AssertEquals(1, chResults.size());
		System.AssertEquals(UtilityMethods.RecordTypeFor('Change_History__c', 'RbA_Work_Order'), chResults[0].RecordTypeId);
		System.AssertEquals('Change', chResults[0].Subtype__c);
		System.AssertEquals(rbaWO1.Id, chResults[0].RbA_Work_Order__c);
		System.Assert(chResults[0].Changes__c != null);
	}

}