RbA Build/src/objects/Charge__c.object
<CustomObject>
    <description>Also known as &quot;Responsibility&quot;</description>
    <fields>
        <fullName>Category__c</fullName>
        <description>Categorizes the problem in the service request</description>
        <inlineHelpText>Categorizes the problem in the service request</inlineHelpText>
        <label>Source of Defect</label>
        <picklist>
            <controllingField>Charge_Cost_To__c</controllingField>
            <picklistValues>
                <fullName>Aesthetics/Function (C)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Aesthetics/Function (R)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AW Logistics</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bayworld</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EMCO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Glass(Sash/Panel) (C)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Glass(Sash/Panel) (R)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Goodwill</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Grilles (C)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Grilles (R)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hardware (C)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hardware (R)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Renewal by Andersen</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Screens (C)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Screens (R)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unit (C)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unit (R)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Provia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Charge_Cost_To__c</fullName>
        <description>The responsible party for the service</description>
        <inlineHelpText>The responsible party for the service</inlineHelpText>
        <label>Responsibility</label>
        <picklist>
            <picklistValues>
                <fullName>Manufacturing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Retailer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Service_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Connects the Charge record to the Order Item</description>
        <label>Service Product</label>
        <referenceTo>OrderItem</referenceTo>
        <relationshipLabel>Responsibility</relationshipLabel>
        <relationshipName>Charges</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Service_Request__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service Request</label>
        <referenceTo>Order</referenceTo>
        <relationshipLabel>Charges</relationshipLabel>
        <relationshipName>Charges</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>What_Where__c</fullName>
        <description>Based on Responsibility and Source of Defect</description>
        <inlineHelpText>Based on Responsibility and Source of Defect</inlineHelpText>
        <label>Defect</label>
        <picklist>
            <controllingField>Category__c</controllingField>
            <picklistValues>
                <fullName>Addition</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Caulk</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Color</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Satisfaction</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Damage</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Data Entry</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Finish</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Handing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Operation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Out of Warranty</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pattern</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Size</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Stain</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Style</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Trim</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wrap</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Charge</label>
    <nameField>
        <displayFormat>CCT-{000}</displayFormat>
        <label>Charge Cost Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Charges</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

RbA Build/src/objects/OrderItem.object
<CustomObject>
    <fields>
        <fullName>Charge_Cost_To__c</fullName>
        <label>Charge Cost To:</label>
        <picklist>
            <picklistValues>
                <fullName>Manufacturer - Replace</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Local - Remake</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer - Replace</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

RbA Build/src/objects/Procedure_Code__c.object
<CustomObject>
    <label>Procedure Code</label>
    <nameField>
        <label>Procedure Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Procedure Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

RbA Build/src/objects/Procedure_Code_Assignment__c.object
<CustomObject>
    <fields>
        <fullName>Procedure_Code__c</fullName>
        <label>Procedure Code</label>
        <referenceTo>Procedure_Code__c</referenceTo>
        <relationshipLabel>Service Product Assignment</relationshipLabel>
        <relationshipName>Product_Procedure_Codes1</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Service_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service Product</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Product2.RecordTypeId</field>
                <operation>equals</operation>
                <value>Service Product</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Product2</referenceTo>
        <relationshipName>Product_Procedure_Codes1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Procedure Code Assignment</label>
    <nameField>
        <label>Procedure Code Assignment</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Procedure Code Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

RbA Build/src/objects/Service_Product__c.object
<CustomObject>
    <description>Junction Object linking Master Products to Service Products</description>
    <fields>
        <fullName>Service_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service Product</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Product2.RecordTypeId</field>
                <operation>equals</operation>
                <value>Service Product</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Master Products</relationshipLabel>
        <relationshipName>Service_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Service Product</label>
    <nameField>
        <displayFormat>SPA-{000000}</displayFormat>
        <label>Service Product Assignment</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

RbA Build/src/objects/Service_Symptom__c.object
<CustomObject>
    <description>The actual Service Symptom code added to the Order Item. Junction Object between Order Item and Service Symptom List</description>
    <fields>
        <fullName>Service_Product__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Service Product</label>
        <referenceTo>OrderItem</referenceTo>
        <relationshipLabel>Service Symptoms</relationshipLabel>
        <relationshipName>Service_Symptoms</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Service_Request__c</fullName>
        <formula>HYPERLINK(&apos;/&apos; &amp; Service_Product__r.Order.Id, Service_Product__r.Order.OrderNumber)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Service Request</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service_Symptom__c</fullName>
        <label>Service Symptom</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>$Source.Service_Product__c</field>
                <operation>equals</operation>
                <valueField>$Source.Service_Product__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Service_Symptom_List__c</referenceTo>
        <relationshipLabel>Service Request Line Items</relationshipLabel>
        <relationshipName>Service_Symptoms</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Service Symptom</label>
    <nameField>
        <displayFormat>SS-{000}</displayFormat>
        <label>Service Symptom #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Symptoms</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

RbA Build/src/objects/Service_Symptom_Assignment__c.object
<CustomObject>
    <description>Junction object between Procedure Code and Product Service Symptom</description>
    <fields>
        <fullName>Procedure_Code__c</fullName>
        <label>Procedure Code</label>
        <referenceTo>Procedure_Code__c</referenceTo>
        <relationshipLabel>Service Symptoms</relationshipLabel>
        <relationshipName>Procedure_Code_Assignments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Service_Symptom__c</fullName>
        <label>Service Symptom</label>
        <referenceTo>Service_Symptom_List__c</referenceTo>
        <relationshipLabel>Procedure Codes</relationshipLabel>
        <relationshipName>Procedure_Code_Assignments</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Service Symptom Assignment</label>
    <nameField>
        <label>Service Symptom Assignment</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Symptom Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

RbA Build/src/objects/Warranty__c.object
<CustomObject>
    <fields>
        <fullName>Charge_Cost_To__c</fullName>
        <label>Charge Cost To Record</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Charge__c.Service_Product__c</field>
                <operation>equals</operation>
                <valueField>$Source.Service_Product__c</valueField>
            </filterItems>
            <filterItems>
                <field>Charge__c.Category__c</field>
                <operation>equals</operation>
                <value>Renewal by Andersen</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Charge__c</referenceTo>
        <relationshipLabel>Reimbursements</relationshipLabel>
        <relationshipName>Warranties</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Procedure_Code__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Procedure Code</label>
        <referenceTo>Procedure_Code_Assignment__c</referenceTo>
        <relationshipLabel>Warranties</relationshipLabel>
        <relationshipName>Warranties</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Service_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service Product</label>
        <referenceTo>OrderItem</referenceTo>
        <relationshipLabel>Reimbursement</relationshipLabel>
        <relationshipName>Warranties</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Service_Request__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service Request</label>
        <referenceTo>Order</referenceTo>
        <relationshipLabel>Warranties</relationshipLabel>
        <relationshipName>Warranties</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Warranty</label>
    <nameField>
        <displayFormat>W-{000}</displayFormat>
        <label>Reimbursement Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Warranties</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

RbA Build/src/classes/RMS_addWarrantiesExt.cls
/*******************************************************//**

@class  RMS_addWarrantiesExt


@author  Brianne Wilson (Slalom.BLW)

@brief 1 of 2 classes used to add Warranties

@version    2016-06-06 Slalom.BLW
Created.


@copyright  (c)2016 Slalom.  All Rights Reserved. 
Unauthorized use is prohibited.

***********************************************************/

public with sharing class RMS_addWarrantiesExt extends RMS_addWarranties
{
    
    
    public OrderItem myWO {get; private set;}
    
    public RMS_addWarrantiesExt(ApexPages.StandardController stdController) 
    {
        super(stdController);
        
        
        this.myWO = [SELECT Id, OrderId, PricebookEntryId, PricebookEntry.Product2Id                      
                     FROM OrderItem
                     WHERE Id =: stdController.getRecord().Id];
        
        this.childList = [SELECT Id,
                          Service_Product__c,
                          Service_Request__c,
                          Procedure_Code__c,
                          Charge_Cost_To__c,
                          Quantity__c                                                
                          FROM Warranty__c
                          WHERE Service_Product__c =: mysObject.Id];
    }
    
    public List<selectOption> getProcs() {
        List<selectOption> options = new List<selectOption>(); //new list for holding all of the picklist options        
        
        List<Id> ssIds = new List<Id>();
        for(Service_Symptom__c symptoms : [SELECT Id, Service_Symptom__c, Service_Product__c
                                          FROM Service_Symptom__c
                                           WHERE Service_Product__c = :myWO.Id]){
                                               ssIds.add(symptoms.Service_Symptom__c);
                                           }
        
        List<Id> ssAssign = new List<Id>();
        for (Service_Symptom_Assignment__c assignments : [Select Id, Service_Symptom__c, Procedure_Code__c
                                                         FROM Service_Symptom_Assignment__c
                                                          WHERE Service_Symptom__c =: ssIds]){
                                                              ssAssign.add(assignments.Procedure_Code__c);
                                                          }
        
        for (Procedure_Code_Assignment__c procedures : [SELECT Id, Name, Service_Product__c, Procedure_Code__c
                                                        FROM Procedure_Code_Assignment__c 
                                                        WHERE Service_Product__c = :myWo.PricebookEntry.Product2Id 
                                                        AND Procedure_Code__c = : ssAssign
                                                        ORDER BY Procedure_Code_Assignment__c.Name ASC]) { 
                                                            options.add(new selectOption(procedures.Id, procedures.Name)); //for all records found - add them to the picklist options
                                                        }
        options.add(new selectOption('', '-- None --')); //add the first option of '- None -' in case the user doesn't want to select a value or in case no values are returned from query below
        return options; //return the picklist options        
    } 
    
        public List<selectOption> getCharges() {
        List<selectOption> options = new List<selectOption>(); //new list for holding all of the picklist options        
        for (Charge__c charges : [SELECT Id, Name, Charge_Cost_To__c,Category__c
                                                        FROM Charge__c 
                                                        WHERE Service_Product__c = :myWo.Id
                                  						AND What_Where__c = 'Renewal by Andersen'
                                                        ORDER BY Charge__c.Charge_Cost_To__c ASC]) { 
                                                            options.add(new selectOption(charges.Id, charges.Charge_Cost_To__c + ' - '+ charges.Category__c)); //for all records found - add them to the picklist options
                                                        }
        options.add(new selectOption('', '-- None --')); //add the first option of '- None -' in case the user doesn't want to select a value or in case no values are returned from query below
        return options; //return the picklist options        
    } 
    
    
    /*
* This method is necessary for reference on the Visualforce page, 
* in order to reference non-standard fields.
*/
    public List<Warranty__c> getChildren()
    {
        return (List<Warranty__c>)childList;
    }
    
    public override sObject initChildRecord()
    {
        Warranty__c child = new Warranty__c();
        child.Service_Product__c = myWO.Id; 
        child.Service_Request__c = myWo.OrderId;                          
        
        return child;
    }
    
}