RbA Build/src/objects/Charge__c.object
<CustomObject>
    <description>Also known as &quot;Responsibility&quot;</description>
    <fields>
        <fullName>Charge_Cost_To__c</fullName>
        <description>The responsible party for the service</description>
        <inlineHelpText>The responsible party for the service</inlineHelpText>
        <label>Responsibility</label>
        <picklist>
            <picklistValues>
                <fullName>Manufacturing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Retailer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Installed_Product__c</fullName>
        <description>Used for UI purposes on VF page to display Installed Product Name</description>
        <formula>Service_Product__r.Sold_Order_Product_Asset__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Installed Product</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Connects the Charge record to the Order Item</description>
        <label>Service Product</label>
        <referenceTo>OrderItem</referenceTo>
        <relationshipLabel>Responsibility</relationshipLabel>
        <relationshipName>Charges</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Service_Request__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service Request</label>
        <referenceTo>Order</referenceTo>
        <relationshipLabel>Charges</relationshipLabel>
        <relationshipName>Charges</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Charge</label>
    <nameField>
        <displayFormat>CCT-{000}</displayFormat>
        <label>Charge Cost Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Charges</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

RbA Build/src/objects/OrderItem.object
<CustomObject>
    <fields>
        <fullName>Charge_Cost_To__c</fullName>
        <label>Charge Cost To:</label>
        <picklist>
            <picklistValues>
                <fullName>Manufacturer - Replace</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Local - Remake</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer - Replace</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Primary_Reason__c</fullName>
        <label>Primary Reason</label>
        <picklist>
            <picklistValues>
                <fullName>Goodwill</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Installation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Order Entry</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Service</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Staining</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tech Measure</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Warehouse</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Homeowner</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Secondary_Reason__c</fullName>
        <label>Secondary Reason</label>
        <picklist>
            <controllingField>Primary_Reason__c</controllingField>
            <picklistValues>
                <fullName>Application</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Blinds/Shutters</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Building Material</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Carbon Monoxide Detector</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Caulking</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Change Order</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Check Rail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Clean-Up</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Color</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Color Mismatch</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Condensation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Satisfaction</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Damage</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Damage Product</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dark Market</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Data Entry</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Discontinued Vendor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Egress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>General Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Glass Type</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Grille Pattern</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Grille Pattern Alignment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Grille Type</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Handing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hardware</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Incomplete Load</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Installation Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Interior Trim</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Math Error</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non-Fitting Unit</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

RbA Build/src/objects/Service_Product__c.object
<CustomObject>
    <description>Junction Object linking Master Products to Service Products</description>
    <fields>
        <fullName>Service_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service Product</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Product2.RecordTypeId</field>
                <operation>equals</operation>
                <value>Service Product</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Master Products</relationshipLabel>
        <relationshipName>Service_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Service Product</label>
    <nameField>
        <displayFormat>SPA-{000000}</displayFormat>
        <label>Service Product Assignment</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

RbA Build/src/classes/RMS_addResponsibilityExt.cls
/*******************************************************//**

@class  RMS_addResponsibilityExt


@author  Brianne Wilson (Slalom.BLW)

@brief 1 of 2 classes used to add Warranties

@version    2016-06-06 Slalom.BLW
Created.


@copyright  (c)2016 Slalom.  All Rights Reserved. 
Unauthorized use is prohibited.

***********************************************************/

public with sharing class RMS_addResponsibilityExt extends RMS_addCharges
{
    
    
    public OrderItem myWO {get; private set;}
    
    public RMS_addResponsibilityExt(ApexPages.StandardController stdController) 
    {
        super(stdController);
        
        
        this.myWO = [SELECT Id,OrderId, PricebookEntryId, PricebookEntry.Product2Id                    
                     FROM OrderItem
                     WHERE Id =: stdController.getRecord().Id];
        
        this.childList = [SELECT Id,
                          Service_Product__c,
                          Service_Product__r.Product_Name__c,
                          Service_Request__c,                          
                          Charge_Cost_To__c,
                          Primary_Reason__c,
                          Secondary_Reason__c,
                          Installed_Product__c
                          FROM Charge__c
                          WHERE Service_Product__c =: mysObject.Id];
    }

    
    
    /*
* This method is necessary for reference on the Visualforce page, 
* in order to reference non-standard fields.
*/
    public List<Charge__c> getChildren()
    {
        return (List<Charge__c>)childList;
    }
    
    public override sObject initChildRecord()
    {
        Charge__c child = new Charge__c();
        child.Service_Product__c = myWO.Id; 
        child.Service_Request__c = myWo.OrderId;                           
        
        return child;
    }
    
}