RbA Build/src/objects/Charge__c.object
<CustomObject>
    <description>Also known as &quot;Responsibility&quot;</description>
    <fields>
        <fullName>Category__c</fullName>
        <description>Categorizes the problem in the service request</description>
        <inlineHelpText>Categorizes the problem in the service request</inlineHelpText>
        <label>Source of Defect</label>
        <picklist>
            <controllingField>Charge_Cost_To__c</controllingField>
            <picklistValues>
                <fullName>Aesthetics/Function (C)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Aesthetics/Function (R)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AW Logistics</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bayworld</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EMCO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Glass(Sash/Panel) (C)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Glass(Sash/Panel) (R)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Goodwill</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Grilles (C)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Grilles (R)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hardware (C)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hardware (R)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Renewal by Andersen</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Screens (C)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Screens (R)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unit (C)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unit (R)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Provia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Charge_Cost_To__c</fullName>
        <description>The responsible party for the service</description>
        <inlineHelpText>The responsible party for the service</inlineHelpText>
        <label>Responsibility</label>
        <picklist>
            <picklistValues>
                <fullName>Manufacturing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Retailer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Charge</label>
    <nameField>
        <displayFormat>CCT-{000}</displayFormat>
        <label>Charge Cost Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Charges</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

RbA Build/src/objects/Warranty__c.object
<CustomObject>
    <fields>
        <fullName>Charge_Cost_To__c</fullName>
        <label>Charge Cost To Record</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Charge__c.Service_Product__c</field>
                <operation>equals</operation>
                <valueField>$Source.Service_Product__c</valueField>
            </filterItems>
            <filterItems>
                <field>Charge__c.Category__c</field>
                <operation>equals</operation>
                <value>Renewal by Andersen</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Charge__c</referenceTo>
        <relationshipLabel>Reimbursements</relationshipLabel>
        <relationshipName>Warranties</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Warranty</label>
    <nameField>
        <displayFormat>W-{000}</displayFormat>
        <label>Reimbursement Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Warranties</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

RbA Build/src/classes/warrantyTriggerTest.cls
@isTest
private class warrantyTriggerTest {

    static testMethod void warrantyTriggerTest() {
         TestUtilityMethods utility = new TestUtilityMethods();       
         utility.setUpConfigs();
        Charge__c cct = new Charge__c(Category__c = 'Renewal by Andersen');
        insert cct;
        Warranty__c newWarranty = new Warranty__c(Charge_Cost_To__c = cct.Id);
        insert newWarranty;    }
}