RbA Build/src/objects/Field_IDs__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Company__c</fullName>
        <label>Company</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Object_ID__c</fullName>
        <label>Object ID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sold_Order__c</fullName>
        <label>Sold Order</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street__c</fullName>
        <label>Street</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zip__c</fullName>
        <label>Zip</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Field IDs</label>
</CustomObject>

RbA Build/src/objects/Order.object
<CustomObject>
    <fields>
        <fullName>Sold_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>When the Sold Order is Job In Progress, the Service Order must be related to the Sold Order.</inlineHelpText>
        <label>Sold Order</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>$Source.AccountId</field>
                <operation>equals</operation>
                <valueField>Order.AccountId</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Order</referenceTo>
        <relationshipLabel>Service Orders</relationshipLabel>
        <relationshipName>Sold_Order</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type_image__c</fullName>
        <formula>CASE( RecordTypeId , 
&quot;0123B000000Ci1R&quot;, IMAGE (&quot;resource/ServiceOrder&quot;,&quot;Service Order&quot;), 
&quot;Install&quot;, IMAGE(&quot;resource/InstallText&quot;,&quot;Install&quot;), 
&quot;Service&quot;, IMAGE(&quot;resource/ServiceText&quot;,&quot;Service&quot;),
&quot;HOA&quot;, IMAGE(&quot;resource/HOAText&quot;,&quot;HOA&quot;),
&quot;Historical&quot;, IMAGE(&quot;resource/HistoricalText&quot;,&quot;Historical&quot;),
&quot;Building Permit&quot;, IMAGE(&quot;resource/BuildingPermitText&quot;,&quot;Building Permit&quot;),
&quot;LSWP&quot;, IMAGE(&quot;resource/LSWP&quot;,&quot;LSWP&quot;),
&quot;Paint/Stain&quot;, IMAGE(&quot;resource/PaintStainText&quot;,&quot;Paint/Stain&quot;),
NULL)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Type</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

RbA Build/src/objects/Purchase_Order__c.object
<CustomObject>
    <description>The purchase order header for ordering RbA and 3rd party products linked to order line items</description>
    <label>Purchase Order</label>
    <nameField>
        <label>Purchase Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Purchase Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

RbA Build/src/objects/SVMXC__Service_Order__c.object
<CustomObject>
    <customHelp>SVMXC__SVMXC_LaunchHelp</customHelp>
    <description>Service Order is used to plan, execute and manage Service events for Field and Depot Service activities. Depending upon the service scenario, the order creation can be triggered by many events: When creating a Support Case, when one or more installed products require periodic service or calibration, when troubleshooting a customer problem on the field, if the field service engineer learns that the product requires specialized conditions of a factory/depot to resolve the problem, or when a new/repair shipment to customer requires specialized installation activity.</description>
    <fields>
        <fullName>Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Company doing the work.</inlineHelpText>
        <label>Company</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Work Orders (Company)</relationshipLabel>
        <relationshipName>Work_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SVMXC__Group_Member__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Name of the group member working on the service order. This does not imply that this member has the ownership of service order record</description>
        <inlineHelpText>Name of the group member working on the service order. This does not imply that this member has the ownership of service order record</inlineHelpText>
        <label>Technician</label>
        <referenceTo>SVMXC__Service_Group_Members__c</referenceTo>
        <relationshipLabel>Work Orders</relationshipLabel>
        <relationshipName>Service_Order</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SVMXC__Order_Status__c</fullName>
        <description>Current status of the service order</description>
        <inlineHelpText>Current status of the service order</inlineHelpText>
        <label>Order Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Open</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wait for Install</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>To be scheduled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Applied</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Received</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Scheduled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>JIP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On Hold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Install Complete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Final Failed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>SVMXC__Order_Type__c</fullName>
        <description>Type of service order: Field Service, Depot repair etc.</description>
        <inlineHelpText>Type of service order: Field Service, Depot repair etc.</inlineHelpText>
        <label>Order Type</label>
        <picklist>
            <picklistValues>
                <fullName>Tech Measure</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Install</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Service</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HOA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Historical</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Building Permit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Paint/Stain</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LSWP</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>SVMXC__Scheduled_Date_Time__c</fullName>
        <label>Scheduled Date Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>SVMXC__Work_Order_Scheduling_Status__c</fullName>
        <description>Indicates various stages of the workflow of scheduling the work order</description>
        <inlineHelpText>Indicates various stages of the workflow of scheduling the work order</inlineHelpText>
        <label>Scheduling Status</label>
        <picklist>
            <controllingField>SVMXC__Order_Status__c</controllingField>
            <picklistValues>
                <fullName>To be scheduled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Scheduled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Complete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tentative</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fixed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dispatched</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Received</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>En Route</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Onsite</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Finished Onsite</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Sold_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sold Order</label>
        <referenceTo>Order</referenceTo>
        <relationshipLabel>Work Orders</relationshipLabel>
        <relationshipName>Work_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type_image__c</fullName>
        <formula>CASE( SVMXC__Order_Type__c, 
&quot;Tech Measure&quot;, IMAGE (&quot;resource/TechMeasureText&quot;,&quot;Tech Measure&quot;), 
&quot;Install&quot;, IMAGE(&quot;resource/InstallText&quot;,&quot;Install&quot;), 
&quot;Service&quot;, IMAGE(&quot;resource/ServiceText&quot;,&quot;Service&quot;),
&quot;HOA&quot;, IMAGE(&quot;resource/HOAText&quot;,&quot;HOA&quot;),
&quot;Historical&quot;, IMAGE(&quot;resource/HistoricalText&quot;,&quot;Historical&quot;),
&quot;Building Permit&quot;, IMAGE(&quot;resource/BuildingPermitText&quot;,&quot;Building Permit&quot;),
&quot;LSWP&quot;, IMAGE(&quot;resource/LSWP&quot;,&quot;LSWP&quot;),
&quot;Paint/Stain&quot;, IMAGE(&quot;resource/PaintStainText&quot;,&quot;Paint/Stain&quot;),
NULL)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Paint/Stain</inlineHelpText>
        <label>Type</label>
        <type>Text</type>
    </fields>
    <label>Work Order</label>
    <nameField>
        <displayFormat>WO-{00000000}</displayFormat>
        <label>Work Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work Orders</pluralLabel>
    <recordTypes>
        <fullName>Actions</fullName>
        <active>true</active>
        <description>Work Order that require Action (HOA, Historical)</description>
        <label>Actions</label>
    </recordTypes>
    <recordTypes>
        <fullName>Visit</fullName>
        <active>true</active>
        <description>Work Orders where a home visit is required</description>
        <label>Visit</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

RbA Build/src/classes/RMS_viewRelatedWorkOrdersController.cls
public with sharing class RMS_viewRelatedWorkOrdersController {
	
	public list<SVMXC__Service_Order__c> workOrdersList = new list<SVMXC__Service_Order__c>();
	public list<SVMXC__Service_Order__c> getWorkOrders() {
        return workOrdersList;
    }
	public string getView(){
		return 'View';
	}
	public String strurl;
	
	/*
	public String getWorkOrderKeyPrefix(){
		Schema.DescribeSObjectResult r = SVMXC__Service_Order__c.sObjectType.getDescribe();
		String keyPrefix = r.getKeyPrefix();
		return keyPrefix;
	}
	
	public String workOrderSoldOrderFieldId {get;set;}
	*/

	
	public string serviceOrderVisitRecordTypeId{get;set;}
	public string serviceOrderActionsRecordTypeId{get;set;}
	
	public string serviceOrderVisitRecordTypeURL{get;set;}
	public string serviceOrderActionsRecordTypeURL{get;set;}
	
/******* Set up Standard Controller for Purchase_Order__c  *****************/
 	private Apexpages.StandardController standardController;
 	private final Order ord;
	
	
	//Constructor
	public RMS_viewRelatedWorkOrdersController(ApexPages.StandardController stdController) {
		this.ord = (Order)stdController.getRecord();
		
		strurl = ApexPages.currentPage().getUrl();
		strurl = strurl.split('apex/')[1];
		
		list<RecordType> serviceOrderVisitRecordType = [SELECT id FROM RecordType WHERE SobjectType = 'SVMXC__Service_Order__c' AND Name = 'Visit'];
    	list<RecordType> serviceOrderActionsRecordType = [SELECT id FROM RecordType WHERE SobjectType = 'SVMXC__Service_Order__c' AND Name = 'Actions'];
    	
    	serviceOrderVisitRecordTypeId = serviceOrderVisitRecordType[0].id;
    	serviceOrderActionsRecordTypeId = serviceOrderActionsRecordType[0].id;
    	
    	String ordId = ord.id;
    	
    	String woQuery=	'SELECT id, '+ 
    					'Name, '+ 
    					'Sold_Order__c, '+
    					'SVMXC__Work_Order_Scheduling_Status__c, '+
    					'Type_image__c, '+
    					'SVMXC__Scheduled_Date_Time__c, '+
    					'SVMXC__Group_Member__c, '+
    					'SVMXC__Order_Status__c, '+
    					'Owner.Name, '+
    					'SVMXC__Order_Type__c '+
    					
    					'FROM SVMXC__Service_Order__c WHERE Sold_Order__c =: ordId';
		
		if(strurl.Contains('Visit') && serviceOrderVisitRecordType.size() > 0){
			String visitRecordType = serviceOrderVisitRecordType[0].id;
			woQuery = woQuery+' AND RecordTypeId = :visitRecordType';
		
		}else if(strurl.Contains('Actions') && serviceOrderActionsRecordType.size() > 0 ){
			String actionsRecordType = serviceOrderActionsRecordType[0].id;
			woQuery = woQuery+' AND RecordTypeId = :actionsRecordType';
		}
		system.debug('ads woQuery: '+woQuery);
		workOrdersList = Database.query(woQuery);
		
		
		
		//building strings to use as URL for create new Workorder
		Schema.DescribeSObjectResult r = SVMXC__Service_Order__c.sObjectType.getDescribe();
		String workOrderKeyPrefix = r.getKeyPrefix();
		
		list<Order> theOrd = [SELECT Id, AccountId, OrderNumber FROM Order WHERE Id =:ordId ];
		
		list<Account> relatedAccount = [SELECT 	Name,
												BillingStreet,
								    			BillingCity,
								    			BillingState,
								    			BillingPostalCode, 
								    			BillingCountry
								    			FROM Account WHERE Id = :theOrd[0].AccountId];
		
		
		map<String, Field_IDs__c> Field_IDs_map = Field_IDs__c.getAll(); 
		Field_IDs__c workOrderFieldIds = Field_IDs_map.get('Work Order');
		
		/*
		String workOrderObjectId = workOrderFieldIds.Object_ID__c;
		
		String workOrderCompanyFieldId = workOrderFieldIds.Company__c;
		String workOrderSoldOrderFieldId = workOrderFieldIds.Sold_Order__c;
		
			
		String workOrderStreetFieldId = workOrderFieldIds.Street__c;
		String workOrderCityFieldId = workOrderFieldIds.City__c;
		String workOrderStateFieldId = workOrderFieldIds.State__c;
		String workOrderZipFieldId = workOrderFieldIds.Zip__c;
		String workOrderCountryFieldId = workOrderFieldIds.Country__c;
		*/

		String baseURL = 	'/'+workOrderKeyPrefix+'/e?'+
											'CF'+workOrderFieldIds.Sold_Order__c+'='+theOrd[0].OrderNumber+
											'&CF'+workOrderFieldIds.Sold_Order__c+'_lkid='+Ord.Id+
											
											'&CF'+workOrderFieldIds.Company__c+'='+relatedAccount[0].Name+
											'&CF'+workOrderFieldIds.Company__c+'_lkid='+relatedAccount[0].Id+
											
											'&'+workOrderFieldIds.Street__c+'='+relatedAccount[0].BillingStreet+
											'&'+workOrderFieldIds.City__c+'='+relatedAccount[0].BillingCity+
											'&'+workOrderFieldIds.State__c+'='+relatedAccount[0].BillingState+
											'&'+workOrderFieldIds.Zip__c+'='+relatedAccount[0].BillingPostalCode+
											'&'+workOrderFieldIds.Country__c+'='+relatedAccount[0].BillingCountry+
											'&ent='+workOrderFieldIds.Object_ID__c+
											'&retURL=%2F'+Ord.Id;
											
		serviceOrderVisitRecordTypeURL = baseURL + '&RecordType='+serviceOrderVisitRecordTypeId;								
		serviceOrderActionsRecordTypeURL = baseURL + '&RecordType='+serviceOrderActionsRecordTypeId;										
											
											

		 
	}
	
	

}