RbA Build/src/objects/Journal_Entry__c.object
<CustomObject>
    <description>Holds the Financial Transactions that are sent to an Accounting System.
Baan ERP, etc.</description>
    <fields>
        <fullName>Payment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Payment</label>
        <referenceTo>Payment__c</referenceTo>
        <relationshipLabel>Journal Entries</relationshipLabel>
        <relationshipName>Journal_Entries</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Journal Entry</label>
    <nameField>
        <displayFormat>JEN-{000000}</displayFormat>
        <label>Journal Entry Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Journal Entries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

RbA Build/src/objects/Payment__c.object
<CustomObject>
    <description>The object used to store payment records</description>
    <label>Payment</label>
    <nameField>
        <displayFormat>P-{00000000}</displayFormat>
        <label>Payment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <recordTypes>
        <fullName>Deposit</fullName>
        <active>true</active>
        <description>Deposit record type</description>
        <label>Deposit</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

RbA Build/src/classes/RMS_financialTransactionManager.cls
/*******************************************************//**

@class	RMS_financialTransactionManager

@brief	Controller to handle finacial transation recording

@author  Anthony Strafaccia (Slalom.ADS)

@version	2015-12/24  Slalom.ADS
	Created.

@see		RMS_financialTransactionManagerTest

@copyright  (c)2015 Slalom.  All Rights Reserved.
			Unauthorized use is prohibited. 

***********************************************************/

public with sharing class RMS_financialTransactionManager {


	public void onBeforeInsert(list<Payment__c> listNew){
		map<Id, list<Journal_Entry__c>> paymentIdToJournalEntryMap = linkJournalEntries(listNew);
		
		for(Payment__c p : listNew){
			//if(p.Deposit);
		}
		
	}
	
	public void onBeforeInsert(list<Payment__c> listOld, list<Payment__c> listNew, map<Id, Payment__c> mapOld, map<Id, Payment__c> mapNew){
	
	}
	
	
	
	
	public map<id, list<Journal_Entry__c>> linkJournalEntries(list<Payment__c> paymentList){
		list<id> paymentIdList = new list<id>();
		for(Payment__c p : paymentList){
			paymentIdList.add(p.id);
		}
		list<Journal_Entry__c> relatedJournalEntries = [SELECT id, Payment__c FROM Journal_Entry__c WHERE Payment__c IN :paymentIdList];
		map<Id, list<Journal_Entry__c>> paymentIdToJournalEntryMap = new map<Id, list<Journal_Entry__c>>();
		for(Journal_Entry__c je : relatedJournalEntries){
			if(paymentIdToJournalEntryMap.containsKey(je.Payment__r.id) ){
				paymentIdToJournalEntryMap.get(je.Payment__c).add(je);
			}
			else{
				paymentIdToJournalEntryMap.put(je.Payment__c, new list<Journal_Entry__c>{je});
			}
		}
		return paymentIdToJournalEntryMap;
	}
	
	
	
	
	
	
	
	
	
	
	
	
}