RbA Build/src/objects/Labor__c.object
<CustomObject>
    <description>Used for logging Labor against a Work Order</description>
    <fields>
        <fullName>Hourly_Rate__c</fullName>
        <defaultValue>0</defaultValue>
        <description>The hourly rate charged for this labor entry.</description>
        <inlineHelpText>The hourly rate charged for this labor entry.</inlineHelpText>
        <label>Hourly Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Standard_Hourly_Rate__c</fullName>
        <description>The standard hourly rate for internal employees as pulled from the store configuration.</description>
        <formula>Store_Location__r.Active_Store_Configuration__r.Standard_Hourly_Rate__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>The standard hourly rate for internal employees as pulled from the store configuration.</inlineHelpText>
        <label>Standard Hourly Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Labor</label>
    <nameField>
        <displayFormat>Labor Record # - {00}</displayFormat>
        <label>Labor Record #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Labor</pluralLabel>
    <recordTypes>
        <fullName>Labor</fullName>
        <active>true</active>
        <description>Used to track Labor against the Work Order</description>
        <label>Labor</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

RbA Build/src/classes/LaborTriggerHandler.cls
/*******************************************************//**

@class	  LaborTriggerHandler

@brief	 Handler for the labor trigger

@author	 Creston Kuenzi (Slalom.CDK)

@version	2016-6-23  Slalom.CDK
	Created

@see		LaborTriggerHandlerTest

@copyright  (c)2016 Slalom.  All Rights Reserved.
			Unauthorized use is prohibited.

***********************************************************/

public with sharing class LaborTriggerHandler {
  // This should be used in conjunction with the ApexTriggerComprehensive.trigger template
  // The origin of this pattern is http://www.embracingthecloud.com/2010/07/08/ASimpleTriggerTemplateForSalesforce.aspx
  private boolean m_isExecuting = false;
  private integer BatchSize = 0;

  public LaborTriggerHandler(boolean isExecuting, integer size){
    m_isExecuting = isExecuting;
    BatchSize = size;
  }

  
  public void OnBeforeInsert(Labor__c[] newLabor){
    updateHourlyRate(newLabor);

  }

 
  /*
  public void OnAfterInsert(User[] newUsers){
  }
*/

/*
  public void OnBeforeUpdate( Map<ID, User> oldMap, Map<ID, User> newMap){
  }
/*  
  /*
  public void OnAfterUpdate( Map<ID, User> oldMap, Map<ID, User> newMap){

  }
*/

/*
  public void OnBeforeDelete(User[] UsersToDelete, Map<ID, User> UsersMap){

  }

  public void OnAfterDelete(User[] deletedUsers, Map<ID, User> UsersMap){

  }


  public void OnUndelete(User[] restoredUsers){

  }*/

	// This method pulls the hourly rate from the store configuration and stores it
	// on the labor record. The standard hourly rate is a formula field
	public void updateHourlyRate(List<Labor__c> laborsToUpdate){
		for(Labor__c l : laborsToUpdate){
			System.Debug('**********hourlyrate=' +l.Standard_Hourly_Rate__c);
			l.Hourly_Rate__c = l.Standard_Hourly_Rate__c;
		}
	}


}