RbA Build/src/objects/Labor__c.object
<CustomObject>
    <description>Used for logging Labor against a Work Order</description>
    <fields>
        <fullName>Related_Work_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related Work Order</label>
        <referenceTo>RbA_Work_Order__c</referenceTo>
        <relationshipLabel>Labor</relationshipLabel>
        <relationshipName>Labor1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Store_Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Store Location</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$User.Store_Location_Text__c</field>
                <operation>contains</operation>
                <valueField>Account.Name</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Labor</relationshipLabel>
        <relationshipName>Labor</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Labor</label>
    <nameField>
        <displayFormat>Labor Record # - {00}</displayFormat>
        <label>Labor Record #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Labor</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

RbA Build/src/objects/Order.object
<CustomObject>
    <fields>
        <fullName>Labor__c</fullName>
        <label>Labor</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Store_Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This order is related to this store location.</description>
        <inlineHelpText>This order is related to this store location.</inlineHelpText>
        <label>Store Location</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Orders (Store Location)</relationshipLabel>
        <relationshipName>Orders1</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

RbA Build/src/classes/RMS_newLaborRedirectExtensionTest.cls
/*******************************************************//**

@class	RMS_newLaborRedirectExtensionTest

@brief	Test Class for RMS_newLaborRedirectExtensionTest

@author  Creston Kuenzi (Slalom.CDK)

@version	2015-2-2  Slalom.CDK
	Created.

@see		RMS_newLaborRedirectExtension

@copyright  (c)2016 Slalom.  All Rights Reserved. 
			Unauthorized use is prohibited.

***********************************************************/
@isTest
private class RMS_newLaborRedirectExtensionTest {

	/*******************************************************
					redirectTestWithOrder
	*******************************************************/
	static testmethod void redirectTestFromOrder(){
		TestUtilityMethods utility = new TestUtilityMethods();
		
		utility.createOrderTestRecords();

		Labor__c l = new Labor__c();
		Order soldOrder = [SELECT Id FROM Order WHERE Name = 'Sold Order 1'];
//		insert theWorkOrder; 

//		l.Related_Work_Order__c = theWorkOrder.Id;


		PageReference pageRef = Page.RMS_prodConfigRedirect;
		Test.setCurrentPage(pageRef);

		ApexPages.StandardController stdController = new ApexPages.StandardController(l);
		RMS_newLaborRedirectExtension customController  = new RMS_newLaborRedirectExtension(stdController);
				
		customController.redirect();
		
		
		// remove the store location from order and retest
		soldOrder.Store_Location__c = null;
		update soldOrder;
		ApexPages.StandardController stdController2 = new ApexPages.StandardController(l);
		RMS_newLaborRedirectExtension customController2  = new RMS_newLaborRedirectExtension(stdController2);
				
		customController2.redirect();		

	}
	/*******************************************************
					redirectTestWithoutWorkOrder
	*******************************************************/
	static testmethod void redirectTestWithoutWorkOrder(){
		TestUtilityMethods utility = new TestUtilityMethods();
		
		utility.createOrderTestRecords();

		Labor__c l = new Labor__c();

		PageReference pageRef = Page.RMS_prodConfigRedirect;
		Test.setCurrentPage(pageRef);
		ApexPages.StandardController stdController = new ApexPages.StandardController(l);
		RMS_newLaborRedirectExtension customController  = new RMS_newLaborRedirectExtension(stdController);
		
		// test with store location
		customController.testStoreLocation = '77 - Twin Cities, MN';				
		customController.redirect();

		// test with null store location
		customController.testStoreLocation = null;				
		customController.redirect();

	}
}