RbA Build/src/objects/Labor__c.object
<CustomObject>
    <description>Used for logging Labor against a Work Order</description>
    <fields>
        <fullName>Related_Work_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related Work Order</label>
        <referenceTo>RbA_Work_Order__c</referenceTo>
        <relationshipLabel>Labor</relationshipLabel>
        <relationshipName>Labor1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Labor</label>
    <nameField>
        <displayFormat>Labor Record # - {00}</displayFormat>
        <label>Labor Record #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Labor</pluralLabel>
    <recordTypes>
        <fullName>Labor</fullName>
        <active>true</active>
        <description>Used to track Labor against the Work Order</description>
        <label>Labor</label>
    </recordTypes>
    <recordTypes>
        <fullName>Misc_Reimbursement</fullName>
        <active>true</active>
        <description>Used to enter miscellaneous reimbursements to contractor. This was formerly called misc sub payments.</description>
        <label>Misc Reimbursement</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

RbA Build/src/objects/Order.object
<CustomObject>
    <fields>
        <fullName>Labor__c</fullName>
        <label>Labor</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

RbA Build/src/classes/RMS_newLaborRedirectExtension.cls
/*******************************************************//**

@class	  RMS_newLaborRedirectExtension

@brief	  Extension for redirecting the user when clicking the New labor button

	Redirects the user directly to a labor or misc reimbursement page depending on if it's linked
	to a work order, bypassing the record type selector

@author	 Creston Kuenzi (Slalom.CDK)

@version	2015-12-29  Slalom.CDK
	Created

@see		RMS_newLaborRedirectExtensionTest

@copyright  (c)2015 Slalom.  All Rights Reserved.
			Unauthorized use is prohibited.

***********************************************************/

public with sharing class RMS_newLaborRedirectExtension {

	/******* Set up Standard Controller for Labor__c  *****************/
	private final Labor__c theLabor;
	
	public RMS_newLaborRedirectExtension(ApexPages.StandardController stdController) {
		this.theLabor = (Labor__c)stdController.getRecord();
		if (this.theLabor == null)
			this.theLabor = new Labor__c(); 
	}

	/******* redirect method  *****************/
	public PageReference redirect() {

		// Retrieve the key prefix for the labor object and insert it into the page reference
		Schema.DescribeSObjectResult r = Labor__c.sObjectType.getDescribe();
		String keyPrefix = r.getKeyPrefix();        
		PageReference p = new PageReference('/' +keyPrefix +'/e');

		// Get all of the url parameters from the current url and put them in the new url
        Map<String, String> m = p.getParameters();
        m.putAll(ApexPages.currentPage().getParameters());

		// If there is a work order, redirect to labor, otherwise redirect to misc reimbursement
		if (theLabor.Related_Work_Order__c == null) {
        	m.put('RecordType', UtilityMethods.RecordTypeFor('Labor__c', 'Misc_Reimbursement'));
		} else {
        	m.put('RecordType', UtilityMethods.RecordTypeFor('Labor__c', 'Labor'));			
		}
        m.put('nooverride', '1');
        return p;
	}
	
}