RbA Build/src/objects/Municipality__c.object
<CustomObject>
    <description>Holds Municipality information that will help with HOA, Historical and Permitting details.</description>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Municipality</label>
    <nameField>
        <label>Agency Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Municipalities</pluralLabel>
    <recordTypes>
        <fullName>HOA</fullName>
        <active>true</active>
        <description>Homeowner Association Details</description>
        <label>HOA</label>
    </recordTypes>
    <recordTypes>
        <fullName>Historical</fullName>
        <active>true</active>
        <description>Holds information on Historial requirements</description>
        <label>Historical</label>
    </recordTypes>
    <recordTypes>
        <fullName>Permit</fullName>
        <active>true</active>
        <description>Hold information for Building Permits (not Building)</description>
        <label>Permit</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

RbA Build/src/objects/Purchase_Order__c.object
<CustomObject>
    <description>The purchase order header for ordering RbA and 3rd party products linked to order line items</description>
    <label>Purchase Order</label>
    <nameField>
        <label>Purchase Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Purchase Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

RbA Build/src/objects/RbA_Work_Order__c.object
<CustomObject>
    <description>Custom Object used to track Work Orders related to Orders.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Dwelling association to the Work Order.</inlineHelpText>
        <label>Account</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Dwelling</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>RbA Work Orders (Account)</relationshipLabel>
        <relationshipName>RbA_Work_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <description>“City” part of the work order location.</description>
        <inlineHelpText>“City” part of the work order location.</inlineHelpText>
        <label>City</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Name of the contact person from the customer account for this service order. Is a lookup to an existing salesforce contact record</description>
        <inlineHelpText>Name of the contact person from the customer account for this service order. Is a lookup to an existing salesforce contact record</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Service_Order</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Municipality__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>What Municipality does this Dwelling fall into?</inlineHelpText>
        <label>Municipality</label>
        <referenceTo>Municipality__c</referenceTo>
        <relationshipLabel>Permit Work Orders</relationshipLabel>
        <relationshipName>Work_Orders_Permits1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Related Opportunity</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Work Orders</relationshipLabel>
        <relationshipName>Work_Orders1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Order_Type__c</fullName>
        <description>Type of service order: Field Service, Depot repair etc.</description>
        <inlineHelpText>Type of service order: Field Service, Depot repair etc.</inlineHelpText>
        <label>Order Type</label>
        <picklist>
            <picklistValues>
                <fullName>Tech Measure</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Install</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Service</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HOA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Historical</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Building Permit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Paint/Stain</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LSWP</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Sold_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sold Order</label>
        <referenceTo>Order</referenceTo>
        <relationshipLabel>Work Orders</relationshipLabel>
        <relationshipName>Work_Orders1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <description>“State” part of the work order location</description>
        <inlineHelpText>“State” part of the work order location</inlineHelpText>
        <label>State</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street__c</fullName>
        <description>“Street” part of the work order location</description>
        <inlineHelpText>“Street” part of the work order location</inlineHelpText>
        <label>Street</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Zip__c</fullName>
        <description>“Zip code” part of the work order location</description>
        <inlineHelpText>“Zip code” part of the work order location</inlineHelpText>
        <label>Zip</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>RbA Work Order</label>
    <nameField>
        <displayFormat>WO-{00000000}</displayFormat>
        <label>Work Order #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RbA Work Orders</pluralLabel>
    <recordTypes>
        <fullName>Actions</fullName>
        <active>true</active>
        <description>Holds HOA and Historical Details</description>
        <label>Actions</label>
    </recordTypes>
    <recordTypes>
        <fullName>LSWP</fullName>
        <active>true</active>
        <description>Holds LSWP Details</description>
        <label>LSWP</label>
    </recordTypes>
    <recordTypes>
        <fullName>Paint_Stain</fullName>
        <active>true</active>
        <description>Hold Paint / Stain Details</description>
        <label>Paint/Stain</label>
    </recordTypes>
    <recordTypes>
        <fullName>Permit</fullName>
        <active>true</active>
        <description>Holds Building Permit Details</description>
        <label>Permit</label>
    </recordTypes>
    <recordTypes>
        <fullName>Visit</fullName>
        <active>true</active>
        <description>Hold Work Order details that can be have a scheduled visit to the home</description>
        <label>Visit</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

RbA Build/src/classes/RMS_createWorkOrderController.cls
public with sharing class RMS_createWorkOrderController {
	
	
	public string woType {get;set;}
	public string orderId {get;set;}
	public string accountId{get;set;}
	public string shippingStreet{get;set;}
	public string shippingCity{get;set;}
	public string shippingState{get;set;}
	public string shippingPostalCode{get;set;}
	public string shippingCountry{get;set;}
	public string hoa{get;set;}
	public string historical{get;set;} 
	public string permit{get;set;}
	public string opportunity{get;set;}
	public string woId{get;set;}
	public string woName{get;set;}
	public string billToContactId{get;set;}
	
	
	public string woRTid;

/******* Set up Standard Controller for Purchase_Order__c  *****************/
	private Apexpages.StandardController standardController;
	private final RbA_Work_Order__c wo;
	
	
	//Constructor
	public RMS_createWorkOrderController(ApexPages.StandardController stdController) {
		this.wo = (RbA_Work_Order__c)stdController.getRecord();
		map<string, string> urlParam = ApexPages.currentPage().getParameters();

		orderId = urlParam.get('orderId');
		accountId = urlParam.get('accountId');
		shippingStreet = urlParam.get('shippingStreet');
		shippingCity = urlParam.get('shippingCity');
		shippingPostalCode = urlParam.get('shippingPostalCode');
		shippingCountry = urlParam.get('shippingCountry');
		shippingState = urlParam.get('shippingState');
		billToContactId = urlParam.get('billToContactId');
		woType = urlParam.get('type');
		
		opportunity = urlParam.get('relatedOpp');
		
		permit = urlParam.get('permit');
		hoa = urlParam.get('hoa');
		historical = urlParam.get('historical');
		
		woName = wo.Name;
		
		if(woType == 'visit'){
			woRTid = UtilityMethods.retrieveRecordTypeId('Visit', 'RbA_Work_Order__c');
			wo.RecordTypeId = woRTid;
		}else if(woType == 'actions'){
			woRTid = UtilityMethods.retrieveRecordTypeId('Actions', 'RbA_Work_Order__c');
			wo.RecordTypeId  = woRTid;
		}else if(woType == 'lswp'){
			woRTid = UtilityMethods.retrieveRecordTypeId('LSWP', 'RbA_Work_Order__c');
			wo.RecordTypeId = woRTid;
		}else if(woType == 'paintStain'){
			woRTid = UtilityMethods.retrieveRecordTypeId('Paint_Stain', 'RbA_Work_Order__c');
			wo.RecordTypeId = woRTid; 
		}else if(woType == 'permit'){
			woRTid = UtilityMethods.retrieveRecordTypeId('Permit', 'RbA_Work_Order__c');
			wo.RecordTypeId = woRTid;
			if(permit != null && permit != '' && permit != 'null'){
				wo.Municipality__c = permit;
			}		
		}
	}
	

	public PageReference save() {
		wo.Sold_Order__c = orderId;
		wo.Account__c = accountId;
		wo.Street__c = shippingStreet;
		wo.City__c = shippingCity; 
		wo.State__c = shippingState;
		wo.Zip__c = shippingPostalCode;
		wo.Country__c = shippingCountry;
		
		if(billToContactId != null && billToContactId != 'null'){
			wo.Contact__c = billToContactId;
		}
        if(opportunity != null && opportunity != '' && opportunity != 'null'){
            wo.Opportunity__c = opportunity;
        }
		if(hoa != null && hoa != '' && hoa != 'null' && wo.Order_Type__c == 'HOA' ){
			wo.Municipality__c = hoa;
		}else if(historical != null && historical != '' && historical != 'null' && wo.Order_Type__c == 'Historical'){
			wo.Municipality__c = historical;
		}
		
		
		wo.RecordTypeId = woRTid;
		
		insert wo;
		
		// Used for redirecting to the view page from javascript
		woId = wo.Id;
		
		return null;
	} 
		
}