RbA Build/src/objects/Municipality__c.object
<CustomObject>
    <description>Holds Municipality information that will help with HOA, Historical and Permitting details.</description>
    <fields>
        <fullName>City_Township__c</fullName>
        <label>City/Township</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>County__c</fullName>
        <label>County</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zip_Code__c</fullName>
        <label>Zip Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Municipality</label>
    <nameField>
        <label>Agency Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Municipalities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

RbA Build/src/objects/Municipality_Match__c.object
<CustomObject>
    <fields>
        <fullName>Agency_Name__c</fullName>
        <label>Agency Name</label>
        <referenceTo>Municipality__c</referenceTo>
        <relationshipLabel>Municipalities Match</relationshipLabel>
        <relationshipName>Municipalities_Match</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>City_Township__c</fullName>
        <label>City/Township</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>County__c</fullName>
        <label>County</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zip_Code__c</fullName>
        <label>Zip Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Municipality Match</label>
    <nameField>
        <displayFormat>MM-{00}</displayFormat>
        <label>Municipality Match Record Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Municipalities Match</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

RbA Build/src/classes/RMS_MunicipalityManager.cls
public with sharing class RMS_MunicipalityManager {
    
    
    public void createMunicipalityMatch(List<Municipality__c> listNew, Map<Id, Municipality__c> mapNew){
        
        Id buildingPermitMunicipalitiesRecordType = UtilityMethods.retrieveRecordTypeId(Constants.PERMIT_MUNICIPALITY_RECORD_TYPE_NAME , 'Municipality__c');
        
        List<Municipality_Match__c> newMatch = new list<Municipality_Match__c>();        
        
        for(Municipality__c m : listNew){ 
            if(m.RecordTypeId == buildingPermitMunicipalitiesRecordType){
                Municipality_Match__c mm = new Municipality_Match__c(
                    Agency_Name__c = m.Id,
                    City_Township__c = m.City_Township__c,
                    Zip_Code__c = m.Zip_Code__c,
                    State__c = m.State__c,
                    County__c = m.County__c);
                
                newMatch.add(mm);
            }
            
            
        }
        insert newMatch;
        
    }
    
}