RbA Build/src/objects/Municipality__c.object
<CustomObject>
    <description>Holds Municipality information that will help with HOA, Historical and Permitting details.</description>
    <fields>
        <fullName>Application_Notes__c</fullName>
        <inlineHelpText>Notes about the Application process</inlineHelpText>
        <label>Application Notes</label>
        <type>TextArea</type>
    </fields>
    <label>Municipality</label>
    <nameField>
        <label>Agency Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Municipalities</pluralLabel>
    <recordTypes>
        <fullName>HOA</fullName>
        <active>true</active>
        <description>Homeowner Association Details</description>
        <label>HOA</label>
    </recordTypes>
    <recordTypes>
        <fullName>Historical</fullName>
        <active>true</active>
        <description>Holds information on Historial requirements</description>
        <label>Historical</label>
    </recordTypes>
    <recordTypes>
        <fullName>Permit</fullName>
        <active>true</active>
        <description>Hold information for Building Permits (not Building)</description>
        <label>Permit</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

RbA Build/src/objects/RbA_Work_Order__c.object
<CustomObject>
    <description>Custom Object used to track Work Orders related to Orders.</description>
    <fields>
        <fullName>Application_Notes__c</fullName>
        <inlineHelpText>Pulled from Municipality record</inlineHelpText>
        <label>Application Notes</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Municipality__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>What Municipality does this Dwelling fall into?</inlineHelpText>
        <label>Municipality</label>
        <referenceTo>Municipality__c</referenceTo>
        <relationshipLabel>Permit Work Orders</relationshipLabel>
        <relationshipName>Work_Orders_Permits1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Work_Order_Type__c</fullName>
        <description>Type of work order: HOA, Historical, LSWP, Building, Tech Measure, Install, Service. etc.</description>
        <inlineHelpText>Type of work order: HOA, Historical, LSWP, Building, Tech Measure, Install, Service. etc.</inlineHelpText>
        <label>Work Order Type</label>
        <picklist>
            <picklistValues>
                <fullName>Tech Measure</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Install</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Service</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HOA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Historical</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Building Permit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Paint/Stain</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LSWP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Collections</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>RbA Work Order</label>
    <nameField>
        <displayFormat>WO-{00000000}</displayFormat>
        <label>Work Order #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RbA Work Orders</pluralLabel>
    <recordTypes>
        <fullName>Permit</fullName>
        <active>true</active>
        <description>Holds Building Permit Details</description>
        <label>Permit</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

RbA Build/src/classes/RMS_addApplicationNotes.cls
public class RMS_addApplicationNotes {    
    
    public void populateApplicationNotesCreate(List<RbA_Work_Order__c> listNew, Map<Id, RbA_Work_Order__c> mapNew){
        
        List <Id> municipality = new List<Id>();
        
        for(RbA_Work_Order__c wo : listNew){
            If(wo.Work_Order_Type__c == 'Building Permit' || wo.Work_Order_Type__c == 'HOA' || wo.Work_Order_Type__c == 'Historical'){                                
                municipality.add(wo.Municipality__c);                
            }   
        }
        
        List <Municipality__c> mun = [Select ID, Application_Notes__c from Municipality__c where Id in :municipality];
        
        for (Integer i = 0; i <listNew.size(); i++){
            if (mun.size() > 0){
                for (Municipality__c z:mun){
                    if (listNew[i].Municipality__c != null){
                        listNew[i].Application_Notes__c = z.Application_Notes__c;
                    }
                }
            }
            
        }
        
    }
    
    public void populateApplicationNotesUpdate (List<RbA_Work_Order__c> listOld, List<RbA_Work_Order__c> listNew, Map<Id, RbA_Work_Order__c> mapOld, Map<Id, RbA_Work_Order__c> mapNew){
        List <Id> municipality = new List<Id>();
        
        for(RbA_Work_Order__c wo : listNew){
            If(wo.Work_Order_Type__c == 'Building Permit' || wo.Work_Order_Type__c == 'HOA' || wo.Work_Order_Type__c == 'Historical'){                                
                municipality.add(wo.Municipality__c);                
            }   
        }
        
        List <Municipality__c> mun = [Select ID, Application_Notes__c from Municipality__c where Id in :municipality];
        
        for (Integer i = 0; i <listNew.size(); i++){
            if (mun.size() > 0){               
                for (Municipality__c z:mun){
                    if (listNew[i].Municipality__c != null && mapOld.get(listNew[i].Id).Municipality__c != listNew[i].Municipality__c){
                        listNew[i].Application_Notes__c = z.Application_Notes__c;
                    }
                }
            }
            
        }
    }
    
}