RbA Build/src/objects/Order.object
<CustomObject>
    <fields>
        <fullName>Service_Type__c</fullName>
        <inlineHelpText>Job In Progress should be selected if the Installation Date of the original product was in the last 30 days. Select Save if the request is solved during the initial phone call. Field Service is the default and only option for Cottage Grove users.</inlineHelpText>
        <label>Service Type</label>
        <picklist>
            <picklistValues>
                <fullName>Job in Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Field Service</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Service</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Save</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

RbA Build/src/objects/RbA_Work_Order__c.object
<CustomObject>
    <description>Custom Object used to track Work Orders related to Orders.</description>
    <fields>
        <fullName>Service_Material_Owner_Id__c</fullName>
        <description>pulls in who the default Service Material Owner should be from the Store Config. Used when adding Service Tasks.</description>
        <formula>Account__r.Store_Location__r.Active_Store_Configuration__r.Service_Material_Owner__c</formula>
        <inlineHelpText>pulls in who the default Service Material Owner should be from the Store Config. Used when adding Service Tasks.</inlineHelpText>
        <label>Service Material Owner Id</label>
        <type>Text</type>
    </fields>
    <label>RbA Work Order</label>
    <nameField>
        <displayFormat>WO-{00000000}</displayFormat>
        <label>Work Order #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RbA Work Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

RbA Build/src/classes/RMS_editableTaskListExt.cls
/*******************************************************//**

@class  RMS_editableTaskListExt


@author  Brianne Wilson (Slalom.BLW)

@brief 1 of 2 classes used on the RMS_addMultipleTaskstoWO page
for creating a dynamic page where user may add multiple records
on a single page. Class used to create records and add/delete
rows on the single page, each representing a new record.

@version    2016-05-11 Slalom.BLW
Created.


@copyright  (c)2016 Slalom.  All Rights Reserved. 
Unauthorized use is prohibited.

***********************************************************/

public with sharing class RMS_editableTaskListExt extends RMS_editableTaskList
{
    
    
    public RbA_Work_Order__c myWO {get; private set;}
    
    public RMS_editableTaskListExt(ApexPages.StandardController stdController) 
    {
        super(stdController);
        
        
        this.myWO = [SELECT Id, Service_Material_Owner_Id__c                             
                     FROM RbA_Work_Order__c
                     WHERE Id =: stdController.getRecord().Id];
        
        this.childList = [SELECT Id,
                          WhatId,
                          Assigned_To__c,
                          Service_Type__c,
                          Subject,
                          Status,
                          OwnerId                          
                          FROM Task
                          WHERE WhatId =: mysObject.Id
                          AND Status = 'Open'];
    }
    
    /*
* This method is necessary for reference on the Visualforce page, 
* in order to reference non-standard fields.
*/
    public List<Task> getChildren()
    {
        return (List<Task>)childList;
    }
    
    public override sObject initChildRecord()
    {
        Task child = new Task();
        child.WhatId = myWO.Id; 
        child.Status = 'Open';                  
        child.Service_Material_Owner_Id__c = myWo.Service_Material_Owner_Id__c;
        
        return child;
    }
    
}