RbA Build/src/objects/Order.object
<CustomObject>
    <fields>
        <fullName>Retail_Total__c</fullName>
        <description>The total retail amount (retail subtotal - discount)</description>
        <formula>Retail_Subtotal__c -  Discount_Amount__c + Change_Order_Total__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>The total retail amount (retail subtotal - discount)</inlineHelpText>
        <label>Retail Total</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Sold_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>When the Sold Order is Job In Progress, the Service Order must be related to the Sold Order.</inlineHelpText>
        <label>Sold Order</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>$Source.AccountId</field>
                <operation>equals</operation>
                <valueField>Order.AccountId</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Order</referenceTo>
        <relationshipLabel>Service Orders</relationshipLabel>
        <relationshipName>Sold_Order</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Change_Order</fullName>
        <active>true</active>
        <label>Change Order</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

RbA Build/src/classes/RMS_ViewChangeOrdersController.cls
/*******************************************************//**

@class  RMS_ViewChangeOrdersController

@brief  Controller for RMS_viewChangeOrders visualforce page

@author  Kai Ruan (Slalom)

@version    2016-8-16  Slalom
Created.

@copyright  (c)2016 Slalom.  All Rights Reserved. 
Unauthorized use is prohibited.

***********************************************************/
public with sharing class RMS_ViewChangeOrdersController {
    
    public String strurl;
    public String baseUrl{get;set;}
    public Id ChangeOrderRecordTypeId{get;set;}
    public List<Order> orders{get;set;}
    public Order ord{get;set;}
    
    /******* Set up Standard Controller for Order  *****************/
    private Apexpages.StandardController standardController;
    
    
    //Constructor
    public RMS_ViewChangeOrdersController(ApexPages.StandardController stdController) {
        this.ord = (Order)stdController.getRecord();
       
        strurl = ApexPages.currentPage().getUrl();
        strurl = strurl.split('apex/')[1];
        baseUrl = URL.getSalesforceBaseUrl().toExternalForm();
        ChangeOrderRecordTypeId = UtilityMethods.retrieveRecordTypeId('Change_Order', 'Order');
        orders = [SELECT 	Name,
                  OrderNumber,
                  Retail_Total__c,
                  CreatedDate
                  FROM 	Order
                  WHERE 	RecordTypeId =: ChangeOrderRecordTypeId
                  AND 	Sold_Order__c =: ord.Id];	 
        
        
    }
    
}