RbA Build/src/objects/Order.object
<CustomObject>
    <fields>
        <fullName>Sold_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>When the Sold Order is Job In Progress, the Service Order must be related to the Sold Order.</inlineHelpText>
        <label>Sold Order</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>$Source.AccountId</field>
                <operation>equals</operation>
                <valueField>Order.AccountId</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Order</referenceTo>
        <relationshipLabel>Service Orders</relationshipLabel>
        <relationshipName>Sold_Order</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

RbA Build/src/objects/RbA_Work_Order__c.object
<CustomObject>
    <description>Custom Object used to track Work Orders related to Orders.</description>
    <fields>
        <fullName>Sold_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sold Order</label>
        <referenceTo>Order</referenceTo>
        <relationshipLabel>Work Orders</relationshipLabel>
        <relationshipName>Work_Orders1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Work_Order_Type__c</fullName>
        <description>Type of work order: HOA, Historical, LSWP, Building, Tech Measure, Install, Service. etc.</description>
        <inlineHelpText>Type of work order: HOA, Historical, LSWP, Building, Tech Measure, Install, Service. etc.</inlineHelpText>
        <label>Work Order Type</label>
        <picklist>
            <picklistValues>
                <fullName>Tech Measure</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Install</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Service</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HOA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Historical</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Building Permit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Paint/Stain</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LSWP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Collections</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>RbA Work Order</label>
    <nameField>
        <displayFormat>WO-{00000000}</displayFormat>
        <label>Work Order #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RbA Work Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

RbA Build/src/classes/RMS_FutureRollups.cls
global with sharing class RMS_FutureRollups {

	@future
	public static void rollupWorkOrdersToOrders(Set<Id> workOrders)
	{  
		List<Order> orderRecords = new List<Order>(); 
		List<RbA_Work_Order__c> workOrderRecords = new List<RbA_Work_Order__c>(); 
		workOrderRecords = [SELECT Id, Work_Order_Type__c, Sold_Order__c from RbA_Work_Order__c where Id IN: workOrders];
		//dlrs.RollupService.rollup(orderRecords);
        orderRecords =  dlrs.RollupService.rollup(workOrderRecords);
        update orderRecords;
    }
}