RbA Build/src/objects/Order.object
<CustomObject>
    <fields>
        <fullName>Service_Type__c</fullName>
        <inlineHelpText>Job In Progress should be selected if the Installation Date of the original product was in the last 30 days. Select Save if the request is solved during the initial phone call. Field Service is the default and only option for Cottage Grove users.</inlineHelpText>
        <label>Service Type</label>
        <picklist>
            <picklistValues>
                <fullName>Job in Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Field Service</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Service</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Save</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

RbA Build/src/objects/RbA_Work_Order__c.object
<CustomObject>
    <description>Custom Object used to track Work Orders related to Orders.</description>
    <label>RbA Work Order</label>
    <nameField>
        <displayFormat>WO-{00000000}</displayFormat>
        <label>Work Order #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RbA Work Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

RbA Build/src/classes/editableTaskListExt.cls
public with sharing class editableTaskListExt extends editableTaskList
{


 public RbA_Work_Order__c myWO {get; private set;}

  public editableTaskListExt(ApexPages.StandardController stdController) 
  {
    super(stdController);


    this.myWO = [SELECT Id                            
                            FROM RbA_Work_Order__c
                            WHERE Id =: stdController.getRecord().Id];
    
    this.childList = [SELECT Id,
                          WhatId,
                          Service_Type__c,
                          Subject,
                          Status,
                          OwnerId,
                          Non_Stock_Material__c                          
                      FROM Task
                      WHERE WhatId =: mysObject.Id
                      AND Status = 'Open'];
  }

  /*
   * This method is necessary for reference on the Visualforce page, 
   * in order to reference non-standard fields.
   */
  public List<Task> getChildren()
  {
    return (List<Task>)childList;
  }

  public override sObject initChildRecord()
  {
    Task child = new Task();
    // Can either use mysObject or acct here
    child.WhatId = mysObject.Id; 
    child.Status = 'Open';        
    
    return child;
  }
    
}