RbA Build/src/objects/Order.object
<CustomObject>
    <fields>
        <fullName>Sold_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>When the Sold Order is Job In Progress, the Service Order must be related to the Sold Order.</inlineHelpText>
        <label>Sold Order</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>$Source.AccountId</field>
                <operation>equals</operation>
                <valueField>Order.AccountId</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Order</referenceTo>
        <relationshipLabel>Service Orders</relationshipLabel>
        <relationshipName>Sold_Order</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

RbA Build/src/objects/Product_Skill__c.object
<CustomObject>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Product Skills</relationshipLabel>
        <relationshipName>Product_Skills</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RbA_Skill__c</fullName>
        <label>RbA Skill</label>
        <referenceTo>RbA_Skills__c</referenceTo>
        <relationshipLabel>Product Skills</relationshipLabel>
        <relationshipName>Product_Skills</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Product Skill</label>
    <nameField>
        <displayFormat>Product Skill #-{00}</displayFormat>
        <label>Product Skill #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Skills</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

RbA Build/src/objects/RbA_Skills__c.object
<CustomObject>
    <description>Used for Scheduling.  Skills are assiged to Resources and RbA Work Orders.</description>
    <label>RbA Skill</label>
    <nameField>
        <label>RbA Skill Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RbA Skills</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

RbA Build/src/objects/RbA_Work_Order__c.object
<CustomObject>
    <description>Custom Object used to track Work Orders related to Orders.</description>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Product in which specialization would be required to service the work order. Calculated from installed product by OptiMax pre-calculation engine</description>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Work Orders</relationshipLabel>
        <relationshipName>Service_Order1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sold_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sold Order</label>
        <referenceTo>Order</referenceTo>
        <relationshipLabel>Work Orders</relationshipLabel>
        <relationshipName>Work_Orders1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Work_Order_Type__c</fullName>
        <description>Type of work order: HOA, Historical, LSWP, Building, Tech Measure, Install, Service. etc.</description>
        <inlineHelpText>Type of work order: HOA, Historical, LSWP, Building, Tech Measure, Install, Service. etc.</inlineHelpText>
        <label>Work Order Type</label>
        <picklist>
            <picklistValues>
                <fullName>Tech Measure</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Install</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Service</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HOA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Historical</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Building Permit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Paint/Stain</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LSWP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Collections</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>RbA Work Order</label>
    <nameField>
        <displayFormat>WO-{00000000}</displayFormat>
        <label>Work Order #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RbA Work Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

RbA Build/src/objects/Work_Order_Required_Skill__c.object
<CustomObject>
    <description>Required Skills on the Work Order</description>
    <fields>
        <fullName>RbA_Skill__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>RbA Skill</label>
        <referenceTo>RbA_Skills__c</referenceTo>
        <relationshipLabel>Work Order Required Skills</relationshipLabel>
        <relationshipName>Work_Order_Required_Skills</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RbA_Work_Order__c</fullName>
        <label>RbA Work Order</label>
        <referenceTo>RbA_Work_Order__c</referenceTo>
        <relationshipLabel>Work Order Required Skills</relationshipLabel>
        <relationshipName>Work_Order_Required_Skills</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Work Order Required Skill</label>
    <nameField>
        <displayFormat>WO ReqSkill - {00}</displayFormat>
        <label>WO Required Skill #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work Order Required Skills</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

RbA Build/src/classes/RMS_addSkilltoWO.cls
/*******************************************************//**

@class  RMS_addSkilltoWO

@brief  For Install and Tech Measure Work Orders, on create, system queries
the Products of the related Order and finds the Skills assigned
to each Product. Then for each skill for each product, a Work
Order Required Skill record is created to denote which skills are 
required for the Work Order. 

data model: RbA Skill represents each actual "Skill" with the name field
a text field. Product Skill is a junction object between Product and RbA Skill.
Resource Skill is a junction object between Resource and RbA Skill. 
Work Order Required Skill is a junction object between RbA Work Order and RbA Skill.

This process is used in part with scheduling, by matching Product Skills to Work 
Order Products to determine the required skills for an install work order. From there,
Resources can be matched to the work order based on resource skills compared to work 
order required skills.

@author  Brianne Wilson (Slalom.BLW)

@version    2016-4-19  Slalom.BLW
Created.


@copyright  (c)2016 Slalom.  All Rights Reserved. 
Unauthorized use is prohibited.

***********************************************************/

public with sharing class RMS_addSkilltoWO {
    
    
    public void addSkilltoWO (List<RbA_Work_Order__c> listNew, Map<Id, RbA_Work_Order__c> mapNew){
        
        //create list to hold Work Order Required Skills
        List<Work_Order_Required_Skill__c> newWORS = new list<Work_Order_Required_Skill__c>();        
        
        //List of ids for the related Sold Orders
        List<Id> relatedOrder = new list<Id>();
        
        //for the new RbA Work Order, add to the related Order Id list the Sold Order field on the WO
        for(RbA_Work_Order__c rwo : listNew){
            if(rwo.Sold_Order__c != null){
                relatedOrder.add(rwo.Sold_Order__c);    
            }            
        }
        
        //Store the list of Order Items of the related Sold Order to find the products and their
        //product skills
        List<id> oiIds = new List<id>();{
            for(OrderItem oi : [SELECT  Id, PricebookEntry.Product2Id
                                FROM OrderItem 
                                WHERE OrderId = :relatedOrder]){
                                    
                                    oiIds.add(oi.PricebookEntry.Product2Id);
                                }   
        }
        
        
        //List of RbA Skill ids of the Products in the Order Items
        //of the related Sold Order. Store the RbA Skill value in the Product Skill to the 
        //skillids list
        List<id> skillIds = new List<id>();{
            for(Product_Skill__c s : [SELECT  Id,RbA_Skill__c, Product__c
                                      FROM Product_Skill__c 
                                      WHERE Product__c = :oiIds]){
                                          
                                          skillIds.add(s.RbA_Skill__c);
                                      } 
            
            //if the new RbA Work Order has a Work Order Type of Install,
            //then for each RbA Skill in the skillids list, create a 
            //Work Order Required Skill record
            for(RbA_Work_Order__c rwo : listNew){ 
                If(rwo.Work_Order_Type__c == 'Install' || rwo.Work_Order_Type__c == 'Tech Measure'){
                    for (RbA_Skills__c r :[Select Id FROM RbA_Skills__c WHERE Id = :skillIds] ) {          
                        Work_Order_Required_Skill__c ch = new Work_Order_Required_Skill__c(
                            RbA_Work_Order__c = rwo.Id,
                            RbA_Skill__c = r.Id);
                        
                        newWORS.add(ch);
                    }
                }
            }
            insert newWORS;
            
        }
        
    }
}