RbA Build/src/objects/Order.object
<CustomObject>
    <fields>
        <fullName>Date_Cancelled__c</fullName>
        <label>Date Cancelled</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Sold_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>When the Sold Order is Job In Progress, the Service Order must be related to the Sold Order.</inlineHelpText>
        <label>Sold Order</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>$Source.AccountId</field>
                <operation>equals</operation>
                <valueField>Order.AccountId</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Order</referenceTo>
        <relationshipLabel>Service Orders</relationshipLabel>
        <relationshipName>Sold_Order</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

RbA Build/src/objects/Order_Discount__c.object
<CustomObject>
    <description>Junction from the discount to the order</description>
    <fields>
        <fullName>Order__c</fullName>
        <description>The discount is applied to this order</description>
        <inlineHelpText>The discount is applied to this order</inlineHelpText>
        <label>Order</label>
        <referenceTo>Order</referenceTo>
        <relationshipName>Discount_Applied</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>The status of the order discount.</description>
        <inlineHelpText>The status of the order discount.</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Applied</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Order Discount</label>
    <nameField>
        <displayFormat>OD-{00000000}</displayFormat>
        <label>Order Discount Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Discounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

RbA Build/src/objects/OrderItem.object
<CustomObject>
    <fields>
        <fullName>Purchase_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The purchase order that covers this sales order line item</description>
        <inlineHelpText>The purchase order that covers this sales order line item</inlineHelpText>
        <label>Purchase Order</label>
        <referenceTo>Purchase_Order__c</referenceTo>
        <relationshipLabel>Order Products</relationshipLabel>
        <relationshipName>Order_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>The status of the order line item.</description>
        <inlineHelpText>The status of the order line item.</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Configured</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Verified</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Partially Received</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Received</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

RbA Build/src/objects/Purchase_Order__c.object
<CustomObject>
    <description>The purchase order header for ordering RbA and 3rd party products linked to order line items</description>
    <fields>
        <fullName>Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The parent sales order of this purchase order</description>
        <inlineHelpText>The parent sales order of this purchase order</inlineHelpText>
        <label>Order</label>
        <referenceTo>Order</referenceTo>
        <relationshipLabel>Purchase Orders</relationshipLabel>
        <relationshipName>Purchase_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>The status of the purchase order.</description>
        <inlineHelpText>The status of the purchase order.</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>In Process</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On Hold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Released</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Confirmed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Received</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Purchase Order</label>
    <nameField>
        <label>Purchase Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Purchase Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

RbA Build/src/objects/RbA_Work_Order__c.object
<CustomObject>
    <description>Custom Object used to track Work Orders related to Orders.</description>
    <fields>
        <fullName>Cancel_Reason__c</fullName>
        <label>Cancel Reason</label>
        <picklist>
            <picklistValues>
                <fullName>Weather</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Family Emergency</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Schedule Conflict</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Resource Constraint</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Order Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Project On Hold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Homeowner Request</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Duplicate</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Number_Open_Events_Formula__c</fullName>
        <description>Determines if there are any open events, if so the Work Order may not be closed/completed</description>
        <formula>IF( 
     AND(ISPICKVAL(Work_Order_Type__c,&quot;Service&quot;),   
     NOT(ISBLANK(Scheduled_Appt_Date_Time_Service__c)),  
     Scheduled_Appt_Date_Time_Service__c&gt;NOW(),
     NOT(ISBLANK(Primary_Service__c))),1,
IF( 
     AND(ISPICKVAL(Work_Order_Type__c,&quot;Install&quot;), 
     NOT(ISBLANK(Scheduled_Appt_Date_Time_Install__c)),   
     Scheduled_Appt_Date_Time_Install__c&gt;NOW(),
     NOT(ISBLANK(Primary_Installer__c))),1,
IF( 
     AND(ISPICKVAL(Work_Order_Type__c,&quot;Tech Measure&quot;), 
     NOT(ISBLANK(Scheduled_Appt_Date_Time_Tech_Measure__c)),   
     Scheduled_Appt_Date_Time_Tech_Measure__c&gt;NOW(),
     NOT(ISBLANK(Primary_Tech_Measure__c))),1,0)))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Determines if there are any open events, if so the Work Order may not be closed/completed</inlineHelpText>
        <label>Number Open Events</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sold_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sold Order</label>
        <referenceTo>Order</referenceTo>
        <relationshipLabel>Work Orders</relationshipLabel>
        <relationshipName>Work_Orders1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Work_Order_Status__c</fullName>
        <description>Current status of the work order</description>
        <inlineHelpText>Current status of the work order</inlineHelpText>
        <label>Work Order Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Open</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wait for Install</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>To be scheduled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Applied</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Received</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Scheduled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>JIP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On Hold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Install Complete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Final Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Final Failed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Denied</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Assignment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Scheduled &amp; Assigned</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Appt Complete / Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Suspended / On Hold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Complete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Shared Services</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Work_Order_Type__c</fullName>
        <description>Type of work order: HOA, Historical, LSWP, Building, Tech Measure, Install, Service. etc.</description>
        <inlineHelpText>Type of work order: HOA, Historical, LSWP, Building, Tech Measure, Install, Service. etc.</inlineHelpText>
        <label>Work Order Type</label>
        <picklist>
            <picklistValues>
                <fullName>Tech Measure</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Install</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Service</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HOA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Historical</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Building Permit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Paint/Stain</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LSWP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Collections</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>RbA Work Order</label>
    <nameField>
        <displayFormat>WO-{00000000}</displayFormat>
        <label>Work Order #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RbA Work Orders</pluralLabel>
    <recordTypes>
        <fullName>LSWP</fullName>
        <active>true</active>
        <description>Holds LSWP Details</description>
        <label>LSWP</label>
    </recordTypes>
    <recordTypes>
        <fullName>Permit</fullName>
        <active>true</active>
        <description>Holds Building Permit Details</description>
        <label>Permit</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

RbA Build/src/classes/RMS_cancelOrderExtension.cls
/*******************************************************//**

@class	RMS_cancelOrderExtension

@brief	Controller extension for VF page RMS_cancelOrder.page

	Cancels the order and other related records

@author  Creston Kuenzi (Slalom.CDK)

@version	2015-10-25  Slalom.CDK
	Created.

@see		RMS_cancelOrderExtensionTest

@copyright  (c)2015 Slalom.  All Rights Reserved.
			Unauthorized use is prohibited. 

***********************************************************/
public with sharing class RMS_cancelOrderExtension {


	/******* Set up Standard Controller for Order  *****************/
	private Apexpages.StandardController standardController;
	private final Order theOrder;
	
	/******* Constructor  *****************/
	public RMS_cancelOrderExtension(ApexPages.StandardController stdController) {
		this.theOrder = (Order)stdController.getRecord();
	}
	
	/*******************************************************
					cancelOrder method
	*******************************************************/
	public PageReference cancelOrder() {
		system.debug('*****Cancelling an order');

		String theId = ApexPages.currentPage().getParameters().get('id');

		if (theId == null) {
			// Display the Visualforce page's content if no Id is found
			return null;
		}

		// Find the order and cancel it
		Order theOrder = [Select Id, Name, Status from Order where id =:theId];
		theOrder.Status = 'Cancelled';
		theOrder.Date_Cancelled__c = System.Today();


		List<RbA_Work_Order__c> workOrdersWithOpenEvents = [Select Id from RbA_Work_Order__c WHERE Sold_Order__c =:theOrder.Id 
                                                            AND Number_Open_Events_Formula__c > 0];
		if(!workOrdersWithOpenEvents.isEmpty()){
			System.debug('Error encountered in RMS_CancelOrderExtensions: ' + RMS_errorMessages.WORK_ORDERS_WITH_OPEN_EVENTS);
			ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, RMS_errorMessages.WORK_ORDERS_WITH_OPEN_EVENTS)); 
			return null;
		}	
		List<Purchase_Order__c> purchaseOrdersToCancel = new List<Purchase_Order__c>();
		List<OrderItem> orderItemsToCancel = new List<OrderItem>();
		List<Order_Discount__c> discountsToCancel = new List<Order_Discount__c>();
		List<RbA_Work_Order__c> workOrdersToCancel = new List<RbA_Work_Order__c>();

		// Find any purchase orders linked to the order that haven't been cancelled and cancel them
		for (Purchase_Order__c poToCancel : [SELECT Id, Status__c FROM Purchase_Order__c 
											WHERE Order__c =: theOrder.Id AND Status__c != 'Cancelled']) 
		{
			poToCancel.Status__c = 'Cancelled';
			purchaseOrdersToCancel.add(poToCancel);
		}

		// Find any order items linked to the order that haven't been cancelled and cancel them
		for (OrderItem orderItemToCancel : [SELECT Id, Status__c FROM OrderItem 
											WHERE OrderId =: theOrder.Id AND Status__c != 'Cancelled']) 
		{
			orderItemToCancel.Status__c = 'Cancelled';
			orderItemsToCancel.add(orderItemToCancel);
		}

		// Find any discounts linked to the order that haven't been cancelled and cancel them
		for (Order_Discount__c discToCancel : [SELECT Id, Status__c FROM Order_Discount__c 
											WHERE Order__c =: theOrder.Id AND Status__c != 'Cancelled']) 
		{
			discToCancel.Status__c = 'Cancelled';
			discountsToCancel.add(discToCancel);
		}

		for(RbA_Work_Order__c woTocancel : [Select Id, Work_Order_Status__c, Work_Order_Type__c, Cancel_Reason__c FROM RbA_Work_Order__c
											WHERE Work_Order_Type__c in ('LSWP','Bulding Permit','HOA','Historical','Tech Measure','Install','Paint/Stain')
											AND Sold_Order__c =:theOrder.Id]){
			woToCancel.Work_Order_Status__c = 'Cancelled';
			if (woToCancel.Cancel_Reason__c == null) woToCancel.Cancel_Reason__c = 'Order Cancelled';
			workOrdersToCancel.add(woTocancel);
		}

		try{
			// upsert all of the cancelled order items, pos, and the order
			upsert purchaseOrdersToCancel;  
			upsert discountsToCancel; 
			upsert orderItemsToCancel; 
			update workOrdersToCancel;
			upsert theOrder;
		} catch (Exception e){
			// TODO: Add comment here
			System.debug('************The following exception occurred in the RMS_cancelOrderExtension in the cancelOrder method:' + e);
			return null;
		}

		// Redirect the user back to the order page
		PageReference pageRef = new PageReference('/' + theId);
		pageRef.setRedirect(true);
		return pageRef;

	}
}