RbA Build/src/objects/Order.object
<CustomObject>
    <fields>
        <fullName>Sold_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>When the Sold Order is Job In Progress, the Service Order must be related to the Sold Order.</inlineHelpText>
        <label>Sold Order</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>$Source.AccountId</field>
                <operation>equals</operation>
                <valueField>Order.AccountId</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Order</referenceTo>
        <relationshipLabel>Service Orders</relationshipLabel>
        <relationshipName>Sold_Order</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

RbA Build/src/objects/Store_Configuration__c.object
<CustomObject>
    <description>Holds Store Settings &amp; Configurations</description>
    <fields>
        <fullName>Install_Work_Order_Queue_Id__c</fullName>
        <label>Install Work Order Queue Id</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Order_Queue_Id__c</fullName>
        <label>Order Queue Id</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Store__c</fullName>
        <label>Store</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Store Configurations</relationshipLabel>
        <relationshipName>Store_Configurations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Tech_Measure_Work_Order_Queue_Id__c</fullName>
        <label>Tech Measure Work Order Queue Id</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Store Configuration</label>
    <nameField>
        <displayFormat>SS-{00}</displayFormat>
        <label>Store Setting Record #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Store Configurations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

RbA Build/src/objects/SVMXC__Service_Order__c.object
<CustomObject>
    <customHelp>SVMXC__SVMXC_LaunchHelp</customHelp>
    <description>Service Order is used to plan, execute and manage Service events for Field and Depot Service activities. Depending upon the service scenario, the order creation can be triggered by many events: When creating a Support Case, when one or more installed products require periodic service or calibration, when troubleshooting a customer problem on the field, if the field service engineer learns that the product requires specialized conditions of a factory/depot to resolve the problem, or when a new/repair shipment to customer requires specialized installation activity.</description>
    <fields>
        <fullName>SVMXC__Order_Type__c</fullName>
        <description>Type of service order: Field Service, Depot repair etc.</description>
        <inlineHelpText>Type of service order: Field Service, Depot repair etc.</inlineHelpText>
        <label>Order Type</label>
        <picklist>
            <picklistValues>
                <fullName>Tech Measure</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Install</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Service</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HOA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Historical</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Building Permit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Paint/Stain</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LSWP</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Sold_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sold Order</label>
        <referenceTo>Order</referenceTo>
        <relationshipLabel>Work Orders</relationshipLabel>
        <relationshipName>Work_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Work Order</label>
    <nameField>
        <displayFormat>WO-{00000000}</displayFormat>
        <label>Work Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

RbA Build/src/classes/RMS_priceCalcSlimAPILogic.cls
public with sharing class RMS_priceCalcSlimAPILogic {

	public String findAppointments(String UserId){
		
		list<Event> eventsOwned = [SELECT Id, WhatId FROM Event Where OwnerId =: UserId];
		if(eventsOwned.size() > 0){
			

			list<appointmentWrapper> appointmentWrapperList = new list<appointmentWrapper>();
			
			List<id> accountIdList = new List<id>();
			List<id> opportunityIdList = new List<id>();
			List<id> contactIdList = New List<id>();
			for(Event e : eventsOwned){
				opportunityIdList.add(e.whatId);
			}
			
			List<Opportunity> relatedOpportunities = [SELECT Id, Name, AccountId FROM Opportunity WHERE Id IN :opportunityIdList];
			
			for(Opportunity o : relatedOpportunities){
				accountIdList.add(o.AccountId);
			}
						
			List<Account> relatedAccounts = [SELECT Id, Name FROM Account WHERE Id IN :accountIdList];
			List<Contact> relatedContacts = [SELECT Id, Name, AccountId FROM Contact WHERE AccountId IN: accountIdList];
			
			Map<id,Opportunity> opportunityIdToOpportunityMap = new Map<id, Opportunity>();
			Map<id,Account> accountIdToAccountMap = new Map<id, Account>();
			Map<id,list<Contact>> accountIdtoContactListMap = new Map<id, list<Contact>>();
			
			for(Opportunity o : relatedOpportunities){
				opportunityIdToOpportunityMap.put(o.id, o);
			}
			for(Account a : relatedAccounts){
				accountIdToAccountMap.put(a.id, a);
			}
			for(Contact c : relatedContacts){
				if(accountIdtoContactListMap.containsKey(c.AccountId)){
					accountIdtoContactListMap.get(c.AccountId).add(c);
				}else{
					accountIdtoContactListMap.put(c.AccountId, new list<Contact>{c});
				}
			}
					
			
			for(Event e : eventsOwned){
				Opportunity opp = opportunityIdToOpportunityMap.get(e.WhatId);
				Account account = accountIdToAccountMap.get(opp.AccountId);
				List<Contact> activeContacts = accountIdtoContactListMap.get(account.id);
				
				AppointmentWrapper aw = new AppointmentWrapper(e, opp, account, activeContacts);
				appointmentWrapperList.add(aw);
			}	
			
			
			return JSON.serializePretty(appointmentWrapperList);
			
		}else{
			return 'No appointments found';
		}

	}
		
	public class AppointmentWrapper{
		public Event event {get; set;}
   		public Opportunity opportunity {get; set;}
   		public Account account {get; set;}
        public List<Contact> contactList {get; set;}
   		
   		
        public AppointmentWrapper(Event e, Opportunity o, Account a, List<Contact> cl ) {
            event = e;
            opportunity = o;
            account = a;
            contactList = cl;
        }                            
    }
    
    
    
    public String updateOpportunity(String OppId, String Status){
    	List<Opportunity> opp = [SELECT Id, Name, AccountId FROM Opportunity WHERE Id = :OppId];
    	if(opp.size() == 0){
    		return 'No Opportunity found with that Id';
    	}else{
    		list<Store_Configuration__c> storeConfig = [SELECT 	Id, 
    															Store__c, 
    															Install_Work_Order_Queue_Id__c, 
    															Tech_Measure_Work_Order_Queue_Id__c, 
    															Order_Queue_Id__c
    															FROM Store_Configuration__c
    															WHERE Store__r.id =: opp[0].AccountId];
    		
    		//ORDER related to the Opp
    		Order ord = new Order(
    			AccountId = opp[0].AccountId,
    			OwnerId = storeConfig[0].Order_Queue_Id__c,
    			Status = 'Draft',
    			EffectiveDate = Date.today(),
    			Opportunity = opp 
    		);
    		insert ord;
    		//Unable to create order with Activated status
    		
    		//Create products on order here
    		
    		//ord.Status = 'Activated';
    		//update ord;
    		
    		/******************* NOW HANDLED IN TRIGGER
    		
    		
    		RecordType serviceOrderScheduleRecordType = [SELECT id FROM RecordType WHERE SobjectType = 'SVMXC__Service_Order__c' AND Name = 'Schedule'];
    		//CREATE WORK ORDER (TECH MEASURE)
    		SVMXC__Service_Order__c techWO = new SVMXC__Service_Order__c(
    			Sold_Order__c = ord.id,
    			RecordType = serviceOrderScheduleRecordType,
    			SVMXC__Order_Type__c = 'Tech Measure',
    			OwnerId = storeConfig[0].Tech_Measure_Work_Order_Queue_Id__c
    		);
    		 	
    		 	system.debug('ads storeConfig[0].Tech_Measure_Work_Order_Queue_Id__c: '+storeConfig[0].Tech_Measure_Work_Order_Queue_Id__c);
    		 	list<QueueSobject> x = [SELECT id, sobjectType, QueueId  FROM QueueSobject WHERE QueueId =: storeConfig[0].Tech_Measure_Work_Order_Queue_Id__c];
				system.debug('ads checking queue type');
				system.debug('ads: '+ x[0].sobjectType);
    		
    		
    		insert techWO;
    		
    		
    		//CREATE WORK ORDER (INSTALL)
    		SVMXC__Service_Order__c installWO = new SVMXC__Service_Order__c(
    			Sold_Order__c = ord.id, 
    			RecordType =  serviceOrderScheduleRecordType,
    			SVMXC__Order_Type__c = 'Install',
    			OwnerId = storeConfig[0].Install_Work_Order_Queue_Id__c
    		);
    		insert installWO;
			
			*********************/
			
			return 'Created Order, Install Work Order and Tech Measure Work Order';
    	}
    }
	
	
}