RbA Build/src/objects/Problem_Component__c.object
<CustomObject>
    <description>The Problem Component code associated to the actual Service Product, filtered based on Service Symptom and Product</description>
    <fields>
        <fullName>Problem_Component_asgn__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This adds a Problem Component to the Service Symptom and Service Product. Looks up to &quot;Problem Component Assignment&quot;. The Problem Component Assignment is the junction object between Problem Components and Service Symptoms. This lookup therefore is filtered to show only those Problem Components for the Service Symptom of this product.</description>
        <inlineHelpText>This adds a Problem Component to the Service Symptom and Service Product. Looks up to &quot;Problem Component Assignment&quot;. The Problem Component Assignment is the junction object between Problem Components and Service Symptoms. This lookup therefore is filtere</inlineHelpText>
        <label>Problem Component</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Problem_Component_Config__c.Service_Symptom__c</field>
                <operation>equals</operation>
                <valueField>$Source.Service_Symptom_Validation__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Problem_Component_Config__c</referenceTo>
        <relationshipLabel>Service Requests - Problem Components</relationshipLabel>
        <relationshipName>Problem_Components</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Service_Product_lkup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Links the Problem Component to the Service Product of the related Service Symptom. Set by code in the backoffice when adding Problem Components.</description>
        <inlineHelpText>Links the Problem Component to the Service Product of the related Service Symptom. Set by code in the backoffice when adding Problem Components.</inlineHelpText>
        <label>Service Product</label>
        <referenceTo>OrderItem</referenceTo>
        <relationshipLabel>Problem Components</relationshipLabel>
        <relationshipName>Problem_Components</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Service_Symptom_Validation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Used in part to ensure that the Problem Components available are filtered properly so that the Service Symptom on the Problem Component Assignment is equal to the Service Symptom List item.</description>
        <inlineHelpText>Used in part to ensure that the Problem Components available are filtered properly so that the Service Symptom on the Problem Component Assignment is equal to the Service Symptom List item.</inlineHelpText>
        <label>Service Symptom Validation</label>
        <referenceTo>Service_Symptom_List__c</referenceTo>
        <relationshipLabel>Problem Components</relationshipLabel>
        <relationshipName>Problem_Components</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Service_Symptom__c</fullName>
        <description>Links the selected Problem Component code to the selected Service Symptom Code</description>
        <inlineHelpText>Links the selected Problem Component code to the selected Service Symptom Code</inlineHelpText>
        <label>Service Symptom</label>
        <referenceTo>Service_Symptom__c</referenceTo>
        <relationshipLabel>Service Requests - Problem Components</relationshipLabel>
        <relationshipName>Problem_Components</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Problem Component</label>
    <nameField>
        <displayFormat>PC-{000}</displayFormat>
        <label>Problem Component</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Problem Components</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

RbA Build/src/objects/Problem_Component_Config__c.object
<CustomObject>
    <description>Junction Object between Product Service Symptom and Problem Component List</description>
    <fields>
        <fullName>Problem_Component__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Problem Component</label>
        <referenceTo>Problem_Component_List__c</referenceTo>
        <relationshipLabel>Service Symptoms</relationshipLabel>
        <relationshipName>Problem_Component_Config</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Service_Symptom__c</fullName>
        <label>Service Symptom</label>
        <referenceTo>Service_Symptom_List__c</referenceTo>
        <relationshipLabel>Problem Components</relationshipLabel>
        <relationshipName>Problem_Component_Config</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Problem Component Assignment</label>
    <nameField>
        <label>Problem Component Assignment</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Problem Component Assignment</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

RbA Build/src/objects/Service_Product__c.object
<CustomObject>
    <description>Junction Object linking Master Products to Service Products</description>
    <fields>
        <fullName>Service_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service Product</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Product2.RecordTypeId</field>
                <operation>equals</operation>
                <value>Service Product</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Master Products</relationshipLabel>
        <relationshipName>Service_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Service Product</label>
    <nameField>
        <displayFormat>SPA-{000000}</displayFormat>
        <label>Service Product Assignment</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

RbA Build/src/objects/Service_Symptom__c.object
<CustomObject>
    <description>The actual Service Symptom code added to the Order Item. Junction Object between Order Item and Service Symptom List</description>
    <fields>
        <fullName>Service_Product__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Service Product</label>
        <referenceTo>OrderItem</referenceTo>
        <relationshipLabel>Service Symptoms</relationshipLabel>
        <relationshipName>Service_Symptoms</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Service_Symptom__c</fullName>
        <label>Service Symptom</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>$Source.Service_Product__c</field>
                <operation>equals</operation>
                <valueField>$Source.Service_Product__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Service_Symptom_List__c</referenceTo>
        <relationshipLabel>Service Request Line Items</relationshipLabel>
        <relationshipName>Service_Symptoms</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Service Symptom</label>
    <nameField>
        <displayFormat>SS-{000}</displayFormat>
        <label>Service Symptom #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Symptoms</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

RbA Build/src/objects/Service_Symptom_List__c.object
<CustomObject>
    <label>Service Symptom List</label>
    <nameField>
        <label>Service Symptom Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Symptom List</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

RbA Build/src/classes/RMS_addProblemComponentsExt.cls
public with sharing class RMS_addProblemComponentsExt extends RMS_addProblemComponents{
    
    
    public Service_Symptom__c myWO {get; private set;}
    
    public RMS_addProblemComponentsExt (ApexPages.StandardController stdController) {        
        super(stdController);        
        
        this.myWO = [SELECT Id, Service_Product__c,Service_Symptom__c               
                     FROM Service_Symptom__c
                     WHERE Id =: stdController.getRecord().Id];
        
        this.childList = [SELECT Id,
                          Problem_Component_asgn__c,
                          Service_Symptom__c,
                          Service_Product_lkup__c ,
                          Service_Symptom_Validation__c                                 
                          FROM Problem_Component__c
                          WHERE Service_Symptom__c =: mysObject.Id];
                
        
    }
    
    public List<selectOption> getSers() {
        List<selectOption> options = new List<selectOption>(); //new list for holding all of the picklist options        
        options.add(new selectOption('', '-- SELECT --'));
        for (Service_Symptom_List__c servs : [SELECT Id,Name 
                                              FROM Service_Symptom_List__c 
                                              WHERE Name != null
                                              ORDER BY Service_Symptom_List__c.Name ASC]) { 
                                                  options.add(new selectOption(servs.Id, servs.Name)); //for all records found - add them to the picklist options
                                              } //add the first option of '- None -' in case the user doesn't want to select a value or in case no values are returned from query below        
        return options; //return the picklist options        
    }
    
    
    
    public List<Problem_Component__c> getChildren()
    {
        return (List<Problem_Component__c>)childList;
    }
    
    public override sObject initChildRecord()
    {     
        Problem_Component__c child = new Problem_Component__c();
        child.Service_Product_lkup__c  = myWO.Service_Product__c; 
        child.Service_Symptom_Validation__c = myWo.Service_Symptom__c;
        child.Service_Symptom__c = myWo.Id;
        
        return child;
    }
    
    //view problem components as picklist
    public List<selectOption> getProbs() {
        List<selectOption> options = new List<selectOption>(); //new list for holding all of the picklist options        
        options.add(new selectOption('', '-- None --')); //add the first option of '- None -' in case the user doesn't want to select a value or in case no values are returned from query below
        for (Problem_Component_Config__c  probs : [SELECT Id, Name, Problem_Component__c, Service_Symptom__c  
                                                   FROM Problem_Component_Config__c
                                                   WHERE Service_Symptom__c = :myWO.Service_Symptom__c  
                                                   ORDER BY Name ASC]) { 
                                                       options.add(new selectOption(probs.Id, probs.Name));
                                                   }        
        return options; //return the picklist options        
    } 
    
}