RbA Build/src/objects/RbA_Skills__c.object
<CustomObject>
    <description>Used for Scheduling.  Skills are assiged to Resources and RbA Work Orders.</description>
    <label>RbA Skill</label>
    <nameField>
        <label>RbA Skill Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RbA Skills</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

RbA Build/src/objects/Resource__c.object
<CustomObject>
    <description>Used to hold details about the recourse for scheduling</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>By default when a Resource is created they will be Active. Will be marked as inactive when any one of the liability insurance expires.</description>
        <inlineHelpText>Is this resource active?</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Crew_Size__c</fullName>
        <label>Crew Size</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Rank__c</fullName>
        <label>Rank</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Resource</label>
    <nameField>
        <label>Resource Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Resources</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

RbA Build/src/objects/Resource_Skill__c.object
<CustomObject>
    <description>Skills assigned to Resources</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>This checkbox determines if the resource skill is active or not</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>RbA_Skill__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>RbA Skill</label>
        <referenceTo>RbA_Skills__c</referenceTo>
        <relationshipLabel>Resource Skills</relationshipLabel>
        <relationshipName>Resource_Skills</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Resource__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Resource</label>
        <referenceTo>Resource__c</referenceTo>
        <relationshipLabel>Resource Skills</relationshipLabel>
        <relationshipName>Resource_Skills</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Resource Skill</label>
    <nameField>
        <displayFormat>Resource Skill #-{00}</displayFormat>
        <label>Resource Skill #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Resource Skills</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

RbA Build/src/classes/MA_SchedulerResource.cls
public with sharing class MA_SchedulerResource implements Comparable {

    public Integer rank;
    public Id resourceId;
    public String headcount;
    public Boolean isActive;
    public Boolean isAssigned;
    public Boolean isAvailable;
    public String resourceName;
    public String skillsMatchedTotal;
    public Integer skillsMatchedCount;
	public Map<Id, String> skillsMatched;
    public Map<Id, String> skillsNotMatched;
    
    public MA_SchedulerResource(Resource__c resource, Map<Id, String> requiredSkills, Set<Id> assignedResources) {
        this.isAvailable = true;
        this.resourceId = resource.Id;
        this.resourceName = resource.Name;
        this.isActive = resource.Active__c;
    	this.rank = (Integer)resource.Rank__c;
        this.headcount = String.valueOf(resource.Crew_Size__c);
        this.isAssigned = assignedResources.contains(this.resourceId);

        this.skillsMatched = new Map<Id, String>();
        this.skillsNotMatched = new Map<Id, String>(requiredSkills);

        for (Resource_Skill__c skill : resource.Resource_Skills__r) {
            this.skillsNotMatched.remove(skill.RbA_Skill__c);
            this.skillsMatched.put(skill.RbA_Skill__c, skill.RbA_Skill__r.Name);
        }

        this.skillsMatchedCount = this.skillsMatched.size();
        this.skillsMatchedTotal = this.skillsMatchedCount + '/' + requiredSkills.size();
    }

    public Integer compareTo(Object compareTo) {
        MA_SchedulerResource compareToResource = (MA_SchedulerResource)compareTo;

        if (skillsMatchedCount == compareToResource.skillsMatchedCount) {
            if (rank == compareToResource.rank) {
            	return 0;
            }
            else if (rank < compareToResource.rank) {
            	return -1;
            }
        }
        else if (skillsMatchedCount > compareToResource.skillsMatchedCount) {
            return -1;
        }

        return 1;
    }

}