RbA Build/src/objects/RMS_Queue_Settings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>Settings that dictate what queue objects will go in.</description>
    <fields>
        <fullName>Install_Work_Order_Queue_Id__c</fullName>
        <label>Install Work Order Queue Id</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Order_Queue_Id__c</fullName>
        <label>Order Queue Id</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Tech_Measure_Work_Order_Queue_Id__c</fullName>
        <label>Tech Measure Work Order Queue Id</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <label>RMS Queue Settings</label>
</CustomObject>

RbA Build/src/objects/RMS_Settings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>A name value list of RMS settings</description>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>RMS Settings</label>
</CustomObject>

RbA Build/src/objects/Store_Configuration__c.object
<CustomObject>
    <description>Holds Store Settings &amp; Configurations</description>
    <fields>
        <fullName>Install_Work_Order_Queue_Id__c</fullName>
        <label>Install Work Order Queue Id</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Order_Queue_Id__c</fullName>
        <label>Order Queue Id</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Store__c</fullName>
        <label>Store</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Store Configurations</relationshipLabel>
        <relationshipName>Store_Configurations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Tech_Measure_Work_Order_Queue_Id__c</fullName>
        <label>Tech Measure Work Order Queue Id</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Store Configuration</label>
    <nameField>
        <displayFormat>SS-{00}</displayFormat>
        <label>Store Setting Record #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Store Configurations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

RbA Build/src/objects/SVMXC__Service_Order__c.object
<CustomObject>
    <customHelp>SVMXC__SVMXC_LaunchHelp</customHelp>
    <description>Service Order is used to plan, execute and manage Service events for Field and Depot Service activities. Depending upon the service scenario, the order creation can be triggered by many events: When creating a Support Case, when one or more installed products require periodic service or calibration, when troubleshooting a customer problem on the field, if the field service engineer learns that the product requires specialized conditions of a factory/depot to resolve the problem, or when a new/repair shipment to customer requires specialized installation activity.</description>
    <label>Work Order</label>
    <nameField>
        <displayFormat>WO-{00000000}</displayFormat>
        <label>Work Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

RbA Build/src/classes/OrderTriggerHandlerTest.cls
@isTest
public with sharing class OrderTriggerHandlerTest {


	static testmethod void test1(){
		
		Profile p = [SELECT Id FROM Profile WHERE Name='Standard User']; 
		TestUtilityMethods utilities = new TestUtilityMethods();

		//Creating Account (Needed for RMS_Queue_Settings__c)
		Account account1 = utilities.createAccount('1');
	 	insert account1;
		
		Account store1 = utilities.createStoreAccount('77 - Twin Cities, MN');
		insert store1;
			
		//Creating RMS_Settings__c
    	RMS_Settings__c customSetting1 = new RMS_Settings__c(Value__c = '1234567890', Name='Data Loading Profile ID');
		insert customSetting1;
		
		//Creating RMS_Queue_Settings__c
		Group Order_Queue = utilities.createQueue('Order_Queue');
		insert Order_Queue;
		QueueSobject Order_Queue_Link = utilities.createQueueSobject(Order_Queue.id ,'Order');
		insert Order_Queue_Link;
		
    	Group Install_Work_Order_Queue = utilities.createQueue('Install_Work_Order_Queue');
		insert Install_Work_Order_Queue;
		QueueSobject Install_Work_Order_Link = utilities.createQueueSobject(Install_Work_Order_Queue.id ,'SVMXC__Service_Order__c');
		insert Install_Work_Order_Link;
		
		Group Tech_Measure_Work_Order_Queue = utilities.createQueue('Tech_Measure_Work_Order');
		insert Tech_Measure_Work_Order_Queue;
		QueueSobject Tech_Measure_Work_Order_Link = utilities.createQueueSobject(Tech_Measure_Work_Order_Queue.id ,'SVMXC__Service_Order__c');
		insert Tech_Measure_Work_Order_Link;
		
    	Store_Configuration__c storeConfig = new Store_Configuration__c(
    		Store__c = store1.id,
        	Order_Queue_Id__c = Order_Queue.id,
    		Install_Work_Order_Queue_Id__c = Install_Work_Order_Queue.id,
        	Tech_Measure_Work_Order_Queue_Id__c = Tech_Measure_Work_Order_Queue.id
        	);
    	insert storeConfig;
		
		Order ord1 = new Order( AccountId = account1.id ,
								Status = 'Draft', 
								EffectiveDate = Date.Today()
								);
		insert ord1;
		
		
		
	}
}