RbA Build/src/objects/Service_Product__c.object
<CustomObject>
    <description>Junction Object linking Master Products to Service Products</description>
    <fields>
        <fullName>Service_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service Product</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Product2.RecordTypeId</field>
                <operation>equals</operation>
                <value>Service Product</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Master Products</relationshipLabel>
        <relationshipName>Service_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Service Product</label>
    <nameField>
        <displayFormat>SPA-{000000}</displayFormat>
        <label>Service Product Assignment</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

RbA Build/src/objects/Service_Symptom__c.object
<CustomObject>
    <description>The actual Service Symptom code added to the Order Item. Junction Object between Order Item and Service Symptom List</description>
    <fields>
        <fullName>Service_Product__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Service Product</label>
        <referenceTo>OrderItem</referenceTo>
        <relationshipLabel>Service Symptoms</relationshipLabel>
        <relationshipName>Service_Symptoms</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Service_Symptom__c</fullName>
        <label>Service Symptom</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>$Source.Service_Product__c</field>
                <operation>equals</operation>
                <valueField>$Source.Service_Product__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Service_Symptom_List__c</referenceTo>
        <relationshipLabel>Service Request Line Items</relationshipLabel>
        <relationshipName>Service_Symptoms</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Service Symptom</label>
    <nameField>
        <displayFormat>SS-{000}</displayFormat>
        <label>Service Symptom #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Symptoms</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

RbA Build/src/objects/Service_Symptom_List__c.object
<CustomObject>
    <label>Service Symptom List</label>
    <nameField>
        <label>Service Symptom Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Symptom List</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

RbA Build/src/classes/RMS_addServiceSymptomExt.cls
public with sharing class RMS_addServiceSymptomExt {
    
    public final Service_Symptom__c s;
    
    public RMS_addServiceSymptomExt (ApexPages.StandardController stdController) {
        this.s = (Service_Symptom__c)stdController.getRecord();            
        
    }
    
    public List<selectOption> getSers() {
        List<selectOption> options = new List<selectOption>(); //new list for holding all of the picklist options        
        options.add(new selectOption('', '-- SELECT --'));
        for (Service_Symptom_List__c servs : [SELECT Id,Name 
                                              FROM Service_Symptom_List__c 
                                              WHERE Name != null
                                              ORDER BY Service_Symptom_List__c.Name ASC]) { 
                                                  options.add(new selectOption(servs.Id, servs.Name)); //for all records found - add them to the picklist options
                                              } //add the first option of '- None -' in case the user doesn't want to select a value or in case no values are returned from query below        
        return options; //return the picklist options        
    }
    
    public String ssSP { get; set; }{
        ssSP = apexpages.currentpage().getparameters().get('ssSP');
        if ( ssSP == null ) ssSP = '';
    }
    public PageReference saveRerender(){
        //deletes the order and redirects to delete confirmation page        
        s.Service_Product__c = ssSp;
        insert s;
        
        PageReference reRender = new PageReference('/apex/RMS_addServiceSymptomP2?id='+ s.Id + '&retUrl=' + s.Service_Product__c);
        reRender.setRedirect(true);
        return reRender;
        
    }
    
    
    
    
}